### ISSUE TITLE
IOError: [Errno 62] Too many levels of symbolic links

### ISSUE THREAD

**Issue by Tset-Noitamotua** [pypa/virtualenv#1006]
I cant create a venv with the name `PYTHON_27` (with underscore)

```shell
> mkvirtualenv PYTHON_27 -p Python2.7
Running virtualenv with interpreter /usr/local/bin/Python2.7
New python executable in /Users/MyMac/.virtualenvs/PYTHON_27/bin/python
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 1231, in install_python
    shutil.copyfile(executable, py_executable)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 62] Too many levels of symbolic links: '/Users/MyMac/.virtualenvs/PYTHON_27/bin/python'
```

But no problem with name `PYTHON-27`

```shell
> mkvirtualenv PYTHON-27 -p Python2.7
Running virtualenv with interpreter /usr/local/bin/Python2.7
New python executable in /Users/MyMac/.virtualenvs/PYTHON-27/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /Users/MyMac/.virtualenvs/PYTHON-27/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/MyMac/.virtualenvs/PYTHON-27/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/MyMac/.virtualenvs/PYTHON-27/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/MyMac/.virtualenvs/PYTHON-27/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/MyMac/.virtualenvs/PYTHON-27/bin/get_env_details
```

**Comment by yan12125** [comment]
Works on Sierra
```
$ python2.7 -m virtualenv PYTHON_27
New python executable in /Users/yen/PYTHON_27/bin/python
Installing setuptools, pip, wheel...done.
```
Could you paste the output of direct virtualenv invocations?

**Comment by Tset-Noitamotua** [comment]
Indeed ... `virtualenv PYTHON_27` worked.

So then it may be an issue of virtualenvwrapper?

**Comment by yan12125** [comment]
> So then it may be an issue of virtualenvwrapper?

Most likely that's it.

**Comment by Tset-Noitamotua** [comment]
I've posted it on virtualenvwrapper's issue tracker on bitbucket. So let's close this one.

Cheers
Tset

**Comment by rngd** [comment]
for the curious, the virtualenvwrapper ticket is this one: https://bitbucket.org/virtualenvwrapper/virtualenvwrapper/issues/288/ioerror-errno-62-too-many-levels-of (still open as of this moment).
