### ISSUE TITLE
why does virtualenv uses /usr/lib64/python2.7/ssl.py ? 

### ISSUE THREAD

**Issue by mosajjal** [pypa/virtualenv#1008]
Hi. I have a consistent problem with virtualenv. After upgrading python (specifically `ssl` module) on the "host", all my virtualenvs will have the same problem. Pip and all modules related to `ssl` module will not work anymore. My question is, why doesn't virtualenv make a snapshot of `/usr/lib64/ssl.py` ? that way at least pip will work and the user can upgrade his virtualenv packages. 

the exact error:

```
import ssl
  File "/usr/lib64/python2.7/ssl.py", line 133, in <module>
    PROTOCOL_SSLv23 = PROTOCOL_TLS
NameError: name 'PROTOCOL_TLS' is not defined
```

**Comment by yan12125** [comment]
How did you upgrade ssl.py? Did you upgrade _ssl.so as well?

> why doesn't virtualenv make a snapshot of /usr/lib64/ssl.py

ssl.py is not part of virtualenv

**Comment by mosajjal** [comment]
I've performed a full system upgrade in Arch, during which my `python2` and `python2-ssl` package have been upgraded. 

wouldn't it be better to have a completely isolated `pip` for resolving these issues?

**Comment by yan12125** [comment]
> I've performed a full system upgrade in Arch

I'm also on Arch, and everything is fine here. I bet you've messed your system up. Please paste the output of this command:
```
python -c 'import _ssl; print(_ssl); print(_ssl.OPENSSL_VERSION)'
```

> wouldn't it be better to have a completely isolated ```pip``` for resolving these issues?

Virtual environments should use as little space as possible. 71MB for each virtualenv is not the way to go.

By the way, there's no python2-ssl package on Arch. Are you using official Arch repositories?

**Comment by mosajjal** [comment]
this is the output of the command:
```
python2 -c 'import _ssl; print(_ssl); print(_ssl.OPENSSL_VERSION)'
<module '_ssl' from '/usr/lib/python2.7/lib-dynload/_ssl.so'>
OpenSSL 1.0.2j  26 Sep 2016
```


also you're right. after looking around I found it was all part of `python` package not `python-ssl`.

**Comment by yan12125** [comment]
Seems correct. What's the output of ```python2 -c "print(_ssl.PROTOCOL_TLS)"``` and ```md5sum /usr/lib/python2.7/lib-dynload/_ssl.so```?

**Comment by mosajjal** [comment]
I've added `import _ssl` to your command and got these results:
```
python2 -c 'import _ssl; print(_ssl.PROTOCOL_TLS)'
2
```
```
md5sum /usr/lib/python2.7/lib-dynload/_ssl.so
50886a044ff9d5c386fc3ee6af6aca54
```

note that my `pip`, `python` and `ssl` are all working fine outside of `virtualenv`

**Comment by yan12125** [comment]
What's the results of all aforemented commands in virtual environments?

**Comment by mosajjal** [comment]
```
python2 -c 'import _ssl; print(_ssl); print(_ssl.OPENSSL_VERSION)'
<module '_ssl' from '/home/.../.../.../lib/python2.7/lib-dynload/_ssl.so'>
OpenSSL 1.0.2j  26 Sep 2016

python2 -c 'import _ssl; print(_ssl.PROTOCOL_TLS)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'PROTOCOL_TLS'
```

also, my _ssl.so is different in my system and my virtualenv

```
diff /home/.../.../.../lib/python2.7/lib-dynload/_ssl.so /usr/lib/python2.7/lib-dynload/_ssl.so
Binary files /home/.../.../.../lib/python2.7/lib-dynload/_ssl.so and /usr/lib/python2.7/lib-dynload/_ssl.so differ
```

**Comment by yan12125** [comment]
virtualenv does not copy _ssl.so. Did you create /home/.../.../.../lib/python2.7/lib-dynload/_ssl.so by yourself?

**Comment by mosajjal** [comment]
no but it's there. I have 3 different virtualenvs all with the same problem. So there problem is having _ssl.so inside them?

**Comment by yan12125** [comment]
> So there problem is having _ssl.so inside them?

Yes. Either both ssl.py and _ssl.so should be copied, or both shouldn't be copied. In your case, apparently _ssl.so is copied but ssl.py not. Are you using the latest virtualenv? (15.0.3)

**Comment by mosajjal** [comment]
I created these virtualenvs more than a year ago, currently I'm using the latest version and if I create a new virtualenv everything works out fine. So it looks like it's been an old bug and it's been resolved since?

**Comment by yan12125** [comment]
Hmm, I found an option --always-copy. With that _ssl.so are indeed copied - that's an acutal virtualenv bug.

**Comment by mosajjal** [comment]
that will cause some serious problems when it comes to use the virtualenv in a production environment.

**Comment by yan12125** [comment]
--always-copy is never implemented as what people expect. See #818

**Comment by mosajjal** [comment]
thanks for your time and info. I'll replace ssl.py and _ssl.so from my machine to my old virtualenvs for the time being. That'll probably solve the problem

**Comment by daniele-sartiano** [comment]
I had a similar problem in my new server. l can't create a virtualenv:
```
$ virtualenv myenv
New python executable in /home/sartiano/myenv/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /home/sartiano/myenv/bin/python - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/__init__.py", line 21, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/__init__.py", line 62, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/packages/__init__.py", line 27, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/packages/urllib3/__init__.py", line 8, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 33, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/packages/urllib3/packages/__init__.py", line 3, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/packages/urllib3/packages/ssl_match_hostname/__init__.py", line 3, in <module>
  File "/usr/lib/python2.7/ssl.py", line 133, in <module>
    PROTOCOL_SSLv23 = PROTOCOL_TLS
NameError: name 'PROTOCOL_TLS' is not defined
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 945, in create_environment
    download=download,
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 797, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/sartiano/myenv/bin/python - setuptools pip wheel failed with error code 1

```

The virtualenv version is:
```
$ pip freeze | grep virtualenv
virtualenv==15.1.0
```

The operative system:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```
The problem exists with Python 2.7.13, I have not problems with Python 3.5.2.


Any suggestion?

**Comment by yan12125** [comment]
@daniele-sartiano That might be something different. Does ```python2 -c 'import ssl'``` run on your machine?

**Comment by daniele-sartiano** [comment]
> Does python2 -c 'import ssl' run on your machine?

Without problems:
```
$ python2 -c 'import ssl'
$ python -c 'import ssl'
$
```

**Comment by yan12125** [comment]
Hmmm, is there a file ```_ssl.so``` in /home/sartiano/myenv or subdirectories?

**Comment by daniele-sartiano** [comment]
> Hmmm, is there a file _ssl.so in /home/sartiano/myenv or subdirectories?

No, there is not:
```
$ find myenv/ -name *ssl.so
$ 
```

**Comment by yan12125** [comment]
Then what's the result of commands below?
```
source myenv/bin/activate
python -c 'import _ssl; print(_ssl)'
```

**Comment by daniele-sartiano** [comment]
I can't activate:

```
$ ll myenv/bin/
total 20
drwxrwxr-x 2 sartiano sartiano  4096 Feb 22 11:51 ./
drwxrwxr-x 5 sartiano sartiano  4096 Feb 22 11:51 ../
-rwxrwxr-x 1 sartiano sartiano 10302 Feb 22 11:51 python*
lrwxrwxrwx 1 sartiano sartiano     6 Feb 22 11:51 python2 -> python*
lrwxrwxrwx 1 sartiano sartiano     6 Feb 22 11:51 python2.7 -> python*
```

**Comment by yan12125** [comment]
Oops. How about: ```myenv/bin/python -c 'import _ssl; print(_ssl)'```?

**Comment by daniele-sartiano** [comment]
Here:
```
$ myenv/bin/python -c 'import _ssl; print(_ssl)'
<module '_ssl' from '/home/sartiano/myenv/lib/python2.7/lib-dynload/_ssl.x86_64-linux-gnu.so'>
```

**Comment by yan12125** [comment]
That looks the same bug as mosajjal's Try replacing _ssl.x86_64-linux-gnu.so with the system copy. I guess that's in /usr/lib/python2.7/lib-dynload/_ssl.x86_64-linux-gnu.so

**Comment by daniele-sartiano** [comment]
The files are equals:

```
$ md5sum /usr/lib/python2.7/lib-dynload/_ssl.x86_64-linux-gnu.so
ea1e1579774d94a76454c2b4f86cae82  /usr/lib/python2.7/lib-dynload/_ssl.x86_64-linux-gnu.so
$ md5sum /home/sartiano/myenv/lib/python2.7/lib-dynload/_ssl.x86_64-linux-gnu.so
ea1e1579774d94a76454c2b4f86cae82  /home/sartiano/myenv/lib/python2.7/lib-dynload/_ssl.x86_64-linux-gnu.so
```

**Comment by yan12125** [comment]
Interesting. What's the result of the following two commands?
```
myenv/bin/python -c "import _ssl; print(_ssl); print(_ssl.PROTOCOL_TLS)"
python2 -c "import _ssl; print(_ssl); print(_ssl.PROTOCOL_TLS)"
```

**Comment by daniele-sartiano** [comment]
I have the error only with the virtualenv:
```
$ myenv/bin/python -c "import _ssl; print(_ssl); print(_ssl.PROTOCOL_TLS)"
<module '_ssl' from '/home/sartiano/myenv/lib/python2.7/lib-dynload/_ssl.x86_64-linux-gnu.so'>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'PROTOCOL_TLS'

$ python2 -c "import _ssl; print(_ssl); print(_ssl.PROTOCOL_TLS)"
<module '_ssl' from '/usr/lib/python2.7/lib-dynload/_ssl.so'>
2
```

**Comment by yan12125** [comment]
I can't tell the actual reason. Here are some ideas:

1. Official Python 2 provides only ```_ssl.so``` but no ```_ssl.x86_64-linux-gnu.so```. [1] It's even more strange that both /usr/lib/python2.7/lib-dynload/_ssl.x86_64-linux-gnu.so and /usr/lib/python2.7/lib-dynload/_ssl.so exist.
2. Ubuntu 16.04 provides up to 2.7.12. [2] How did you install 2.7.13? Maybe there's something wrong in your installation.

[1] PEP 3149 -- ABI version tagged .so files. https://www.python.org/dev/peps/pep-3149/
[2] http://packages.ubuntu.com/search?keywords=python2.7

**Comment by daniele-sartiano** [comment]
Here the steps used to setup the server.

```sudo apt-get install cmake
sudo apt-get install emacs24
sudo apt-get install libreadline-dev
sudo apt-get install unzip
sudo apt-get install python-numpy python-scipy python-dev python-pip python-nose g++ libblas-dev git
sudo -H pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git --user

pip install --upgrade pip
sudo -H pip install conda
pip install --upgrade pip
sudo -H pip install auxlib
sudo -H pip install fish
sudo -H pip install tqdm
sudo -H pip install docopt
pip install --upgrade pip
sudo -H pip install requests
sudo -H pip install pycosat
sudo -H conda install -c https://conda.anaconda.org/anaconda pandas

# CUDA 8.0
wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
sudo dpkg -i cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
sudo apt-get update
sudo apt-get install cuda
```

**Comment by yan12125** [comment]
This line looks suspicious:
```
sudo -H conda install -c https://conda.anaconda.org/anaconda pandas
```
AFAIK Anaconda uses its own package manager and comes with its own Python executable. It's likely that the two are conflicting with each other. (providing incompatible ```_ssl``` modules in this case) Try removing either the Python from Anaconda or the system Python via apt-get.

**Comment by daniele-sartiano** [comment]
Hi, How can I remove Python from Anaconda?

**Comment by yan12125** [comment]
Sorry I'm not familiar with Anaconda. Anaconda forums or issue trackers are better places.

**Comment by MiguelChiang** [comment]
Anaconda is confirmed to be conflict with virtualenv, try disabling conda and use the system python library.

i.e. https://stackoverflow.com/questions/38221144/how-to-solve-the-issue-of-the-conflict-of-anaconda-and-virtualenv
