### ISSUE TITLE
lib64 -> lib is broken link

### ISSUE THREAD

**Issue by j00bar** [pypa/virtualenv#1016]
Running in a Centos 7 Docker container:

```
[root@1884c38970d4 /]# virtualenv --version
15.1.0
[root@1884c38970d4 /]#  virtualenv -vvv --always-copy --system-site-packages /app/venv
Creating /app/venv/lib/python2.7
This system uses lib64; symlinking lib64 to lib
Symlinking /app/venv/lib64
Symlinking Python bootstrap modules
  Copying to /app/venv/lib/python2.7/config
  Copying to /app/venv/lib/python2.7/lib-dynload
  Creating parent directories for /app/venv/lib64/python2.7
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 1132, in install_python
    copy_required_modules(home_dir, symlink)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 1063, in copy_required_modules
    copyfile(filename, dst_filename, symlink)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 343, in copyfile
    os.makedirs(os.path.dirname(dest))
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 2] No such file or directory: '/app/venv/lib64/python2.7'
[root@1884c38970d4 /]# ls -l /app/venv
total 4
drwxr-xr-x 3 root root 4096 Feb 13 21:02 lib
lrwxrwxrwx 1 root root    7 Feb 13 21:02 lib64 -> usr/lib
```

The link from `lib64` to `usr/lib` is a broken link. I'm guessing the desired target is `lib` not `usr/lib`.

**Comment by daa** [comment]
I believe this issue is fixed by #1249 .
