### ISSUE TITLE
Missing dependency `six` for `setuptools` when enable virtualenv for Python 2.7

### ISSUE THREAD

**Issue by reyoung** [pypa/virtualenv#1053]
When we activate a clean `virtualenv` now, the `setuptools.py27compat` cannot be imported because of missing dependency `six`.

We could use `docker` to reproduce this problem, the commands are:

```
docker run -it  python:2.7.13-slim /bin/bash
# inside docker
pip install virtualenv
virtualenv test_env
source test_env/bin/activate
python -c 'import setuptools.py27compat'
```

The recorded video is [here](https://asciinema.org/a/bctil9q83e543siln7kexxx7c).

This will let some package installation failed inside a clean `virtualenv`. The error like below

```text
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-m3mYGK/singleton/setup.py", line 13, in <module>
        url='https://github.com/reyoung/singleton'
      File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/test_env/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python2.7/distutils/command/install.py", line 575, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/test_env/lib/python2.7/site-packages/setuptools/command/install_scripts.py", line 17, in run
        import setuptools.command.easy_install as ei
      File "/test_env/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 49, in <module>
        from setuptools.py27compat import rmtree_safe
      File "/test_env/lib/python2.7/site-packages/setuptools/py27compat.py", line 7, in <module>
        import six
    ImportError: No module named six
```

The recorded video about failing to install a package is [here](https://asciinema.org/a/2j4timq026yg6tyaw9j45jb26).

Is this an issue of virtualenv? And please let me know if there is a bypass way to temporary fix this problem?

Thanks.

**Comment by reyoung** [comment]
BTW, I think it because the setuptools just release the `36.0.0` version.

![image](https://cloud.githubusercontent.com/assets/728699/26669937/478f85c8-46e2-11e7-88e1-d9b14c9c9ad2.png)

And it seems that this version adds six as a dependency, but I did not dig into setuptools code.

**Comment by ashemedai** [comment]
This is related to [No module named 'six'](https://github.com/pypa/setuptools/issues/1042)

**Comment by dstufft** [comment]
Fixed upstream.
