### ISSUE TITLE
python 2.7 issue

### ISSUE THREAD

**Issue by hamedmoustafa** [pypa/virtualenv#1070]
that's what i get if i run any file.py in kali linux
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 563, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 545, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python2.7/site.py", line 278, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python2.7/site.py", line 253, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python2.7/site.py", line 243, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python2.7/sysconfig.py", line 521, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python2.7/sysconfig.py", line 420, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python2.7/sysconfig.py", line 288, in _init_posix
    raise IOError(msg)
IOError: invalid Python installation: unable to open /usr/lib/python2.7/config/Makefile (No such file or directory)

**Comment by pfmoore** [comment]
Sorry but it's not clear how virtualenv is involved here. Could you clarify? From what I can tell, this looks more like your Python installation is broken.

**Comment by gst** [comment]
I agree it looks broken installation.

**Comment by ssbarnea** [comment]
@pfmoore can we close this ticket? Seems to be too obsolete and pollutes the tracker.
