### ISSUE TITLE
AppVeyor always fails because Python 2.6 does not support set comprehensions

### ISSUE THREAD

**Issue by cclauss** [pypa/virtualenv#1138]
Python 2.6 reached its [end of life](https://devguide.python.org/#branchstatus) 4+ years ago.

**Comment by cclauss** [comment]
```
Traceback (most recent call last):
  File "c:\python26\Lib\runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python26\Lib\runpy.py", line 34, in _run_code
    exec code in run_globals
  File "C:\projects\virtualenv\.tox\py\Scripts\pip.EXE\__main__.py", line 5, in <module>
  File "c:\projects\virtualenv\.tox\py\lib\site-packages\pip\_internal\__init__.py", line 42, in <module>
    from pip._internal import cmdoptions
  File "c:\projects\virtualenv\.tox\py\lib\site-packages\pip\_internal\cmdoptions.py", line 16, in <module>
    from pip._internal.index import (
  File "c:\projects\virtualenv\.tox\py\lib\site-packages\pip\_internal\index.py", line 526
    {str(c.version) for c in all_candidates},
                      ^
SyntaxError: invalid syntax
```

**Comment by gaborbernat** [comment]
we also moved to Azure
