### ISSUE TITLE
"Permission denied" when create an env, using vagrant and smb (windows)

### ISSUE THREAD

**Issue by quoidautre** [pypa/virtualenv#1142]
Hi,

I've en issue when I create an environment. Link to stackoverflow [here](https://stackoverflow.com/questions/49106867/permission-denied-using-virtualenv-vagrant-and-smb-on-windows).
```shell
$ sudo virtualenv --always-copy env -p python3

Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /var/www/my-project/env/bin/python3
Also creating executable in /var/www/my-project/env/bin/python
ERROR: The executable /var/www/my-project/env/bin/python3 could not be run: [Errno 13] Permission denied
```
I'm using Vagrant and SMB to synchronize the folders. (launched with powershell in administrator mode).

When I desactivate SMB (sync_type: default), it's work. But my VM is slow :(.

Have you an idea ?

Thanks a lot.
F.

```
$ virtualenv env -p python3
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /var/www/my-project/env/bin/python3
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1232, in install_python
    make_exe(py_executable)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 389, in make_exe
    os.chmod(fn, newmode)
PermissionError: [Errno 1] Operation not permitted: '/var/www/my-project/env/bin/python3'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
ImportError: No module named 'apport'

Original exception was:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1232, in install_python
    make_exe(py_executable)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 389, in make_exe
    os.chmod(fn, newmode)
PermissionError: [Errno 1] Operation not permitted: '/var/www/my-project/env/bin/python3'
```

**Comment by ozbillwang** [comment]
https://superuser.com/questions/1475952/virtualenv-returns-errno-13-permission-denied
