### ISSUE TITLE
virtualenv command fails if workdir has html files without read permissions

### ISSUE THREAD

**Issue by andrunah** [pypa/virtualenv#1151]
There is an issue creating virtualenv if there is ANY html file owned by other user inside the working directory.
Steps to reproduce:
1) Create html file that is not readable by your user (owned by some other user or without read permissions):
```
# whoami
test_user
$ ls -la test_vdfgkd.html
-rw------- 1 root root 0 Mar 21 15:11 test_vdfgkd.html
```

2) Try creating virtualenv:

```
$ virtualenv test_venv
New python executable in test_venv/bin/python
Installing setuptools, pip...
  Complete output from command /home/test_user/test_venv/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
  Ignoring indexes: https://pypi.python.org/simple/
Downloading/unpacking setuptools
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/index.py", line 252, in find_requirement
    for page in self._get_pages(locations, req):
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/index.py", line 387, in _get_pages
    page = self._get_page(location, req)
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/index.py", line 568, in _get_page
    session=self.session,
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/index.py", line 670, in get_page
    resp = session.get(url, headers={"Accept": "text/html"})
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/_vendor/requests/sessions.py", line 395, in get
    return self.request('GET', url, **kwargs)
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/download.py", line 237, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/_vendor/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/_vendor/requests/sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/download.py", line 202, in send
    resp.raw = LocalFSResponse(open(pathname, "rb"))
IOError: [Errno 13] Permission denied: u'/home/test_user/test_vdfgkd.html'

Storing debug log for failure in /home/test_user/.pip/pip.log
----------------------------------------
...Installing setuptools, pip...done.
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 3, in <module>
    virtualenv.main()
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 825, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 993, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 961, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 903, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/test_user/test_venv/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 2
```

**Comment by domcorvasce** [comment]
What version are you using?

```shell
virtualenv --version
```

**Comment by andrunah** [comment]
```
$ virtualenv --version
1.11.4
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
```

**Comment by domcorvasce** [comment]
You're using an old version of virtualenv. We're currently at 15.2.0.
Instead of using ubuntu repos, try installing virtualenv using **pip**:

```shell
pip install virtualenv
```

**Comment by andrunah** [comment]
Confirmed, issue not reproduced with latest virtualenv.
