### ISSUE TITLE
Calling virtualenv again with a different --python option value results in failure and circular symbolic links

### ISSUE THREAD

**Issue by ben-g-** [pypa/virtualenv#1181]
I have virtualenv 16.0.0.

I call `virtualenv` twice, with the difference `--python=python` vs. `--python=/usr/bin/python2.7`.

The second call fails. Also note the circular symbolic links that it creates among bin/python* in the virtual environment.

```
$ virtualenv --python=python --clear .python-env
Running virtualenv with interpreter /usr/bin/python
Not deleting /home/it/.python-env/bin
New python executable in /home/it/.python-env/bin/python
Installing setuptools, pip, wheel...done.

$ ls -l .python-env/bin/python*
-rwxrwxr-x 1 it it 3492656 May 23 12:00 .python-env/bin/python
lrwxrwxrwx 1 it it       6 May 23 12:00 .python-env/bin/python2 -> python
lrwxrwxrwx 1 it it       6 May 23 12:00 .python-env/bin/python2.7 -> python
-rwxrwxr-x 1 it it    2338 May 23 12:00 .python-env/bin/python-config

$ virtualenv --python=/usr/bin/python2.7 --clear .python-env
Running virtualenv with interpreter /usr/bin/python2.7
Deleting tree /home/it/.python-env/lib/python2.7
Not deleting /home/it/.python-env/bin
New python executable in /home/it/.python-env/bin/python2.7
Not overwriting existing python script /home/it/.python-env/bin/python (you must use /home/it/.python-env/bin/python2.7)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/virtualenv.py", line 2343, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/usr/local/lib/python3.5/dist-packages/virtualenv.py", line 927, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/local/lib/python3.5/dist-packages/virtualenv.py", line 1389, in install_python
    os.symlink(py_executable_base, full_pth)
OSError: [Errno 17] File exists

$ ls -l .python-env/bin/python*
lrwxrwxrwx 1 it it    9 May 23 12:01 .python-env/bin/python -> python2.7
lrwxrwxrwx 1 it it    6 May 23 12:00 .python-env/bin/python2 -> python
lrwxrwxrwx 1 it it    6 May 23 12:00 .python-env/bin/python2.7 -> python
-rwxrwxr-x 1 it it 2338 May 23 12:00 .python-env/bin/python-config
```

**Comment by gaborbernat** [comment]
Can you replicate with 16.2.0? Also please provide exact OS information. Once done I'll reopen, thanks!
