### ISSUE TITLE
cannot create new venv, ImportError: cannot import name main

### ISSUE THREAD

**Issue by bluemandora** [pypa/virtualenv#1186]
I use pip2 from anaconda, the version of pip is 10.0.1.
While I try to create new virtual environment, this error occur:

```
New python executable in /home/ices/LabelGAN/venv/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /home/ices/LabelGAN/venv/bin/python - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 11, in <module>
ImportError: cannot import name main
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/home/ices/anaconda2/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/home/ices/anaconda2/lib/python2.7/site-packages/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/home/ices/anaconda2/lib/python2.7/site-packages/virtualenv.py", line 947, in create_environment
    download=download,
  File "/home/ices/anaconda2/lib/python2.7/site-packages/virtualenv.py", line 904, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/home/ices/anaconda2/lib/python2.7/site-packages/virtualenv.py", line 796, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/ices/LabelGAN/venv/bin/python - setuptools pip wheel failed with error code 1
```

**Comment by lgh2** [comment]
I'm having the same issue with  `pip` 10.0.1 and `virtualenv` 16.0.0 on Linux Mint 18.1 Serena. It appears to be a `pip` issue: https://github.com/pypa/pip/issues/5240

**Comment by gaborbernat** [comment]
Closing as per above.
