### ISSUE TITLE
ImportError: No module named functools

### ISSUE THREAD

**Issue by zhengtulymGh** [pypa/virtualenv#1188]
what's wrong with my project?

sys win7

`Python 2.7.14`
`Django 1.6.2`

```
(env)
liyimin@liyimin-PC MINGW64 /e/project/snakecage/Snake (develop)
$ python manage.py runserver 5000
Traceback (most recent call last):
  File "E:\project\snakecage\Snake\env\lib\site.py", line 703, in <module>
    main()
  File "E:\project\snakecage\Snake\env\lib\site.py", line 692, in main
    aliasmbcs()
  File "E:\project\snakecage\Snake\env\lib\site.py", line 515, in aliasmbcs
    import locale, codecs
  File "E:\project\snakecage\Snake\env\lib\locale.py", line 17, in <module>
    import functools
ImportError: No module named functools
```

```
(env)
liyimin@liyimin-PC MINGW64 /e/project/snakecage/Snake (develop)
$ pip
Traceback (most recent call last):
  File "e:\project\snakecage\snake\env\lib\site.py", line 703, in <module>
    main()
  File "e:\project\snakecage\snake\env\lib\site.py", line 692, in main
    aliasmbcs()
  File "e:\project\snakecage\snake\env\lib\site.py", line 515, in aliasmbcs
    import locale, codecs
  File "e:\project\snakecage\snake\env\lib\locale.py", line 17, in <module>
    import functools
ImportError: No module named functools
(env)
```

**Comment by RonnyPfannschmidt** [comment]
this looks like a broken python install at first, since you skipped most of the system information nobody can help

**Comment by zhengtulymGh** [comment]
what else system information should I support?

**Comment by slmg** [comment]
This can occur if there is a mismatch between the Python interpreter inside your virtualenv and your "system" Python (the one available in your PATH). The reason being that virtualenvs do not encapsulate the standard lib upon creation, which `functools` is part of.
