### ISSUE TITLE
Problem Setting up Virtualevn

### ISSUE THREAD

**Issue by akjagadish** [pypa/virtualenv#1197]
Running virtualenv with interpreter /home/akshay/anaconda2/bin/python2
New python executable in /home/akshay/DL/PCL/pcl-python/bin/python2
Not overwriting existing python script /home/akshay/DL/PCL/pcl-python/bin/python (you must use /home/akshay/DL/PCL/pcl-python/bin/python2)
Installing setuptools, pkg_resources, pip, wheel...
  Complete output from command /home/akshay/DL/PCL/pcl-python/bin/python2 - setuptools pkg_resources pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/__init__.py", line 5, in <module>
  File "/home/akshay/anaconda2/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "/home/akshay/anaconda2/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
----------------------------------------
...Installing setuptools, pkg_resources, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 988, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 918, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 812, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/akshay/DL/PCL/pcl-python/bin/python2 - setuptools pkg_resources pip wheel failed with error code 1

**Comment by daa** [comment]
> Not overwriting existing python script /home/akshay/DL/PCL/pcl-python/bin/python
> ImportError: cannot import name _remove_dead_weakref

Seems that virtualenv already existed in ``/home/akshay/DL/PCL/pcl-python/`` and was made with older python which was upgraded some time ago. Try to remove that path and create virtualenv again.

**Comment by gaborbernat** [comment]
As per above.
