### ISSUE TITLE
python path case sensitive on Windows when creating env

### ISSUE THREAD

**Issue by vbabiy** [pypa/virtualenv#12]
When doing a "virtualenv --python=c:\python25\python.exe", I got this error:

AssertionError: Filename C:\Python25\lib\site-packages\readline.py does not start with any of these prefixes: ['c:\python25']

Changing the case in the command line made it work.

---
- Bitbucket: https://bitbucket.org/ianb/virtualenv/issue/78
- Originally Reported By:  
- Originally Created At: 2011-02-05 19:30:47

**Comment by zvodd** [comment]
This is still an issue in virtualenv-15.0.2!

````
    D:\Projects\somevenvtest>virtualenv myvenv
    Traceback (most recent call last):
      File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "C:\Python27\Lib\runpy.py", line 72, in _run_code
        exec code in run_globals
      File "C:\Python27\Scripts\virtualenv.exe\__main__.py", line 9, in <module>
      File "C:\Python27\Lib\site-packages\virtualenv.py", line 711, in main
        symlink=options.symlink)
      File "C:\Python27\Lib\site-packages\virtualenv.py", line 924, in create_environment
        site_packages=site_packages, clear=clear, symlink=symlink))
      File "C:\Python27\Lib\site-packages\virtualenv.py", line 1131, in install_python
        copy_required_modules(home_dir, symlink)
      File "C:\Python27\Lib\site-packages\virtualenv.py", line 1061, in copy_required_modules
        dst_filename = change_prefix(filename, dst_prefix)
      File "C:\Python27\Lib\site-packages\virtualenv.py", line 1035, in change_prefix
        (filename, prefixes)
    AssertionError: Filename C:\Python27\Lib\os.py does not start with any of these prefixes: ['C:\\python27']
````

**Comment by dzhwinter** [comment]
+1 at redhat6.3 enterprisel

**Comment by lit-uriy** [comment]
I have the same error on Windows XP (Python 3.4.4 / Virtualenv 15.0.2).
I am fix in [commit](https://github.com/lit-uriy/virtualenv/commit/5959b26765dfbd52714e392df92a352a91d3ca53).

But I have no confidence that it will work in all cases. (And I don't know how to do MergRequest)

**Comment by thefifo** [comment]
+1 Win7
