### ISSUE TITLE
No module named 'pkgutil'

### ISSUE THREAD

**Issue by erbatyr** [pypa/virtualenv#1204]
python 3.7.0
windows 10

PS C:\Users\Ербатыр\virenvs> virtualenv majesty
Using base prefix 'c:\\users\\ербатыр\\appdata\\local\\programs\\python\\python36'
New python executable in C:\Users\Ербатыр\virenvs\majesty\Scripts\python.exe
Installing setuptools, pip, wheel...
  Complete output from command C:\Users\Ербатыр\vir...y\Scripts\python.exe - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
ModuleNotFoundError: No module named 'pkgutil'
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "c:\users\ербатыр\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ербатыр\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ербатыр\AppData\Local\Programs\Python\Python36\Scripts\virtualenv.exe\__main__.py", line 9, in <module>
  File "c:\users\ербатыр\appdata\local\programs\python\python36\lib\site-packages\virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "c:\users\ербатыр\appdata\local\programs\python\python36\lib\site-packages\virtualenv.py", line 947, in create_environment
    download=download,
  File "c:\users\ербатыр\appdata\local\programs\python\python36\lib\site-packages\virtualenv.py", line 904, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "c:\users\ербатыр\appdata\local\programs\python\python36\lib\site-packages\virtualenv.py", line 796, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command C:\Users\Ербатыр\vir...y\Scripts\python.exe - setuptools pip wheel failed with error code 1

**Comment by Cervidae90** [comment]
Please try:
python -m venv <desired_venv_path>

**Comment by gaborbernat** [comment]
This does not have enough information to replicate. Consider providing exact environment description, with package versions, etc. We'll reopen once that happens, thanks!

**Comment by hatingman** [comment]
Have the same problem today. Fixed it with removing python to 'c:\python37' from appdata. It cuz you have unicode chars in the path name.

**Comment by remyroy** [comment]
This is likely related to having non-ASCII characters in your python PATH. I just had the same issue with Windows 10 and Python 3.7.3 while python was installed in ```C:\Users\Rémy Roy\AppData\Local\Programs\Python\Python37-32```. I reinstalled Python in ```C:\Python37-32``` and the problem was fixed.
