### ISSUE TITLE
Virtualenv 16.2.0 Error Finding Pip 

### ISSUE THREAD

**Issue by NazarTrilisky** [pypa/virtualenv#1288]
Repro steps:  run ``virtualenv <some_directory_name``
Issue resolved by downgrading virtualenv from 16.2.0 to 15.1.0.

Sample output  below:

```
$ virtualenv -p python my_venv
Already using interpreter /usr/bin/python
New python executable in /home/your_user_name/my_venv/bin/python
Cannot find a wheel for setuptools
Cannot find a wheel for pip
Installing setuptools, pip, wheel...

  Complete output from command /home/your_user_name/my_venv/bin/python - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 11, in <module>
ImportError: No module named pip
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 11, in <module>
    load_entry_point('virtualenv==16.2.0', 'console_scripts', 'virtualenv')()
  File "build/bdist.cygwin-<version>-x86_64/egg/virtualenv.py", line 768, in main
  File "build/bdist.cygwin-<version>-x86_64/egg/virtualenv.py", line 1030, in create_environment
  File "build/bdist.cygwin-<version>-x86_64/egg/virtualenv.py", line 983, in install_wheel
  File "build/bdist.cygwin-<version>-x86_64/egg/virtualenv.py", line 861, in call_subprocess
OSError: Command /home/your_user_name/my_venv/bin/python - setuptools pip wheel failed with error code 1
```

**Comment by gaborbernat** [comment]
This seems a cygwin bug 🤔

**Comment by kaselis** [comment]
I get the same issue on linux trying to install [platter](http://platter.pocoo.org/dev/) produced build, which fetches 16.3.0 virtualenv

**Comment by gaborbernat** [comment]
I think the rewrite branch fixes this, please try again with it.
