### ISSUE TITLE
Unstated dependency on pip >= 10

### ISSUE THREAD

**Issue by drcraig** [pypa/virtualenv#1301]
If you are in the situation where you have an old version of pip < 10, virtualenv 16.3.0 will happily install, but fails when you try to create a virtualenv because it's shelling out to `pip -m config`, which was [added in pip 10](https://pip.pypa.io/en/stable/news/#b1-2018-03-31). Virtualenv does not appear to declare a dependency on pip and the [Installation docs](https://virtualenv.pypa.io/en/latest/installation/) only say that pip > 1.3 is recommended.

```
$ pip --version
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)

$ pip list | grep virtualenv
virtualenv (16.3.0)

$ virtualenv /tmp/venv
New python executable in /tmp/venv/bin/python
Complete output from command /tmp/venv/bin/python -m pip config list:
ERROR: unknown command "config"
----------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 793, in main
    symlink=options.symlink,
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1087, in create_environment
    install_wheel(to_install, py_executable, search_dirs, download=download)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 935, in install_wheel
    _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 964, in _install_wheel_with_search_dir
    config = _pip_config(py_executable, python_path)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1038, in _pip_config
    remove_from_env=["PIP_VERBOSE", "PIP_QUIET"],
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 886, in call_subprocess
    raise OSError("Command {} failed with error code {}".format(cmd_desc, proc.returncode))
OSError: Command /tmp/venv/bin/python -m pip config list failed with error code 1
```

**Comment by gaborbernat** [comment]
I think we can still work in this case, just disable this feature. 👍
