### ISSUE TITLE
IndentationError: unexpected indent - when create virtulenv

### ISSUE THREAD

**Issue by Turall** [pypa/virtualenv#1337]
Thanks for submitting an issue!
OS: Fedorra 29
python 3.7

````pyhton
[tural@localhost Documents]$  virtualenv -p python3 myenv
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
  No LICENSE.txt / LICENSE found in source
New python executable in /home/tural/Documents/myenv/bin/python3
Also creating executable in /home/tural/Documents/myenv/bin/python
Command /home/tural/Documents/myenv/bin/python3 -m pip config list had error code 1
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/virtualenv.py", line 793, in main
    symlink=options.symlink,
  File "/usr/local/lib/python3.7/site-packages/virtualenv.py", line 1088, in create_environment
    install_wheel(to_install, py_executable, search_dirs, download=download)
  File "/usr/local/lib/python3.7/site-packages/virtualenv.py", line 935, in install_wheel
    _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs)
  File "/usr/local/lib/python3.7/site-packages/virtualenv.py", line 964, in _install_wheel_with_search_dir
    config = _pip_config(py_executable, python_path)
  File "/usr/local/lib/python3.7/site-packages/virtualenv.py", line 1043, in _pip_config
    config[key] = ast.literal_eval(value)
  File "/usr/lib64/python3.7/ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib64/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    threading.local()
    ^
IndentationError: unexpected indent

```

**Comment by sinscary** [comment]
@gaborbernat I would like to work on this.

**Comment by sinscary** [comment]
@gaborbernat Hi I got busy with some work. I am looking into it. Will try to fix ASAP

**Comment by Turall** [comment]
> @gaborbernat Hi I got busy with some work. I am looking into it. Will try to fix ASAP

Ok,thanks

**Comment by Ajk4** [comment]
Same error with python3.8

**Comment by Brodan** [comment]
I just got this when trying to make a virtualenv as well out of nowhere. what the heck is going on? can someone fix this
```
christopherhranj@~/quest$ virtualenv --version
16.7.7
christopherhranj@~/quest$ python3 -V
Python 3.7.4
christopherhranj@~/quest$ virtualenv venv
Using base prefix '/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7'
New python executable in /Users/christopherhranj/quest/venv/bin/python3.7
Also creating executable in /Users/christopherhranj/quest/venv/bin/python
Command /Users/christopherhr...t/venv/bin/python3.7 -m pip config list had error code 1
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/virtualenv.py", line 870, in main
    symlink=options.symlink,
  File "/usr/local/lib/python3.7/site-packages/virtualenv.py", line 1173, in create_environment
    install_wheel(to_install, py_executable, search_dirs, download=download)
  File "/usr/local/lib/python3.7/site-packages/virtualenv.py", line 1019, in install_wheel
    _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs)
  File "/usr/local/lib/python3.7/site-packages/virtualenv.py", line 1046, in _install_wheel_with_search_dir
    config = _pip_config(py_executable, python_path)
  File "/usr/local/lib/python3.7/site-packages/virtualenv.py", line 1128, in _pip_config
    config[key] = ast.literal_eval(value)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    float(sys.argv[1])
    ^
IndentationError: unexpected indent
```

**Comment by dingobar** [comment]
Hi, I am having the same issue on a windows machine, using `pipenv install --path c:\path\to\py38`. The path points to a python executable in a conda environment.

**Comment by gaborbernat** [comment]
I think the rewrite branch, release 20.0.0b2 fixed this.
