### ISSUE TITLE
Regression: virtualenv 16.7.3 breaking on OSX + miniconda (Python 2 only)

### ISSUE THREAD

**Issue by effigies** [pypa/virtualenv#1407]
As of today, our Travis builds are failing for Python 2 on OSX. We use miniconda to provide the base Python environment on OSX, but use virtualenv to allow us to have a consistent test across operating systems.

To set up the base environment on OSX:

```Shell
export PYTHON_VERSION=2.7
export MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh"
export MINICONDA=$HOME/miniconda
export PATH="$MINICONDA/bin:$PATH"

wget $MINICONDA_URL -O miniconda.sh
bash miniconda.sh -b -s -f -p $MINICONDA
conda config --set always_yes yes
conda info -a
conda install --quiet python=$PYTHON_VERSION
```

To reproduce the error:

```
pip install --upgrade pip "virtualenv~=16.7.3"
virtualenv --python=python venv
```

Traceback from [Travis](https://travis-ci.org/bids-standard/pybids/jobs/572815356#L1162-L1195):

```
$ virtualenv --python=python venv
Already using interpreter /Users/travis/miniconda/bin/python
New python executable in /Users/travis/build/bids-standard/pybids/venv/bin/python
Command /Users/travis/build/...bids/venv/bin/python -m pip config list had error code 1
Installing setuptools, pip, wheel...
  Complete output from command /Users/travis/build/...bids/venv/bin/python - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/Users/travis/miniconda/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/Users/travis/miniconda/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/Users/travis/build/bids-standard/pybids/venv/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Users/travis/build/bids-standard/pybids/venv/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /Users/travis/build/bids-standard/pybids/venv/lib/python2.7/lib-dynload/_io.so
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/virtualenv", line 10, in <module>
    sys.exit(main())
  File "/Users/travis/miniconda/lib/python2.7/site-packages/virtualenv.py", line 870, in main
    symlink=options.symlink,
  File "/Users/travis/miniconda/lib/python2.7/site-packages/virtualenv.py", line 1173, in create_environment
    install_wheel(to_install, py_executable, search_dirs, download=download)
  File "/Users/travis/miniconda/lib/python2.7/site-packages/virtualenv.py", line 1019, in install_wheel
    _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs)
  File "/Users/travis/miniconda/lib/python2.7/site-packages/virtualenv.py", line 1110, in _install_wheel_with_search_dir
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=script)
  File "/Users/travis/miniconda/lib/python2.7/site-packages/virtualenv.py", line 963, in call_subprocess
    raise OSError("Command {} failed with error code {}".format(cmd_desc, proc.returncode))
OSError: Command /Users/travis/build/...bids/venv/bin/python - setuptools pip wheel failed with error code 1
```

This does not error for Python 3.6+ (Python 3.5 on OSX has had conda-related issues for a while) or for any version we run on Linux. All of them upgrade `virtualenv` to the latest before running.

**Comment by effigies** [comment]
Hmm. Happening on 16.7.2, now. I guess it's not virtualenv. I'll try to track this down more. I'll reopen if it turns out to be virtualenv.
