### ISSUE TITLE
Test suite blows up under (tox running under) pypy

### ISSUE THREAD

**Issue by Julian** [pypa/virtualenv#1420]
This seems likely to actually be an upstream tox issue, or an upstream pypy3 issue (from how early on in
the process it occurs), but filing it here anyways since I'm at the packaging
sprint (originally trying to fix #1193) but not sure whether I'll get all the way to the bottom of this.

But the following blows up when run on virtualenv's test suite / tox setup:

```sh
?  rm -rf venv; pypy3 -m venv venv && venv/bin/pip install -U pip && venv/bin/pip install tox && venv/bin/tox |& pbcopy
Traceback (most recent call last):
  File "venv/bin/tox", line 10, in <module>
    sys.exit(cmdline())
  File "/Users/julian/Development/virtualenv/venv/site-packages/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File "/Users/julian/Development/virtualenv/venv/site-packages/tox/session/__init__.py", line 68, in main
    exit_code = session.runcommand()
  File "/Users/julian/Development/virtualenv/venv/site-packages/tox/session/__init__.py", line 192, in runcommand
    return self.subcommand_test()
  File "/Users/julian/Development/virtualenv/venv/site-packages/tox/session/__init__.py", line 208, in subcommand_test
    venv.package = self.hook.tox_package(session=self, venv=venv)
  File "/Users/julian/Development/virtualenv/venv/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/julian/Development/virtualenv/venv/site-packages/pluggy/manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/julian/Development/virtualenv/venv/site-packages/pluggy/manager.py", line 86, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/julian/Development/virtualenv/venv/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/julian/Development/virtualenv/venv/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/julian/Development/virtualenv/venv/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/julian/Development/virtualenv/venv/site-packages/tox/package/__init__.py", line 16, in tox_package
    session.package, session.dist = get_package(session)
  File "/Users/julian/Development/virtualenv/venv/site-packages/tox/package/__init__.py", line 29, in get_package
    package = acquire_package(config, session)
  File "/Users/julian/Development/virtualenv/venv/site-packages/tox/package/__init__.py", line 40, in acquire_package
    path = build_package(config, session)
  File "/Users/julian/Development/virtualenv/venv/site-packages/tox/package/builder/__init__.py", line 9, in build_package
    return build(config, session)
  File "/Users/julian/Development/virtualenv/venv/site-packages/tox/package/builder/isolated.py", line 33, in build
    build_requires = get_build_requires(build_info, package_venv, config.setupdir)
  File "/Users/julian/Development/virtualenv/venv/site-packages/tox/package/builder/isolated.py", line 128, in get_build_requires
    return json.loads(result.split("\n")[-2])
  File "/usr/local/Cellar/pypy3/7.1.1_1/libexec/lib-python/3/json/__init__.py", line 361, in loads
    if _pypyjson else _default_decoder.decode(s))
json.decoder.JSONDecodeError: Unexpected 'i' at: line 1 column 3 (char 2)
```

I use tox + pypy3 all the time, so if this *is* an upstream issue I have a sneaky suspicion it's related to `isolated`, but will update this if/when I find the underlying issue (or figure out that I've done something dumb).

**Comment by Julian** [comment]
OK, via a debugger, starting to confirm this is likely an upstream tox + isolated issue (or PyPy issue)...

From a debugger, in tox, [get_build_requires](https://github.com/tox-dev/tox/blob/b0c5331a3d1157dde6b92c4c5123d89a38e3c7c0/src/tox/package/builder/isolated.py#L115-L127) results in:

```
>>> result
'["setuptools>=40.6.3"]\n'
```

but on PyPy:

```
>>> result
'["setuptools>=40.6.3"]\n/Users/julian/Development/virtualenv/.tox/.package/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp
module is deprecated in favour of importlib; see the module\'s documentation for alternative uses\n  import imp\n'
```

Now to figure out who/what's assuming it has a clean stdout there...

**Comment by gaborbernat** [comment]
closing as it's a tox issue
