### ISSUE TITLE
python2: posix_spawn: <ENV_DIR>/bin/python22.7: No such file or directory

### ISSUE THREAD

**Issue by mhyousefi** [pypa/virtualenv#1427]
Hi, I'm trying to create a `virtualenv` for `Python 2.7` on MacOS (`ZSH` shell). I use the command `virtualenv -p /usr/local/bin/python2 <ENV_DIR>`. I get the following stack trace:
```
Running virtualenv with interpreter /usr/local/bin/python2
New python executable in <ENV_DIR>/bin/python2
Also creating executable in <ENV_DIR>/bin/python
python2: posix_spawn: <ENV_DIR>/bin/python22.7: No such file or directory
Installing setuptools, pip, wheel...
  Complete output from command <ENV_DIR>/bin/python2 - setuptools pip wheel:
  python2: posix_spawn: <ENV_DIR>/bin/python22.7: No such file or directory
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 2349, in <module>
    main()
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 953, in create_environment
    download=download,
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 904, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 796, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command <ENV_DIR>/bin/python2 - setuptools pip wheel failed with error code 1
```

The **`python22.7`** part is extremely confusing to me! How can I resolve this issue?

Now, I have the following Python installations:
```
ls /usr/local/bin/python                                                                                   
python2@            python3@            python3-config@     python3.7@          python3.7-config@   python3.7m@         python3.7m-config@
```

And upon running `python2.7`, I enter the Python 2.7 interpreter on my shell:
```
Python 2.7.10 (default, Feb 22 2019, 21:55:15) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

This is the result of `pip list`:
```
Package                  Version     Location                                              
------------------------ ----------- ------------------------------------------------------
absl-py                  0.3.0       
aiohttp                  4.0.0a1     
alabaster                0.7.12      
appnope                  0.1.0       
argh                     0.26.2      
asn1crypto               1.0.1       
astor                    0.7.1       
async-timeout            3.0.1       
atomicwrites             1.3.0       
attrs                    19.2.0      
Babel                    2.7.0       
backcall                 0.1.0       
Beaker                   1.11.0      
bleach                   2.1.3       
certifi                  2019.9.11   
cffi                     1.12.3      
chardet                  3.0.4       
click                    6.7         
cloudpickle              0.5.3       
cryptography             2.3         
cycler                   0.10.0      
dask                     0.18.2      
decorator                4.3.0       
distributed              1.22.1      
dj-config-url            0.1.1       
Django                   2.0.7       
djangorestframework      3.10.2      
djangorestframework-jwt  1.11.0      
docutils                 0.15.2      
entrypoints              0.3         
falcon                   1.1.0       
falcon-cors              1.1.7       
flake8                   3.7.8       
gast                     0.2.0       
gevent                   1.5a1       
graphviz                 0.8.4       
greenlet                 0.4.15      
grpcio                   1.13.0      
gunicorn                 19.9.0      
h5py                     2.8.0       
HeapDict                 1.0.0       
html5lib                 1.0.1       
icalendar                4.0.3       
idna                     2.8         
imagesize                1.1.0       
importlib-metadata       0.23        
ipykernel                4.8.2       
ipython                  6.5.0       
ipython-genutils         0.2.0       
ipywidgets               7.3.1       
irisclient               1.3.0       
jedi                     0.12.1      
Jinja2                   2.10        
jsonschema               2.6.0       
jupyter                  1.0.0       
jupyter-client           5.2.3       
jupyter-console          5.2.0       
jupyter-core             4.4.0       
Keras                    2.2.2       
Keras-Applications       1.0.4       
Keras-Preprocessing      1.0.2       
kiwisolver               1.0.1       
livereload               2.6.1       
locket                   0.2.0       
Markdown                 2.6.11      
MarkupSafe               1.0         
matplotlib               3.0.0       
mccabe                   0.6.1       
mistune                  0.8.3       
more-itertools           7.2.0       
msgpack                  0.5.6       
multidict                4.5.2       
nbconvert                5.3.1       
nbformat                 4.4.0       
notebook                 5.6.0       
numpy                    1.15.0      
oncall                   1.1.0       <PATH2Proj>/oncall/src
packaging                19.2        
pandas                   0.23.3      
pandocfilters            1.4.2       
parso                    0.3.1       
partd                    0.3.8       
pathtools                0.1.2       
pexpect                  4.6.0       
phonenumbers             8.10.20     
pickleshare              0.7.4       
Pillow                   5.2.0       
pip                      19.2.3      
pluggy                   0.13.0      
port-for                 0.3.1       
prometheus-client        0.3.1       
prompt-toolkit           1.0.15      
protobuf                 3.6.0       
psutil                   5.4.6       
ptyprocess               0.6.0       
py                       1.8.0       
pyasn1                   0.4.7       
pyasn1-modules           0.2.6       
pycodestyle              2.5.0       
pycparser                2.19        
pyeasyga                 0.3.1       
pyflakes                 2.1.1       
Pygments                 2.2.0       
PyJWT                    1.7.1       
pyldap                   3.0.0.post1 
pymsteams                0.1.12      
PyMySQL                  0.9.3       
pyparsing                2.2.1       
pytest                   5.2.1       
pytest-mock              1.11.1      
python-dateutil          2.7.3       
python-ldap              3.2.0       
python-mimeparse         1.6.0       
pytz                     2018.5      
PyYAML                   3.13        
pyzmq                    17.1.0      
qtconsole                4.3.1       
requests                 2.22.0      
scikit-learn             0.19.2      
scipy                    1.1.0       
Send2Trash               1.5.0       
setuptools               39.1.0      
simplegeneric            0.8.1       
six                      1.11.0      
sklearn                  0.0         
sklearn-pandas           1.7.0       
slackclient              2.2.1       
snowballstemmer          2.0.0       
sortedcontainers         2.0.4       
Sphinx                   1.5.6       
sphinx-autobuild         0.7.1       
sphinx-rtd-theme         0.4.3       
sphinxcontrib-httpdomain 1.7.0       
SQLAlchemy               1.3.10      
streql                   3.0.2       
tblib                    1.3.2       
tensorboard              1.9.0       
tensorflow               1.9.0       
termcolor                1.1.0       
terminado                0.8.1       
testpath                 0.3.1       
toolz                    0.9.0       
torch                    0.4.1       
torchvision              0.2.1       
tornado                  5.1         
traitlets                4.3.2       
typing-extensions        3.7.4       
ujson                    1.35        
urllib3                  1.25.6      
watchdog                 0.9.0       
wcwidth                  0.1.7       
webassets                0.12.1      
webencodings             0.5.1       
Werkzeug                 0.14.1      
wheel                    0.31.1      
widgetsnbextension       3.3.1       
xlrd                     1.1.0       
yarl                     1.4.0a11    
zict                     0.1.3       
zipp                     0.6.0
```

**Comment by gaborbernat** [comment]
This should be fixed by the rewrite branch.
