### ISSUE TITLE
OSError: Command /home/x/prj/fd_dev/.venv/bin/python3.7 - setuptools pip wheel failed with error code 1

### ISSUE THREAD

**Issue by 1lin24** [pypa/virtualenv#1432]
I get an error like title when I use command:
```
virtualenv --no-site-packages .venv
```

Here is my environment:

* CentOS 7
```
~/prj/fd_dev(2.0) » pyenv --version                               x@1lin24
pyenv 1.2.14-5-g68a77df0
---------------------------------------------------------------------------
~/prj/fd_dev(2.0) » pyenv versions                                x@1lin24
  system
* 3.7.5 (set by /home/x/.pyenv/version)
  3.8.0
---------------------------------------------------------------------------
~/prj/fd_dev(2.0) » pip list                                      x@1lin24
Package    Version
---------- -------
pip        19.3.1 
setuptools 41.2.0 
virtualenv 16.7.6 
```

And here is what I got:
```
virtualenv --no-site-packages .venv           x@1lin24
Using base prefix '/home/x/.pyenv/versions/3.7.5'
New python executable in /home/x/prj/fd_dev/.venv/bin/python3.7
Not overwriting existing python script /home/x/prj/fd_dev/.venv/bin/python (you must use /home/x/prj/fd_dev/.venv/bin/python3.7)
Command /home/x/prj/fd_dev/.venv/bin/python3.7 -m pip config list had error code 1
Installing setuptools, pip, wheel...

  Complete output from command /home/x/prj/fd_dev/.venv/bin/python3.7 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 10, in <module>
  File "/home/x/.pyenv/versions/3.7.5/lib/python3.7/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/__init__.py", line 40, in <module>
  File "/home/x/.pyenv/versions/3.7.5/lib/python3.7/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/cli/autocompletion.py", line 8, in <module>
  File "/home/x/.pyenv/versions/3.7.5/lib/python3.7/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/cli/main_parser.py", line 12, in <module>
  File "/home/x/.pyenv/versions/3.7.5/lib/python3.7/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/commands/__init__.py", line 6, in <module>
  File "/home/x/.pyenv/versions/3.7.5/lib/python3.7/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/commands/completion.py", line 6, in <module>
  File "/home/x/.pyenv/versions/3.7.5/lib/python3.7/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/cli/base_command.py", line 20, in <module>
  File "/home/x/.pyenv/versions/3.7.5/lib/python3.7/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/download.py", line 37, in <module>
  File "/home/x/.pyenv/versions/3.7.5/lib/python3.7/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/utils/glibc.py", line 3, in <module>
  File "/home/x/.pyenv/versions/3.7.5/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 13, in <module>
ImportError: cannot import name 'main' from 'pip' (/home/x/.pyenv/versions/3.7.5/lib/python3.7/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/__init__.py)
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/home/x/.pyenv/versions/3.7.5/bin/virtualenv", line 8, in <module>
    sys.exit(main())
  File "/home/x/.pyenv/versions/3.7.5/lib/python3.7/site-packages/virtualenv.py", line 870, in main
    symlink=options.symlink,
  File "/home/x/.pyenv/versions/3.7.5/lib/python3.7/site-packages/virtualenv.py", line 1173, in create_environment
    install_wheel(to_install, py_executable, search_dirs, download=download)
  File "/home/x/.pyenv/versions/3.7.5/lib/python3.7/site-packages/virtualenv.py", line 1019, in install_wheel
    _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs)
  File "/home/x/.pyenv/versions/3.7.5/lib/python3.7/site-packages/virtualenv.py", line 1110, in _install_wheel_with_search_dir
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=script)
  File "/home/x/.pyenv/versions/3.7.5/lib/python3.7/site-packages/virtualenv.py", line 963, in call_subprocess
    raise OSError("Command {} failed with error code {}".format(cmd_desc, proc.returncode))
OSError: Command /home/x/prj/fd_dev/.venv/bin/python3.7 - setuptools pip wheel failed with error code 1

```

Thanks for your help.

**Comment by gaborbernat** [comment]
Seems like the bundled wheel is not compatible with your platform. Can you test with virtualenv --no-site-packages .venv --download?

**Comment by pfmoore** [comment]
See https://github.com/pypa/pip/pull/6678 - prior to this change, pip's glibc detection assumed Python was built with ctypes available.
