### ISSUE TITLE
Failed install virtualenv 20.0.0b1 for Ubuntu14.04

### ISSUE THREAD

**Issue by pelliu** [pypa/virtualenv#1537]
Our image(OS Ubuntu 14.04) test virtual env installation failed, the python version we installed is 2.7.6, and the error log thus, but I saw the latest virtualenv version can support py2.7, so anyone can help on this? Thanks!

> [Step 5/5] ++ sudo pip install virtualenv
[20:14:39]	[Step 5/5] Traceback (most recent call last):
[20:14:39]	[Step 5/5]   File "/usr/local/bin/pip", line 7, in <module>
[20:14:39]	[Step 5/5]     from pip._internal.cli.main import main
[20:14:39]	[Step 5/5]   File "/usr/local/lib/python3.4/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
[20:14:39]	[Step 5/5]     from pip._internal.cli.autocompletion import autocomplete
[20:14:39]	[Step 5/5]   File "/usr/local/lib/python3.4/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
[20:14:39]	[Step 5/5]     from pip._internal.cli.main_parser import create_main_parser
[20:14:39]	[Step 5/5]   File "/usr/local/lib/python3.4/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
[20:14:39]	[Step 5/5]     from pip._internal.cli import cmdoptions
[20:14:39]	[Step 5/5]   File "/usr/local/lib/python3.4/dist-packages/pip/_internal/cli/cmdoptions.py", line 28, in <module>
[20:14:39]	[Step 5/5]     from pip._internal.models.target_python import TargetPython
[20:14:39]	[Step 5/5]   File "/usr/local/lib/python3.4/dist-packages/pip/_internal/models/target_python.py", line 4, in <module>
[20:14:39]	[Step 5/5]     from pip._internal.utils.misc import normalize_version_info
[20:14:39]	[Step 5/5]   File "/usr/local/lib/python3.4/dist-packages/pip/_internal/utils/misc.py", line 20, in <module>
[20:14:39]	[Step 5/5]     from pip._vendor import pkg_resources
[20:14:39]	[Step 5/5]   File "/usr/local/lib/python3.4/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 92, in <module>
[20:14:39]	[Step 5/5]     raise RuntimeError("Python 3.5 or later is required")
[20:14:39]	[Step 5/5] RuntimeError: Python 3.5 or later is required

**Comment by gaborbernat** [comment]
Can you display the verbose install log (pip install -vvv virtualenv), also seems like you're installing 16.7.7 instead of 20.0.0b1

**Comment by gaborbernat** [comment]
Closing for no feedback. We'll reopen if you can get back to us.
