### ISSUE TITLE
zipapp virtual environment creation fails if zipapp path not absolute on python3.4/3.5/3.6

### ISSUE THREAD

**Issue by asottile** [pypa/virtualenv#1543]
```console
$ python3 virtualenv.pyz --version
virtualenv 20.0.0b2 from virtualenv.pyz/virtualenv/__init__.py
$ python3 --version --version
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
$ uname -a
Linux asottile-MacBookPro 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

```console
$ python3 virtualenv.pyz venv
Traceback (most recent call last):
  File "/tmp/virtualenv.pyz/__virtualenv__/importlib_resources-1.0.2-py2.py3-none-any/importlib_resources/_py3.py", line 120, in open_text
NotADirectoryError: [Errno 20] Not a directory: '/tmp/virtualenv.pyz/virtualenv/activation/bash/activate.sh'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "virtualenv.pyz/__main__.py", line 169, in <module>
  File "virtualenv.pyz/__main__.py", line 165, in run
  File "virtualenv.pyz/virtualenv/__main__.py", line 16, in run
  File "virtualenv.pyz/virtualenv/run/__init__.py", line 22, in run_via_cli
  File "virtualenv.pyz/virtualenv/session.py", line 20, in run
  File "virtualenv.pyz/virtualenv/session.py", line 40, in _activate
  File "virtualenv.pyz/virtualenv/activation/via_template.py", line 26, in generate
  File "virtualenv.pyz/virtualenv/activation/via_template.py", line 41, in _generate
  File "virtualenv.pyz/virtualenv/activation/via_template.py", line 50, in instantiate_template
  File "/tmp/virtualenv.pyz/__virtualenv__/importlib_resources-1.0.2-py2.py3-none-any/importlib_resources/_py3.py", line 158, in read_text
  File "/tmp/virtualenv.pyz/__virtualenv__/importlib_resources-1.0.2-py2.py3-none-any/importlib_resources/_py3.py", line 134, in open_text
FileNotFoundError: 'activate.sh' resource not found in 'virtualenv.activation.bash'
```

**Comment by gaborbernat** [comment]
Feels like I've published a bad zipapp 🤔 to get-virtualenv.

**Comment by gaborbernat** [comment]
@asottile I'm having trouble replicating this, can you please run it with `-vvv`? And post the log like that. You might want to start with clearing virtualenv appdata before doing that (``-h`` will display its location).

**Comment by gaborbernat** [comment]
Never mind managed to replicate 😆

**Comment by gaborbernat** [comment]
Sigh, this is just another manifestation of upstream bug https://gitlab.com/python-devs/importlib_resources/issues/75; just pass the absolute path for now and you'll be OK; until we fix upstream.

**Comment by gaborbernat** [comment]
I'll close this now as there's no actionable element on our side, please comment on the upstream issue if this is affecting you.
