### ISSUE TITLE
Tox broken with `ImportError: cannot import name 'ensure_text'` on TravisCI

### ISSUE THREAD

**Issue by waylan** [pypa/virtualenv#1586]
This failure appears to be different than the other recently reported failures.

Our CI builds starting failing today, but only for Python 3.6 and pypy3, not Python 3.5, 3.7, or 3.8. The failure occurred on [multiple][1] [different][2] [PRs][3]. The more recent failures provided this output:

```
$ tox
GLOB sdist-make: /home/travis/build/mkdocs/mkdocs/setup.py
py36-unittests create: /home/travis/build/mkdocs/mkdocs/.tox/py36-unittests
ERROR: invocation failed (exit code 1), logfile: /home/travis/build/mkdocs/mkdocs/.tox/py36-unittests/log/py36-unittests-0.log
================================== log start ===================================
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/virtualenv/__main__.py", line 30, in run_with_catch
    run(args, options)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/virtualenv/__main__.py", line 12, in run
    from virtualenv.run import run_via_cli
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/virtualenv/run/__init__.py", line 7, in <module>
    from ..config.cli.parser import VirtualEnvConfigParser
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/virtualenv/config/cli/parser.py", line 6, in <module>
    from ..ini import IniConfig
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/virtualenv/config/ini.py", line 8, in <module>
    from virtualenv.dirs import default_config_dir
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/virtualenv/dirs.py", line 5, in <module>
    from virtualenv.util.lock import ReentrantFileLock
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/virtualenv/util/lock.py", line 11, in <module>
    from virtualenv.util.path import Path
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/virtualenv/util/path/__init__.py", line 5, in <module>
    from ._sync import copy, copytree, ensure_dir, link, symlink
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/virtualenv/util/path/_sync.py", line 7, in <module>
    from six import PY2, PY3, ensure_text
ImportError: cannot import name 'ensure_text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/3.6.3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python/3.6.3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/virtualenv/__main__.py", line 41, in <module>
    run_with_catch()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/virtualenv/__main__.py", line 32, in run_with_catch
    if options.with_traceback:
AttributeError: 'Namespace' object has no attribute 'with_traceback'

=================================== log end ====================================
ERROR: InvocationError for command /home/travis/virtualenv/python3.6.3/bin/python -m virtualenv --no-download --python /home/travis/virtualenv/python3.6.3/bin/python py36-unittests (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py36-unittests: InvocationError for command /home/travis/virtualenv/python3.6.3/bin/python -m virtualenv --no-download --python /home/travis/virtualenv/python3.6.3/bin/python py36-unittests (exited with code 1)
The command "tox" exited with 1.
```

However, older failures provided a shorter, less helpful output:

```
$ tox
GLOB sdist-make: /home/travis/build/mkdocs/mkdocs/setup.py
py36-min-req create: /home/travis/build/mkdocs/mkdocs/.tox/py36-min-req
ERROR: invocation failed (exit code 1), logfile: /home/travis/build/mkdocs/mkdocs/.tox/py36-min-req/log/py36-min-req-0.log
================================== log start ===================================
ERROR:root:ImportError: cannot import name 'ensure_text'

=================================== log end ====================================
ERROR: InvocationError for command /home/travis/virtualenv/python3.6.3/bin/python -m virtualenv --no-download --python /home/travis/virtualenv/python3.6.3/bin/python py36-min-req (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py36-min-req: InvocationError for command /home/travis/virtualenv/python3.6.3/bin/python -m virtualenv --no-download --python /home/travis/virtualenv/python3.6.3/bin/python py36-min-req (exited with code 1)
The command "tox" exited with 1.
```

Given the time difference, presumably, the later failures with longer output were from the 2.0.2 release while the earlier failures with shorter output were from 2.0.1.

The only relevant dependency is a `pip install tox` command in our `travis.yml` file), which installs `tox` along with its latest dependencies, presumably including `virtualenv` and `six`.

The relevant bit appears to be this:

```
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/virtualenv/util/path/_sync.py", line 7, in <module>
    from six import PY2, PY3, ensure_text
ImportError: cannot import name 'ensure_text'
```

Why `six`'s [`unsure_text`][4] function would be available in only some Python versions (3.5, 3.7 and 3.8) but not others (3.6 and pypy3) is not clear to me.

[1]: https://travis-ci.org/mkdocs/mkdocs/builds/648910825?utm_source=github_status&utm_medium=notification
[2]: https://travis-ci.org/mkdocs/mkdocs/builds/649050383?utm_source=github_status&utm_medium=notification
[3]: https://travis-ci.org/mkdocs/mkdocs/builds/649065580?utm_source=github_status&utm_medium=notification
[4]: https://six.readthedocs.io/#six.ensure_text

**Comment by gaborbernat** [comment]
I think this is related to the Travis images being broken 🤔

**Comment by waylan** [comment]
What leads you to believe Travis images are broken? AFAICT, the problem was introduced with the new version of virtualenv.

**Comment by waylan** [comment]
By the way, I added the following before the `pip install tox` line to my travis config and the error has gone away:

```
pip install 'virtualenv<2.0.0'
```

As far as I can tell, virutalenv 20 is causing this error.

**Comment by gaborbernat** [comment]
It's pip issue, does not respect our install requires if the target already has any six 🤷‍♂️
