### ISSUE TITLE
writefile chuckles on str

### ISSUE THREAD

**Issue by tgulacsi** [pypa/virtualenv#162]
Hi, 

virtualenv.py:437 throws 

```
tgulacsi@tgulacsi-desktop:/tmp$ virtualenv -p ~/Letöltések/pypy-c-jit-43780-b590cf6de419-linux64/bin/pypy pypy
Running virtualenv with interpreter /home/tgulacsi/Letöltések/pypy-c-jit-43780-b590cf6de419-linux64/bin/pypy
Overwriting pypy/lib-python/modified-2.7/orig-prefix.txt with new content
Traceback (most recent call last):
  File "app_main.py", line 53, in run_toplevel
  File "/usr/local/lib/python2.7/dist-packages/virtualenv-1.6.4-py2.7.egg/virtualenv.py", line 1952, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/virtualenv-1.6.4-py2.7.egg/virtualenv.py", line 810, in main
    never_download=options.never_download)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv-1.6.4-py2.7.egg/virtualenv.py", line 901, in create_environment
    site_packages=site_packages, clear=clear))
  File "/usr/local/lib/python2.7/dist-packages/virtualenv-1.6.4-py2.7.egg/virtualenv.py", line 1049, in install_python
    writefile(join(site_dir, 'orig-prefix.txt'), prefix)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv-1.6.4-py2.7.egg/virtualenv.py", line 437, in writefile
    f.write(content.encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 18: ordinal not in range(128)
```

Obvious fix:

```
diff --git a/virtualenv.py b/virtualenv.py
index c173dd4..fd26a19 100644
--- a/virtualenv.py
+++ b/virtualenv.py
@@ -434,7 +434,8 @@ def writefile(dest, content, overwrite=True):
                 return
             logger.notify('Overwriting %s with new content', dest)
             f = open(dest, 'wb')
-            f.write(content.encode('utf-8'))
+            f.write(content.encode('utf-8') if isinstance(content, unicode) 
+                    else content)
             f.close()
         else:
             logger.info('Content %s already in place', dest)
```

GThomas

**Comment by gaborbernat** [comment]
I don' think this should still exist.
