### ISSUE TITLE
OS Error 9 when trying to create a virtual env for a specific python version

### ISSUE THREAD

**Issue by ShaleenAg** [pypa/virtualenv#1722]
**Issue**

whenever I try to create a virtual environment for a specific version of python (3.6.0 in this case) . I 
get the following error 

code : 
    virtualenv -p C:\Users\Shaleen\AppData\Local\Programs\Python\Python36\python.exe venv
output:- 
    OSError: [Errno 9] Bad file descriptor

**Environment**

Provide at least:
- OS: Win10
- ``pip list`` of the host python where ``virtualenv`` is installed:

```console
Package                  Version
------------------------ ------------------
absl-py                  0.8.1
aiofiles                 0.4.0
aiohttp                  3.6.2
appdirs                  1.4.3
APScheduler              3.6.3
astor                    0.8.0
async-generator          1.10
async-timeout            3.0.1
attrs                    19.3.0
Automat                  0.8.0
backcall                 0.1.0
bert                     2.2.0
bert-dp                  1.0
bleach                   3.1.0
boto3                    1.11.0
botocore                 1.14.0
bz2file                  0.98
cachetools               3.1.1
certifi                  2019.9.11
cffi                     1.13.1
chardet                  3.0.4
Click                    7.0
cloudpickle              1.2.2
colorama                 0.4.1
colorclass               2.2.0
coloredlogs              10.0
colorhash                1.0.2
ConfigArgParse           1.0
constantly               15.1.0
cryptography             2.8
cssselect                1.1.0
cycler                   0.10.0
Cython                   0.29.12
DAWG-Python              0.7.2
decorator                4.4.0
deeppavlov               0.7.1
defusedxml               0.6.0
dill                     0.3.1.1
distlib                  0.3.0
dnspython                1.16.0
docopt                   0.6.2
docutils                 0.15.2
dopamine-rl              3.0.1
entrypoints              0.3
erlastic                 2.0.0
fastapi                  0.38.1
fbmessenger              6.0.0
filelock                 3.0.12
Flask                    1.1.1
future                   0.18.2
fuzzywuzzy               0.17.0
gast                     0.2.2
gevent                   1.4.0
gin-config               0.3.0
google-api-python-client 1.7.11
google-auth              1.6.3
google-auth-httplib2     0.0.3
google-auth-oauthlib     0.4.1
google-pasta             0.1.7
googleapis-common-protos 1.6.0
graphviz                 0.8.4
greenlet                 0.4.15
grpcio                   1.24.3
gunicorn                 20.0.4
gym                      0.15.4
h11                      0.8.1
h2                       3.1.1
h5py                     2.9.0
hpack                    3.0.0
httpcore                 0.3.0
httplib2                 0.15.0
httptools                0.0.13
humanfriendly            4.18
hyperframe               5.2.0
hyperlink                19.0.0
idna                     2.8
imageio                  2.5.0
importlib-metadata       0.23
incremental              17.5.0
ipykernel                5.1.3
ipython                  7.9.0
ipython-genutils         0.2.0
ipywidgets               7.5.1
itsdangerous             1.1.0
jedi                     0.15.1
Jinja2                   2.10.3
jmespath                 0.9.4
joblib                   0.14.0
jsonpickle               1.2
jsonschema               3.1.1
jupyter                  1.0.0
jupyter-client           5.3.4
jupyter-console          6.0.0
jupyter-core             4.6.1
Keras                    2.2.4
Keras-Applications       1.0.8
Keras-Preprocessing      1.1.0
kfac                     0.2.0
kiwisolver               1.1.0
lxml                     4.4.2
Markdown                 3.1.1
MarkupSafe               1.1.1
matplotlib               3.1.1
mattermostwrapper        2.1
mesh-tensorflow          0.1.9
mistune                  0.8.4
more-itertools           7.2.0
mpmath                   1.1.0
multidict                4.6.1
mxnet                    1.4.1
mysql                    0.0.2
mysql-connector-python   8.0.17
mysqlclient              1.4.5
nbconvert                5.6.1
nbformat                 4.4.0
networkx                 2.3
nltk                     3.2.5
notebook                 6.0.2
numpy                    1.16.4
oauth2client             4.1.3
oauthlib                 3.1.0
opencv-python            4.1.1.26
opt-einsum               3.1.0
overrides                1.9
packaging                19.2
pandas                   0.24.2
pandocfilters            1.4.2
parsel                   1.5.2
parso                    0.5.1
pickleshare              0.7.5
pika                     1.0.1
Pillow                   6.1.0
pip                      19.3.1
progressbar2             3.39.3
prometheus-client        0.7.1
promise                  2.3
prompt-toolkit           2.0.10
Protego                  0.1.15
protobuf                 3.10.0
pyasn1                   0.4.7
pyasn1-modules           0.2.7
pycparser                2.19
pydantic                 0.32.2
PyDispatcher             2.0.5
pydot                    1.4.1
pyglet                   1.3.2
Pygments                 2.4.2
PyHamcrest               1.9.0
PyJWT                    1.7.1
pykwalify                1.7.0
pymongo                  3.10.1
pymorphy2                0.8
pymorphy2-dicts          2.4.393442.3710985
pymorphy2-dicts-ru       2.4.404381.4453942
pyOpenSSL                19.0.0
pyparsing                2.4.0
pypng                    0.0.20
pyreadline               2.1
pyrsistent               0.15.5
pyTelegramBotAPI         3.6.6
pytesseract              0.3.0
python-crfsuite          0.9.6
python-dateutil          2.8.0
python-engineio          3.11.2
python-socketio          4.4.0
python-telegram-bot      11.1.0
python-utils             2.3.0
pytz                     2019.1
pyvips                   2.1.8
PyWavelets               1.0.3
pywin32                  225
pywinpty                 0.5.5
PyYAML                   5.1.1
pyzmq                    18.1.0
qtconsole                4.6.0
questionary              1.4.0
queuelib                 1.5.0
rasa                     1.6.1
rasa-sdk                 1.6.1
redis                    3.3.11
requests                 2.22.0
requests-async           0.5.0
requests-oauthlib        1.2.0
requests-toolbelt        0.9.1
rfc3986                  1.3.2
rocketchat-API           0.6.36
rsa                      4.0
ruamel.yaml              0.15.100
rusenttokenize           0.0.5
s3transfer               0.3.0
sanic                    19.9.0
Sanic-Cors               0.9.9.post1
sanic-jwt                1.4.0
Sanic-Plugins-Framework  0.8.2.post1
scikit-image             0.15.0
scikit-learn             0.21.2
scipy                    1.3.0
Scrapy                   1.8.0
seaborn                  0.9.0
Send2Trash               1.5.0
service-identity         18.1.0
setuptools               41.6.0
six                      1.12.0
sklearn-crfsuite         0.3.6
slackclient              1.3.2
SQLAlchemy               1.3.12
starlette                0.12.8
sugartensor              1.0.0.2
sympy                    1.5.1
tabulate                 0.8.6
tensor2tensor            1.14.1
tensorboard              1.14.0
tensorflow               1.15.0
tensorflow-datasets      1.3.2
tensorflow-estimator     1.14.0
tensorflow-gan           2.0.0
tensorflow-gpu           1.14.0
tensorflow-hub           0.7.0
tensorflow-metadata      0.21.0
tensorflow-probability   0.7.0
tensorlayer              2.1.0
termcolor                1.1.0
terminado                0.8.2
terminaltables           3.1.0
tesseract                0.1.3
testpath                 0.4.4
Theano                   1.0.4
tornado                  6.0.3
tqdm                     4.32.2
traitlets                4.3.3
twilio                   6.35.2
Twisted                  19.10.0
tzlocal                  2.0.0
uritemplate              3.0.1
urllib3                  1.25.6
uvicorn                  0.9.0
virtualenv               20.0.10
w3lib                    1.21.0
wcwidth                  0.1.7
webencodings             0.5.1
webexteamssdk            1.2
websocket-client         0.54.0
websockets               8.1
Werkzeug                 0.16.0
wheel                    0.33.6
widgetsnbextension       3.5.1
wrapt                    1.11.2
xlrd                     1.2.0
yarl                     1.4.2
zipp                     0.6.0
zope.interface           4.7.1
```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console

528 setup logging to NOTSET [DEBUG report:43]
529 could not create app data folder C:\Users\Shaleen\AppData\Local\pypa\virtualenv due to FileNotFoundError(2, 'The system cannot find the path specified') [INFO app_data:54]
658 created temporary app data folder D:\Temporary\temp1\tmpgx5dfvso [DEBUG app_data:32]
658 find interpreter for spec PythonSpec(path=C:\Users\Shaleen\AppData\Local\Programs\Python\Python36\python.exe) [INFO builtin:44]
659 Attempting to acquire lock 2426337143608 on D:\Temporary\temp1\tmpgx5dfvso\py_info\20.0.10\62d096c24dd080dd59c18a8bcc978f1f90dd8322c13b0cc3bae1e262ea8ffa6c.lock [DEBUG filelock:270]
660 Lock 2426337143608 acquired on D:\Temporary\temp1\tmpgx5dfvso\py_info\20.0.10\62d096c24dd080dd59c18a8bcc978f1f90dd8322c13b0cc3bae1e262ea8ffa6c.lock [INFO filelock:274]
660 get interpreter info via cmd: 'C:\Users\Shaleen\AppData\Local\Programs\Python\Python36\python.exe' 'c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\discovery\py_info.py' [DEBUG cached_py_info:105]
1013 write PythonInfo to D:\Temporary\temp1\tmpgx5dfvso\py_info\20.0.10\62d096c24dd080dd59c18a8bcc978f1f90dd8322c13b0cc3bae1e262ea8ffa6c.json for C:\Users\Shaleen\AppData\Local\Programs\Python\Python36\python.exe [DEBUG cached_py_info:91]
1148 Attempting to release lock 2426337143608 on D:\Temporary\temp1\tmpgx5dfvso\py_info\20.0.10\62d096c24dd080dd59c18a8bcc978f1f90dd8322c13b0cc3bae1e262ea8ffa6c.lock [DEBUG filelock:315]
1148 Lock 2426337143608 released on D:\Temporary\temp1\tmpgx5dfvso\py_info\20.0.10\62d096c24dd080dd59c18a8bcc978f1f90dd8322c13b0cc3bae1e262ea8ffa6c.lock [INFO filelock:318]
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Shaleen\AppData\Local\Programs\Python\Python37\Scripts\virtualenv.exe\__main__.py", line 7, in <module>
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\__main__.py", line 50, in run_with_catch
    run(args, options)
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\__main__.py", line 20, in run
    session = cli_run(args, options)
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\run\__init__.py", line 27, in cli_run
    session = session_via_cli(args, options)
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\run\__init__.py", line 35, in session_via_cli
    parser = build_parser(args, options)
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\run\__init__.py", line 71, in build_parser
    parser._interpreter = interpreter = discover.interpreter
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\discovery\discover.py", line 44, in interpreter
    self._interpreter = self.run()
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\discovery\builtin.py", line 33, in run
    return get_interpreter(self.python_spec, self.app_data.folder)
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\discovery\builtin.py", line 46, in get_interpreter
    for interpreter, impl_must_match in propose_interpreters(spec, app_data):
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\discovery\builtin.py", line 60, in propose_interpreters
    yield PythonInfo.from_exe(spec.path, app_data), True
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\discovery\py_info.py", line 290, in from_exe
    proposed = from_exe(cls, app_data, exe, raise_on_error=raise_on_error, ignore_cache=ignore_cache)
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\discovery\cached_py_info.py", line 32, in from_exe
    result = _get_from_cache(cls, py_info_cache, app_data, exe, ignore_cache=ignore_cache)
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\discovery\cached_py_info.py", line 56, in _get_from_cache
    py_info = _get_via_file_cache(cls, py_info_cache, app_data, exe_path, exe)
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\discovery\cached_py_info.py", line 92, in _get_via_file_cache
    data_file_path.write_text(ensure_text(json.dumps(file_cache_content, indent=2)))
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\pathlib.py", line 1219, in write_text
    return f.write(data)
OSError: [Errno 9] Bad file descriptor

```

**Comment by gaborbernat** [comment]
Seems first we're trying to use ``C:\Users\Shaleen\AppData\Local\pypa\virtualenv`` but this does not exist, so we fallback to a temporary folder, and looking at the log seems that the file ``D:\Temporary\temp1\tmpgx5dfvso\py_info\20.0.10\62d096c24dd080dd59c18a8bcc978f1f90dd8322c13b0cc3bae1e262ea8ffa6c.json`` cannot be written by the OS. Do you have a write-protected temp folder?

You can also try creating the ``C:\Users\Shaleen\AppData\Local\pypa\virtualenv``  folder, I think that might fix it too. We should create it if does not exists though. A bug fix on our side.

**Comment by ShaleenAg** [comment]
> Seems first we're trying to use `C:\Users\Shaleen\AppData\Local\pypa\virtualenv` but this does not exist, so we fallback to a temporary folder, and looking at the log seems that the file `D:\Temporary\temp1\tmpgx5dfvso\py_info\20.0.10\62d096c24dd080dd59c18a8bcc978f1f90dd8322c13b0cc3bae1e262ea8ffa6c.json` cannot be written by the OS. Do you have a write-protected temp folder?
> 
> You can also try creating the `C:\Users\Shaleen\AppData\Local\pypa\virtualenv` folder, I think that might fix it too. We should create it if does not exists though. A bug fix on our side.

I removed the write protection from my temp folder(never bothered me before but eh..whatever) and created the folders as per the path specified ..not it's giving me this error

C:\Users\Shaleen>virtualenv -p C:\Users\Shaleen\AppData\Local\Programs\Python\Python36\python.exe venv -vvv --with-traceback
531 setup logging to NOTSET [DEBUG report:43]
653 find interpreter for spec PythonSpec(path=C:\Users\Shaleen\AppData\Local\Programs\Python\Python36\python.exe) [INFO builtin:44]
654 Attempting to acquire lock 2209084290552 on C:\Users\Shaleen\AppData\Local\pypa\virtualenv\py_info\20.0.10\62d096c24dd080dd59c18a8bcc978f1f90dd8322c13b0cc3bae1e262ea8ffa6c.lock [DEBUG filelock:270]
656 Lock 2209084290552 acquired on C:\Users\Shaleen\AppData\Local\pypa\virtualenv\py_info\20.0.10\62d096c24dd080dd59c18a8bcc978f1f90dd8322c13b0cc3bae1e262ea8ffa6c.lock [INFO filelock:274]
656 get interpreter info via cmd: 'C:\Users\Shaleen\AppData\Local\Programs\Python\Python36\python.exe' 'c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\discovery\py_info.py' [DEBUG cached_py_info:105]
885 write PythonInfo to C:\Users\Shaleen\AppData\Local\pypa\virtualenv\py_info\20.0.10\62d096c24dd080dd59c18a8bcc978f1f90dd8322c13b0cc3bae1e262ea8ffa6c.json for C:\Users\Shaleen\AppData\Local\Programs\Python\Python36\python.exe [DEBUG cached_py_info:91]
899 Attempting to release lock 2209084290552 on C:\Users\Shaleen\AppData\Local\pypa\virtualenv\py_info\20.0.10\62d096c24dd080dd59c18a8bcc978f1f90dd8322c13b0cc3bae1e262ea8ffa6c.lock [DEBUG filelock:315]
900 Lock 2209084290552 released on C:\Users\Shaleen\AppData\Local\pypa\virtualenv\py_info\20.0.10\62d096c24dd080dd59c18a8bcc978f1f90dd8322c13b0cc3bae1e262ea8ffa6c.lock [INFO filelock:318]
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Shaleen\AppData\Local\Programs\Python\Python37\Scripts\virtualenv.exe\__main__.py", line 7, in <module>
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\__main__.py", line 50, in run_with_catch
    run(args, options)
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\__main__.py", line 20, in run
    session = cli_run(args, options)
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\run\__init__.py", line 27, in cli_run
    session = session_via_cli(args, options)
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\run\__init__.py", line 35, in session_via_cli
    parser = build_parser(args, options)
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\run\__init__.py", line 71, in build_parser
    parser._interpreter = interpreter = discover.interpreter
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\discovery\discover.py", line 44, in interpreter
    self._interpreter = self.run()
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\discovery\builtin.py", line 33, in run
    return get_interpreter(self.python_spec, self.app_data.folder)
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\discovery\builtin.py", line 46, in get_interpreter
    for interpreter, impl_must_match in propose_interpreters(spec, app_data):
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\discovery\builtin.py", line 60, in propose_interpreters
    yield PythonInfo.from_exe(spec.path, app_data), True
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\discovery\py_info.py", line 290, in from_exe
    proposed = from_exe(cls, app_data, exe, raise_on_error=raise_on_error, ignore_cache=ignore_cache)
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\discovery\cached_py_info.py", line 32, in from_exe
    result = _get_from_cache(cls, py_info_cache, app_data, exe, ignore_cache=ignore_cache)
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\discovery\cached_py_info.py", line 56, in _get_from_cache
    py_info = _get_via_file_cache(cls, py_info_cache, app_data, exe_path, exe)
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\discovery\cached_py_info.py", line 92, in _get_via_file_cache
    data_file_path.write_text(ensure_text(json.dumps(file_cache_content, indent=2)))
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\pathlib.py", line 1219, in write_text
    return f.write(data)
OSError: [Errno 9] Bad file descriptor

**Comment by ShaleenAg** [comment]
UPDATE: Tried a fresh install with cmd admin and now it's throwing this
**
C:\WINDOWS\system32>virtualenv -p C:\Users\Shaleen\AppData\Local\Programs\Python\Python36 D:/myenv -vvv --with-traceback
483 setup logging to NOTSET [DEBUG report:43]
606 find interpreter for spec PythonSpec(path=C:\Users\Shaleen\AppData\Local\Programs\Python\Python36) [INFO builtin:44]
607 Attempting to acquire lock 1782257623728 on C:\Users\Shaleen\AppData\Local\pypa\virtualenv\py_info\20.0.10\b9403fda969e38ee7ad4fb069feaa905a2d2911984f59919f617d6d622f68759.lock [DEBUG filelock:270]
608 Lock 1782257623728 acquired on C:\Users\Shaleen\AppData\Local\pypa\virtualenv\py_info\20.0.10\b9403fda969e38ee7ad4fb069feaa905a2d2911984f59919f617d6d622f68759.lock [INFO filelock:274]
609 get interpreter info via cmd: 'C:\Users\Shaleen\AppData\Local\Programs\Python\Python36' 'c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\discovery\py_info.py' [DEBUG cached_py_info:105]
610 Attempting to release lock 1782257623728 on C:\Users\Shaleen\AppData\Local\pypa\virtualenv\py_info\20.0.10\b9403fda969e38ee7ad4fb069feaa905a2d2911984f59919f617d6d622f68759.lock [DEBUG filelock:315]
610 Lock 1782257623728 released on C:\Users\Shaleen\AppData\Local\pypa\virtualenv\py_info\20.0.10\b9403fda969e38ee7ad4fb069feaa905a2d2911984f59919f617d6d622f68759.lock [INFO filelock:318]
Traceback (most recent call last):
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Shaleen\AppData\Local\Programs\Python\Python37\Scripts\virtualenv.exe\__main__.py", line 7, in <module>
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\__main__.py", line 50, in run_with_catch
    run(args, options)
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\__main__.py", line 20, in run
    session = cli_run(args, options)
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\run\__init__.py", line 27, in cli_run
    session = session_via_cli(args, options)
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\run\__init__.py", line 35, in session_via_cli
    parser = build_parser(args, options)
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\run\__init__.py", line 71, in build_parser
    parser._interpreter = interpreter = discover.interpreter
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\discovery\discover.py", line 44, in interpreter
    self._interpreter = self.run()
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\discovery\builtin.py", line 33, in run
    return get_interpreter(self.python_spec, self.app_data.folder)
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\discovery\builtin.py", line 46, in get_interpreter
    for interpreter, impl_must_match in propose_interpreters(spec, app_data):
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\discovery\builtin.py", line 60, in propose_interpreters
    yield PythonInfo.from_exe(spec.path, app_data), True
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\discovery\py_info.py", line 290, in from_exe
    proposed = from_exe(cls, app_data, exe, raise_on_error=raise_on_error, ignore_cache=ignore_cache)
  File "c:\users\shaleen\appdata\local\programs\python\python37\lib\site-packages\virtualenv\discovery\cached_py_info.py", line 35, in from_exe
    raise result
RuntimeError: failed to query C:\Users\Shaleen\AppData\Local\Programs\Python\Python36 with code 13 err: 'Access is denied'
**

**Comment by gaborbernat** [comment]
How did you install python, per @zooba you're system installation is in a corrupt state:

> This is one of the issues you get from mixing C runtimes, either debug builds or MinGW builds.

Normally these errors shouldn't happen.

**Comment by ShaleenAg** [comment]
Umm i installed it in the usual way with the setup..
But yea I had different builds of gcc and mingw running bwfore I uninstalled gcc

**Comment by gaborbernat** [comment]
@ShaleenAg maybe gcc left behind some files that are still present on your path and that breaks the world. The later error says we don't have access to run ``C:\Users\Shaleen\AppData\Local\Programs\Python\Python36``; in which case we can't do much. You should check what prohibits python 3.7 from running python 3.6 you're pointing at. Note cmd admin does not mean you can run everything; further enforced policies might be stopping you.
