### ISSUE TITLE
Windows regression in v20.0.11

### ISSUE THREAD

**Issue by gregersrygg** [pypa/virtualenv#1732]
**Issue**

After virtualenv v20.0.11 the creation of a virtualenv fails on Windows Server 2019 (Github Actions runner). The virtualenv was successfully created an hour earlier, when virtualenv v20.0.10 was installed. The workflow is on a schedule every hour.

**Environment**

- OS: Windows Server 2019

GitHub Actions windows-latest runner with Python 3.7. After major issues with the pip v20 release, I ended up using these steps to install pip and pipenv:

```console
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    python get-pip.py pip==19.3.1
    python -m pip install -I 'pipenv==2018.11.26'
```

See [full workflow file for details](https://github.com/ExploratoryEngineering/nrf9160-telenor/blob/master/.github/workflows/main.yml). It should be easy to reproduce the error using this file.

- ``pip list`` of the host python where ``virtualenv`` is installed:

  ```console
  Package            Version   
  ------------------ ----------
  appdirs            1.4.3     
  certifi            2019.11.28
  distlib            0.3.0     
  filelock           3.0.12    
  importlib-metadata 1.5.0     
  pip                20.0.2    
  pipenv             2018.11.26
  setuptools         46.0.0    
  six                1.14.0    
  virtualenv         20.0.11   
  virtualenv-clone   0.5.3     
  wheel              0.34.2    
  zipp               3.1.0  
  ```

**Output of the virtual environment creation**

> Make sure to run the creation with `-vvv --with-traceback`:

We're not using virtualenv directly, but through pipenv. Here is the output of `pipenv -vv install`:

```console
2020-03-18T21:11:47.5089439Z Creating a virtualenv for this projectï¿½
2020-03-18T21:11:47.5090081Z Pipfile: D:\a\nrf9160-telenor\nrf9160-telenor\Pipfile
2020-03-18T21:11:47.5090601Z Using C:/hostedtoolcache/windows/Python/3.7.6/x64/python.exe (3.7.6) to create virtualenvï¿½
2020-03-18T21:11:47.5100996Z 
2020-03-18T21:11:47.6011928Z [    ] Creating virtual environment...
2020-03-18T21:11:47.6962771Z [=   ] Creating virtual environment...
2020-03-18T21:11:47.7215292Z [==  ] Creating virtual environment...RuntimeError: failed to find interpreter for Builtin discover of python_spec='C:/hostedtoolcache/windows/Python/3.7.6/x64/python.exe'
2020-03-18T21:11:47.7215604Z 
2020-03-18T21:11:47.7900243Z Failed creating virtual environment 
2020-03-18T21:11:47.7901917Z Traceback (most recent call last):
2020-03-18T21:11:47.7903634Z   File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\runpy.py", line 193, in _run_module_as_main
2020-03-18T21:11:47.8001135Z     "__main__", mod_spec)
2020-03-18T21:11:47.8001605Z   File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\runpy.py", line 85, in _run_code
2020-03-18T21:11:47.8002315Z     exec(code, run_globals)
2020-03-18T21:11:47.8002854Z   File "C:\hostedtoolcache\windows\Python\3.7.6\x64\Scripts\pipenv.exe\__main__.py", line 7, in <module>
2020-03-18T21:11:47.8005711Z   File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\site-packages\pipenv\vendor\click\core.py", line 764, in __call__
2020-03-18T21:11:47.8009680Z     return self.main(*args, **kwargs)
2020-03-18T21:11:47.8010121Z   File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\site-packages\pipenv\vendor\click\core.py", line 717, in main
2020-03-18T21:11:47.8012401Z     rv = self.invoke(ctx)
2020-03-18T21:11:47.8012789Z   File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\site-packages\pipenv\vendor\click\core.py", line 1137, in invoke
2020-03-18T21:11:47.8016429Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2020-03-18T21:11:47.8016856Z   File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\site-packages\pipenv\vendor\click\core.py", line 956, in invoke
2020-03-18T21:11:47.8020600Z     return ctx.invoke(self.callback, **ctx.params)
2020-03-18T21:11:47.8020995Z   File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
2020-03-18T21:11:47.8023975Z     return callback(*args, **kwargs)
2020-03-18T21:11:47.8024351Z   File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\site-packages\pipenv\vendor\click\decorators.py", line 64, in new_func
2020-03-18T21:11:47.8025920Z     return ctx.invoke(f, obj, *args, **kwargs)
2020-03-18T21:11:47.8026725Z   File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
2020-03-18T21:11:47.8029283Z     return callback(*args, **kwargs)
2020-03-18T21:11:47.8029826Z   File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\site-packages\pipenv\vendor\click\decorators.py", line 17, in new_func
2020-03-18T21:11:47.8031215Z     return f(get_current_context(), *args, **kwargs)
2020-03-18T21:11:47.8031662Z   File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\site-packages\pipenv\cli\command.py", line 254, in install
2020-03-18T21:11:47.8034076Z     editable_packages=state.installstate.editables,
2020-03-18T21:11:47.8036207Z   File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\site-packages\pipenv\core.py", line 1741, in do_install
2020-03-18T21:11:47.8044187Z     pypi_mirror=pypi_mirror,
2020-03-18T21:11:47.8044694Z   File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\site-packages\pipenv\core.py", line 574, in ensure_project
2020-03-18T21:11:47.8048414Z     pypi_mirror=pypi_mirror,
2020-03-18T21:11:47.8049034Z   File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\site-packages\pipenv\core.py", line 506, in ensure_virtualenv
2020-03-18T21:11:47.8052607Z     python=python, site_packages=site_packages, pypi_mirror=pypi_mirror
2020-03-18T21:11:47.8053018Z   File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\site-packages\pipenv\core.py", line 935, in do_create_virtualenv
2020-03-18T21:11:47.8059141Z     extra=[crayons.blue("{0}".format(c.err)),]
2020-03-18T21:11:47.8059559Z pipenv.exceptions.VirtualenvCreationException: Failed to create virtual environment.
2020-03-18T21:11:47.9453108Z ##[error]Process completed with exit code 1.
```

**Comment by gaborbernat** [comment]
I'd still require the virtualenv creation with debug flags, that would make things easier. I don't have access to GitHub actions easily.

**Comment by gaborbernat** [comment]
Did anyone manage to replicate this outside of pipenv?

**Comment by gaborbernat** [comment]
Can anyone validate if https://github.com/pypa/virtualenv/pull/1734 fixes this?

**Comment by gaborbernat** [comment]
A fix went in via https://github.com/pypa/virtualenv/pull/1734

**Comment by gaborbernat** [comment]
Can anyone validate if this is still around with https://pypi.org/project/virtualenv/20.0.12/; thanks!

**Comment by gregersrygg** [comment]
#1734 seems to have fixed the problem. Thank you for the quick resolution 😄
