### ISSUE TITLE
virtualenv raises StopIteration exception when processing extra search directory wheels.

### ISSUE THREAD

**Issue by kevinp89** [pypa/virtualenv#1757]
**Issue**

When creating virtualenv when using `--extra-search-directory`, ``StopIteration`` exception is raised when processing wheels.
**Environment**

Provide at least:
- OS: Centos7
- ``virtualenv`` is installed:
virtualenv version: 20.0.15
```console
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/virtualenv/seed/via_app_data/via_app_data.py", line 75, in _get
    self.app_data,
  File "/usr/local/lib/python3.6/site-packages/virtualenv/seed/embed/wheels/acquire.py", line 30, in get_wheels
    acquire_from_dir(processed, for_py_version, wheel_cache_dir, extra_search_dir)
  File "/usr/local/lib/python3.6/site-packages/virtualenv/seed/embed/wheels/acquire.py", line 74, in acquire_from_dir
    if wheel_support_py(filename, for_py_version):
  File "/usr/local/lib/python3.6/site-packages/virtualenv/seed/embed/wheels/acquire.py", line 91, in wheel_support_py
    requires = next(i[len(marker) :] for i in metadata.splitlines() if i.startswith(marker))
StopIteration
```

**Comment by gaborbernat** [comment]
Can you please post the content of that extra search directory? Thanks.

**Comment by gaborbernat** [comment]
Seems ``setuptools-41.6.0-py2.py3-none-any.whl`` does not have ``Requires-Python:`` metadata embedded, which we assumed (wrongfully it must always exist).

**Comment by gaborbernat** [comment]
Thanks for the detailed report, created the fix under https://github.com/pypa/virtualenv/pull/1758

**Comment by gaborbernat** [comment]
This now has been released with https://pypi.org/project/virtualenv/20.0.16/

**Comment by kevinp89** [comment]
Wow, that was fast, thanks for all the hard work and continuing to improve python package management!

**Comment by gaborbernat** [comment]
You're welcome.
