### ISSUE TITLE
20.0.19 Fails on CentOS 7/older Python 2 - AttributeError: 'module' object has no attribute 'get_makefile_name'

### ISSUE THREAD

**Issue by ianw** [pypa/virtualenv#1810]
**Issue**

20.0.19 fails on centos 7 with Python 2.7.5

```
-bash-4.2# virtualenv --version
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 5, in <module>
    from virtualenv.__main__ import run_with_catch
  File "/usr/lib/python2.7/site-packages/virtualenv/__init__.py", line 3, in <module>
    from .run import cli_run
  File "/usr/lib/python2.7/site-packages/virtualenv/run/__init__.py", line 12, in <module>
    from .plugin.creators import CreatorSelector
  File "/usr/lib/python2.7/site-packages/virtualenv/run/plugin/creators.py", line 6, in <module>
    from virtualenv.create.via_global_ref.builtin.builtin_way import VirtualenvBuiltin
  File "/usr/lib/python2.7/site-packages/virtualenv/create/via_global_ref/builtin/builtin_way.py", line 7, in <module>
    from virtualenv.create.creator import Creator
  File "/usr/lib/python2.7/site-packages/virtualenv/create/creator.py", line 14, in <module>
    from virtualenv.discovery.cached_py_info import LogCmd
  File "/usr/lib/python2.7/site-packages/virtualenv/discovery/cached_py_info.py", line 26, in <module>
    _CACHE[Path(sys.executable)] = PythonInfo()
  File "/usr/lib/python2.7/site-packages/virtualenv/discovery/py_info.py", line 82, in __init__
    ("makefile_filename", sysconfig.get_makefile_filename()),
AttributeError: 'module' object has no attribute 'get_makefile_filename'
```

Seems to be from dfafc1102a0746f3fe6efdee3520a8d83e88b9ef which introduced the usage of this call.  After reading https://bugs.python.org/issue22199, it appears this might be _ prefixed on some platforms with older Python, such as CentOS 7 (looks like it only got renamed for 2.7.9?)

**Comment by gaborbernat** [comment]
Hello, this now has been released via https://pypi.org/project/virtualenv/20.0.20/

![heads up](https://media.tenor.co/images/0118006f847acfcfd22e8bf0fd405e42/tenor.gif)
