### ISSUE TITLE
Fail to run bootstrap virtualenv.pyz on Python 3.6 

### ISSUE THREAD

**Issue by pombredanne** [pypa/virtualenv#1822]
**Issue**
virtualenv.pyz fails on Python 3.6
```
$ wget https://bootstrap.pypa.io/virtualenv.pyz
[...]
$ sha256sum  virtualenv.pyz
d7ca00e138dcffa5fb017b4c6dfa256bb6fdd74af964fbe9798aed59db8ec6f5  virtualenv.pyz
$ python3.6 --version
Python 3.6.9
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
```
The error is the same on Python 3.6.8 and 3.6.9 and there is no rror on the system Python 2.7.12:
```

Traceback (most recent call last):
  File "/home/user/tmp/venv/virtualenv.pyz/__virtualenv__/importlib_resources-1.5.0-py2.py3-none-any/importlib_resources/_py3.py", line 85, in open_binary
NotADirectoryError: [Errno 20] Not a directory: '/home/user/tmp/venv/virtualenv.pyz/virtualenv/activation/bash/activate.sh'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "virtualenv.pyz/__main__.py", line 169, in <module>
  File "virtualenv.pyz/__main__.py", line 165, in run
  File "virtualenv.pyz/virtualenv/__main__.py", line 20, in run
  File "virtualenv.pyz/virtualenv/run/__init__.py", line 26, in cli_run
  File "virtualenv.pyz/virtualenv/session.py", line 48, in run
  File "virtualenv.pyz/virtualenv/session.py", line 68, in _activate
  File "virtualenv.pyz/virtualenv/activation/via_template.py", line 28, in generate
  File "virtualenv.pyz/virtualenv/activation/via_template.py", line 45, in _generate
  File "virtualenv.pyz/virtualenv/activation/via_template.py", line 56, in instantiate_template
  File "/home/user/tmp/venv/virtualenv.pyz/__virtualenv__/importlib_resources-1.5.0-py2.py3-none-any/importlib_resources/_py3.py", line 127, in read_text
  File "/home/user/tmp/venv/virtualenv.pyz/__virtualenv__/importlib_resources-1.5.0-py2.py3-none-any/importlib_resources/_py3.py", line 109, in open_text
  File "/home/user/tmp/venv/virtualenv.pyz/__virtualenv__/importlib_resources-1.5.0-py2.py3-none-any/importlib_resources/_py3.py", line 99, in open_binary
FileNotFoundError: 'activate.sh' resource not found in 'virtualenv.activation.bash'
```

Describe what's the expected behaviour and what you're observing.

**Environment**

Provide at least:
- OS: Ubunt 16.04 X86_64
- pyenv with Python  version 3.6.8  and 3.6.9
- ``pip list`` is empty

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console
$ python virtualenv.pyz -vvv --with-traceback .
107 setup logging to NOTSET [DEBUG report:42]
117 find interpreter for spec PythonSpec(path=/home/user/.pyenv/versions/3.6.9/bin/python) [INFO builtin:44]
117 proposed PythonInfo(spec=CPython3.6.9.final.0-64, exe=/home/user/.pyenv/versions/3.6.9/bin/python, platform=linux, version='3.6.9 (default, May 11 2020, 15:27:50) \n[GCC 5.4.0 20160609]', encoding_fs_io=utf-8-UTF-8) [INFO builtin:50]
117 accepted PythonInfo(spec=CPython3.6.9.final.0-64, exe=/home/user/.pyenv/versions/3.6.9/bin/python, platform=linux, version='3.6.9 (default, May 11 2020, 15:27:50) \n[GCC 5.4.0 20160609]', encoding_fs_io=utf-8-UTF-8) [DEBUG builtin:52]
123 filesystem is case-sensitive [DEBUG info:28]
162 create virtual environment via CPython3Posix(dest=/home/user/tmp/venv, clear=False, global=False) [INFO session:52]
163 create folder /home/user/tmp/venv/bin [DEBUG _sync:21]
163 create folder /home/user/tmp/venv/lib/python3.6/site-packages [DEBUG _sync:21]
163 write /home/user/tmp/venv/pyvenv.cfg [DEBUG pyenv_cfg:34]
163 	home = /home/user/.pyenv/versions/3.6.9 [DEBUG pyenv_cfg:38]
163 	implementation = CPython [DEBUG pyenv_cfg:38]
163 	version_info = 3.6.9.final.0 [DEBUG pyenv_cfg:38]
163 	virtualenv = 20.0.20 [DEBUG pyenv_cfg:38]
163 	include-system-site-packages = false [DEBUG pyenv_cfg:38]
163 	base-prefix = /home/user/.pyenv/versions/3.6.9 [DEBUG pyenv_cfg:38]
163 	base-exec-prefix = /home/user/.pyenv/versions/3.6.9 [DEBUG pyenv_cfg:38]
164 	base-executable = /home/user/.pyenv/versions/3.6.9/bin/python [DEBUG pyenv_cfg:38]
164 symlink /home/user/.pyenv/versions/3.6.9/bin/python to /home/user/tmp/venv/bin/python [DEBUG _sync:40]
164 Attempting to acquire lock 140237286666192 on /home/user/.local/share/virtualenv/zipapp/extract/20.0.20/_virtualenv.py.lock [DEBUG filelock:270]
164 Lock 140237286666192 acquired on /home/user/.local/share/virtualenv/zipapp/extract/20.0.20/_virtualenv.py.lock [INFO filelock:274]
165 Attempting to release lock 140237286666192 on /home/user/.local/share/virtualenv/zipapp/extract/20.0.20/_virtualenv.py.lock [DEBUG filelock:315]
165 Lock 140237286666192 released on /home/user/.local/share/virtualenv/zipapp/extract/20.0.20/_virtualenv.py.lock [INFO filelock:318]
165 create virtualenv import hook file /home/user/tmp/venv/lib/python3.6/site-packages/_virtualenv.pth [DEBUG api:95]
165 create /home/user/tmp/venv/lib/python3.6/site-packages/_virtualenv.py [DEBUG api:98]
165 ============================== target debug ============================== [DEBUG session:54]
166 Attempting to acquire lock 140237285941600 on /home/user/.local/share/virtualenv/zipapp/extract/20.0.20/debug.py.lock [DEBUG filelock:270]
166 Lock 140237285941600 acquired on /home/user/.local/share/virtualenv/zipapp/extract/20.0.20/debug.py.lock [INFO filelock:274]
166 extract /home/user/tmp/venv/virtualenv.pyz/virtualenv/create/debug.py to /home/user/.local/share/virtualenv/zipapp/extract/20.0.20/debug.py [DEBUG zipapp:23]
168 debug via /home/user/tmp/venv/bin/python /home/user/.local/share/virtualenv/zipapp/extract/20.0.20/debug.py [DEBUG creator:187]
200 Attempting to release lock 140237285941600 on /home/user/.local/share/virtualenv/zipapp/extract/20.0.20/debug.py.lock [DEBUG filelock:315]
200 Lock 140237285941600 released on /home/user/.local/share/virtualenv/zipapp/extract/20.0.20/debug.py.lock [INFO filelock:318]
165 {
  "sys": {
    "executable": "/home/user/tmp/venv/bin/python",
    "_base_executable": null,
    "prefix": "/home/user/tmp/venv",
    "base_prefix": "/home/user/.pyenv/versions/3.6.9",
    "real_prefix": null,
    "exec_prefix": "/home/user/tmp/venv",
    "base_exec_prefix": "/home/user/.pyenv/versions/3.6.9",
    "path": [
      "/home/user/.pyenv/versions/3.6.9/lib/python36.zip",
      "/home/user/.pyenv/versions/3.6.9/lib/python3.6",
      "/home/user/.pyenv/versions/3.6.9/lib/python3.6/lib-dynload",
      "/home/user/tmp/venv/lib/python3.6/site-packages"
    ],
    "meta_path": [
      "<class '_virtualenv._Finder'>",
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib_external.PathFinder'>"
    ],
    "fs_encoding": "utf-8",
    "io_encoding": "UTF-8"
  },
  "version": "3.6.9 (default, May 11 2020, 15:27:50) \n[GCC 5.4.0 20160609]",
  "makefile_filename": "/home/user/.pyenv/versions/3.6.9/lib/python3.6/config-3.6m-x86_64-linux-gnu/Makefile",
  "os": "<module 'os' from '/home/user/.pyenv/versions/3.6.9/lib/python3.6/os.py'>",
  "site": "<module 'site' from '/home/user/.pyenv/versions/3.6.9/lib/python3.6/site.py'>",
  "datetime": "<module 'datetime' from '/home/user/.pyenv/versions/3.6.9/lib/python3.6/datetime.py'>",
  "math": "<module 'math' from '/home/user/.pyenv/versions/3.6.9/lib/python3.6/lib-dynload/math.cpython-36m-x86_64-linux-gnu.so'>",
  "json": "<module 'json' from '/home/user/.pyenv/versions/3.6.9/lib/python3.6/json/__init__.py'>"
} [DEBUG session:55]
200 add seed packages via FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/user/.local/share/virtualenv/seed-app-data/v1.0.1) [INFO session:59]
201 Attempting to acquire lock 140237286752552 on /home/user/.local/share/virtualenv/seed-app-data/v1.0.1/3.6/wheels.lock [DEBUG filelock:270]
201 Lock 140237286752552 acquired on /home/user/.local/share/virtualenv/seed-app-data/v1.0.1/3.6/wheels.lock [INFO filelock:274]
202 get bundled wheel /home/user/tmp/venv/virtualenv.pyz/virtualenv/seed/embed/wheels/pip-20.1-py2.py3-none-any.whl [DEBUG acquire:60]
203 extract /home/user/tmp/venv/virtualenv.pyz/virtualenv/seed/embed/wheels/pip-20.1-py2.py3-none-any.whl to /home/user/.local/share/virtualenv/seed-app-data/v1.0.1/3.6/wheels/pip-20.1-py2.py3-none-any.whl [DEBUG zipapp:23]
203 get bundled wheel /home/user/tmp/venv/virtualenv.pyz/virtualenv/seed/embed/wheels/setuptools-46.1.3-py3-none-any.whl [DEBUG acquire:60]
203 extract /home/user/tmp/venv/virtualenv.pyz/virtualenv/seed/embed/wheels/setuptools-46.1.3-py3-none-any.whl to /home/user/.local/share/virtualenv/seed-app-data/v1.0.1/3.6/wheels/setuptools-46.1.3-py3-none-any.whl [DEBUG zipapp:23]
204 get bundled wheel /home/user/tmp/venv/virtualenv.pyz/virtualenv/seed/embed/wheels/wheel-0.34.2-py2.py3-none-any.whl [DEBUG acquire:60]
204 extract /home/user/tmp/venv/virtualenv.pyz/virtualenv/seed/embed/wheels/wheel-0.34.2-py2.py3-none-any.whl to /home/user/.local/share/virtualenv/seed-app-data/v1.0.1/3.6/wheels/wheel-0.34.2-py2.py3-none-any.whl [DEBUG zipapp:23]
215 install wheel from wheel /home/user/.local/share/virtualenv/seed-app-data/v1.0.1/3.6/wheels/wheel-0.34.2-py2.py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:47]
215 install setuptools from wheel /home/user/.local/share/virtualenv/seed-app-data/v1.0.1/3.6/wheels/setuptools-46.1.3-py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:47]
215 install pip from wheel /home/user/.local/share/virtualenv/seed-app-data/v1.0.1/3.6/wheels/pip-20.1-py2.py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:47]
216 copy /home/user/.local/share/virtualenv/seed-app-data/v1.0.1/3.6/image/CopyPipInstall/wheel-0.34.2-py2.py3-none-any/wheel-0.34.2.virtualenv to /home/user/tmp/venv/lib/python3.6/site-packages/wheel-0.34.2.virtualenv [DEBUG _sync:48]
216 copy directory /home/user/.local/share/virtualenv/seed-app-data/v1.0.1/3.6/image/CopyPipInstall/setuptools-46.1.3-py3-none-any/setuptools-46.1.3.dist-info to /home/user/tmp/venv/lib/python3.6/site-packages/setuptools-46.1.3.dist-info [DEBUG _sync:48]
216 copy directory /home/user/.local/share/virtualenv/seed-app-data/v1.0.1/3.6/image/CopyPipInstall/pip-20.1-py2.py3-none-any/pip-20.1.dist-info to /home/user/tmp/venv/lib/python3.6/site-packages/pip-20.1.dist-info [DEBUG _sync:48]
216 copy directory /home/user/.local/share/virtualenv/seed-app-data/v1.0.1/3.6/image/CopyPipInstall/wheel-0.34.2-py2.py3-none-any/wheel-0.34.2.dist-info to /home/user/tmp/venv/lib/python3.6/site-packages/wheel-0.34.2.dist-info [DEBUG _sync:48]
219 copy /home/user/.local/share/virtualenv/seed-app-data/v1.0.1/3.6/image/CopyPipInstall/pip-20.1-py2.py3-none-any/pip-20.1.virtualenv to /home/user/tmp/venv/lib/python3.6/site-packages/pip-20.1.virtualenv [DEBUG _sync:48]
220 copy directory /home/user/.local/share/virtualenv/seed-app-data/v1.0.1/3.6/image/CopyPipInstall/wheel-0.34.2-py2.py3-none-any/wheel to /home/user/tmp/venv/lib/python3.6/site-packages/wheel [DEBUG _sync:48]
220 copy directory /home/user/.local/share/virtualenv/seed-app-data/v1.0.1/3.6/image/CopyPipInstall/pip-20.1-py2.py3-none-any/pip to /home/user/tmp/venv/lib/python3.6/site-packages/pip [DEBUG _sync:48]
220 copy directory /home/user/.local/share/virtualenv/seed-app-data/v1.0.1/3.6/image/CopyPipInstall/setuptools-46.1.3-py3-none-any/pkg_resources to /home/user/tmp/venv/lib/python3.6/site-packages/pkg_resources [DEBUG _sync:48]
226 changing mode of /home/user/tmp/venv/bin/wheel-3.6 to 775 [INFO util:566]
227 changing mode of /home/user/tmp/venv/bin/wheel to 775 [INFO util:566]
227 changing mode of /home/user/tmp/venv/bin/wheel3 to 775 [INFO util:566]
227 generated console scripts wheel wheel3 wheel-3.6 [DEBUG base:53]
229 copy /home/user/.local/share/virtualenv/seed-app-data/v1.0.1/3.6/image/CopyPipInstall/setuptools-46.1.3-py3-none-any/easy_install.py to /home/user/tmp/venv/lib/python3.6/site-packages/easy_install.py [DEBUG _sync:48]
229 copy directory /home/user/.local/share/virtualenv/seed-app-data/v1.0.1/3.6/image/CopyPipInstall/setuptools-46.1.3-py3-none-any/setuptools to /home/user/tmp/venv/lib/python3.6/site-packages/setuptools [DEBUG _sync:48]
248 copy /home/user/.local/share/virtualenv/seed-app-data/v1.0.1/3.6/image/CopyPipInstall/setuptools-46.1.3-py3-none-any/setuptools-46.1.3.virtualenv to /home/user/tmp/venv/lib/python3.6/site-packages/setuptools-46.1.3.virtualenv [DEBUG _sync:48]
250 changing mode of /home/user/tmp/venv/bin/easy_install3 to 775 [INFO util:566]
250 changing mode of /home/user/tmp/venv/bin/easy_install-3.6 to 775 [INFO util:566]
250 changing mode of /home/user/tmp/venv/bin/easy_install to 775 [INFO util:566]
250 generated console scripts easy_install3 easy_install easy_install-3.6 [DEBUG base:53]
275 changing mode of /home/user/tmp/venv/bin/pip3 to 775 [INFO util:566]
276 changing mode of /home/user/tmp/venv/bin/pip-3.6 to 775 [INFO util:566]
276 changing mode of /home/user/tmp/venv/bin/pip to 775 [INFO util:566]
276 changing mode of /home/user/tmp/venv/bin/pip3.6 to 775 [INFO util:566]
276 generated console scripts pip pip-3.6 pip3 pip3.6 [DEBUG base:53]
276 Attempting to release lock 140237286752552 on /home/user/.local/share/virtualenv/seed-app-data/v1.0.1/3.6/wheels.lock [DEBUG filelock:315]
276 Lock 140237286752552 released on /home/user/.local/share/virtualenv/seed-app-data/v1.0.1/3.6/wheels.lock [INFO filelock:318]
276 add activators for Bash, CShell, Fish, PowerShell, Python, Xonsh [INFO session:65]
Traceback (most recent call last):
  File "/home/user/tmp/venv/virtualenv.pyz/__virtualenv__/importlib_resources-1.5.0-py2.py3-none-any/importlib_resources/_py3.py", line 85, in open_binary
NotADirectoryError: [Errno 20] Not a directory: '/home/user/tmp/venv/virtualenv.pyz/virtualenv/activation/bash/activate.sh'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.6.9/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/.pyenv/versions/3.6.9/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "virtualenv.pyz/__main__.py", line 169, in <module>
  File "virtualenv.pyz/__main__.py", line 165, in run
  File "virtualenv.pyz/virtualenv/__main__.py", line 20, in run
  File "virtualenv.pyz/virtualenv/run/__init__.py", line 26, in cli_run
  File "virtualenv.pyz/virtualenv/session.py", line 48, in run
  File "virtualenv.pyz/virtualenv/session.py", line 68, in _activate
  File "virtualenv.pyz/virtualenv/activation/via_template.py", line 28, in generate
  File "virtualenv.pyz/virtualenv/activation/via_template.py", line 45, in _generate
  File "virtualenv.pyz/virtualenv/activation/via_template.py", line 56, in instantiate_template
  File "/home/user/tmp/venv/virtualenv.pyz/__virtualenv__/importlib_resources-1.5.0-py2.py3-none-any/importlib_resources/_py3.py", line 127, in read_text
  File "/home/user/tmp/venv/virtualenv.pyz/__virtualenv__/importlib_resources-1.5.0-py2.py3-none-any/importlib_resources/_py3.py", line 109, in open_text
  File "/home/user/tmp/venv/virtualenv.pyz/__virtualenv__/importlib_resources-1.5.0-py2.py3-none-any/importlib_resources/_py3.py", line 99, in open_binary
FileNotFoundError: 'activate.sh' resource not found in 'virtualenv.activation.bash'



```

**Comment by gaborbernat** [comment]
This is upstream bug https://gitlab.com/python-devs/importlib_resources/-/issues/75, while that gets fixed pass in the zipapp as absolute path to work around the issue.

**Comment by pombredanne** [comment]
@gaborbernat Thanks!
