### ISSUE TITLE
Problem creating conda package for virtualenv 20.0.4:

### ISSUE THREAD

**Issue by nicoddemus** [pypa/virtualenv#1829]
Hi!

I'm trying to build version 20.0.4 for [conda-forge](https://github.com/conda-forge/virtualenv-feedstock/issues/32) from the sdist, but I'm running into an error during the build-environment creation process.

I'm getting this error:

```
      File "C:\Users\Bruno\AppData\Local\Temp\pip-req-build-vkeklb_q\src\virtualenv\run\__init__.py", line 8, in <module>
        from ..version import __version__
    ModuleNotFoundError: No module named 'virtualenv.version'
```

Which I guess is related to `setuptools_scm` not generating the version file.

I'm installing `setuptools_scm` during the build process as expected, anything else I should be doing?

Here are the build dependencies being used:

```
  host:
    - python
    - pip >=18
    - setuptools >=41
    - setuptools_scm >=2
    - appdirs >=1.4.3,<2
    - distlib >=0.3.0,<1
    - filelock >=3.0.0,<4
    - six >=1.9.0,<2   # keep it >=1.9.0 as it may cause problems on LTS platforms
    - contextlib2 >=0.6.0,<1  # [py<33]
    - importlib-metadata >=0.12,<2  # [py<38]
    - importlib_resources >=1.0,<2  # [py<37]
    - pathlib2 >=2.3.3,<3
```

And the command being executed during conda's build step:

```
python -m pip install . -vv
```

<details>
<summary>Full output from the build stage</summary>

```
Non-user install because user site-packages disabled
Ignoring indexes: https://pypi.org/simple
Created temporary directory: C:\Users\Bruno\AppData\Local\Temp\pip-ephem-wheel-cache-oy6m7r_o
Created temporary directory: C:\Users\Bruno\AppData\Local\Temp\pip-req-tracker-pw7wk6pp
Initialized build tracking at C:\Users\Bruno\AppData\Local\Temp\pip-req-tracker-pw7wk6pp
Created build tracker: C:\Users\Bruno\AppData\Local\Temp\pip-req-tracker-pw7wk6pp
Entered build tracker: C:\Users\Bruno\AppData\Local\Temp\pip-req-tracker-pw7wk6pp
Created temporary directory: C:\Users\Bruno\AppData\Local\Temp\pip-install-9t5byoki
Processing d:\miniconda3\conda-bld\virtualenv_1589565529221\work
  Created temporary directory: C:\Users\Bruno\AppData\Local\Temp\pip-req-build-vkeklb_q
  Added file:///D:/miniconda3/conda-bld/virtualenv_1589565529221/work to build tracker 'C:\\Users\\Bruno\\AppData\\Local\\Temp\\pip-req-tracker-pw7wk6pp'
    Created temporary directory: C:\Users\Bruno\AppData\Local\Temp\pip-modern-metadata-ryrewhpc
    Preparing wheel metadata: started
    Running command 'D:\miniconda3\conda-bld\virtualenv_1589565529221\_h_env\python.exe' 'D:\miniconda3\conda-bld\virtualenv_1589565529221\_h_env\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\Bruno\AppData\Local\Temp\tmpi6m3x558'
    Traceback (most recent call last):
      File "D:\miniconda3\conda-bld\virtualenv_1589565529221\_h_env\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 257, in <module>
        main()
      File "D:\miniconda3\conda-bld\virtualenv_1589565529221\_h_env\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 240, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "D:\miniconda3\conda-bld\virtualenv_1589565529221\_h_env\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 110, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "D:\miniconda3\conda-bld\virtualenv_1589565529221\_h_env\lib\site-packages\setuptools\build_meta.py", line 158, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "D:\miniconda3\conda-bld\virtualenv_1589565529221\_h_env\lib\site-packages\setuptools\build_meta.py", line 143, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 3, in <module>
        setup()
      File "D:\miniconda3\conda-bld\virtualenv_1589565529221\_h_env\lib\site-packages\setuptools\__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "D:\miniconda3\conda-bld\virtualenv_1589565529221\_h_env\lib\distutils\core.py", line 121, in setup
        dist.parse_config_files()
      File "D:\miniconda3\conda-bld\virtualenv_1589565529221\_h_env\lib\site-packages\setuptools\dist.py", line 690, in parse_config_files
        ignore_option_errors=ignore_option_errors)
      File "D:\miniconda3\conda-bld\virtualenv_1589565529221\_h_env\lib\site-packages\setuptools\config.py", line 121, in parse_configuration
        meta.parse()
      File "D:\miniconda3\conda-bld\virtualenv_1589565529221\_h_env\lib\site-packages\setuptools\config.py", line 426, in parse
        section_parser_method(section_options)
      File "D:\miniconda3\conda-bld\virtualenv_1589565529221\_h_env\lib\site-packages\setuptools\config.py", line 399, in parse_section
        self[name] = value
      File "D:\miniconda3\conda-bld\virtualenv_1589565529221\_h_env\lib\site-packages\setuptools\config.py", line 184, in __setitem__
        value = parser(value)
      File "D:\miniconda3\conda-bld\virtualenv_1589565529221\_h_env\lib\site-packages\setuptools\config.py", line 515, in _parse_version
        version = self._parse_attr(value, self.package_dir)
      File "D:\miniconda3\conda-bld\virtualenv_1589565529221\_h_env\lib\site-packages\setuptools\config.py", line 349, in _parse_attr
        module = import_module(module_name)
      File "D:\miniconda3\conda-bld\virtualenv_1589565529221\_h_env\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "C:\Users\Bruno\AppData\Local\Temp\pip-req-build-vkeklb_q\src\virtualenv\__init__.py", line 3, in <module>
        from .run import cli_run
      File "C:\Users\Bruno\AppData\Local\Temp\pip-req-build-vkeklb_q\src\virtualenv\run\__init__.py", line 8, in <module>
        from ..version import __version__
    ModuleNotFoundError: No module named 'virtualenv.version'
    Preparing wheel metadata: finished with status 'error'
Cleaning up...
  Removing source in C:\Users\Bruno\AppData\Local\Temp\pip-req-build-vkeklb_q
Removed file:///D:/miniconda3/conda-bld/virtualenv_1589565529221/work from build tracker 'C:\\Users\\Bruno\\AppData\\Local\\Temp\\pip-req-tracker-pw7wk6pp'
Removed build tracker: 'C:\\Users\\Bruno\\AppData\\Local\\Temp\\pip-req-tracker-pw7wk6pp'
```
</details>

**Environment**

I'm trying this one Windows, using conda version 4.8.3 and conda-build 3.19.2 (both latest versions).

<details>
<summary>Here is the full recipe I'm using</summary>

```yaml
{% set version = "20.0.4" %}

package:
  name: virtualenv
  version: {{ version }}

source:
  url: https://github.com/pypa/virtualenv/archive/{{ version }}.tar.gz
  sha256: 6af7af7f73b57487b933e3a7811dbfe00aa9cad2fd3e1d6f93c29c5335104614

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - virtualenv = virtualenv:run_with_catch

requirements:
  host:
    - python
    - pip >=18
    - setuptools >=41
    - setuptools_scm >=2
    - appdirs >=1.4.3,<2
    - distlib >=0.3.0,<1
    - filelock >=3.0.0,<4
    - six >=1.9.0,<2   # keep it >=1.9.0 as it may cause problems on LTS platforms
    - contextlib2 >=0.6.0,<1  # [py<33]
    - importlib-metadata >=0.12,<2  # [py<38]
    - importlib_resources >=1.0,<2  # [py<37]
    - pathlib2 >=2.3.3,<3
  run:
    - python
    - appdirs >=1.4.3,<2
    - distlib >=0.3.0,<1
    - filelock >=3.0.0,<4
    - six >=1.9.0,<2   # keep it >=1.9.0 as it may cause problems on LTS platforms
    - contextlib2 >=0.6.0,<1  # [py<33]
    - importlib-metadata >=0.12,<2  # [py<38]
    - importlib_resources >=1.0,<2  # [py<37]
    - pathlib2 >=2.3.3,<3  # [py<34 and not win]

test:
  commands:
    - virtualenv --help
    # Skipping py2k tests b/c it fails on our docker image
    # but I'm 99% sure it should work locally.
    - |
      virtualenv -p "$(which python)" /tmp/venv-$$  # [not win]
      source /tmp/venv-$$/bin/activate  # [not win]
      python -c 'import sys ; sys.exit(not hasattr(sys, "real_prefix"))'  # [not win]
  imports:
    - virtualenv

about:
  home: https://virtualenv.pypa.io/
  license: MIT
  license_file: LICENSE.txt
  summary: Virtual Python Environment builder
  description: |
    virtualenv is a tool to create isolated Python environments.
  doc_url: https://virtualenv.pypa.io/en/latest/
  dev_url: https://github.com/pypa/virtualenv

extra:
  recipe-maintainers:
    - mingwandroid
    - kalefranz

```

</details>

Any hints or insights are appreciated. :+1:

**Comment by asottile** [comment]
I suspect this is missing `setuptools-scm` while building

**Comment by asottile** [comment]
hmmm, maybe try a newer version?  I think that `version =` was moved into setuptools-scm after that (apparently in 20.0.5?)  1d9b7d1898a31258a8a4af588b0cbe02081a3a0c

**Comment by gaborbernat** [comment]
You also need git for this to work.

**Comment by gaborbernat** [comment]
But while at it definitely package latest, aka 20.0.20 😁

**Comment by nicoddemus** [comment]
> You also need git for this to work.

DUH of course, thanks! Will try that now and come back here with the results! 👍

**Comment by gaborbernat** [comment]
Did your issue get solved?

**Comment by nicoddemus** [comment]
Yes thanks again! Sorry I haven't closed it until now, I was about to do that once I published the package on conda-forge, but that got stuck for other reasons. 

Thanks again!
