### ISSUE TITLE
Can't create virtualenv on Mac Catalilna

### ISSUE THREAD

**Issue by davidcsi** [pypa/virtualenv#1863]
**Issue**

I'm trying to create a new virtual environment and it's failing. This has been going for some time and I have no idea how to solve it.

**Environment**

Provide at least:
- OS: MAC OSX 10.15.5
- 

```
pip3 list   
Package                       Version
----------------------------- ----------
apipkg                        1.5
appnope                       0.1.0
asn1crypto                    0.24.0
astroid                       2.0.4
attrs                         19.3.0
autopep8                      1.4.4
backcall                      0.2.0
backports.functools-lru-cache 1.5
bcrypt                        3.1.4
beautifulsoup4                4.9.1
boto                          2.49.0
boto3                         1.9.25
botocore                      1.12.25
brython                       3.8.9
cchardet                      2.1.6
certifi                       2020.4.5.2
cffi                          1.14.0
chardet                       3.0.4
cheroot                       6.5.2
CherryPy                      18.0.1
colorama                      0.4.3
commonmark                    0.9.1
coverage                      5.1
cryptography                  2.9.2
decorator                     4.4.2
docutils                      0.14
docx                          0.2.4
etree-trunc                   0.2
execnet                       1.7.1
flake8                        3.8.3
html-to-etree                 0.2.0
idna                          2.9
importlib-metadata            1.6.1
ipdb                          0.13.2
ipython                       7.15.0
ipython-genutils              0.2.0
isort                         4.3.4
jaraco.functools              1.20
jedi                          0.17.0
jmespath                      0.9.3
lazy-object-proxy             1.3.1
lxml                          4.2.5
lxml-asserts                  0.1.2
mccabe                        0.6.1
more-itertools                4.3.0
nose                          1.3.7
packaging                     20.4
parameterized                 0.7.4
paramiko                      2.4.2
parso                         0.7.0
pdfminer.six                  20200517
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        5.3.0
pip                           20.1.1
pluggy                        0.13.1
portend                       2.3
pprintpp                      0.4.0
prompt-toolkit                3.0.5
ptyprocess                    0.6.0
py                            1.8.2
pyasn1                        0.4.4
pycodestyle                   2.6.0
pycparser                     2.19
pycryptodome                  3.9.7
pyflakes                      2.2.0
Pygments                      2.6.1
pylint                        2.1.1
PyMySQL                       0.9.3
PyNaCl                        1.3.0
pyOpenSSL                     19.1.0
pyotp                         2.3.0
pyparsing                     2.4.7
pytest                        5.4.3
pytest-cov                    2.10.0
pytest-forked                 1.1.3
pytest-html                   2.0.1
pytest-metadata               1.9.0
pytest-ordering               0.6
pytest-rerunfailures          9.0
pytest-xdist                  1.32.0
python-dateutil               2.7.3
pytz                          2018.7
requests                      2.24.0
rich                          2.2.3
s3transfer                    0.1.13
selenium                      3.141.0
selenium-base                 0.1.0
seleniumbase                  1.40.2
setuptools                    47.3.1
setuptools-scm                4.1.2
six                           1.11.0
sortedcontainers              2.2.2
soupsieve                     2.0.1
subprocess32                  3.5.3
tempora                       1.14
termcolor                     1.1.0
traitlets                     4.3.3
typing-extensions             3.7.4.2
urllib3                       1.25.9
virtualenv                    16.7.2
w3lib                         1.22.0
wcwidth                       0.2.4
wheel                         0.33.6
wrapt                         1.10.11
zc.lockfile                   1.4
zipp                          3.1.0
```

of the host python where ``virtualenv`` is installed:

  ```console

  ```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```
 virtualenv -p `which python3` -vvv venv
Running virtualenv with interpreter /usr/bin/python3
Already using interpreter /Applications/Xcode.app/Contents/Developer/usr/bin/python3
Using base prefix '/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7'
Creating /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7
Symlinking Python bootstrap modules
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/lib-dynload
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/config-3.7m-darwin
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/os.py
  Ignoring built-in bootstrap module: posix
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/posixpath.py
  Cannot import bootstrap module: nt
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/ntpath.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/genericpath.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/fnmatch.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/locale.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/encodings
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/codecs.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/stat.py
  Cannot import bootstrap module: UserDict
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/readline.so
  Cannot import bootstrap module: copy_reg
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/types.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/re.py
  Cannot import bootstrap module: sre
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/sre_parse.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/sre_constants.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/sre_compile.py
  File /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/lib-dynload/zlib.cpython-37m-darwin.so already exists
  Cannot import bootstrap module: _abcoll
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/warnings.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/linecache.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/abc.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/io.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/_weakrefset.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/copyreg.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/tempfile.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/random.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/__future__.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/collections
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/keyword.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/tarfile.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/shutil.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/struct.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/copy.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/tokenize.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/token.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/functools.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/heapq.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/bisect.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/weakref.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/reprlib.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/base64.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/_dummy_thread.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/hashlib.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/hmac.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/imp.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/importlib
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/rlcompleter.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/operator.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/_collections_abc.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/_bootlocale.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/enum.py
  Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/LICENSE.txt
Creating /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/site-packages
Writing /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/site.py
Writing /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/orig-prefix.txt
Writing /Users/david/Documents/mydrive/dev/selenium/venv/lib/python3.7/no-global-site-packages.txt
Creating parent directories for /Users/david/Documents/mydrive/dev/selenium/venv/include
Symlinking /Users/david/Documents/mydrive/dev/selenium/venv/include/python3.7m
Creating /Users/david/Documents/mydrive/dev/selenium/venv/bin
New python executable in /Users/david/Documents/mydrive/dev/selenium/venv/bin/python3
Changed mode of /Users/david/Documents/mydrive/dev/selenium/venv/bin/python3 to 0o755
Also creating executable in /Users/david/Documents/mydrive/dev/selenium/venv/bin/python
Changed mode of /Users/david/Documents/mydrive/dev/selenium/venv/bin/python to 0o755
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/virtualenv.py", line 2635, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/virtualenv.py", line 870, in main
    symlink=options.symlink,
  File "/usr/local/lib/python3.7/site-packages/virtualenv.py", line 1156, in create_environment
    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
  File "/usr/local/lib/python3.7/site-packages/virtualenv.py", line 1621, in install_python
    shutil.copy(original_python, py_executable)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/shutil.py", line 103, in copyfile
    if _samefile(src, dst):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/shutil.py", line 88, in _samefile
    return os.path.samefile(src, dst)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/genericpath.py", line 96, in samefile
    s1 = os.stat(f1)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType```

**Comment by gaborbernat** [comment]
You're using a very old outdated version ``virtualenv                    16.7.2``, please upgrade to ``20.0.23``

**Comment by davidcsi** [comment]
thanks!
