### ISSUE TITLE
ImportError: No module named 'virtualenv.seed.via_app_data'

### ISSUE THREAD

**Issue by quarthex** [pypa/virtualenv#1875]
**Issue**

A module seems to be missing.

```sh
$ /cygdrive/c/Python34/python -m virtualenv -vvv --with-traceback
234 setup logging to NOTSET [DEBUG report:42]
250 find interpreter for spec PythonSpec(path=C:\Python34\python.exe) [INFO builtin:44]
250 proposed PythonInfo(spec=CPython3.4.4.final.0-32, exe=C:\Python34\python.exe, platform=win32, version='3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)]', encoding_fs_io=mbcs-cp1252) [INFO builtin:50]
250 accepted PythonInfo(spec=CPython3.4.4.final.0-32, exe=C:\Python34\python.exe, platform=win32, version='3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)]', encoding_fs_io=mbcs-cp1252) [DEBUG builtin:52]
265 symlink on filesystem does not work [DEBUG info:47]
265 filesystem is not case-sensitive [DEBUG info:28]
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\cygwin\home\😐\Python\Python34\site-packages\virtualenv\__main__.py", line 77, in <module>
    run_with_catch()  # pragma: no cov
  File "C:\cygwin\home\😐\Python\Python34\site-packages\virtualenv\__main__.py", line 63, in run_with_catch
    run(args, options)
  File "C:\cygwin\home\😐\Python\Python34\site-packages\virtualenv\__main__.py", line 17, in run
    session = cli_run(args, options)
  File "C:\cygwin\home\😐\Python\Python34\site-packages\virtualenv\run\__init__.py", line 24, in cli_run
    session = session_via_cli(args, options)
  File "C:\cygwin\home\😐\Python\Python34\site-packages\virtualenv\run\__init__.py", line 32, in session_via_cli
    parser, elements = build_parser(args, options)
  File "C:\cygwin\home\😐\Python\Python34\site-packages\virtualenv\run\__init__.py", line 60, in build_parser
    SeederSelector(interpreter, parser),
  File "C:\cygwin\home\😐\Python\Python34\site-packages\virtualenv\run\plugin\seeders.py", line 8, in __init__
    possible = self.options("virtualenv.seed")
  File "C:\cygwin\home\😐\Python\Python34\site-packages\virtualenv\run\plugin\base.py", line 39, in options
    cls._OPTIONS = cls.entry_points_for(key)
  File "C:\cygwin\home\😐\Python\Python34\site-packages\virtualenv\run\plugin\base.py", line 18, in entry_points_for
    return OrderedDict((e.name, e.load()) for e in cls.entry_points().get(key, {}))
  File "C:\Python34\lib\collections\__init__.py", line 60, in __init__
    self.__update(*args, **kwds)
  File "C:\Python34\lib\_collections_abc.py", line 597, in update
    for key, value in other:
  File "C:\cygwin\home\😐\Python\Python34\site-packages\virtualenv\run\plugin\base.py", line 18, in <genexpr>
    return OrderedDict((e.name, e.load()) for e in cls.entry_points().get(key, {}))
  File "C:\Python34\lib\site-packages\importlib_metadata\__init__.py", line 95, in load
    module = import_module(match.group('module'))
  File "C:\Python34\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'virtualenv.seed.via_app_data'
```

**Environment**

- OS: Windows XP / Cygwin
- ``pip list`` of the host python where ``virtualenv`` is installed:

```console
Package             Version
------------------- -------
appdirs             1.4.3
cx-Freeze           5.0.2
distlib             0.3.0
filelock            3.0.12
importlib-metadata  1.1.3
importlib-resources 1.0.2
numpy               1.16.6
pathlib2            2.3.5
Pillow              5.3.0 
pip                 19.1.1
py2exe              0.9.2.2
PyIDL               2.65
Pypubsub            4.0.0
pyreadline          2.1
pyserial            3.0.1
scandir             1.10.0
setuptools          43.0.0
six                 1.15.0
typing              3.7.4.1
virtualenv          20.0.25
wxPython            4.0.6
zipp                1.2.0
```

**Comment by gaborbernat** [comment]
You seem to have installed both a new old version of virtualenv and they are conflicting with each other. Please clean up your environments, and reinstall virtualenv.

**Comment by ycd** [comment]
@gaborbernat I don't think the problem is new and old versions of virtualenv i't happened on my fresh installed os. Could it be a problem with related to releases after 20.0.23?

Cause only uninstalling then installing the virtualenv==20.0.23 version solved my problem, thanks.

**Comment by gaborbernat** [comment]
It's a conflict between two existing virtualenv installation. You might have installed latest version, however if in the same python you also have an old version installed this error will pop up. Maybe you have a user and system installation in parallel.
