### ISSUE TITLE
Unable to create virtualenv for Jython 2.7.1

### ISSUE THREAD

**Issue by electricsam** [pypa/virtualenv#1908]
**Issue**

I need to support Python 2.7, specifically Jython.  When I run virtualenv directly or through pyenv virtualenv, I get the following error:
```
 RuntimeError: No virtualenv implementation for PythonInfo(spec=Jython2.7.1.final.0-32, exe=/Users/cslater/.pyenv/versions/jython-2.7.1/bin/jython, platform=java1.8.0_202, version=u'2.7.1 (default:0df7adb1b397, Jun 30 2017, 19:02:43) \n[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)]', encoding_fs_io=utf-8-UTF-8)
```

**Environment**

- OS: macOS 10.15.5
- ``pip list`` of the host python where ``virtualenv`` is installed:
```
$ pip list
Package             Version
------------------- -----------
appdirs             1.4.4
configparser        4.0.2
contextlib2         0.6.0.post1
distlib             0.3.1
filelock            3.0.12
importlib-metadata  1.7.0
importlib-resources 3.0.0
pathlib2            2.3.5
pip                 20.1.1
scandir             1.10.0
setuptools          28.8.0
singledispatch      3.4.0.3
six                 1.15.0
typing              3.7.4.3
virtualenv          20.0.28
zipp                1.2.0
```

```console
$ python --version
Jython 2.7.1
```

**Output of the virtual environment creation**

  ```console
$ python -m virtualenv venv -vvv --with-traceback
/Users/cslater/.pyenv/versions/jython-2.7.1/Lib/site-packages/filelock.py:451: UserWarning: only soft file lock is available
  warnings.warn("only soft file lock is available")
3101 setup logging to NOTSET [DEBUG report:43]
3263 find interpreter for spec PythonSpec(path=/Users/cslater/.pyenv/versions/jython-2.7.1/bin/jython) [INFO builtin:44]
3266 proposed PythonInfo({'exec_prefix': u'/Users/cslater/.pyenv/versions/jython-2.7.1', 'distutils_install': {u'headers': u'Include/UNKNOWN', u'platlib': u'Lib/site-packages', u'data': u'', u'purelib': u'Lib/site-packages', u'scripts': u'bin'}, 'prefix': u'/Users/cslater/.pyenv/versions/jython-2.7.1', 'system_stdlib_platform': u'/Users/cslater/.pyenv/versions/jython-2.7.1/lib/jython', 'platform': u'java1.8.0_202', 'real_prefix': None, 'path': [u'', u'/Users/cslater/.pyenv/versions/jython-2.7.1/Lib', u'__classpath__', u'__pyclasspath__/', u'/Users/cslater/.pyenv/versions/jython-2.7.1/Lib/site-packages'], 'file_system_encoding': u'utf-8', 'sysconfig': {u'makefile_filename': u'/Users/cslater/.pyenv/versions/jython-2.7.1/lib/jython/config/Makefile'}, 'has_venv': False, 'sysconfig_paths': {u'include': u'{base}/include/jython', u'platlib': u'{base}/lib/jython', u'data': u'{base}', u'platstdlib': u'{base}/lib/jython', u'stdlib': u'{base}/lib/jython', u'purelib': u'{base}/lib/jython', u'scripts': u'{base}/bin'}, 'architecture': 32, 'original_executable': u'/Users/cslater/.pyenv/versions/jython-2.7.1/bin/jython', 'os': u'java', 'system_stdlib': u'/Users/cslater/.pyenv/versions/jython-2.7.1/lib/jython', 'implementation': u'Jython', 'base_exec_prefix': None, 'version_info': VersionInfo(major=2, minor=7, micro=1, releaselevel=u'final', serial=0), 'version': u'2.7.1 (default:0df7adb1b397, Jun 30 2017, 19:02:43) \n[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)]', 'executable': '/Users/cslater/.pyenv/versions/jython-2.7.1/bin/jython', 'max_size': 2147483647, 'stdout_encoding': u'UTF-8', 'system_executable': u'/Users/cslater/.pyenv/versions/jython-2.7.1/bin/jython', 'sysconfig_vars': {u'PYTHONFRAMEWORK': u'', u'base': u'/Users/cslater/.pyenv/versions/jython-2.7.1'}, 'base_prefix': None}) [INFO builtin:50]
3269 accepted PythonInfo({'exec_prefix': u'/Users/cslater/.pyenv/versions/jython-2.7.1', 'distutils_install': {u'headers': u'Include/UNKNOWN', u'platlib': u'Lib/site-packages', u'data': u'', u'purelib': u'Lib/site-packages', u'scripts': u'bin'}, 'prefix': u'/Users/cslater/.pyenv/versions/jython-2.7.1', 'system_stdlib_platform': u'/Users/cslater/.pyenv/versions/jython-2.7.1/lib/jython', 'platform': u'java1.8.0_202', 'real_prefix': None, 'path': [u'', u'/Users/cslater/.pyenv/versions/jython-2.7.1/Lib', u'__classpath__', u'__pyclasspath__/', u'/Users/cslater/.pyenv/versions/jython-2.7.1/Lib/site-packages'], 'file_system_encoding': u'utf-8', 'sysconfig': {u'makefile_filename': u'/Users/cslater/.pyenv/versions/jython-2.7.1/lib/jython/config/Makefile'}, 'has_venv': False, 'sysconfig_paths': {u'include': u'{base}/include/jython', u'platlib': u'{base}/lib/jython', u'data': u'{base}', u'platstdlib': u'{base}/lib/jython', u'stdlib': u'{base}/lib/jython', u'purelib': u'{base}/lib/jython', u'scripts': u'{base}/bin'}, 'architecture': 32, 'original_executable': u'/Users/cslater/.pyenv/versions/jython-2.7.1/bin/jython', 'os': u'java', 'system_stdlib': u'/Users/cslater/.pyenv/versions/jython-2.7.1/lib/jython', 'implementation': u'Jython', 'base_exec_prefix': None, 'version_info': VersionInfo(major=2, minor=7, micro=1, releaselevel=u'final', serial=0), 'version': u'2.7.1 (default:0df7adb1b397, Jun 30 2017, 19:02:43) \n[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)]', 'executable': '/Users/cslater/.pyenv/versions/jython-2.7.1/bin/jython', 'max_size': 2147483647, 'stdout_encoding': u'UTF-8', 'system_executable': u'/Users/cslater/.pyenv/versions/jython-2.7.1/bin/jython', 'sysconfig_vars': {u'PYTHONFRAMEWORK': u'', u'base': u'/Users/cslater/.pyenv/versions/jython-2.7.1'}, 'base_prefix': None}) [DEBUG builtin:52]
3309 filesystem is not case-sensitive [DEBUG info:28]
Traceback (most recent call last):
  File "/Users/cslater/.pyenv/versions/jython-2.7.1/Lib/runpy.py", line 161, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/cslater/.pyenv/versions/jython-2.7.1/Lib/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/cslater/.pyenv/versions/jython-2.7.1/Lib/site-packages/virtualenv/__main__.py", line 77, in <module>
    run_with_catch()  # pragma: no cov
  File "/Users/cslater/.pyenv/versions/jython-2.7.1/Lib/site-packages/virtualenv/__main__.py", line 62, in run_with_catch
    run(args, options)
  File "/Users/cslater/.pyenv/versions/jython-2.7.1/Lib/site-packages/virtualenv/__main__.py", line 16, in run
    session = cli_run(args, options)
  File "/Users/cslater/.pyenv/versions/jython-2.7.1/Lib/site-packages/virtualenv/__main__.py", line 16, in run
    session = cli_run(args, options)
  File "/Users/cslater/.pyenv/versions/jython-2.7.1/Lib/site-packages/virtualenv/run/__init__.py", line 26, in cli_run
    of_session = session_via_cli(args, options, setup_logging)
  File "/Users/cslater/.pyenv/versions/jython-2.7.1/Lib/site-packages/virtualenv/run/__init__.py", line 42, in session_via_cli
    parser, elements = build_parser(args, options, setup_logging)
  File "/Users/cslater/.pyenv/versions/jython-2.7.1/Lib/site-packages/virtualenv/run/__init__.py", line 67, in build_parser
    elements = [
  File "/Users/cslater/.pyenv/versions/jython-2.7.1/Lib/site-packages/virtualenv/run/plugin/creators.py", line 15, in __init__
    creators, self.key_to_meta, self.describe, self.builtin_key = self.for_interpreter(interpreter)
  File "/Users/cslater/.pyenv/versions/jython-2.7.1/Lib/site-packages/virtualenv/run/plugin/creators.py", line 46, in for_interpreter
    raise RuntimeError("No virtualenv implementation for {}".format(interpreter))
RuntimeError: No virtualenv implementation for PythonInfo(spec=Jython2.7.1.final.0-32, exe=/Users/cslater/.pyenv/versions/jython-2.7.1/bin/jython, platform=java1.8.0_202, version=u'2.7.1 (default:0df7adb1b397, Jun 30 2017, 19:02:43) \n[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)]', encoding_fs_io=utf-8-UTF-8)

  ```

**Comment by gaborbernat** [comment]
virtualenv does not support Jython. And does not plan to add it to core virtualenv. Instead with the rewrite we allow custom python interpreter developers past PyPy and CPython to add support for their interpreters via a plugin, see https://virtualenv.pypa.io/en/latest/extend.html#creators for more details. So in short either reach out to the Jython developers to create this plugin, or create it yourself. If you do this please post here the link towards the plugin adding support.

**Comment by gaborbernat** [comment]
By the way you might consider moving your project to graalpython, that might work, see https://github.com/graalvm/graalpython/blob/master/docs/user/JYTHON.md
