### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 3: ordinal not in range(128)

### ISSUE THREAD

**Issue by Sriram21** [pypa/virtualenv#1932]
Hi,

I have an application which uses pyvenv. When i upload a json data to a remote server its getting through. On the other hand if i send a zip data it is getting failed with the following exception.

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/engineio/client.py", line 578, in _write_loop
    headers={'Content-Type': 'application/octet-stream'})
  File "/usr/local/lib/python2.7/dist-packages/engineio/client.py", line 406, in _send_request
    return self.http.request(method, url, headers=headers, body=body)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 323, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 880, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 3: ordinal not in range(128)

Upon researching on this exception it says the python v2 needs a patch to be updated in /usr/lib/python2.7/httplib.py

Fix : https://bugs.python.org/file21747/python-2.7.1-fix-httplib-UnicodeDecodeError.patch

Is there any other way to fix this without modifying the /usr/lib/python2.7/httplib.py from our application itself.

Any help will be appreciated

Regards,
Sriram

**Comment by gaborbernat** [comment]
This doesn't seem virtualenv related.
