### ISSUE TITLE
Venv Setup Fails in OSX

### ISSUE THREAD

**Issue by Sriram21** [pypa/virtualenv#1933]
Hi,

Two things i m trying to achieve here. 

1) Install venv and install pip using that python ( python3 virtualenv.py )
2) Install python modules using pip

Both results in the following exceptions.

Setting up virtual environment
/opt/app//pypi/virtualenv.py:1086: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/opt/app//pypi/virtualenv.py", line 2338, in <module>
    main()
  File "/opt/app//pypi/virtualenv.py", line 824, in main
    symlink=options.symlink)
  File "/opt/app//pypi/virtualenv.py", line 984, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/opt/app//pypi/virtualenv.py", line 1351, in install_python
    shutil.copy(original_python, py_executable)
UnboundLocalError: local variable 'original_python' referenced before assignment

############# Done ########

Installing python packages using pip
dyld: Library not loaded: @executable_path/../Python3
  Referenced from: /opt/app/venv/bin/python
  Reason: image not found

dyld: Library not loaded: @executable_path/../Python3
  Referenced from: /opt/app/venv/bin/python
  Reason: image not found

dyld: Library not loaded: @executable_path/../Python3
  Referenced from: /opt/app/venv/bin/python
  Reason: image not found

dyld: Library not loaded: @executable_path/../Python3
  Referenced from: /opt/app/venv/bin/python
  Reason: image not found

dyld: Library not loaded: @executable_path/../Python3
  Referenced from: /opt/app/venv/bin/python
  Reason: image not found

dyld: Library not loaded: @executable_path/../Python3
  Referenced from: /opt/app/venv/bin/python
  Reason: image not found

dyld: Library not loaded: @executable_path/../Python3
  Referenced from: /opt/app/venv/bin/python
  Reason: image not found

dyld: Library not loaded: @executable_path/../Python3
  Referenced from: /opt/app/venv/bin/python
  Reason: image not found

############# Done ########

Any help will be appreciated.

Regards.
Sriram

**Comment by gaborbernat** [comment]
That's for an old unsupported version of virtualenv 🙏 please upgrade.

**Comment by Sriram21** [comment]
@gaborbernat : Tried with a higher version of virtual env.

Found the below exception

Traceback (most recent call last):
  File "/opt/app/pypi/virtualenv.py", line 2635, in <module>
    main()
  File "/opt/app/pypi/virtualenv.py", line 870, in main
    symlink=options.symlink,
  File "/opt/app/pypi/virtualenv.py", line 1173, in create_environment
    install_wheel(to_install, py_executable, search_dirs, download=download)
  File "/opt/app/pypi/virtualenv.py", line 1019, in install_wheel
    _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs)
  File "/opt/app/pypi/virtualenv.py", line 1110, in _install_wheel_with_search_dir
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=script)
  File "/opt/app/pypi/virtualenv.py", line 963, in call_subprocess
    raise OSError("Command {} failed with error code {}".format(cmd_desc, proc.returncode))
OSError: Command /opt/app/venv/bin/python2.7 - wheel failed with error code 1


Is it possible to share the stable version of virtual env which doesn't throw any error while building an app?

Correct me if am doing anything wrong?

Regards 
Sriram

**Comment by gaborbernat** [comment]
Latest version doesn't have virtualenv.py. you're trying with old version.

**Comment by Sriram21** [comment]
@gaborbernat : It seems the latest virtualenv.py i could find was in version 16.7.0 . Post that installations are suggested to try via zipapp. But the zipapp has issues in python3.3v and supported from v3.6 . How can i make this thing work in all subversion of python3 and 2.7

**Comment by gaborbernat** [comment]
Then you cannot. Sorry, you're in unsupported domain.

**Comment by Sriram21** [comment]
@gaborbernat : I tried setting up virtual environment using zipapp . It works properly in Linux machines but not the case with OSX.

Following error occured ::

**python detected :: python3.7**

Detected shell :: bash
Setting up virtual environment
installing via zip app
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/app/pypi/virtualenv.pyz/__main__.py", line 168, in <module>
  File "/opt/app/pypi/virtualenv.pyz/__main__.py", line 162, in run
  File "/opt/app/pypi/virtualenv.pyz/virtualenv/__init__.py", line 3, in <module>
  File "/opt/app/pypi/virtualenv.pyz/virtualenv/run/__init__.py", line 9, in <module>
  File "/opt/app/pypi/virtualenv.pyz/virtualenv/seed/wheels/__init__.py", line 3, in <module>
  File "/opt/app/pypi/virtualenv.pyz/virtualenv/seed/wheels/acquire.py", line 15, in <module>
  File "/opt/app/pypi/virtualenv.pyz/virtualenv/seed/wheels/bundle.py", line 6, in <module>
  File "/opt/app/pypi/virtualenv.pyz/virtualenv/seed/wheels/periodic_update.py", line 10, in <module>
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: dlopen(/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_ssl.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_ssl.cpython-37m-darwin.so
  Reason: image not found

**Comment by gaborbernat** [comment]
The error comes from your python, not virtualenv. You'll need to fix your Python there.
