### ISSUE TITLE
Fatal Python error: initsite: Failed to import the site module

### ISSUE THREAD

**Issue by iHTCboy** [pypa/virtualenv#1937]
**Issue**

```
Fatal Python error: initsite: Failed to import the site module
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site.py", line 579, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site.py", line 562, in main
    known_paths = venv(known_paths)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site.py", line 480, in venv
    with open(virtual_conf, encoding='utf-8') as f:
PermissionError: [Errno 1] Operation not permitted: '/Users/htc/Downloads/project-py/venv/pyvenv.cfg'
```

**Environment**

Provide at least:
- OS: macOS 10.15.6
- ``pip list`` of the host python where ``virtualenv`` is installed:

 ```console

Package            Version
------------------ -------
appdirs            1.4.4
distlib            0.3.1
filelock           3.0.12
importlib-metadata 1.7.0
pip                20.2.3
setuptools         47.1.0
six                1.15.0
virtualenv         20.0.31
zipp               3.1.0
 
```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console
113 setup logging to NOTSET [DEBUG report:43]
122 find interpreter for spec PythonSpec(implementation=CPython, major=3, minor=7) [INFO builtin:44]
122 proposed PythonInfo(spec=CPython3.7.9.final.0-64, exe=/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7, platform=darwin, version='3.7.9 (v3.7.9:13c94747c7, Aug 15 2020, 01:31:08) \n[Clang 6.0 (clang-600.0.57)]', encoding_fs_io=utf-8-UTF-8) [INFO builtin:50]
122 accepted PythonInfo(spec=CPython3.7.9.final.0-64, exe=/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7, platform=darwin, version='3.7.9 (v3.7.9:13c94747c7, Aug 15 2020, 01:31:08) \n[Clang 6.0 (clang-600.0.57)]', encoding_fs_io=utf-8-UTF-8) [DEBUG builtin:52]
125 filesystem is not case-sensitive [DEBUG info:28]
187 create virtual environment via CPython3Posix(dest=/Users/htc/Downloads/project-py/venv, clear=False, global=False) [INFO session:52]
187 create folder /Users/htc/Downloads/project-py/venv/bin [DEBUG _sync:25]
188 create folder /Users/htc/Downloads/project-py/venv/lib/python3.7/site-packages [DEBUG _sync:25]
188 write /Users/htc/Downloads/project-py/venv/pyvenv.cfg [DEBUG pyenv_cfg:34]
188 	home = /Library/Frameworks/Python.framework/Versions/3.7 [DEBUG pyenv_cfg:38]
189 	implementation = CPython [DEBUG pyenv_cfg:38]
189 	version_info = 3.7.9.final.0 [DEBUG pyenv_cfg:38]
189 	virtualenv = 20.0.31 [DEBUG pyenv_cfg:38]
189 	include-system-site-packages = false [DEBUG pyenv_cfg:38]
189 	base-prefix = /Library/Frameworks/Python.framework/Versions/3.7 [DEBUG pyenv_cfg:38]
189 	base-exec-prefix = /Library/Frameworks/Python.framework/Versions/3.7 [DEBUG pyenv_cfg:38]
189 	base-executable = /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 [DEBUG pyenv_cfg:38]
189 symlink /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 to /Users/htc/Downloads/project-py/venv/bin/python [DEBUG _sync:44]
190 create virtualenv import hook file /Users/htc/Downloads/project-py/venv/lib/python3.7/site-packages/_virtualenv.pth [DEBUG api:94]
191 create /Users/htc/Downloads/project-py/venv/lib/python3.7/site-packages/_virtualenv.py [DEBUG api:97]
192 ============================== target debug ============================== [DEBUG session:54]
192 debug via /Users/htc/Downloads/project-py/venv/bin/python /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/virtualenv/create/debug.py [DEBUG creator:209]
192 {
  "sys": {
    "executable": "/Users/htc/Downloads/project-py/venv/bin/python",
    "_base_executable": null,
    "prefix": "/Users/htc/Downloads/project-py/venv",
    "base_prefix": "/Library/Frameworks/Python.framework/Versions/3.7",
    "real_prefix": null,
    "exec_prefix": "/Users/htc/Downloads/project-py/venv",
    "base_exec_prefix": "/Library/Frameworks/Python.framework/Versions/3.7",
    "path": [
      "/Library/Frameworks/Python.framework/Versions/3.7/lib/python37.zip",
      "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7",
      "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload",
      "/Users/htc/Downloads/project-py/venv/lib/python3.7/site-packages"
    ],
    "meta_path": [
      "<class '_virtualenv._Finder'>",
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib_external.PathFinder'>"
    ],
    "fs_encoding": "utf-8",
    "io_encoding": "UTF-8"
  },
  "version": "3.7.9 (v3.7.9:13c94747c7, Aug 15 2020, 01:31:08) \n[Clang 6.0 (clang-600.0.57)]",
  "makefile_filename": "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin/Makefile",
  "os": "<module 'os' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py'>",
  "site": "<module 'site' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site.py'>",
  "datetime": "<module 'datetime' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/datetime.py'>",
  "math": "<module 'math' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/math.cpython-37m-darwin.so'>",
  "json": "<module 'json' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py'>"
} [DEBUG session:55]
241 add seed packages via FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/htc/Library/Application Support/virtualenv) [INFO session:59]
246 got embed update of distribution pip from /Users/htc/Library/Application Support/virtualenv/wheel/3.7/embed/1/pip.json [DEBUG via_disk_folder:133]
249 got embed update of distribution wheel from /Users/htc/Library/Application Support/virtualenv/wheel/3.7/embed/1/wheel.json [DEBUG via_disk_folder:133]
250 got embed update of distribution setuptools from /Users/htc/Library/Application Support/virtualenv/wheel/3.7/embed/1/setuptools.json [DEBUG via_disk_folder:133]
252 got embed update of distribution pip from /Users/htc/Library/Application Support/virtualenv/wheel/3.7/embed/1/pip.json [DEBUG via_disk_folder:133]
253 got embed update of distribution setuptools from /Users/htc/Library/Application Support/virtualenv/wheel/3.7/embed/1/setuptools.json [DEBUG via_disk_folder:133]
254 got embed update of distribution wheel from /Users/htc/Library/Application Support/virtualenv/wheel/3.7/embed/1/wheel.json [DEBUG via_disk_folder:133]
255 install pip from wheel /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/virtualenv/seed/wheels/embed/pip-20.2.2-py2.py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:53]
255 Attempting to acquire lock 140687437408848 on /Users/htc/Library/Application Support/virtualenv/wheel/3.7/image/1/CopyPipInstall/pip-20.2.2-py2.py3-none-any.lock [DEBUG filelock:270]
255 install setuptools from wheel /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/virtualenv/seed/wheels/embed/setuptools-49.6.0-py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:53]
256 Lock 140687437408848 acquired on /Users/htc/Library/Application Support/virtualenv/wheel/3.7/image/1/CopyPipInstall/pip-20.2.2-py2.py3-none-any.lock [INFO filelock:274]
256 Attempting to acquire lock 140687437409552 on /Users/htc/Library/Application Support/virtualenv/wheel/3.7/image/1/CopyPipInstall/setuptools-49.6.0-py3-none-any.lock [DEBUG filelock:270]
256 install wheel from wheel /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/virtualenv/seed/wheels/embed/wheel-0.35.1-py2.py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:53]
256 Attempting to acquire lock 140687437408208 on /Users/htc/Library/Application Support/virtualenv/wheel/3.7/image/1/CopyPipInstall/wheel-0.35.1-py2.py3-none-any.lock [DEBUG filelock:270]
256 Lock 140687437409552 acquired on /Users/htc/Library/Application Support/virtualenv/wheel/3.7/image/1/CopyPipInstall/setuptools-49.6.0-py3-none-any.lock [INFO filelock:274]
256 Lock 140687437408208 acquired on /Users/htc/Library/Application Support/virtualenv/wheel/3.7/image/1/CopyPipInstall/wheel-0.35.1-py2.py3-none-any.lock [INFO filelock:274]
257 Attempting to release lock 140687437408848 on /Users/htc/Library/Application Support/virtualenv/wheel/3.7/image/1/CopyPipInstall/pip-20.2.2-py2.py3-none-any.lock [DEBUG filelock:315]
257 Lock 140687437408848 released on /Users/htc/Library/Application Support/virtualenv/wheel/3.7/image/1/CopyPipInstall/pip-20.2.2-py2.py3-none-any.lock [INFO filelock:318]
257 Attempting to release lock 140687437408208 on /Users/htc/Library/Application Support/virtualenv/wheel/3.7/image/1/CopyPipInstall/wheel-0.35.1-py2.py3-none-any.lock [DEBUG filelock:315]
257 Lock 140687437408208 released on /Users/htc/Library/Application Support/virtualenv/wheel/3.7/image/1/CopyPipInstall/wheel-0.35.1-py2.py3-none-any.lock [INFO filelock:318]
257 Attempting to release lock 140687437409552 on /Users/htc/Library/Application Support/virtualenv/wheel/3.7/image/1/CopyPipInstall/setuptools-49.6.0-py3-none-any.lock [DEBUG filelock:315]
257 Lock 140687437409552 released on /Users/htc/Library/Application Support/virtualenv/wheel/3.7/image/1/CopyPipInstall/setuptools-49.6.0-py3-none-any.lock [INFO filelock:318]
258 copy directory /Users/htc/Library/Application Support/virtualenv/wheel/3.7/image/1/CopyPipInstall/pip-20.2.2-py2.py3-none-any/pip-20.2.2.dist-info to /Users/htc/Downloads/project-py/venv/lib/python3.7/site-packages/pip-20.2.2.dist-info [DEBUG _sync:52]
258 copy directory /Users/htc/Library/Application Support/virtualenv/wheel/3.7/image/1/CopyPipInstall/wheel-0.35.1-py2.py3-none-any/wheel to /Users/htc/Downloads/project-py/venv/lib/python3.7/site-packages/wheel [DEBUG _sync:52]
259 copy /Users/htc/Library/Application Support/virtualenv/wheel/3.7/image/1/CopyPipInstall/setuptools-49.6.0-py3-none-any/easy_install.py to /Users/htc/Downloads/project-py/venv/lib/python3.7/site-packages/easy_install.py [DEBUG _sync:52]
260 copy /Users/htc/Library/Application Support/virtualenv/wheel/3.7/image/1/CopyPipInstall/setuptools-49.6.0-py3-none-any/setuptools-49.6.0.virtualenv to /Users/htc/Downloads/project-py/venv/lib/python3.7/site-packages/setuptools-49.6.0.virtualenv [DEBUG _sync:52]
261 copy /Users/htc/Library/Application Support/virtualenv/wheel/3.7/image/1/CopyPipInstall/setuptools-49.6.0-py3-none-any/distutils-precedence.pth to /Users/htc/Downloads/project-py/venv/lib/python3.7/site-packages/distutils-precedence.pth [DEBUG _sync:52]
262 copy directory /Users/htc/Library/Application Support/virtualenv/wheel/3.7/image/1/CopyPipInstall/setuptools-49.6.0-py3-none-any/setuptools to /Users/htc/Downloads/project-py/venv/lib/python3.7/site-packages/setuptools [DEBUG _sync:52]
270 copy directory /Users/htc/Library/Application Support/virtualenv/wheel/3.7/image/1/CopyPipInstall/pip-20.2.2-py2.py3-none-any/pip to /Users/htc/Downloads/project-py/venv/lib/python3.7/site-packages/pip [DEBUG _sync:52]
280 copy directory /Users/htc/Library/Application Support/virtualenv/wheel/3.7/image/1/CopyPipInstall/wheel-0.35.1-py2.py3-none-any/wheel-0.35.1.dist-info to /Users/htc/Downloads/project-py/venv/lib/python3.7/site-packages/wheel-0.35.1.dist-info [DEBUG _sync:52]
290 copy /Users/htc/Library/Application Support/virtualenv/wheel/3.7/image/1/CopyPipInstall/wheel-0.35.1-py2.py3-none-any/wheel-0.35.1.virtualenv to /Users/htc/Downloads/project-py/venv/lib/python3.7/site-packages/wheel-0.35.1.virtualenv [DEBUG _sync:52]
296 generated console scripts wheel3 wheel wheel-3.7 wheel3.7 [DEBUG base:48]
425 copy directory /Users/htc/Library/Application Support/virtualenv/wheel/3.7/image/1/CopyPipInstall/setuptools-49.6.0-py3-none-any/pkg_resources to /Users/htc/Downloads/project-py/venv/lib/python3.7/site-packages/pkg_resources [DEBUG _sync:52]
465 copy directory /Users/htc/Library/Application Support/virtualenv/wheel/3.7/image/1/CopyPipInstall/setuptools-49.6.0-py3-none-any/setuptools-49.6.0.dist-info to /Users/htc/Downloads/project-py/venv/lib/python3.7/site-packages/setuptools-49.6.0.dist-info [DEBUG _sync:52]
590 copy directory /Users/htc/Library/Application Support/virtualenv/wheel/3.7/image/1/CopyPipInstall/setuptools-49.6.0-py3-none-any/_distutils_hack to /Users/htc/Downloads/project-py/venv/lib/python3.7/site-packages/_distutils_hack [DEBUG _sync:52]
597 generated console scripts easy_install3.7 easy_install-3.7 easy_install easy_install3 [DEBUG base:48]
830 copy /Users/htc/Library/Application Support/virtualenv/wheel/3.7/image/1/CopyPipInstall/pip-20.2.2-py2.py3-none-any/pip-20.2.2.virtualenv to /Users/htc/Downloads/project-py/venv/lib/python3.7/site-packages/pip-20.2.2.virtualenv [DEBUG _sync:52]
836 generated console scripts pip pip3.7 pip-3.7 pip3 [DEBUG base:48]
837 add activators for Bash, CShell, Fish, PowerShell, Python, Xonsh [INFO session:65]
844 write /Users/htc/Downloads/project-py/venv/pyvenv.cfg [DEBUG pyenv_cfg:34]
844 	home = /Library/Frameworks/Python.framework/Versions/3.7 [DEBUG pyenv_cfg:38]
844 	implementation = CPython [DEBUG pyenv_cfg:38]
844 	version_info = 3.7.9.final.0 [DEBUG pyenv_cfg:38]
844 	virtualenv = 20.0.31 [DEBUG pyenv_cfg:38]
844 	include-system-site-packages = false [DEBUG pyenv_cfg:38]
844 	base-prefix = /Library/Frameworks/Python.framework/Versions/3.7 [DEBUG pyenv_cfg:38]
844 	base-exec-prefix = /Library/Frameworks/Python.framework/Versions/3.7 [DEBUG pyenv_cfg:38]
844 	base-executable = /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 [DEBUG pyenv_cfg:38]
845 created virtual environment CPython3.7.9.final.0-64 in 734ms
  creator CPython3Posix(dest=/Users/htc/Downloads/project-py/venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/htc/Library/Application Support/virtualenv)
    added seed packages: pip==20.2.2, setuptools==49.6.0, wheel==0.35.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator [WARNING __main__:17]
```

**Comment by iHTCboy** [comment]
This issue seems related to the local file permissions on your operating system, and not django-apscheduler.

You should be able to find more information on how to change local file permissions on OSX with a quick internet search.
