### ISSUE TITLE
--always-copy is not working

### ISSUE THREAD

**Issue by michal-halenka-datasentics** [pypa/virtualenv#1942]
**Issue**

I am trying to use `virtualenv --always-copy`

**Environment**

Provide at least:
- OS: Fedora 32
- ``pip list`` of the host python where ``virtualenv`` is installed:

  ```console
  ❯ pip list
  Package                               Version       
  ------------------------------------- --------------
  adal                                  1.2.4         
  aiodns                                2.0.0         
  aiohttp                               3.6.2         
  aiohttp-cors                          0.7.0         
  ansible                               2.9.13        
  antlr4-python3-runtime                4.7.2         
  appdirs                               1.4.3         
  applicationinsights                   0.11.9        
  apsw                                  3.33.0.post1  
  argcomplete                           1.10.0        
  arrow                                 0.15.5        
  asciinema                             2.0.2         
  async-timeout                         3.0.1         
  attrs                                 19.3.0        
  Automat                               20.2.0        
  awscli                                1.17.17       
  azure-batch                           9.0.0         
  azure-cli                             2.11.1        
  azure-cli-command-modules-nspkg       2.0.3         
  azure-cli-core                        2.11.1        
  azure-cli-nspkg                       3.0.4         
  azure-cli-telemetry                   1.0.4         
  azure-common                          1.1.25        
  azure-core                            1.7.0         
  azure-cosmos                          3.2.0         
  azure-datalake-store                  0.0.49        
  azure-functions-devops-build          0.0.22        
  azure-graphrbac                       0.60.0        
  azure-keyvault                        1.1.0         
  azure-loganalytics                    0.1.0         
  azure-mgmt-advisor                    2.0.1         
  azure-mgmt-apimanagement              0.1.0         
  azure-mgmt-appconfiguration           0.5.0         
  azure-mgmt-applicationinsights        0.1.1         
  azure-mgmt-authorization              0.52.0        
  azure-mgmt-batch                      9.0.0         
  azure-mgmt-batchai                    2.0.0         
  azure-mgmt-billing                    0.2.0         
  azure-mgmt-botservice                 0.2.0         
  azure-mgmt-cdn                        5.0.0         
  azure-mgmt-cognitiveservices          6.2.0         
  azure-mgmt-compute                    13.0.0        
  azure-mgmt-consumption                2.0.0         
  azure-mgmt-containerinstance          1.5.0         
  azure-mgmt-containerregistry          3.0.0rc14     
  azure-mgmt-containerservice           9.0.1         
  azure-mgmt-core                       1.0.0         
  azure-mgmt-cosmosdb                   0.15.0        
  azure-mgmt-datalake-analytics         0.2.1         
  azure-mgmt-datalake-nspkg             3.0.1         
  azure-mgmt-datalake-store             0.5.0         
  azure-mgmt-datamigration              0.1.0         
  azure-mgmt-deploymentmanager          0.2.0         
  azure-mgmt-devtestlabs                4.0.0         
  azure-mgmt-dns                        2.1.0         
  azure-mgmt-eventgrid                  3.0.0rc7      
  azure-mgmt-eventhub                   4.0.0         
  azure-mgmt-hdinsight                  1.7.0         
  azure-mgmt-imagebuilder               0.4.0         
  azure-mgmt-iotcentral                 3.0.0         
  azure-mgmt-iothub                     0.12.0        
  azure-mgmt-iothubprovisioningservices 0.2.0         
  azure-mgmt-keyvault                   7.0.0b3       
  azure-mgmt-kusto                      0.3.0         
  azure-mgmt-loganalytics               0.7.0         
  azure-mgmt-managedservices            1.0.0         
  azure-mgmt-managementgroups           0.2.0         
  azure-mgmt-maps                       0.1.0         
  azure-mgmt-marketplaceordering        0.2.1         
  azure-mgmt-media                      2.2.0         
  azure-mgmt-monitor                    0.11.0        
  azure-mgmt-msi                        0.2.0         
  azure-mgmt-netapp                     0.12.0        
  azure-mgmt-network                    11.0.0        
  azure-mgmt-nspkg                      3.0.2         
  azure-mgmt-policyinsights             0.5.0         
  azure-mgmt-privatedns                 0.1.0         
  azure-mgmt-rdbms                      2.2.0         
  azure-mgmt-recoveryservices           0.4.0         
  azure-mgmt-recoveryservicesbackup     0.6.0         
  azure-mgmt-redhatopenshift            0.1.0         
  azure-mgmt-redis                      7.0.0rc1      
  azure-mgmt-relay                      0.1.0         
  azure-mgmt-reservations               0.6.0         
  azure-mgmt-resource                   10.2.0        
  azure-mgmt-search                     2.1.0         
  azure-mgmt-security                   0.4.1         
  azure-mgmt-servicebus                 0.6.0         
  azure-mgmt-servicefabric              0.4.0         
  azure-mgmt-signalr                    0.4.0         
  azure-mgmt-sql                        0.19.0        
  azure-mgmt-sqlvirtualmachine          0.5.0         
  azure-mgmt-storage                    11.1.0        
  azure-mgmt-synapse                    0.3.0         
  azure-mgmt-trafficmanager             0.51.0        
  azure-mgmt-web                        0.47.0        
  azure-multiapi-storage                0.4.1         
  azure-nspkg                           3.0.2         
  azure-storage-common                  1.4.2         
  azure-synapse-accesscontrol           0.2.0         
  azure-synapse-spark                   0.2.0         
  b2sdk                                 1.1.4         
  Babel                                 2.8.0         
  backcall                              0.1.0         
  bcrypt                                3.1.7         
  beautifulsoup4                        4.9.1         
  black                                 19.10b0       
  bleach                                3.1.4         
  blivet                                3.2.2         
  blivet-gui                            2.1.15        
  bodhi                                 5.1.1         
  bodhi-client                          5.1.1         
  boto                                  2.49.0        
  boto3                                 1.11.17       
  botocore                              1.14.17       
  Bottleneck                            1.2.1         
  cached-property                       1.5.1         
  cachetools                            4.1.0         
  CCColUtils                            1.5           
  certifi                               2018.10.15    
  cffi                                  1.14.0        
  chardet                               3.0.4         
  click                                 7.1.1         
  click-plugins                         1.1.1         
  colorama                              0.4.1         
  conda                                 4.8.2         
  conda-package-handling                1.6.0         
  constantly                            15.1.0        
  cryptography                          2.8           
  css-parser                            1.0.4         
  cssselect                             0.9.2         
  cssutils                              1.0.2         
  cupshelpers                           1.0           
  cycler                                0.10.0        
  cytoolz                               0.10.1        
  dasbus                                0.2           
  databricks-cli                        0.11.0        
  dbus-python                           1.2.16        
  decorator                             4.4.0         
  defusedxml                            0.6.0         
  dictdiffer                            0.1.dev1+dirty
  distro                                1.4.0         
  dnspython                             1.16.0        
  docker                                4.2.0         
  docker-compose                        1.25.4        
  docker-pycreds                        0.4.0         
  dockerpty                             0.4.1         
  docopt                                0.6.2         
  docutils                              0.15.2        
  dropbox                               10.1.2        
  duplicity                             0.8.15        
  ecdsa                                 0.15          
  entrypoints                           0.3           
  evdev                                 1.1.2         
  fabric                                2.5.0         
  fasteners                             0.14.1        
  fedora-review                         0.7.5         
  fedpkg                                1.39          
  feedparser                            5.2.1         
  fido2                                 0.8.1         
  file-magic                            0.4.0         
  flake8                                3.7.7         
  fluidity-sm                           0.2.0         
  frozendict                            1.2           
  funcsigs                              1.0.2         
  future                                0.18.2        
  GDAL                                  3.0.4         
  gitdb2                                2.0.3         
  GitPython                             3.0.2         
  google-api-python-client              1.6.7         
  google-auth                           1.21.1        
  gpg                                   1.14.0        
  greenlet                              0.4.16        
  gssapi                                1.6.1         
  html2text                             2019.9.26     
  html5-parser                          0.4.9         
  html5lib                              1.0.1         
  httpie                                1.0.3         
  httplib2                              0.18.1        
  humanfriendly                         8.2           
  humanize                              0.5.1         
  hyperlink                             19.0.0        
  idna                                  2.8           
  ifaddr                                0.1.6         
  img2pdf                               0.3.4         
  incremental                           17.5.0        
  initial-setup                         0.3.80        
  invoke                                1.4.1         
  iotop                                 0.6           
  ipykernel                             5.1.4         
  ipython                               7.12.0        
  ipython-genutils                      0.1.0         
  isodate                               0.6.0         
  javaproperties                        0.5.1         
  jedi                                  0.15.1        
  Jinja2                                2.11.2        
  jmespath                              0.9.4         
  jsmin                                 2.2.2         
  jsondiff                              1.2.0         
  jsonschema                            3.2.0         
  jupyter-client                        5.3.4         
  jupyter-core                          4.6.1         
  kitchen                               1.2.6         
  kiwisolver                            1.2.0         
  knack                                 0.7.2         
  kubernetes                            11.0.0        
  langtable                             0.0.53        
  lexicon                               1.0.0         
  libarchive-c                          2.9           
  libcomps                              0.1.15        
  libvirt-python                        6.1.0         
  lockfile                              0.11.0        
  logfury                               0.1.2         
  lutris                                0.5.7.1       
  lxml                                  4.4.1         
  Markdown                              3.2.2         
  MarkupSafe                            1.1.1         
  matplotlib                            3.2.2         
  mccabe                                0.6.1         
  mechanize                             0.4.3         
  meld                                  3.20.2        
  meson                                 0.55.3        
  mistune                               0.8.3         
  mock                                  3.0.5         
  msal                                  1.0.0         
  msal-extensions                       0.1.3         
  msgpack                               0.6.2         
  msrest                                0.6.17        
  msrestazure                           0.6.4         
  multidict                             4.7.4         
  munch                                 2.3.2         
  nbconvert                             5.6.0         
  nbformat                              5.0.4         
  netaddr                               0.7.19        
  netifaces                             0.10.6        
  networkx                              2.5           
  nftables                              0.1           
  notebook                              6.0.2         
  ntlm-auth                             1.1.0         
  ntplib                                0.3.3         
  numexpr                               2.7.1         
  numpy                                 1.18.4        
  oauth2client                          4.1.3         
  oauthlib                              3.0.2         
  ocrmypdf                              9.8.2         
  odfpy                                 1.4.0         
  olefile                               0.46          
  openidc-client                        0.6.0         
  openshift                             0.11.2        
  ordered-set                           3.1           
  packaging                             20.1          
  pandas                                0.25.3        
  pandas-datareader                     0.8.0         
  pandocfilters                         1.4.1         
  paramiko                              2.7.1         
  parso                                 0.5.2         
  pathspec                              0.6.0         
  pbr                                   5.4.3         
  pdfminer.six                          20181108      
  pexpect                               4.7.0         
  pickleshare                           0.7.5         
  pid                                   2.2.3         
  pikepdf                               1.19.3        
  Pillow                                7.0.0         
  pip                                   19.3.1        
  pkginfo                               1.5.0.1       
  ply                                   3.11          
  portalocker                           1.7.0         
  powerline-status                      2.8           
  productmd                             1.27          
  prometheus-client                     0.7.1         
  prompt-toolkit                        2.0.10        
  psutil                                5.6.7         
  ptyprocess                            0.6.0         
  pwquality                             1.4.2         
  py-cpuinfo                            5.0.0         
  pyasn1                                0.4.8         
  pyasn1-modules                        0.2.8         
  pycairo                               1.18.2        
  pycares                               3.1.1         
  pycodestyle                           2.5.0         
  pycosat                               0.6.3         
  pycparser                             2.19          
  pycrypto                              2.6.1         
  pycryptodomex                         3.9.8         
  pycups                                2.0.1         
  pycurl                                7.43.0.5      
  pydbus                                0.6.0         
  pydot                                 1.4.1         
  PyDrive                               1.3.1         
  pyenchant                             2.0.0         
  pyflakes                              2.1.1         
  pygit2                                1.2.1         
  Pygments                              2.4.2         
  PyGObject                             3.36.1        
  pygraphviz                            1.5           
  PyHamcrest                            1.9.0         
  pyinotify                             0.9.6         
  PyJWT                                 1.7.1         
  pykickstart                           3.24          
  PyNaCl                                1.3.0         
  pynvim                                0.4.0         
  pyOpenSSL                             19.0.0        
  pyparsing                             2.4.7         
  pyparted                              3.11.4        
  PyQt5                                 5.14.2        
  PyQt5-sip                             4.19.21       
  PyQtWebEngine                         5.14.0        
  pyroute2                              0.5.6         
  pyrsistent                            0.16.0        
  pyscard                               1.9.7         
  PySocks                               1.7.1         
  python-augeas                         0.5.0         
  python-bugzilla                       2.5.0         
  python-dateutil                       2.8.0         
  python-fedora                         0.10.0        
  python-meh                            0.48          
  python-string-utils                   0.6.0         
  python-yubico                         1.3.3         
  pytz                                  2019.1        
  pyudev                                0.22.0        
  pyusb                                 1.0.2         
  pywinrm                               0.3.0         
  PyYAML                                5.3.1         
  pyzmq                                 18.1.0        
  qtconsole                             4.6.0         
  regex                                 2020.7.14     
  reportlab                             3.5.44        
  requests                              2.22.0        
  requests-file                         1.4.3         
  requests-ftp                          0.3.1         
  requests-gssapi                       1.2.2         
  requests-ntlm                         1.1.0         
  requests-oauthlib                     1.2.0         
  rpkg                                  1.61          
  rpm                                   4.15.1        
  rpmconf                               1.0.21        
  rsa                                   3.4.2         
  ruamel.yaml                           0.16.6        
  ruamel.yaml.clib                      0.1.2         
  s3transfer                            0.3.3         
  scipy                                 1.4.1         
  scour                                 0.37          
  scp                                   0.13.2        
  selinux                               3.0           
  Send2Trash                            1.4.2         
  sepolicy                              3.0           
  service-identity                      18.1.0        
  setools                               4.3.0         
  setroubleshoot                        1.1           
  setuptools                            41.6.0        
  shodan                                1.23.1        
  simplegeneric                         0.8.1         
  simpleline                            1.6           
  six                                   1.14.0        
  slip                                  0.6.4         
  slip.dbus                             0.6.4         
  smmap2                                2.0.3         
  solaar                                1.0.3         
  sortedcontainers                      2.2.2         
  sos                                   3.9           
  soupsieve                             1.9.2         
  sshtunnel                             0.1.5         
  stevedore                             1.31.0        
  straight.plugin                       1.5.0         
  systemd-python                        234           
  tables                                3.5.2         
  tabulate                              0.8.7         
  terminado                             0.8.3         
  testpath                              0.3.1         
  texttable                             1.6.2         
  toml                                  0.10.0        
  toolz                                 0.10.0        
  tornado                               6.0.3         
  tqdm                                  4.47.0        
  traitlets                             4.3.3         
  Twisted                               20.3.0        
  typed-ast                             1.4.1         
  udiskie                               2.2.0         
  uritemplate                           3.0.0         
  urllib3                               1.25.7        
  virtualenv                            16.7.10       
  virtualenv-clone                      0.5.3         
  virtualenvwrapper                     4.8.2         
  vsts                                  0.1.25        
  vsts-cd-manager                       1.0.2         
  wcwidth                               0.2.4         
  webencodings                          0.5.1         
  websocket-client                      0.56.0        
  wrapt                                 1.11.2        
  xlrd                                  1.2.0         
  XlsxWriter                            1.2.9         
  xlwt                                  1.1.2         
  xmltodict                             0.12.0        
  yarl                                  1.4.2         
  youtube-dl                            2020.9.14     
  yubikey-manager                       3.1.1         
  zeroconf                              0.26.1        
  zope.event                            4.2.0         
  zope.interface                        4.7.1
  ```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console
❯ virtualenv --always-copy -vvv --with-traceback cookiecutter
Usage: virtualenv [OPTIONS] DEST_DIR

virtualenv: error: no such option: --with-traceback
❯ virtualenv --always-copy -vvv cookiecutter                 
Using base prefix '/usr'
Creating /home/username/work/DataScience/cookiecutter/lib/python3.8
This system uses lib64; symlinking lib64 to lib
Copying to /home/username/work/DataScience/cookiecutter/lib64
Symlinking Python bootstrap modules
  Copying to /home/username/work/DataScience/cookiecutter/lib/python3.8/lib-dynload
  Copying to /home/username/work/DataScience/cookiecutter/lib/python3.8/config-3.8-x86_64-linux-gnu
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/os.py
  Ignoring built-in bootstrap module: posix
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/posixpath.py
  Cannot import bootstrap module: nt
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/ntpath.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/genericpath.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/fnmatch.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/locale.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/encodings
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/codecs.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/stat.py
  Cannot import bootstrap module: UserDict
  Creating parent directories for /home/username/work/DataScience/cookiecutter/lib64/python3.8/lib-dynload
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/lib-dynload/readline.cpython-38-x86_64-linux-gnu.so
  Cannot import bootstrap module: copy_reg
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/types.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/re.py
  Cannot import bootstrap module: sre
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/sre_parse.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/sre_constants.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/sre_compile.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/lib-dynload/zlib.cpython-38-x86_64-linux-gnu.so
  Cannot import bootstrap module: _abcoll
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/warnings.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/linecache.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/abc.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/io.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/_weakrefset.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/copyreg.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/tempfile.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/random.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/__future__.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/collections
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/keyword.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/tarfile.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/shutil.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/struct.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/copy.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/tokenize.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/token.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/functools.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/heapq.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/bisect.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/weakref.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/reprlib.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/base64.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/_dummy_thread.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/hashlib.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/hmac.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/imp.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/importlib
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/rlcompleter.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/operator.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/_collections_abc.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/_bootlocale.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/enum.py
  Copying to /home/username/work/DataScience/cookiecutter/lib64/python3.8/LICENSE.txt
Creating /home/username/work/DataScience/cookiecutter/lib/python3.8/site-packages
Writing /home/username/work/DataScience/cookiecutter/lib64/python3.8/site.py
Writing /home/username/work/DataScience/cookiecutter/lib64/python3.8/orig-prefix.txt
Writing /home/username/work/DataScience/cookiecutter/lib64/python3.8/no-global-site-packages.txt
Creating parent directories for /home/username/work/DataScience/cookiecutter/include
Copying to /home/username/work/DataScience/cookiecutter/include/python3.8
Creating /home/username/work/DataScience/cookiecutter/bin
New python executable in /home/username/work/DataScience/cookiecutter/bin/python3
Changed mode of /home/username/work/DataScience/cookiecutter/bin/python3 to 0o775
Also creating executable in /home/username/work/DataScience/cookiecutter/bin/python
Changed mode of /home/username/work/DataScience/cookiecutter/bin/python to 0o775
Copying to /home/username/work/DataScience/cookiecutter/bin/python
Copying to /home/username/work/DataScience/cookiecutter/bin/python3.8
Testing executable with /home/username/work/DataScience/cookiecutter/bin/python3 -c "import sys;out=sys.stdout;getattr(out, "buffer", out).write(sys.prefix.encode("utf-8"))"
Got sys.prefix result: '/home/username/work/DataScience/cookiecutter'
Creating /home/username/work/DataScience/cookiecutter/lib64/python3.8/distutils
Writing /home/username/work/DataScience/cookiecutter/lib64/python3.8/distutils/__init__.py
Writing /home/username/work/DataScience/cookiecutter/lib64/python3.8/distutils/distutils.cfg
Running command /home/username/work/Dat...iecutter/bin/python3 -m pip config list
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/share/python-wheels/pip-19.3.1-py2.py3-none-any.whl/pip/__main__.py", line 16, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/pip-19.3.1-py2.py3-none-any.whl/pip/_internal/__init__.py", line 3, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/pip-19.3.1-py2.py3-none-any.whl/pip/_internal/main.py", line 13, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/pip-19.3.1-py2.py3-none-any.whl/pip/_internal/cli/autocompletion.py", line 11, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/pip-19.3.1-py2.py3-none-any.whl/pip/_internal/cli/main_parser.py", line 7, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/pip-19.3.1-py2.py3-none-any.whl/pip/_internal/cli/cmdoptions.py", line 24, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/pip-19.3.1-py2.py3-none-any.whl/pip/_internal/exceptions.py", line 10, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/pip-19.3.1-py2.py3-none-any.whl/pip/_vendor/six.py", line 631, in <module>
  File "/home/username/work/DataScience/cookiecutter/lib64/python3.8/struct.py", line 13, in <module>
    from _struct import *
ModuleNotFoundError: No module named '_struct'
Command /home/username/work/Dat...iecutter/bin/python3 -m pip config list had error code 1
Installing setuptools, pip, wheel...

  Running command /home/username/work/Dat...iecutter/bin/python3 - setuptools pip wheel
  Traceback (most recent call last):
    File "<stdin>", line 4, in <module>
    File "/home/username/work/DataScience/cookiecutter/lib64/python3.8/tempfile.py", line 45, in <module>
      from random import Random as _Random
    File "/home/username/work/DataScience/cookiecutter/lib64/python3.8/random.py", line 41, in <module>
      from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
  ModuleNotFoundError: No module named 'math'
  Complete output from command /home/username/work/Dat...iecutter/bin/python3 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/username/work/DataScience/cookiecutter/lib64/python3.8/tempfile.py", line 45, in <module>
    from random import Random as _Random
  File "/home/username/work/DataScience/cookiecutter/lib64/python3.8/random.py", line 41, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ModuleNotFoundError: No module named 'math'
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 11, in <module>
    load_entry_point('virtualenv==16.7.10', 'console_scripts', 'virtualenv')()
  File "/usr/lib/python3.8/site-packages/virtualenv.py", line 870, in main
    create_environment(
  File "/usr/lib/python3.8/site-packages/virtualenv.py", line 1195, in create_environment
    install_wheel(to_install, py_executable, search_dirs, download=download)
  File "/usr/lib/python3.8/site-packages/virtualenv.py", line 1035, in install_wheel
    _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs)
  File "/usr/lib/python3.8/site-packages/virtualenv.py", line 1132, in _install_wheel_with_search_dir
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=script)
  File "/usr/lib/python3.8/site-packages/virtualenv.py", line 973, in call_subprocess
    raise OSError("Command {} failed with error code {}".format(cmd_desc, proc.returncode))
OSError: Command /home/username/work/Dat...iecutter/bin/python3 - setuptools pip wheel failed with error code 1

```

**Comment by michal-halenka-datasentics** [comment]
might be related to #1192

**Comment by gaborbernat** [comment]
```bash
virtualenv: error: no such option: --with-traceback
```

This part tells me that you're not using the latest release. Please try again with that https://pypi.org/project/virtualenv/20.0.31/.

**Comment by michal-halenka-datasentics** [comment]
Correct, can not reproduce this on version 20.0.31
