### ISSUE TITLE
python3.4: Path has no attribute write_bytes

### ISSUE THREAD

**Issue by asottile** [pypa/virtualenv#1963]
**Issue**

appears to have regressed in #1924

**Environment**

Provide at least:
- OS: linux
- ``pip list`` of the host python where ``virtualenv`` is installed:

  ```console
   appdirs==1.4.4
   distlib==0.3.1
   filelock==3.0.12
   importlib-metadata==1.1.3
   importlib-resources==1.0.2
   pathlib2==2.3.5
   PyYAML==3.10
   scandir==1.10.0
   six==1.15.0
   typing==3.7.4.3
   virtualenv==20.0.32
   zipp==1.2.0
  ```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console
root@e8c42617e572:/# virtualenv venv -vvv --with-traceback
106 setup logging to NOTSET [DEBUG report:43]
133 find interpreter for spec PythonSpec(path=/usr/bin/python3) [INFO builtin:44]
133 proposed PythonInfo(spec=CPython3.4.3.final.0-64, exe=/usr/bin/python3, platform=linux, version='3.4.3 (default, Nov 12 2018, 22:25:49) \n[GCC 4.8.4]', encoding_fs_io=ascii-ANSI_X3.4-1968) [INFO builtin:50]
134 accepted PythonInfo(spec=CPython3.4.3.final.0-64, exe=/usr/bin/python3, platform=linux, version='3.4.3 (default, Nov 12 2018, 22:25:49) \n[GCC 4.8.4]', encoding_fs_io=ascii-ANSI_X3.4-1968) [DEBUG builtin:52]
135 filesystem is case-sensitive [DEBUG info:28]
179 create virtual environment via CPython3Posix(dest=/venv, clear=False, global=False) [INFO session:52]
180 create folder /venv/bin [DEBUG _sync:25]
180 create folder /venv/lib/python3.4/site-packages [DEBUG _sync:25]
180 write /venv/pyvenv.cfg [DEBUG pyenv_cfg:34]
180 	home = /usr [DEBUG pyenv_cfg:38]
180 	implementation = CPython [DEBUG pyenv_cfg:38]
181 	version_info = 3.4.3.final.0 [DEBUG pyenv_cfg:38]
181 	virtualenv = 20.0.32 [DEBUG pyenv_cfg:38]
181 	include-system-site-packages = false [DEBUG pyenv_cfg:38]
181 	base-prefix = /usr [DEBUG pyenv_cfg:38]
181 	base-exec-prefix = /usr [DEBUG pyenv_cfg:38]
181 	base-executable = /usr/bin/python3 [DEBUG pyenv_cfg:38]
181 symlink /usr/bin/python3 to /venv/bin/python [DEBUG _sync:44]
182 create virtualenv import hook file /venv/lib/python3.4/site-packages/_virtualenv.pth [DEBUG api:95]
183 create /venv/lib/python3.4/site-packages/_virtualenv.py [DEBUG api:98]
183 ============================== target debug ============================== [DEBUG session:54]
184 debug via /venv/bin/python /usr/local/lib/python3.4/dist-packages/virtualenv/create/debug.py [DEBUG creator:213]
183 {
  "version": "3.4.3 (default, Nov 12 2018, 22:25:49) \n[GCC 4.8.4]",
  "datetime": "<module 'datetime' from '/usr/lib/python3.4/datetime.py'>",
  "site": "<module 'site' from '/usr/lib/python3.4/site.py'>",
  "makefile_filename": "/usr/lib/python3.4/config-3.4m-x86_64-linux-gnu/Makefile",
  "sys": {
    "path": [
      "/usr/lib/python3.4",
      "/usr/lib/python3.4/plat-x86_64-linux-gnu",
      "/usr/lib/python3.4/lib-dynload",
      "/venv/lib/python3.4/site-packages"
    ],
    "fs_encoding": "ascii",
    "io_encoding": "ANSI_X3.4-1968",
    "exec_prefix": "/venv",
    "_base_executable": null,
    "base_prefix": "/usr",
    "base_exec_prefix": "/usr",
    "executable": "/venv/bin/python",
    "real_prefix": null,
    "prefix": "/venv",
    "meta_path": [
      "<class '_virtualenv._Finder'>",
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib.PathFinder'>"
    ]
  },
  "os": "<module 'os' from '/usr/lib/python3.4/os.py'>",
  "json": "<module 'json' from '/usr/lib/python3.4/json/__init__.py'>",
  "math": "<module 'math' (built-in)>"
} [DEBUG session:55]
230 add seed packages via FromAppData(download=False, pip=bundle, wheel=bundle, setuptools=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv) [INFO session:59]
233 got embed update of distribution setuptools from /root/.local/share/virtualenv/wheel/3.4/embed/1/setuptools.json [DEBUG via_disk_folder:133]
234 got embed update of distribution pip from /root/.local/share/virtualenv/wheel/3.4/embed/1/pip.json [DEBUG via_disk_folder:133]
234 got embed update of distribution wheel from /root/.local/share/virtualenv/wheel/3.4/embed/1/wheel.json [DEBUG via_disk_folder:133]
238 got embed update of distribution pip from /root/.local/share/virtualenv/wheel/3.4/embed/1/pip.json [DEBUG via_disk_folder:133]
239 got embed update of distribution wheel from /root/.local/share/virtualenv/wheel/3.4/embed/1/wheel.json [DEBUG via_disk_folder:133]
239 got embed update of distribution setuptools from /root/.local/share/virtualenv/wheel/3.4/embed/1/setuptools.json [DEBUG via_disk_folder:133]
239 install pip from wheel /usr/local/lib/python3.4/dist-packages/virtualenv/seed/wheels/embed/pip-19.1.1-py2.py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:53]
240 Attempting to acquire lock 140611254941288 on /root/.local/share/virtualenv/wheel/3.4/image/1/CopyPipInstall/pip-19.1.1-py2.py3-none-any.lock [DEBUG filelock:270]
240 install setuptools from wheel /usr/local/lib/python3.4/dist-packages/virtualenv/seed/wheels/embed/setuptools-43.0.0-py2.py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:53]
240 install wheel from wheel /usr/local/lib/python3.4/dist-packages/virtualenv/seed/wheels/embed/wheel-0.33.6-py2.py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:53]
240 Lock 140611254941288 acquired on /root/.local/share/virtualenv/wheel/3.4/image/1/CopyPipInstall/pip-19.1.1-py2.py3-none-any.lock [INFO filelock:274]
240 Attempting to acquire lock 140611254942072 on /root/.local/share/virtualenv/wheel/3.4/image/1/CopyPipInstall/setuptools-43.0.0-py2.py3-none-any.lock [DEBUG filelock:270]
243 Lock 140611254942072 acquired on /root/.local/share/virtualenv/wheel/3.4/image/1/CopyPipInstall/setuptools-43.0.0-py2.py3-none-any.lock [INFO filelock:274]
241 Attempting to release lock 140611254941288 on /root/.local/share/virtualenv/wheel/3.4/image/1/CopyPipInstall/pip-19.1.1-py2.py3-none-any.lock [DEBUG filelock:315]
240 Attempting to acquire lock 140611254941512 on /root/.local/share/virtualenv/wheel/3.4/image/1/CopyPipInstall/wheel-0.33.6-py2.py3-none-any.lock [DEBUG filelock:270]
243 Attempting to release lock 140611254942072 on /root/.local/share/virtualenv/wheel/3.4/image/1/CopyPipInstall/setuptools-43.0.0-py2.py3-none-any.lock [DEBUG filelock:315]
243 Lock 140611254941288 released on /root/.local/share/virtualenv/wheel/3.4/image/1/CopyPipInstall/pip-19.1.1-py2.py3-none-any.lock [INFO filelock:318]
244 Lock 140611254942072 released on /root/.local/share/virtualenv/wheel/3.4/image/1/CopyPipInstall/setuptools-43.0.0-py2.py3-none-any.lock [INFO filelock:318]
244 Lock 140611254941512 acquired on /root/.local/share/virtualenv/wheel/3.4/image/1/CopyPipInstall/wheel-0.33.6-py2.py3-none-any.lock [INFO filelock:274]
244 copy /root/.local/share/virtualenv/wheel/3.4/image/1/CopyPipInstall/setuptools-43.0.0-py2.py3-none-any/setuptools-43.0.0.virtualenv to /venv/lib/python3.4/site-packages/setuptools-43.0.0.virtualenv [DEBUG _sync:52]
245 copy directory /root/.local/share/virtualenv/wheel/3.4/image/1/CopyPipInstall/pip-19.1.1-py2.py3-none-any/pip-19.1.1.dist-info to /venv/lib/python3.4/site-packages/pip-19.1.1.dist-info [DEBUG _sync:52]
245 Attempting to release lock 140611254941512 on /root/.local/share/virtualenv/wheel/3.4/image/1/CopyPipInstall/wheel-0.33.6-py2.py3-none-any.lock [DEBUG filelock:315]
245 Lock 140611254941512 released on /root/.local/share/virtualenv/wheel/3.4/image/1/CopyPipInstall/wheel-0.33.6-py2.py3-none-any.lock [INFO filelock:318]
246 copy /root/.local/share/virtualenv/wheel/3.4/image/1/CopyPipInstall/wheel-0.33.6-py2.py3-none-any/wheel-0.33.6.virtualenv to /venv/lib/python3.4/site-packages/wheel-0.33.6.virtualenv [DEBUG _sync:52]
246 copy directory /root/.local/share/virtualenv/wheel/3.4/image/1/CopyPipInstall/setuptools-43.0.0-py2.py3-none-any/setuptools-43.0.0.dist-info to /venv/lib/python3.4/site-packages/setuptools-43.0.0.dist-info [DEBUG _sync:52]
247 copy directory /root/.local/share/virtualenv/wheel/3.4/image/1/CopyPipInstall/wheel-0.33.6-py2.py3-none-any/wheel-0.33.6.dist-info to /venv/lib/python3.4/site-packages/wheel-0.33.6.dist-info [DEBUG _sync:52]
251 copy directory /root/.local/share/virtualenv/wheel/3.4/image/1/CopyPipInstall/pip-19.1.1-py2.py3-none-any/pip to /venv/lib/python3.4/site-packages/pip [DEBUG _sync:52]
252 copy directory /root/.local/share/virtualenv/wheel/3.4/image/1/CopyPipInstall/wheel-0.33.6-py2.py3-none-any/wheel to /venv/lib/python3.4/site-packages/wheel [DEBUG _sync:52]
254 copy directory /root/.local/share/virtualenv/wheel/3.4/image/1/CopyPipInstall/setuptools-43.0.0-py2.py3-none-any/setuptools to /venv/lib/python3.4/site-packages/setuptools [DEBUG _sync:52]
265 generated console scripts wheel wheel-3.4 wheel3.4 wheel3 [DEBUG base:48]
313 copy /root/.local/share/virtualenv/wheel/3.4/image/1/CopyPipInstall/setuptools-43.0.0-py2.py3-none-any/easy_install.py to /venv/lib/python3.4/site-packages/easy_install.py [DEBUG _sync:52]
313 copy directory /root/.local/share/virtualenv/wheel/3.4/image/1/CopyPipInstall/setuptools-43.0.0-py2.py3-none-any/pkg_resources to /venv/lib/python3.4/site-packages/pkg_resources [DEBUG _sync:52]
327 generated console scripts easy_install3 easy_install easy_install-3.4 easy_install3.4 [DEBUG base:48]
437 copy /root/.local/share/virtualenv/wheel/3.4/image/1/CopyPipInstall/pip-19.1.1-py2.py3-none-any/pip-19.1.1.virtualenv to /venv/lib/python3.4/site-packages/pip-19.1.1.virtualenv [DEBUG _sync:52]
439 generated console scripts pip-3.4 pip3.4 pip3 pip [DEBUG base:48]
440 add activators for PowerShell, Fish, Python, Bash, CShell [INFO session:66]
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 10, in <module>
    sys.exit(run_with_catch())
  File "/usr/local/lib/python3.4/dist-packages/virtualenv/__main__.py", line 62, in run_with_catch
    run(args, options)
  File "/usr/local/lib/python3.4/dist-packages/virtualenv/__main__.py", line 16, in run
    session = cli_run(args, options)
  File "/usr/local/lib/python3.4/dist-packages/virtualenv/run/__init__.py", line 28, in cli_run
    of_session.run()
  File "/usr/local/lib/python3.4/dist-packages/virtualenv/run/session.py", line 48, in run
    self._activate()
  File "/usr/local/lib/python3.4/dist-packages/virtualenv/run/session.py", line 69, in _activate
    activator.generate(self.creator)
  File "/usr/local/lib/python3.4/dist-packages/virtualenv/activation/via_template.py", line 30, in generate
    generated = self._generate(replacements, self.templates(), dest_folder, creator)
  File "/usr/local/lib/python3.4/dist-packages/virtualenv/activation/via_template.py", line 58, in _generate
    dest.write_bytes(text.encode("utf-8"))
AttributeError: 'Path' object has no attribute 'write_bytes'
```

**Comment by gaborbernat** [comment]
@asottile 
![fixed it](https://media.tenor.co/images/d1c161f2ad06f70fba959e77551da0cc/tenor.gif)
