### ISSUE TITLE
RuntimeError: no .dist-info has pip

### ISSUE THREAD

**Issue by nautatva** [pypa/virtualenv#1971]
**Issue**
I'm trying to set up a pre-commit hook and got this bug. 
https://github.com/pre-commit/pre-commit/issues/1628

**Describe what's the expected behaviour and what you're observing.**
Using Python 3.8 (virtual environment), tried with pip 20.1.1 as well as pip 20.2.3. The error says .dist-info not found, I checked out the particular directory, that indeed is the case.
![image](https://user-images.githubusercontent.com/28155271/95292602-669f6600-088f-11eb-875c-0f2882a78379.png)

Expected should be a venv should be created

- OS: Windows
- ``pip list``: Tried making venv with pip 20.1.1 and 20.2.3 
- Python 3.8,

**Output of the virtual environment creation**
No issue in pip. I can use pip globally as well. Created venv using `python3 -m venv env` and this works fine

Make sure to run the creation with `-vvv --with-traceback`:

```console

(env) D:\Mac\Sites\project-reconnaissance>git commit -m "some message here"
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to C:\Users\cool dude\.cache\pre-commit\patch1602049156.
[INFO] Installing environment for https://github.com/timothycrosley/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Restored changes from C:\Users\cool dude\.cache\pre-commit\patch1602049156.
An unexpected error has occurred: CalledProcessError: command: ('d:\\mac\\sites\\project-reconnaissance\\env\\scripts\\python.exe', '-mvirtualenv', 'C:\\Users\\cool dude\\.cache\\pre-commit\\repowq_8m7xu\\py_env-python3.8', '-p', 'd:\\mac\\sites\\project-reconnaissance\\env\\scripts\\python.exe')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to build image pip because:
    Traceback (most recent call last):
      File "d:\mac\sites\project-reconnaissance\env\lib\site-packages\virtualenv\seed\embed\via_app_data\via_app_data.py", line 58, in 
_install
        installer.install(creator.interpreter.version_info)
      File "d:\mac\sites\project-reconnaissance\env\lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 46, in install
        for name, module in self._console_scripts.items():
      File "d:\mac\sites\project-reconnaissance\env\lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 116, in _console_scripts
        entry_points = self._dist_info / "entry_points.txt"
      File "d:\mac\sites\project-reconnaissance\env\lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 103, in _dist_info
        raise RuntimeError(msg)  # pragma: no cover
    RuntimeError: no .dist-info at C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\pip-20.2.3-py2.py3-none-any, has pip
```

**Comment by gaborbernat** [comment]
Can you try removing folder ``C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv`` and try again? You can achieve this by calling virtualenv with the ``--reset-app-data`` flag.

**Comment by gaborbernat** [comment]
Can you post the verbose output when you pass in the ``--reset-app-data``?

**Comment by nautatva** [comment]
Here: 
```
(env) D:\Mac\Sites\project-reconnaissance>python -mvirtualenv testenv -vvv --with-traceback --reset-app-data 
83 setup logging to NOTSET [DEBUG report:43]
86 reset app data folder C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv [DEBUG via_disk_folder:60]
178 find interpreter for spec PythonSpec(path=D:\Mac\Sites\project-reconnaissance\env\Scripts\python.exe) [INFO 
builtin:44]
179 Attempting to acquire lock 2807114782608 on C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\py_info\1\c874d2356398e7d73b6575972079bc7f9802680a36acc333dbd3ec7c9e6dced5.lock [DEBUG filelock:270]
181 Lock 2807114782608 acquired on C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\py_info\1\c874d2356398e7d73b6575972079bc7f9802680a36acc333dbd3ec7c9e6dced5.lock [INFO filelock:274]
181 get interpreter info via cmd: 'C:\Users\cool dude\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' 'D:\Mac\Sites\project-reconnaissance\env\lib\site-packages\virtualenv\discovery\py_info.py' [DEBUG cached_py_info:87]
310 wrote python info of C:\Users\cool dude\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe at C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\py_info\1\c874d2356398e7d73b6575972079bc7f9802680a36acc333dbd3ec7c9e6dced5.json [DEBUG via_disk_folder:162]
311 Attempting to release lock 2807114782608 on C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\py_info\1\c874d2356398e7d73b6575972079bc7f9802680a36acc333dbd3ec7c9e6dced5.lock [DEBUG filelock:315]
318 Lock 2807114782608 released on C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\py_info\1\c874d2356398e7d73b6575972079bc7f9802680a36acc333dbd3ec7c9e6dced5.lock [INFO filelock:318]
320 proposed PythonInfo(spec=CPython3.8.6.final.0-64, system=C:\Users\cool dude\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe, exe=D:\Mac\Sites\project-reconnaissance\env\Scripts\python.exe, platform=win32, version='3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]', encoding_fs_io=utf-8-cp1252) [INFO builtin:50]
321 accepted PythonInfo(spec=CPython3.8.6.final.0-64, system=C:\Users\cool dude\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe, exe=D:\Mac\Sites\project-reconnaissance\env\Scripts\python.exe, platform=win32, version='3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]', encoding_fs_io=utf-8-cp1252) [DEBUG builtin:52]
324 symlink on filesystem does not work [DEBUG info:47]
325 filesystem is not case-sensitive [DEBUG info:28]
372 create virtual environment via Venv(dest=D:\Mac\Sites\project-reconnaissance\testenv, clear=False, global=False, describe=CPython3Windows) [INFO session:52]
373 using host built-in venv to create via C:\Users\cool dude\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe -m venv --without-pip --copies D:\Mac\Sites\project-reconnaissance\testenv [INFO venv:58]
504 create virtualenv import hook file D:\Mac\Sites\project-reconnaissance\testenv\Lib\site-packages\_virtualenv.pth [DEBUG api:95]
505 create D:\Mac\Sites\project-reconnaissance\testenv\Lib\site-packages\_virtualenv.py [DEBUG api:98]
508 ============================== target debug ============================== [DEBUG session:54]
512 debug via 'D:\Mac\Sites\project-reconnaissance\testenv\Scripts\python.exe' 'D:\Mac\Sites\project-reconnaissance\env\lib\site-packages\virtualenv\create\debug.py' [DEBUG creator:213]
512 {
  "sys": {
    "executable": "D:\\Mac\\Sites\\project-reconnaissance\\testenv\\Scripts\\python.exe",
    "_base_executable": "C:\\Users\\cool dude\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\python.exe",
    "prefix": "D:\\Mac\\Sites\\project-reconnaissance\\testenv",
    "base_prefix": "C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0",
    "real_prefix": null,
    "exec_prefix": "D:\\Mac\\Sites\\project-reconnaissance\\testenv",
    "base_exec_prefix": "C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0",
    "path": [
      "C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\\python38.zip",
      "C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\\DLLs",      "C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\\lib", 
      "C:\\Users\\cool dude\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0",
      "D:\\Mac\\Sites\\project-reconnaissance\\testenv",
      "D:\\Mac\\Sites\\project-reconnaissance\\testenv\\lib\\site-packages"
    ],
    "meta_path": [
      "<class '_virtualenv._Finder'>",
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib_external.PathFinder'>"
    ],
    "fs_encoding": "utf-8",
    "io_encoding": "cp1252"
  },
  "version": "3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]",
  "makefile_filename": "C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\\Lib\\config\\Makefile",
  "os": "<module 'os' from 'C:\\\\Program Files\\\\WindowsApps\\\\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\\\\lib\\\\os.py'>",
  "site": "<module 'site' from 'C:\\\\Program Files\\\\WindowsApps\\\\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\\\\lib\\\\site.py'>",
  "datetime": "<module 'datetime' from 'C:\\\\Program Files\\\\WindowsApps\\\\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\\\\lib\\\\datetime.py'>",
  "math": "<module 'math' (built-in)>",
  "json": "<module 'json' from 'C:\\\\Program Files\\\\WindowsApps\\\\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\\\\lib\\\\json\\\\__init__.py'>"
} [DEBUG session:55]
631 add seed packages via FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv) [INFO session:59]
635 wrote embed update of distribution setuptools at C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\embed\1\setuptools.json [DEBUG via_disk_folder:162]
635 wrote embed update of distribution wheel at C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\embed\1\wheel.json [DEBUG via_disk_folder:162]
635 wrote embed update of distribution pip at C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\embed\1\pip.json [DEBUG via_disk_folder:162]
640 triggered periodic upgrade of setuptools==50.3.0 (for python 3.8) via background process having PID 4312 [INFO periodic_update:194]
640 triggered periodic upgrade of wheel==0.35.1 (for python 3.8) via background process having PID 5732 [INFO periodic_update:194]
642 triggered periodic upgrade of pip==20.2.3 (for python 3.8) via background process having PID 6860 [INFO periodic_update:194]
649 got embed update of distribution wheel from C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\embed\1\wheel.json [DEBUG via_disk_folder:133]
652 got embed update of distribution setuptools from C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\embed\1\setuptools.json [DEBUG via_disk_folder:133]
659 got embed update of distribution pip from C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\embed\1\pip.json [DEBUG via_disk_folder:133]
702 install wheel from wheel D:\Mac\Sites\project-reconnaissance\env\lib\site-packages\virtualenv\seed\wheels\embed\wheel-0.35.1-py2.py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:51]
705 install setuptools from wheel D:\Mac\Sites\project-reconnaissance\env\lib\site-packages\virtualenv\seed\wheels\embed\setuptools-50.3.0-py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:51]
706 install pip from wheel D:\Mac\Sites\project-reconnaissance\env\lib\site-packages\virtualenv\seed\wheels\embed\pip-20.2.3-py2.py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:51]
706 Attempting to acquire lock 2807117356192 on C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\wheel-0.35.1-py2.py3-none-any.lock [DEBUG filelock:270]
708 Attempting to acquire lock 2807117356288 on C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\setuptools-50.3.0-py3-none-any.lock [DEBUG filelock:270]
708 Attempting to acquire lock 2807117356960 on C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\pip-20.2.3-py2.py3-none-any.lock [DEBUG filelock:270]
723 Lock 2807117356192 acquired on C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\wheel-0.35.1-py2.py3-none-any.lock [INFO filelock:274]
725 Lock 2807117356288 acquired on C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\setuptools-50.3.0-py3-none-any.lock [INFO filelock:274]
739 Lock 2807117356960 acquired on C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\pip-20.2.3-py2.py3-none-any.lock [INFO filelock:274]
740 build install image for wheel-0.35.1-py2.py3-none-any.whl to C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\wheel-0.35.1-py2.py3-none-any [DEBUG base:52]
740 build install image for setuptools-50.3.0-py3-none-any.whl to C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\setuptools-50.3.0-py3-none-any [DEBUG base:52]
741 build install image for pip-20.2.3-py2.py3-none-any.whl to C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\pip-20.2.3-py2.py3-none-any [DEBUG base:52]
805 Attempting to release lock 2807117356192 on C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\wheel-0.35.1-py2.py3-none-any.lock [DEBUG filelock:315]
806 Lock 2807117356192 released on C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\wheel-0.35.1-py2.py3-none-any.lock [INFO filelock:318]
810 copy directory C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\wheel-0.35.1-py2.py3-none-any\wheel to D:\Mac\Sites\project-reconnaissance\testenv\Lib\site-packages\wheel [DEBUG _sync:52]
909 copy directory C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\wheel-0.35.1-py2.py3-none-any\wheel-0.35.1.dist-info to D:\Mac\Sites\project-reconnaissance\testenv\Lib\site-packages\wheel-0.35.1.dist-info [DEBUG _sync:52]
952 copy C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\wheel-0.35.1-py2.py3-none-any\wheel-0.35.1.virtualenv to D:\Mac\Sites\project-reconnaissance\testenv\Lib\site-packages\wheel-0.35.1.virtualenv [DEBUG _sync:52] 
979 generated console scripts wheel3.8.exe wheel.exe wheel3.exe wheel-3.8.exe [DEBUG base:48]
1059 Attempting to release lock 2807117356288 on C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\setuptools-50.3.0-py3-none-any.lock [DEBUG filelock:315]
1060 Lock 2807117356288 released on C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\setuptools-50.3.0-py3-none-any.lock [INFO filelock:318]
1062 copy C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\setuptools-50.3.0-py3-none-any\distutils-precedence.pth to D:\Mac\Sites\project-reconnaissance\testenv\Lib\site-packages\distutils-precedence.pth [DEBUG _sync:52]
1065 copy C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\setuptools-50.3.0-py3-none-any\easy_install.py 
to D:\Mac\Sites\project-reconnaissance\testenv\Lib\site-packages\easy_install.py [DEBUG _sync:52]
1068 copy directory C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\setuptools-50.3.0-py3-none-any\pkg_resources to D:\Mac\Sites\project-reconnaissance\testenv\Lib\site-packages\pkg_resources [DEBUG _sync:52]
1204 copy directory C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\setuptools-50.3.0-py3-none-any\setuptools to D:\Mac\Sites\project-reconnaissance\testenv\Lib\site-packages\setuptools [DEBUG _sync:52]
1454 Attempting to release lock 2807117356960 on C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\pip-20.2.3-py2.py3-none-any.lock [DEBUG filelock:315]
1455 Lock 2807117356960 released on C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\pip-20.2.3-py2.py3-none-any.lock [INFO filelock:318]
2022 copy directory C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\setuptools-50.3.0-py3-none-any\setuptools-50.3.0.dist-info to D:\Mac\Sites\project-reconnaissance\testenv\Lib\site-packages\setuptools-50.3.0.dist-info [DEBUG _sync:52]
2053 copy C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\setuptools-50.3.0-py3-none-any\setuptools-50.3.0.virtualenv to D:\Mac\Sites\project-reconnaissance\testenv\Lib\site-packages\setuptools-50.3.0.virtualenv [DEBUG _sync:52]
2055 copy directory C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\setuptools-50.3.0-py3-none-any\_distutils_hack to D:\Mac\Sites\project-reconnaissance\testenv\Lib\site-packages\_distutils_hack [DEBUG _sync:52]     
2067 generated console scripts easy_install3.exe easy_install.exe easy_install-3.8.exe easy_install3.8.exe [DEBUG base:48]
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Mac\Sites\project-reconnaissance\env\lib\site-packages\virtualenv\__main__.py", line 77, in <module>
    run_with_catch()  # pragma: no cov
  File "D:\Mac\Sites\project-reconnaissance\env\lib\site-packages\virtualenv\__main__.py", line 62, in run_with_catch
    run(args, options)
  File "D:\Mac\Sites\project-reconnaissance\env\lib\site-packages\virtualenv\__main__.py", line 16, in run      
    session = cli_run(args, options)
  File "D:\Mac\Sites\project-reconnaissance\env\lib\site-packages\virtualenv\run\__init__.py", line 28, in cli_run
    of_session.run()
  File "D:\Mac\Sites\project-reconnaissance\env\lib\site-packages\virtualenv\run\session.py", line 47, in run   
    self._seed()
  File "D:\Mac\Sites\project-reconnaissance\env\lib\site-packages\virtualenv\run\session.py", line 60, in _seed 
    self.seeder.run(self.creator)
  File "D:\Mac\Sites\project-reconnaissance\env\lib\site-packages\virtualenv\seed\embed\via_app_data\via_app_data.py", line 72, in run
    raise RuntimeError("\n".join(messages))
RuntimeError: failed to build image pip because:
Traceback (most recent call last):
  File "D:\Mac\Sites\project-reconnaissance\env\lib\site-packages\virtualenv\seed\embed\via_app_data\via_app_data.py", line 57, in _install
    installer.build_image()
  File "D:\Mac\Sites\project-reconnaissance\env\lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 54, in build_image
    zip_ref.extractall(str(self._image_dir))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\cool dude\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\Local\\pypa\\virtualenv\\wheel\\3.8\\image\\1\\CopyPipInstall\\pip-20.2.3-py2.py3-none-any\\pip\\_vendor\\urllib3\\packages\\ssl_match_hostname\\_implementation.py'
```

**Comment by gaborbernat** [comment]
Did you enable long paths for your windows? https://superuser.com/questions/1119883/windows-10-enable-ntfs-long-paths-policy-option-missing

That error sounds like you've just reached Windows long path limit.... Would you have Python installed under a shorter path you'd not have this issue but:

```
len("C:\\Users\\cool dude\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0")
91
```
leaves not much space for depth within your Python.
