### ISSUE TITLE
Module not found virtualenv.seed.via_app_data on WSL1

### ISSUE THREAD

**Issue by payoto** [pypa/virtualenv#1972]
**Issue**

     python -m virtualenv

fails with a module not found error:

     ModuleNotFoundError: No module named 'virtualenv.seed.via_app_data'

Linked to this issue:
https://github.com/pre-commit/pre-commit/issues/1632

Thanks for the help!

**Environment**

This is where it gets funky:
Provide at least:
* Windows subsystem for linux (WSL1)
*  Ubuntu 20.04.1 LTS
*  conda 4.8.5

- ``pip list`` of the host python where ``virtualenv`` is installed: [pip-list.txt](https://github.com/pypa/virtualenv/files/5351623/pip-list.txt)
- `conda list` : [conda-list.txt](https://github.com/pypa/virtualenv/files/5351622/conda-list.txt)

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console
137 setup logging to NOTSET [DEBUG report:43]
188 find interpreter for spec PythonSpec(path=/home/payoto/anaconda3/envs/xopt/bin/python) [INFO builtin:44]
188 proposed PythonInfo(spec=CPython3.8.5.final.0-64, exe=/home/payoto/anaconda3/envs/xopt/bin/python, platform=linux, version='3.8.5 | packaged by conda-forge | (default, Sep 24 2020, 16:55:52) \n[GCC 7.5.0]', encoding_fs_io=utf-8-utf-8) [INFO builtin:50]
189 accepted PythonInfo(spec=CPython3.8.5.final.0-64, exe=/home/payoto/anaconda3/envs/xopt/bin/python, platform=linux, version='3.8.5 | packaged by conda-forge | (default, Sep 24 2020, 16:55:52) \n[GCC 7.5.0]', encoding_fs_io=utf-8-utf-8) [DEBUG builtin:52]
193 filesystem is case-sensitive [DEBUG info:28]
Traceback (most recent call last):
  File "/home/payoto/anaconda3/envs/xopt/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/payoto/anaconda3/envs/xopt/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/payoto/.local/lib/python3.8/site-packages/virtualenv/__main__.py", line 78, in <module>
    run_with_catch()  # pragma: no cov
  File "/home/payoto/.local/lib/python3.8/site-packages/virtualenv/__main__.py", line 63, in run_with_catch
    run(args, options)
  File "/home/payoto/.local/lib/python3.8/site-packages/virtualenv/__main__.py", line 17, in run
    session = cli_run(args, options)
  File "/home/payoto/.local/lib/python3.8/site-packages/virtualenv/run/__init__.py", line 24, in cli_run
    session = session_via_cli(args, options)
  File "/home/payoto/.local/lib/python3.8/site-packages/virtualenv/run/__init__.py", line 32, in session_via_cli
    parser, elements = build_parser(args, options)
  File "/home/payoto/.local/lib/python3.8/site-packages/virtualenv/run/__init__.py", line 60, in build_parser
    SeederSelector(interpreter, parser),
  File "/home/payoto/.local/lib/python3.8/site-packages/virtualenv/run/plugin/seeders.py", line 8, in __init__
    possible = self.options("virtualenv.seed")
  File "/home/payoto/.local/lib/python3.8/site-packages/virtualenv/run/plugin/base.py", line 39, in options
    cls._OPTIONS = cls.entry_points_for(key)
  File "/home/payoto/.local/lib/python3.8/site-packages/virtualenv/run/plugin/base.py", line 18, in entry_points_for
    return OrderedDict((e.name, e.load()) for e in cls.entry_points().get(key, {}))
  File "/home/payoto/.local/lib/python3.8/site-packages/virtualenv/run/plugin/base.py", line 18, in <genexpr>
    return OrderedDict((e.name, e.load()) for e in cls.entry_points().get(key, {}))
  File "/home/payoto/anaconda3/envs/xopt/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/payoto/anaconda3/envs/xopt/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'virtualenv.seed.via_app_data'
```

**Comment by gaborbernat** [comment]
Can you post the output of the following command:

```
/home/payoto/anaconda3/envs/xopt/bin/python -c 'import sys; import os; print("\n".join(i for i in sys.path if os.path.exists(os.path.join(os.path.abspath(i), "virtualenv"))))'
```

**Comment by gaborbernat** [comment]
```
virtualenv                    20.0.27
virtualenv                20.0.20                  py38_1
```

You have virtualenv installed with both conda, and pip. And they are different versions. You should not combine them. Mixing two versions of the same package in the same python environment is never a good idea. Use virtual environments if you want differing versions of the same package.

**Comment by payoto** [comment]
Thanks for the help picking that out!
