### ISSUE TITLE
RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.9'

### ISSUE THREAD

**Issue by oncleben31** [pypa/virtualenv#1975]
**Issue**

Nox does not find Python 3.9.0, even though it is present via pyenv local.
Seems similar to #1643

**Environment**

Provide at least:
- OS: MacOS 10.15.7
- nox is installed with pipx (`package nox 2020.8.22, Python 3.8.5`)
- ``pip list`` of the host python where ``virtualenv`` is installed:

```console
/Users/benoit/.local/pipx/venvs/nox/bin/python -m pip list
Package     Version
----------- ---------
appdirs     1.4.4
argcomplete 1.12.1
colorlog    4.4.0
distlib     0.3.1
filelock    3.0.12
nox         2020.8.22
pip         20.2.3
py          1.9.0
setuptools  50.3.0
six         1.15.0
virtualenv  20.0.33
wheel       0.35.1
```

**Output of the virtual environment creation**

<details>
  <summary>Make sure to run the creation with `-vvv --with-traceback`:</summary>

```console
/Users/benoit/.local/pipx/venvs/nox/bin/python -m virtualenv -vvv --with-traceback /Users/benoit/Dev/freebox-api/.nox/tests-3-9  -p python3.9 

159 setup logging to NOTSET [DEBUG report:43]
173 find interpreter for spec PythonSpec(implementation=CPython, major=3, minor=9) [INFO builtin:44]
173 discover exe for PythonInfo(spec=CPython3.8.5.final.0-64, exe=/Users/benoit/.local/pipx/venvs/nox/bin/python, platform=darwin, version='3.8.5 (default, Jul 21 2020, 10:48:26) \n[Clang 11.0.3 (clang-1103.0.32.62)]', encoding_fs_io=utf-8-utf-8) in /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8 [DEBUG py_info:371]
174 filesystem is not case-sensitive [DEBUG info:28]
178 Attempting to acquire lock 4355621648 on /Users/benoit/Library/Application Support/virtualenv/py_info/1/f18a4039b52cba542189536e87fe9a35f2c3ec28f83d49c4da45938af89bff90.lock [DEBUG filelock:270]
178 Lock 4355621648 acquired on /Users/benoit/Library/Application Support/virtualenv/py_info/1/f18a4039b52cba542189536e87fe9a35f2c3ec28f83d49c4da45938af89bff90.lock [INFO filelock:274]
179 got python info of /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/bin/python3.8 from /Users/benoit/Library/Application Support/virtualenv/py_info/1/f18a4039b52cba542189536e87fe9a35f2c3ec28f83d49c4da45938af89bff90.json [DEBUG via_disk_folder:133]
179 Attempting to release lock 4355621648 on /Users/benoit/Library/Application Support/virtualenv/py_info/1/f18a4039b52cba542189536e87fe9a35f2c3ec28f83d49c4da45938af89bff90.lock [DEBUG filelock:315]
179 Lock 4355621648 released on /Users/benoit/Library/Application Support/virtualenv/py_info/1/f18a4039b52cba542189536e87fe9a35f2c3ec28f83d49c4da45938af89bff90.lock [INFO filelock:318]
180 Attempting to acquire lock 4355733632 on /Users/benoit/Library/Application Support/virtualenv/py_info/1/1ee38ef4a5a9feb55287fd749643f13d043cb0a7addaab2a9c224cbe137c0062.lock [DEBUG filelock:270]
180 Lock 4355733632 acquired on /Users/benoit/Library/Application Support/virtualenv/py_info/1/1ee38ef4a5a9feb55287fd749643f13d043cb0a7addaab2a9c224cbe137c0062.lock [INFO filelock:274]
180 got python info of /usr/local/opt/python@3.8/bin/python3.8 from /Users/benoit/Library/Application Support/virtualenv/py_info/1/1ee38ef4a5a9feb55287fd749643f13d043cb0a7addaab2a9c224cbe137c0062.json [DEBUG via_disk_folder:133]
181 Attempting to release lock 4355733632 on /Users/benoit/Library/Application Support/virtualenv/py_info/1/1ee38ef4a5a9feb55287fd749643f13d043cb0a7addaab2a9c224cbe137c0062.lock [DEBUG filelock:315]
181 Lock 4355733632 released on /Users/benoit/Library/Application Support/virtualenv/py_info/1/1ee38ef4a5a9feb55287fd749643f13d043cb0a7addaab2a9c224cbe137c0062.lock [INFO filelock:318]
181 proposed PythonInfo(spec=CPython3.8.5.final.0-64, system=/usr/local/opt/python@3.8/bin/python3.8, exe=/Users/benoit/.local/pipx/venvs/nox/bin/python, platform=darwin, version='3.8.5 (default, Jul 21 2020, 10:48:26) \n[Clang 11.0.3 (clang-1103.0.32.62)]', encoding_fs_io=utf-8-utf-8) [INFO builtin:50]
182 discover PATH[0]=/Users/benoit/.local/bin [DEBUG builtin:84]
182 discover PATH[1]=/Users/benoit/.pyenv/shims [DEBUG builtin:84]
182 Attempting to acquire lock 4355733152 on /Users/benoit/Library/Application Support/virtualenv/py_info/1/5025f316306ddc7e180d9f78e5768261849de0c6da731b9680bc0d546837f982.lock [DEBUG filelock:270]
192 Lock 4355733152 acquired on /Users/benoit/Library/Application Support/virtualenv/py_info/1/5025f316306ddc7e180d9f78e5768261849de0c6da731b9680bc0d546837f982.lock [INFO filelock:274]
193 get interpreter info via cmd: /Users/benoit/.pyenv/shims/python3.9 /Users/benoit/.local/pipx/venvs/nox/lib/python3.8/site-packages/virtualenv/discovery/py_info.py [DEBUG cached_py_info:87]
343 Attempting to release lock 4355733152 on /Users/benoit/Library/Application Support/virtualenv/py_info/1/5025f316306ddc7e180d9f78e5768261849de0c6da731b9680bc0d546837f982.lock [DEBUG filelock:315]
343 Lock 4355733152 released on /Users/benoit/Library/Application Support/virtualenv/py_info/1/5025f316306ddc7e180d9f78e5768261849de0c6da731b9680bc0d546837f982.lock [INFO filelock:318]
343 failed to query /Users/benoit/.pyenv/shims/python3.9 with code 127 err: "pyenv: python3.9: command not found\n\nThe `python3.9' command exists in these Python versions:\n  3.9.0\n\nNote: See 'pyenv help global' for tips on allowing both\n      python2 and python3 to be found.\n" [INFO cached_py_info:33]
344 Attempting to acquire lock 4355732720 on /Users/benoit/Library/Application Support/virtualenv/py_info/1/163aa86f7cc5f26cdfa4aa9059fa40a9e028acc33ecafdb5d9e4c9806d0169a0.lock [DEBUG filelock:270]
344 Lock 4355732720 acquired on /Users/benoit/Library/Application Support/virtualenv/py_info/1/163aa86f7cc5f26cdfa4aa9059fa40a9e028acc33ecafdb5d9e4c9806d0169a0.lock [INFO filelock:274]
345 got python info of /Users/benoit/.pyenv/shims/python3 from /Users/benoit/Library/Application Support/virtualenv/py_info/1/163aa86f7cc5f26cdfa4aa9059fa40a9e028acc33ecafdb5d9e4c9806d0169a0.json [DEBUG via_disk_folder:133]
346 Attempting to release lock 4355732720 on /Users/benoit/Library/Application Support/virtualenv/py_info/1/163aa86f7cc5f26cdfa4aa9059fa40a9e028acc33ecafdb5d9e4c9806d0169a0.lock [DEBUG filelock:315]
346 Lock 4355732720 released on /Users/benoit/Library/Application Support/virtualenv/py_info/1/163aa86f7cc5f26cdfa4aa9059fa40a9e028acc33ecafdb5d9e4c9806d0169a0.lock [INFO filelock:318]
347 Attempting to acquire lock 4355735120 on /Users/benoit/Library/Application Support/virtualenv/py_info/1/b7755b3f5a5eb16ca23779fb006f2f7455a2ce09513a0c848d50d30fa6d140b1.lock [DEBUG filelock:270]
347 Lock 4355735120 acquired on /Users/benoit/Library/Application Support/virtualenv/py_info/1/b7755b3f5a5eb16ca23779fb006f2f7455a2ce09513a0c848d50d30fa6d140b1.lock [INFO filelock:274]
356 got python info of /Users/benoit/.pyenv/versions/3.8.6/bin/python3 from /Users/benoit/Library/Application Support/virtualenv/py_info/1/b7755b3f5a5eb16ca23779fb006f2f7455a2ce09513a0c848d50d30fa6d140b1.json [DEBUG via_disk_folder:133]
357 Attempting to release lock 4355735120 on /Users/benoit/Library/Application Support/virtualenv/py_info/1/b7755b3f5a5eb16ca23779fb006f2f7455a2ce09513a0c848d50d30fa6d140b1.lock [DEBUG filelock:315]
358 Lock 4355735120 released on /Users/benoit/Library/Application Support/virtualenv/py_info/1/b7755b3f5a5eb16ca23779fb006f2f7455a2ce09513a0c848d50d30fa6d140b1.lock [INFO filelock:318]
358 proposed PathPythonInfo(spec=CPython3.8.6.final.0-64, system=/Users/benoit/.pyenv/versions/3.8.6/bin/python3, exe=/Users/benoit/.pyenv/shims/python3, platform=darwin, version='3.8.6 (default, Oct 10 2020, 13:33:34) \n[Clang 11.0.0 (clang-1100.0.33.16)]', encoding_fs_io=utf-8-utf-8) [INFO builtin:50]
359 Attempting to acquire lock 4355387696 on /Users/benoit/Library/Application Support/virtualenv/py_info/1/7d82cc0808cbfb3008a042b9d46a849e5c5f54f4a2a880c722bd297651ef4979.lock [DEBUG filelock:270]
359 Lock 4355387696 acquired on /Users/benoit/Library/Application Support/virtualenv/py_info/1/7d82cc0808cbfb3008a042b9d46a849e5c5f54f4a2a880c722bd297651ef4979.lock [INFO filelock:274]
359 got python info of /Users/benoit/.pyenv/shims/python from /Users/benoit/Library/Application Support/virtualenv/py_info/1/7d82cc0808cbfb3008a042b9d46a849e5c5f54f4a2a880c722bd297651ef4979.json [DEBUG via_disk_folder:133]
360 Attempting to release lock 4355387696 on /Users/benoit/Library/Application Support/virtualenv/py_info/1/7d82cc0808cbfb3008a042b9d46a849e5c5f54f4a2a880c722bd297651ef4979.lock [DEBUG filelock:315]
361 Lock 4355387696 released on /Users/benoit/Library/Application Support/virtualenv/py_info/1/7d82cc0808cbfb3008a042b9d46a849e5c5f54f4a2a880c722bd297651ef4979.lock [INFO filelock:318]
361 Attempting to acquire lock 4355388512 on /Users/benoit/Library/Application Support/virtualenv/py_info/1/0ab660759edb88b598aee0ad25f269fcab57a63b97308ab7f3ca51f98abdc6df.lock [DEBUG filelock:270]
361 Lock 4355388512 acquired on /Users/benoit/Library/Application Support/virtualenv/py_info/1/0ab660759edb88b598aee0ad25f269fcab57a63b97308ab7f3ca51f98abdc6df.lock [INFO filelock:274]
362 got python info of /Users/benoit/.pyenv/versions/3.8.6/bin/python from /Users/benoit/Library/Application Support/virtualenv/py_info/1/0ab660759edb88b598aee0ad25f269fcab57a63b97308ab7f3ca51f98abdc6df.json [DEBUG via_disk_folder:133]
363 Attempting to release lock 4355388512 on /Users/benoit/Library/Application Support/virtualenv/py_info/1/0ab660759edb88b598aee0ad25f269fcab57a63b97308ab7f3ca51f98abdc6df.lock [DEBUG filelock:315]
363 Lock 4355388512 released on /Users/benoit/Library/Application Support/virtualenv/py_info/1/0ab660759edb88b598aee0ad25f269fcab57a63b97308ab7f3ca51f98abdc6df.lock [INFO filelock:318]
363 proposed PathPythonInfo(spec=CPython3.8.6.final.0-64, system=/Users/benoit/.pyenv/versions/3.8.6/bin/python, exe=/Users/benoit/.pyenv/shims/python, platform=darwin, version='3.8.6 (default, Oct 10 2020, 13:33:34) \n[Clang 11.0.0 (clang-1100.0.33.16)]', encoding_fs_io=utf-8-utf-8) [INFO builtin:50]
363 discover PATH[2]=/usr/local/bin [DEBUG builtin:84]
363 Attempting to acquire lock 4355389328 on /Users/benoit/Library/Application Support/virtualenv/py_info/1/aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49.lock [DEBUG filelock:270]
364 Lock 4355389328 acquired on /Users/benoit/Library/Application Support/virtualenv/py_info/1/aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49.lock [INFO filelock:274]
364 got python info of /usr/local/bin/python3 from /Users/benoit/Library/Application Support/virtualenv/py_info/1/aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49.json [DEBUG via_disk_folder:133]
365 Attempting to release lock 4355389328 on /Users/benoit/Library/Application Support/virtualenv/py_info/1/aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49.lock [DEBUG filelock:315]
365 Lock 4355389328 released on /Users/benoit/Library/Application Support/virtualenv/py_info/1/aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49.lock [INFO filelock:318]
365 discover PATH[3]=/usr/bin [DEBUG builtin:84]
366 Attempting to acquire lock 4355390144 on /Users/benoit/Library/Application Support/virtualenv/py_info/1/31f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6.lock [DEBUG filelock:270]
366 Lock 4355390144 acquired on /Users/benoit/Library/Application Support/virtualenv/py_info/1/31f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6.lock [INFO filelock:274]
366 got python info of /usr/bin/python3 from /Users/benoit/Library/Application Support/virtualenv/py_info/1/31f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6.json [DEBUG via_disk_folder:133]
367 Attempting to release lock 4355390144 on /Users/benoit/Library/Application Support/virtualenv/py_info/1/31f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6.lock [DEBUG filelock:315]
367 Lock 4355390144 released on /Users/benoit/Library/Application Support/virtualenv/py_info/1/31f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6.lock [INFO filelock:318]
368 Attempting to acquire lock 4355390960 on /Users/benoit/Library/Application Support/virtualenv/py_info/1/5edc29c2ed010d6458d71a83433b383a96a8cbd3efe8531bc90c4b8a5b8bcec9.lock [DEBUG filelock:270]
377 Lock 4355390960 acquired on /Users/benoit/Library/Application Support/virtualenv/py_info/1/5edc29c2ed010d6458d71a83433b383a96a8cbd3efe8531bc90c4b8a5b8bcec9.lock [INFO filelock:274]
379 got python info of /Library/Developer/CommandLineTools/usr/bin/python3 from /Users/benoit/Library/Application Support/virtualenv/py_info/1/5edc29c2ed010d6458d71a83433b383a96a8cbd3efe8531bc90c4b8a5b8bcec9.json [DEBUG via_disk_folder:133]
382 Attempting to release lock 4355390960 on /Users/benoit/Library/Application Support/virtualenv/py_info/1/5edc29c2ed010d6458d71a83433b383a96a8cbd3efe8531bc90c4b8a5b8bcec9.lock [DEBUG filelock:315]
382 Lock 4355390960 released on /Users/benoit/Library/Application Support/virtualenv/py_info/1/5edc29c2ed010d6458d71a83433b383a96a8cbd3efe8531bc90c4b8a5b8bcec9.lock [INFO filelock:318]
382 proposed PathPythonInfo(spec=CPython3.7.3.final.0-64, system=/Library/Developer/CommandLineTools/usr/bin/python3, exe=/usr/bin/python3, platform=darwin, version='3.7.3 (default, Nov 15 2019, 04:04:52) \n[Clang 11.0.0 (clang-1100.0.33.16)]', encoding_fs_io=utf-8-UTF-8) [INFO builtin:50]
383 Attempting to acquire lock 4355732960 on /Users/benoit/Library/Application Support/virtualenv/py_info/1/767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90.lock [DEBUG filelock:270]
383 Lock 4355732960 acquired on /Users/benoit/Library/Application Support/virtualenv/py_info/1/767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90.lock [INFO filelock:274]
396 got python info of /usr/bin/python from /Users/benoit/Library/Application Support/virtualenv/py_info/1/767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90.json [DEBUG via_disk_folder:133]
398 Attempting to release lock 4355732960 on /Users/benoit/Library/Application Support/virtualenv/py_info/1/767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90.lock [DEBUG filelock:315]
398 Lock 4355732960 released on /Users/benoit/Library/Application Support/virtualenv/py_info/1/767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90.lock [INFO filelock:318]
399 Attempting to acquire lock 4355733824 on /Users/benoit/Library/Application Support/virtualenv/py_info/1/545e036c4b32438aced1f6b3c8d38ca151d9c36189e05839cb0aa568fda70ddd.lock [DEBUG filelock:270]
399 Lock 4355733824 acquired on /Users/benoit/Library/Application Support/virtualenv/py_info/1/545e036c4b32438aced1f6b3c8d38ca151d9c36189e05839cb0aa568fda70ddd.lock [INFO filelock:274]
400 got python info of /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python from /Users/benoit/Library/Application Support/virtualenv/py_info/1/545e036c4b32438aced1f6b3c8d38ca151d9c36189e05839cb0aa568fda70ddd.json [DEBUG via_disk_folder:133]
415 Attempting to release lock 4355733824 on /Users/benoit/Library/Application Support/virtualenv/py_info/1/545e036c4b32438aced1f6b3c8d38ca151d9c36189e05839cb0aa568fda70ddd.lock [DEBUG filelock:315]
415 Lock 4355733824 released on /Users/benoit/Library/Application Support/virtualenv/py_info/1/545e036c4b32438aced1f6b3c8d38ca151d9c36189e05839cb0aa568fda70ddd.lock [INFO filelock:318]
415 proposed PathPythonInfo(spec=CPython2.7.16.final.0-64, system=/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python, exe=/usr/bin/python, platform=darwin, version='2.7.16 (default, Jun  5 2020, 22:59:21) \n[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-', encoding_fs_io=utf-8-None) [INFO builtin:50]
415 discover PATH[4]=/bin [DEBUG builtin:84]
415 discover PATH[5]=/usr/sbin [DEBUG builtin:84]
415 discover PATH[6]=/sbin [DEBUG builtin:84]
416 discover PATH[7]=/Users/benoit/.local/bin [DEBUG builtin:84]
416 discover PATH[8]=/Users/benoit/.pyenv/shims [DEBUG builtin:84]
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/benoit/.local/pipx/venvs/nox/lib/python3.8/site-packages/virtualenv/__main__.py", line 77, in <module>
    run_with_catch()  # pragma: no cov
  File "/Users/benoit/.local/pipx/venvs/nox/lib/python3.8/site-packages/virtualenv/__main__.py", line 62, in run_with_catch
    run(args, options)
  File "/Users/benoit/.local/pipx/venvs/nox/lib/python3.8/site-packages/virtualenv/__main__.py", line 16, in run
    session = cli_run(args, options)
  File "/Users/benoit/.local/pipx/venvs/nox/lib/python3.8/site-packages/virtualenv/run/__init__.py", line 26, in cli_run
    of_session = session_via_cli(args, options, setup_logging)
  File "/Users/benoit/.local/pipx/venvs/nox/lib/python3.8/site-packages/virtualenv/run/__init__.py", line 42, in session_via_cli
    parser, elements = build_parser(args, options, setup_logging)
  File "/Users/benoit/.local/pipx/venvs/nox/lib/python3.8/site-packages/virtualenv/run/__init__.py", line 66, in build_parser
    raise RuntimeError("failed to find interpreter for {}".format(discover))
RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.9'
```
</details>

**Comment by gaborbernat** [comment]
Can you please post the output of running this script: https://github.com/pypa/virtualenv/blob/main/src/virtualenv/discovery/py_info.py, against the python3.9 in question?

**Comment by oncleben31** [comment]
OK my bad. I have forgotten to activate the Python 3.9 with the command:
`$ pyenv local 3.9.0`

Sorry.
