### ISSUE TITLE
Virtualenv Tries to Use Windows Redirector Scripts with Mingw-w64

### ISSUE THREAD

**Issue by danyeaw** [pypa/virtualenv#1987]
**Issue**

When trying to run `virtualenv .venv` with mingw-w64 Python, I get the following error:
`FileNotFoundError: [Errno 2] No such file or directory: 'C:/tools/msys64/mingw64/lib/python3.8/venv/scripts/nt/python.exe'`

Describe what's the expected behaviour and what you're observing.

I would expect that virtualenv creation is successful. It looks like virtualenv is trying to use windows re-director scripts, instead I think it should only be using venv scripts that are available for the mingw-w64 version of Python.

**Environment**

Provide at least:
- OS: Windows 10
- Python: platform=win32, version='3.8.6 (default, Oct  1 2020, 13:01:33)  [GCC 10.2.0 64 bit (AMD64)]', encoding_fs_io=utf-8-utf-8) in C:/tools/msys64/mingw64
- ``pip list`` of the host python where ``virtualenv`` is installed:
```console
Package    Version
---------- -------
appdirs    1.4.4
distlib    0.3.1
filelock   3.0.12
pip        20.2.1
setuptools 49.2.1
six        1.15.0
virtualenv 20.0.35
```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console
$ virtualenv -vvv --with-traceback .venv3
223 setup logging to NOTSET [DEBUG report:43]
231 find interpreter for spec PythonSpec(path=c:/tools/msys64/home/dyeaw/gaphor/.venv2/bin/python.exe) [INFO builtin:44]

231 discover exe for PythonInfo(spec=CPython3.8.6.final.0-64, exe=C:/tools/msys64/home/dyeaw/gaphor/.venv2/bin/python.exe, platform=win32, version='3.8.6 (default, Oct  1 2020, 13:01:33)  [GCC 10.2.0 64 bit (AMD64)]', encoding_fs_io=utf-8-utf-8) in C:/tools/msys64/mingw64 [DEBUG py_info:371]
231 filesystem is not case-sensitive [DEBUG info:28]
239 Attempting to acquire lock 1437261912384 on C:/Users/dyeaw/AppData/Local/pypa/virtualenv/py_info/1/6192f06487ca60923166b053a164ccf81cc8e95757c98002a1e2629727b26e79.lock [DEBUG filelock:270]
239 Lock 1437261912384 acquired on C:/Users/dyeaw/AppData/Local/pypa/virtualenv/py_info/1/6192f06487ca60923166b053a164ccf81cc8e95757c98002a1e2629727b26e79.lock [INFO filelock:274]
239 got python info of C:/tools/msys64/mingw64/bin/python3.8.exe from C:/Users/dyeaw/AppData/Local/pypa/virtualenv/py_info/1/6192f06487ca60923166b053a164ccf81cc8e95757c98002a1e2629727b26e79.json [DEBUG via_disk_folder:133]
239 Attempting to release lock 1437261912384 on C:/Users/dyeaw/AppData/Local/pypa/virtualenv/py_info/1/6192f06487ca60923166b053a164ccf81cc8e95757c98002a1e2629727b26e79.lock [DEBUG filelock:315]
247 Lock 1437261912384 released on C:/Users/dyeaw/AppData/Local/pypa/virtualenv/py_info/1/6192f06487ca60923166b053a164ccf81cc8e95757c98002a1e2629727b26e79.lock [INFO filelock:318]
247 proposed PythonInfo(spec=CPython3.8.6.final.0-64, system=C:/tools/msys64/mingw64/bin/python3.8.exe, exe=C:/tools/msys64/home/dyeaw/gaphor/.venv2/bin/python.exe, platform=win32, version='3.8.6 (default, Oct  1 2020, 13:01:33)  [GCC 10.2.0 64 bit (AMD64)]', encoding_fs_io=utf-8-cp1252) [INFO builtin:50]
247 accepted PythonInfo(spec=CPython3.8.6.final.0-64, system=C:/tools/msys64/mingw64/bin/python3.8.exe, exe=C:/tools/msys64/home/dyeaw/gaphor/.venv2/bin/python.exe, platform=win32, version='3.8.6 (default, Oct  1 2020, 13:01:33)  [GCC 10.2.0 64 bit (AMD64)]', encoding_fs_io=utf-8-cp1252) [DEBUG builtin:52]
247 symlink on filesystem does not work [DEBUG info:47]
311 create virtual environment via CPython3Windows(dest=C:/tools/msys64/home/dyeaw/gaphor/.venv3, clear=False, global=False) [INFO session:52]
311 write C:/tools/msys64/home/dyeaw/gaphor/.venv3/pyvenv.cfg [DEBUG pyenv_cfg:34]
311     home = C:/tools/msys64/mingw64 [DEBUG pyenv_cfg:38]
311     implementation = CPython [DEBUG pyenv_cfg:38]
311     version_info = 3.8.6.final.0 [DEBUG pyenv_cfg:38]
311     virtualenv = 20.0.35 [DEBUG pyenv_cfg:38]
311     include-system-site-packages = false [DEBUG pyenv_cfg:38]
311     base-prefix = C:/tools/msys64/mingw64 [DEBUG pyenv_cfg:38]
311     base-exec-prefix = C:/tools/msys64/mingw64 [DEBUG pyenv_cfg:38]
311     base-executable = C:/tools/msys64/mingw64/bin/python3.8.exe [DEBUG pyenv_cfg:38]
311 copy C:/tools/msys64/mingw64/lib/python3.8/venv/scripts/nt/python.exe to C:/tools/msys64/home/dyeaw/gaphor/.venv3/bin/python.exe [DEBUG _sync:52]
Traceback (most recent call last):
  File "C:/tools/msys64/mingw64/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:/tools/msys64/mingw64/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:/tools/msys64/home/dyeaw/gaphor/.venv2/bin/virtualenv.exe/__main__.py", line 7, in <module>
  File "C:/tools/msys64/home/dyeaw/gaphor/.venv2/lib/python3.8/site-packages/virtualenv/__main__.py", line 62, in run_with_catch
    run(args, options)
  File "C:/tools/msys64/home/dyeaw/gaphor/.venv2/lib/python3.8/site-packages/virtualenv/__main__.py", line 16, in run
    session = cli_run(args, options)
  File "C:/tools/msys64/home/dyeaw/gaphor/.venv2/lib/python3.8/site-packages/virtualenv/run/__init__.py", line 28, in cli_run
    of_session.run()
  File "C:/tools/msys64/home/dyeaw/gaphor/.venv2/lib/python3.8/site-packages/virtualenv/run/session.py", line 46, in run

    self._create()
  File "C:/tools/msys64/home/dyeaw/gaphor/.venv2/lib/python3.8/site-packages/virtualenv/run/session.py", line 53, in _create
    self.creator.run()
  File "C:/tools/msys64/home/dyeaw/gaphor/.venv2/lib/python3.8/site-packages/virtualenv/create/creator.py", line 161, in run
    self.create()
  File "C:/tools/msys64/home/dyeaw/gaphor/.venv2/lib/python3.8/site-packages/virtualenv/create/via_global_ref/builtin/via_global_self_do.py", line 97, in create
    src.run(self, self.symlinks)
  File "C:/tools/msys64/home/dyeaw/gaphor/.venv2/lib/python3.8/site-packages/virtualenv/create/via_global_ref/builtin/ref.py", line 157, in run
    method(self.src, dest)
  File "C:/tools/msys64/home/dyeaw/gaphor/.venv2/lib/python3.8/site-packages/virtualenv/util/path/_sync.py", line 53, in copy
    method(norm(src), norm(dest))
  File "C:/tools/msys64/mingw64/lib/python3.8/shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:/tools/msys64/mingw64/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/tools/msys64/mingw64/lib/python3.8/venv/scripts/nt/python.exe'
```

**Comment by gaborbernat** [comment]
Per https://github.com/msys2/MINGW-packages/pull/7134 this feels a MinGW bug, so I'll close.
