### ISSUE TITLE
Unexpected AttributeError from activate_this.py

### ISSUE THREAD

**Issue by arifer612** [pypa/virtualenv#1993]
**Issue**

Activating a virtual environment while still in another threw an AttributeError. The error message is `AttributeError: 'str' object has no attribute 'decode'`. The line in the code which corresponds to this is:
https://github.com/pypa/virtualenv/blob/9569493453a39d63064ed7c20653987ba15c99e5/src/virtualenv/activation/python/activate_this.py#L28

Describe what's the expected behaviour and what you're observing.

Expected behaviour:
    - No AttributeError messages when using `exec(open(this_file).read(), {'__file__': this_file})` in any valid situation.

Observed:
    - AttributeError messages when executing the activation line while in another virtual environment.
    - No AttributeError messages when executing the activation line while using the system python environment.

**Environment**

Provide at least:
- OS: Elementary OS Hera
- ``pip list`` of the host python where ``virtualenv`` is installed:

  ```console
    alabaster                     0.7.12
    appdirs                       1.4.4
    asn1crypto                    0.24.0
    Babel                         2.8.0
    beautifulsoup4                4.9.3
    bleach                        3.2.1
    Brlapi                        0.6.6
    bs4                           0.0.1
    certifi                       2020.6.20
    cffi                          1.14.3
    chardet                       3.0.4
    colorama                      0.4.3
    command-not-found             0.3
    cryptography                  3.1.1
    cssselect                     1.1.0
    defer                         1.0.6
    devscripts                    2.17.12ubuntu1.1
    distlib                       0.3.1
    distro-info                   0.18ubuntu0.18.04.1
    docutils                      0.16
    epc                           0.0.5
    evdev                         0.7.0
    fake-useragent                0.1.11
    filelock                      3.0.12
    gpg                           1.10.0
    homebase                      1.0.1
    html5lib                      0.999999999
    httplib2                      0.9.2
    idna                          2.10
    imagesize                     1.2.0
    importlib-metadata            2.0.0
    importlib-resources           3.0.0
    importmagic                   0.1.7
    jeepney                       0.4.3
    Jinja2                        2.11.2
    keyring                       21.4.0
    keyrings.alt                  4.0.0
    language-selector             0.1
    lark-parser                   0.9.0
    louis                         3.5.0
    lxml                          4.5.2
    Mako                          1.1.3
    Markdown                      3.3.1
    MarkupSafe                    1.1.1
    netifaces                     0.10.4
    numpy                         1.19.2
    olefile                       0.45.1
    onboard                       1.4.1
    packaging                     20.4
    pandas                        1.1.3
    parse                         1.16.0
    pdoc3                         0.9.1
    pexpect                       4.2.1
    Pillow                        5.1.0
    pip                           20.2.4
    pkginfo                       1.5.0.1
    plyer                         1.4.3
    prettyetc                     0.4.0
    pycairo                       1.16.2
    pycparser                     2.20
    pycrypto                      2.6.1
    pycurl                        7.43.0.1
    pyee                          7.0.2
    Pygments                      2.7.1
    pygobject                     3.26.1
    pyparsing                     2.4.7
    pyperclip                     1.8.0
    pyppeteer                     0.2.2
    pyquery                       1.4.1
    PySimpleGUI                   4.26.0
    pystray                       0.16.0
    python-apt                    1.6.5-ubuntu0.3-elementary16-ubuntu5.1.5.1
    python-dateutil               2.8.1
    python-debian                 0.1.32
    python-magic                  0.4.16
    python-xlib                   0.27
    pytz                          2020.1
    pyxdg                         0.25
    PyYAML                        5.3.1
    readme-renderer               26.0
    reportlab                     3.4.0
    requests                      2.24.0
    requests-html                 0.10.0
    requests-toolbelt             0.9.1
    requests-unixsocket           0.1.5
    rfc3986                       1.4.0
    ruamel.yaml                   0.16.10
    ruamel.yaml.clib              0.2.0
    SecretStorage                 3.1.2
    setuptools                    50.3.0
    sexpdata                      0.0.3
    shiboken2                     5.15.0
    six                           1.15.0
    snowballstemmer               2.0.0
    soupsieve                     2.0.1
    sphinxcontrib-applehelp       1.0.2
    sphinxcontrib-devhelp         1.0.2
    sphinxcontrib-htmlhelp        1.0.3
    sphinxcontrib-jsmath          1.0.1
    sphinxcontrib-qthelp          1.0.3
    sphinxcontrib-serializinghtml 1.1.4
    ssh-import-id                 5.7
    tqdm                          4.50.2
    twine                         3.2.0
    ubuntu-drivers-common         0.0.0
    ufw                           0.36
    unidiff                       0.5.4
    urllib3                       1.25.10
    virtualenv                    20.0.35
    w3lib                         1.22.0
    webencodings                  0.5.1
    websockets                    8.1
    wheel                         0.35.1
    xkit                          0.0.0
    youtube-dl                    2020.9.20
    zipp                          3.3.0
  ```

**Output of the virtual environment activation**

Make sure to run the creation with `-vvv --with-traceback`: _N.A._

```console
    >>> exec(open('venv/bin/activate_this.py').read(), {'__file__': 'venv/bin/activate_this.py'})
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "<string>", line 26, in <module>
    AttributeError: 'str' object has no attribute 'decode'
```

**Suggestion**

The cheapest way I got out of this was to include an exception handler:
```console
    try:
        site.addsitedir(path.decode("utf-8") if "__DECODE_PATH__" else path)
    except AttributeError:
        site.addsitedir(path)
```

**Side comment**

There is also a very minor typo in the AssertionError message here:
https://github.com/pypa/virtualenv/blob/9569493453a39d63064ed7c20653987ba15c99e5/src/virtualenv/activation/python/activate_this.py#L15

It has one extra paranthesis and should be `"You must use exec(open(this_file).read(), {'__file__': this_file})"` instead.

**Comment by gaborbernat** [comment]
Can you please provide the python version information? Both for the activation (host) python, and the virtual environment python.

**Comment by arifer612** [comment]
They are both Python 3.6.9

**Comment by arifer612** [comment]
This issue no longer appears in virtualenv 20.4.3 for Python 3.6.9

**Comment by Anquuni** [comment]
I have the same issue for Python 3.7.3. With the suggested solution by @arifer612 the problem is solved.

**Comment by stryker2k2** [comment]
The suggestion by @arifer612 solved my issue.

Python 3.10.12 with WSGI on Apache2 with _activate_this.py_ dropped into 'venv/bin' folder.
