### ISSUE TITLE
An incompatible version is intalled for Python 3.5.3

### ISSUE THREAD

**Issue by dobairoland** [pypa/virtualenv#2005]
**Issue**

Virtualenv with Python 3.6 features are installed for Python 3.5.2.

I would expect from ``python -m pip install virtualenv`` to install a compatible `virtualenv`. My workaround is: ``python -m pip install "virtualenv<20"``

**Environment**

Provide at least:
- OS: Ubuntu 16.04 LTS
- ``python -m pip list``:

  ```console
appdirs (1.4.4)
apturl (0.5.2)
beautifulsoup4 (4.4.1)
blinker (1.3)
Brlapi (0.6.4)
chardet (2.3.0)
checkbox-support (0.22)
command-not-found (0.3)
cryptography (1.2.3)
defer (1.0.6)
distlib (0.3.1)
feedparser (5.1.3)
filelock (3.0.12)
guacamole (0.9.2)
html5lib (0.999)
httplib2 (0.9.1)
idna (2.0)
importlib-metadata (2.0.0)
importlib-resources (3.3.0)
Jinja2 (2.8)
language-selector (0.1)
louis (2.6.4)
lxml (3.5.0)
Mako (1.0.3)
MarkupSafe (0.23)
oauthlib (1.0.3)
onboard (1.2.0)
padme (1.1.1)
pexpect (4.0.1)
Pillow (3.1.2)
pip (8.1.1)
plainbox (0.25)
ptyprocess (0.5)
pyasn1 (0.1.9)
pycups (1.9.73)
pycurl (7.43.0)
pygobject (3.20.0)
PyJWT (1.3.0)
pyparsing (2.0.3)
python-apt (1.1.0b1+ubuntu0.16.4.9)
python-debian (0.1.27)
python-systemd (231)
pyxdg (0.25)
reportlab (3.3.0)
requests (2.9.1)
sessioninstaller (0.0.0)
setuptools (20.7.0)
six (1.15.0)
system-service (0.3)
ubuntu-drivers-common (0.0.0)
ufw (0.35)
unattended-upgrades (0.1)
unity-scope-calculator (0.1)
unity-scope-chromiumbookmarks (0.1)
unity-scope-colourlovers (0.1)
unity-scope-devhelp (0.1)
unity-scope-firefoxbookmarks (0.1)
unity-scope-gdrive (0.7)
unity-scope-manpages (0.1)
unity-scope-openclipart (0.1)
unity-scope-texdoc (0.1)
unity-scope-tomboy (0.1)
unity-scope-virtualbox (0.1)
unity-scope-yelp (0.1)
unity-scope-zotero (0.1)
urllib3 (1.13.1)
usb-creator (0.3.0)
virtualenv (16.7.10)
wheel (0.29.0)
xdiagnose (3.8.4.1)
xkit (0.0.0)
XlsxWriter (0.7.3)
zipp (3.4.0)
You are using pip version 8.1.1, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
  ```
Notice that ``python -m virtualenv --version`` shows 20.1.0 and ``python -m pip list`` a different version.

**Output of the virtual environment creation**

```console
124 setup logging to NOTSET [DEBUG report:43]
151 find interpreter for spec PythonSpec(path=/usr/bin/python) [INFO builtin:51]
152 proposed PythonInfo(spec=CPython3.5.2.final.0-64, exe=/usr/bin/python, platform=linux, version='3.5.2 (default, Oct  7 2020, 17:19:02) \n[GCC 5.4.0 20160609]', encoding_fs_io=utf-8-UTF-8) [INFO builtin:57]
152 accepted PythonInfo(spec=CPython3.5.2.final.0-64, exe=/usr/bin/python, platform=linux, version='3.5.2 (default, Oct  7 2020, 17:19:02) \n[GCC 5.4.0 20160609]', encoding_fs_io=utf-8-UTF-8) [DEBUG builtin:59]
154 filesystem is case-sensitive [DEBUG info:28]
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/roland/.local/lib/python3.5/site-packages/virtualenv/__main__.py", line 77, in <module>
    run_with_catch()  # pragma: no cov
  File "/home/roland/.local/lib/python3.5/site-packages/virtualenv/__main__.py", line 62, in run_with_catch
    run(args, options)
  File "/home/roland/.local/lib/python3.5/site-packages/virtualenv/__main__.py", line 16, in run
    session = cli_run(args, options)
  File "/home/roland/.local/lib/python3.5/site-packages/virtualenv/run/__init__.py", line 26, in cli_run
    of_session = session_via_cli(args, options, setup_logging)
  File "/home/roland/.local/lib/python3.5/site-packages/virtualenv/run/__init__.py", line 42, in session_via_cli
    parser, elements = build_parser(args, options, setup_logging)
  File "/home/roland/.local/lib/python3.5/site-packages/virtualenv/run/__init__.py", line 70, in build_parser
    ActivationSelector(interpreter, parser),
  File "/home/roland/.local/lib/python3.5/site-packages/virtualenv/run/plugin/activators.py", line 13, in __init__
    (k, v) for k, v in self.options("virtualenv.activate").items() if v.supports(interpreter)
  File "/home/roland/.local/lib/python3.5/site-packages/virtualenv/run/plugin/base.py", line 39, in options
    cls._OPTIONS = cls.entry_points_for(key)
  File "/home/roland/.local/lib/python3.5/site-packages/virtualenv/run/plugin/base.py", line 18, in entry_points_for
    return OrderedDict((e.name, e.load()) for e in cls.entry_points().get(key, {}))
  File "/home/roland/.local/lib/python3.5/site-packages/virtualenv/run/plugin/base.py", line 18, in <genexpr>
    return OrderedDict((e.name, e.load()) for e in cls.entry_points().get(key, {}))
  File "/home/roland/.local/lib/python3.5/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/roland/.local/lib/python3.5/site-packages/virtualenv/activation/__init__.py", line 3, in <module>
    from .bash import BashActivator
  File "/home/roland/.local/lib/python3.5/site-packages/virtualenv/activation/bash/__init__.py", line 5, in <module>
    from ..via_template import ViaTemplateActivator
  File "/home/roland/.local/lib/python3.5/site-packages/virtualenv/activation/via_template.py", line 16, in <module>
    from importlib_resources import read_binary
  File "/home/roland/.local/lib/python3.5/site-packages/importlib_resources/__init__.py", line 31, in <module>
    from importlib_resources._py3 import (
  File "/home/roland/.local/lib/python3.5/site-packages/importlib_resources/_py3.py", line 20, in <module>
    Resource = Union[str, os.PathLike]
AttributeError: module 'os' has no attribute 'PathLike'
```
https://docs.python.org/3/library/os.html#os.PathLike is a feature from Python 3.6.

**Comment by gaborbernat** [comment]
Did you consider addressing the warning at the end of your command?

```
You are using pip version 8.1.1, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

You need a pip 19+ for pip to do the job correctly. This is a pip issue, not virtualenv.

**Comment by dobairoland** [comment]
@gaborbernat 

1. `python3-pip` is interfering with the update so I've uninstalled it. I made sure there is no `pip` or `virtualenv` installed.

2. I've installed `pip-20.2.4` manually by `python get-pip.py`.

3. `pip==20.2.4` still installs `virtualenv==20.1.0` for Python 3.5.

**Comment by gaborbernat** [comment]
> 3\. `pip==20.2.4` still installs `virtualenv==20.1.0` for Python 3.5.

That's expected. Why would it not install that version? We support it.

**Comment by dobairoland** [comment]
Ok, thank you. It works now. I'm sorry for the false alarm. I was playing with this for hours.
