### ISSUE TITLE
Unable to execute console_scripts inside virtual environment

### ISSUE THREAD

**Issue by m8mble** [pypa/virtualenv#2039]
**Issue**

I have a python package with the following (pretty much standard) `setup.py`:

```python3
from setuptools import setup, find_packages

setup(
    name='safe-move',
    packages=find_packages(exclude=['config', 'docs', 'tests']),
    python_requires='>=3.7',
    entry_points={
        'console_scripts': [
            'smv=src.cli:main',
        ],
    },
)
```

After `python setup.py install` in a fresh virtualenv, I get the following errors when attempting to launch the `smv` console script:
```console
$ smv -h
Traceback (most recent call last):
  File "/home/m8mble/work/scripts/safe-move/venv/bin/smv", line 33, in <module>
    sys.exit(load_entry_point('safe-move==0.1.0', 'console_scripts', 'smv')())
  File "/home/m8mble/work/scripts/safe-move/venv/bin/smv", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'src'
```

Before upgrading to python 3.9, this worked without errors (and printend the usual help dialog from `argparse`).

In all honesty, I'm not really certain this is an issue of `virtualenv`. But I'm unable to identify the root-cause of this problem. In case this a consequence of some issue of another package, feel free to give me a simple hint. I'd be happy to take this somewhere else.

**Environment**

Running on ArchLinux with python3.9.0. Packages installed on host (outside any virtualenv):
```console
$ pip list
pip list
Package          Version
---------------- -----------
appdirs          1.4.4
argcomplete      1.12.2
asn1crypto       1.4.0
brz-etckeeper    0.0.0
btrfsutil        5.9
CacheControl     0.12.6
certifi          2020.6.20
cffi             1.14.4
chardet          3.0.4
click            7.1.2
colorama         0.4.4
contextlib2      0.6.0.post1
cryptography     3.3.1
distlib          0.3.1
distro           1.5.0
docopt           0.6.2
feedparser       5.2.1
filelock         3.0.12
greenlet         0.4.17
html5lib         1.1
idna             2.10
iotop            0.6
isc              2.0
lockfile         0.12.2
meld             3.20.2
msgpack          1.0.0
mutagen          1.45.1
ordered-set      4.0.2
packaging        20.7
pep517           0.9.1
pip              20.3.1
pipenv           2020.11.15
pipx             0.15.6.0
ply              3.11
progress         1.5
pwquality        1.4.4
pycairo          1.20.0
pycparser        2.20
PyGObject        3.38.0
pynvim           0.4.2
pyOpenSSL        20.0.0
pyparsing        2.4.7
python-dateutil  2.8.1
pytoml           0.1.21
quodlibet        4.3.0
requests         2.25.0
resolvelib       0.5.3
retrying         1.3.3
senf             1.5.0
setuptools       50.3.2
six              1.15.0
team             1.0
toml             0.10.2
urllib3          1.25.10
userpath         1.4.1
virtualenv       20.2.2
virtualenv-clone 0.5.4
webencodings     0.5.1
WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.
```

The following packages are present in my new virtualenv:
```console
$ pip list
Package    Version
---------- -------
pip        20.3.3
safe-move  0.1.0
setuptools 51.0.0
wheel      0.36.1
  ```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console
$ virtualenv venv -vvv --with-traceback
42 setup logging to NOTSET [DEBUG report:43]
53 find interpreter for spec PythonSpec(path=/usr/bin/python) [INFO builtin:52]
53 proposed PythonInfo(spec=CPython3.9.0.final.0-64, exe=/usr/bin/python, platform=linux, version='3.9.0 (default, Oct  7 2020, 23:09:01) \n[GCC 10.2.0]', encoding_fs_io=utf-8-utf-8) [INFO builtin:58]
53 accepted PythonInfo(spec=CPython3.9.0.final.0-64, exe=/usr/bin/python, platform=linux, version='3.9.0 (default, Oct  7 2020, 23:09:01) \n[GCC 10.2.0]', encoding_fs_io=utf-8-utf-8) [DEBUG builtin:60]
54 filesystem is case-sensitive [DEBUG info:28]
79 create virtual environment via CPython3Posix(dest=/home/m8mble/work/scripts/safe-move/venv, clear=False, no_vcs_ignore=False, global=False) [INFO session:52]
79 create folder /home/m8mble/work/scripts/safe-move/venv/bin [DEBUG _sync:25]
80 create folder /home/m8mble/work/scripts/safe-move/venv/lib/python3.9/site-packages [DEBUG _sync:25]
80 write /home/m8mble/work/scripts/safe-move/venv/pyvenv.cfg [DEBUG pyenv_cfg:34]
80      home = /usr [DEBUG pyenv_cfg:38]
80      implementation = CPython [DEBUG pyenv_cfg:38]
80      version_info = 3.9.0.final.0 [DEBUG pyenv_cfg:38]
80      virtualenv = 20.2.2 [DEBUG pyenv_cfg:38]
80      include-system-site-packages = false [DEBUG pyenv_cfg:38]
80      base-prefix = /usr [DEBUG pyenv_cfg:38]
80      base-exec-prefix = /usr [DEBUG pyenv_cfg:38]
80      base-executable = /usr/bin/python [DEBUG pyenv_cfg:38]
80 symlink /usr/bin/python to /home/m8mble/work/scripts/safe-move/venv/bin/python [DEBUG _sync:44]
80 create virtualenv import hook file /home/m8mble/work/scripts/safe-move/venv/lib/python3.9/site-packages/_virtualenv.pth [DEBUG api:95]
81 create /home/m8mble/work/scripts/safe-move/venv/lib/python3.9/site-packages/_virtualenv.py [DEBUG api:98]
81 ============================== target debug ============================== [DEBUG session:54]
81 debug via /home/m8mble/work/scripts/safe-move/venv/bin/python /usr/lib/python3.9/site-packages/virtualenv/create/debug.py [DEBUG creator:223]
81 {
  "sys": {
    "executable": "/home/m8mble/work/scripts/safe-move/venv/bin/python",
    "_base_executable": "/home/m8mble/work/scripts/safe-move/venv/bin/python",
    "prefix": "/home/m8mble/work/scripts/safe-move/venv",
    "base_prefix": "/usr",
    "real_prefix": null,
    "exec_prefix": "/home/m8mble/work/scripts/safe-move/venv",
    "base_exec_prefix": "/usr",
    "path": [
      "/usr/lib/python39.zip",
      "/usr/lib/python3.9",
      "/usr/lib/python3.9/lib-dynload",
      "/home/m8mble/work/scripts/safe-move/venv/lib/python3.9/site-packages"
    ],
    "meta_path": [
      "<class '_virtualenv._Finder'>",
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib_external.PathFinder'>"
    ],
    "fs_encoding": "utf-8",
    "io_encoding": "utf-8"
  },
  "version": "3.9.0 (default, Oct  7 2020, 23:09:01) \n[GCC 10.2.0]",
  "makefile_filename": "/usr/lib/python3.9/config-3.9-x86_64-linux-gnu/Makefile",
  "os": "<module 'os' from '/usr/lib/python3.9/os.py'>",
  "site": "<module 'site' from '/usr/lib/python3.9/site.py'>",
  "datetime": "<module 'datetime' from '/usr/lib/python3.9/datetime.py'>",
  "math": "<module 'math' from '/usr/lib/python3.9/lib-dynload/math.cpython-39-x86_64-linux-gnu.so'>",
  "json": "<module 'json' from '/usr/lib/python3.9/json/__init__.py'>"
} [DEBUG session:55]
109 add seed packages via FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/m8mble/.local/share/virtualenv) [INFO session:59]
111 got embed update of distribution wheel from /home/m8mble/.local/share/virtualenv/wheel/3.9/embed/1/wheel.json [DEBUG via_disk_folder:135]
111 got embed update of distribution setuptools from /home/m8mble/.local/share/virtualenv/wheel/3.9/embed/1/setuptools.json [DEBUG via_disk_folder:135]
111 got embed update of distribution pip from /home/m8mble/.local/share/virtualenv/wheel/3.9/embed/1/pip.json [DEBUG via_disk_folder:135]
114 got embed update of distribution wheel from /home/m8mble/.local/share/virtualenv/wheel/3.9/embed/1/wheel.json [DEBUG via_disk_folder:135]
114 got embed update of distribution setuptools from /home/m8mble/.local/share/virtualenv/wheel/3.9/embed/1/setuptools.json [DEBUG via_disk_folder:135]
115 got embed update of distribution pip from /home/m8mble/.local/share/virtualenv/wheel/3.9/embed/1/pip.json [DEBUG via_disk_folder:135]
115 install wheel from wheel /usr/lib/python3.9/site-packages/virtualenv/seed/wheels/embed/wheel-0.36.1-py2.py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:49]
115 Attempting to acquire lock 140532008128464 on /home/m8mble/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/wheel-0.36.1-py2.py3-none-any.lock [DEBUG filelock:270]
115 install setuptools from wheel /usr/lib/python3.9/site-packages/virtualenv/seed/wheels/embed/setuptools-51.0.0-py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:49]
115 install pip from wheel /usr/lib/python3.9/site-packages/virtualenv/seed/wheels/embed/pip-20.3.1-py2.py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:49]
115 Lock 140532008128464 acquired on /home/m8mble/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/wheel-0.36.1-py2.py3-none-any.lock [INFO filelock:274]
116 Attempting to acquire lock 140532007821904 on /home/m8mble/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/setuptools-51.0.0-py3-none-any.lock [DEBUG filelock:270]
116 Attempting to acquire lock 140532007821424 on /home/m8mble/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/pip-20.3.1-py2.py3-none-any.lock [DEBUG filelock:270]
116 Attempting to release lock 140532008128464 on /home/m8mble/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/wheel-0.36.1-py2.py3-none-any.lock [DEBUG filelock:315]
116 Lock 140532007821904 acquired on /home/m8mble/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/setuptools-51.0.0-py3-none-any.lock [INFO filelock:274]
116 Lock 140532008128464 released on /home/m8mble/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/wheel-0.36.1-py2.py3-none-any.lock [INFO filelock:318]
116 Lock 140532007821424 acquired on /home/m8mble/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/pip-20.3.1-py2.py3-none-any.lock [INFO filelock:274]
116 Attempting to release lock 140532007821904 on /home/m8mble/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/setuptools-51.0.0-py3-none-any.lock [DEBUG filelock:315]
116 copy directory /home/m8mble/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/wheel-0.36.1-py2.py3-none-any/wheel to /home/m8mble/work/scripts/safe-move/venv/lib/python3.9/site-packages/wheel [DEBUG _sync:52]
116 Lock 140532007821904 released on /home/m8mble/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/setuptools-51.0.0-py3-none-any.lock [INFO filelock:318]
117 Attempting to release lock 140532007821424 on /home/m8mble/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/pip-20.3.1-py2.py3-none-any.lock [DEBUG filelock:315]
117 Lock 140532007821424 released on /home/m8mble/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/pip-20.3.1-py2.py3-none-any.lock [INFO filelock:318]
117 copy directory /home/m8mble/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/setuptools-51.0.0-py3-none-any/pkg_resources to /home/m8mble/work/scripts/safe-move/venv/lib/python3.9/site-packages/pkg_resources [DEBUG _sync:52]
117 copy directory /home/m8mble/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/pip-20.3.1-py2.py3-none-any/pip to /home/m8mble/work/scripts/safe-move/venv/lib/python3.9/site-packages/pip [DEBUG _sync:52]
122 copy /home/m8mble/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/wheel-0.36.1-py2.py3-none-any/wheel-0.36.1.virtualenv to /home/m8mble/work/scripts/safe-move/venv/lib/python3.9/site-packages/wheel-0.36.1.virtualenv [DEBUG _sync:52]
122 copy directory /home/m8mble/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/wheel-0.36.1-py2.py3-none-any/wheel-0.36.1.dist-info to /home/m8mble/work/scripts/safe-move/venv/lib/python3.9/site-packages/wheel-0.36.1.dist-info [DEBUG _sync:52]
124 copy directory /home/m8mble/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/setuptools-51.0.0-py3-none-any/setuptools to /home/m8mble/work/scripts/safe-move/venv/lib/python3.9/site-packages/setuptools [DEBUG _sync:52]
127 generated console scripts wheel-3.9 wheel wheel3 wheel3.9 [DEBUG base:48]
144 copy directory /home/m8mble/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/setuptools-51.0.0-py3-none-any/_distutils_hack to /home/m8mble/work/scripts/safe-move/venv/lib/python3.9/site-packages/_distutils_hack [DEBUG _sync:52]
145 copy /home/m8mble/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/setuptools-51.0.0-py3-none-any/distutils-precedence.pth to /home/m8mble/work/scripts/safe-move/venv/lib/python3.9/site-packages/distutils-precedence.pth [DEBUG _sync:52]
145 copy /home/m8mble/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/setuptools-51.0.0-py3-none-any/easy_install.py to /home/m8mble/work/scripts/safe-move/venv/lib/python3.9/site-packages/easy_install.py [DEBUG _sync:52]
145 copy /home/m8mble/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/setuptools-51.0.0-py3-none-any/setuptools-51.0.0.virtualenv to /home/m8mble/work/scripts/safe-move/venv/lib/python3.9/site-packages/setuptools-51.0.0.virtualenv [DEBUG _sync:52]
146 copy directory /home/m8mble/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/setuptools-51.0.0-py3-none-any/setuptools-51.0.0.dist-info to /home/m8mble/work/scripts/safe-move/venv/lib/python3.9/site-packages/setuptools-51.0.0.dist-info [DEBUG _sync:52]
148 generated console scripts easy_install-3.9 easy_install3.9 easy_install easy_install3 [DEBUG base:48]
171 copy /home/m8mble/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/pip-20.3.1-py2.py3-none-any/pip-20.3.1.virtualenv to /home/m8mble/work/scripts/safe-move/venv/lib/python3.9/site-packages/pip-20.3.1.virtualenv [DEBUG _sync:52]
172 copy directory /home/m8mble/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/pip-20.3.1-py2.py3-none-any/pip-20.3.1.dist-info to /home/m8mble/work/scripts/safe-move/venv/lib/python3.9/site-packages/pip-20.3.1.dist-info [DEBUG _sync:52]
173 generated console scripts pip3 pip pip-3.9 pip3.9 [DEBUG base:48]
173 add activators for Bash, CShell, Fish, PowerShell, Python, Xonsh [INFO session:64]
174 write /home/m8mble/work/scripts/safe-move/venv/pyvenv.cfg [DEBUG pyenv_cfg:34]
174     home = /usr [DEBUG pyenv_cfg:38]
174     implementation = CPython [DEBUG pyenv_cfg:38]
174     version_info = 3.9.0.final.0 [DEBUG pyenv_cfg:38]
174     virtualenv = 20.2.2 [DEBUG pyenv_cfg:38]
174     include-system-site-packages = false [DEBUG pyenv_cfg:38]
174     base-prefix = /usr [DEBUG pyenv_cfg:38]
174     base-exec-prefix = /usr [DEBUG pyenv_cfg:38]
174     base-executable = /usr/bin/python [DEBUG pyenv_cfg:38]
175 created virtual environment CPython3.9.0.final.0-64 in 134ms
  creator CPython3Posix(dest=/home/m8mble/work/scripts/safe-move/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/m8mble/.local/share/virtualenv)
    added seed packages: pip==20.3.1, setuptools==51.0.0, wheel==0.36.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator [WARNING __main__:17]
```

**Comment by gaborbernat** [comment]
For us to take this anywhere, you'll need to post a Github Repository that reproduces the issue. Ideally, have a Docker image in there.

**Comment by m8mble** [comment]
Thanks for motivating me to narrow it down. It has nothing to do with `virtualenv`. 

My issue was rather a `pyproject.toml` vs `setup.py` problem: The latter included my most recent config, the former only lay around for an old experiment with `poetry`. But apparently PEP517 changed pip to read the outdated `pyproject.toml` (instead of `setup.py` as I was assuming).

Hope this explanation can help others. Closing.
