### ISSUE TITLE
--upgrade-embed-wheels broken in virtualenv 20.4.0

### ISSUE THREAD

**Issue by J-M0** [pypa/virtualenv#2058]
**Issue**

Running `virtualenv --upgrade-embed-wheels` crashes and results in tracebacks printed to the terminal

**Environment**

- OS: macOS Mojave and Red Hat Linux 7
- ``pip list`` of the host python where ``virtualenv`` is installed:

```console
Package             Version
------------------- -------
appdirs             1.4.4
distlib             0.3.1
filelock            3.0.12
importlib-metadata  3.4.0
importlib-resources 5.1.0
pip                 20.3.3
setuptools          51.3.3
six                 1.15.0
typing-extensions   3.7.4.3
virtualenv          20.4.0
wheel               0.36.2
zipp                3.4.0
```

Output of failure:
<details><summary>virtualenv --upgrade-embed-wheels</summary>

```console
upgrade pip for python 3.10 with current pip-20.3.3-py2.py3-none-any.whl
upgrade setuptools for python 3.10 with current setuptools-51.3.3-py3-none-any.whl
upgrade wheel for python 3.10 with current wheel-0.36.2-py2.py3-none-any.whl
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 342, in _run_manual_upgrade
    periodic=False,
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 207, in do_update
    versions = _run_do_update(app_data, distribution, embed_filename, for_py_version, periodic, search_dirs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 237, in _run_do_update
    to_folder=wheelhouse,
TypeError: download_wheel() missing 1 required positional argument: 'env'

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 342, in _run_manual_upgrade
    periodic=False,
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 207, in do_update
    versions = _run_do_update(app_data, distribution, embed_filename, for_py_version, periodic, search_dirs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 237, in _run_do_update
    to_folder=wheelhouse,
TypeError: download_wheel() missing 1 required positional argument: 'env'

upgrade pip for python 3.9 with current pip-20.3.3-py2.py3-none-any.whl
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 342, in _run_manual_upgrade
    periodic=False,
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 207, in do_update
    versions = _run_do_update(app_data, distribution, embed_filename, for_py_version, periodic, search_dirs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 237, in _run_do_update
    to_folder=wheelhouse,
TypeError: download_wheel() missing 1 required positional argument: 'env'

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 342, in _run_manual_upgrade
    periodic=False,
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 207, in do_update
    versions = _run_do_update(app_data, distribution, embed_filename, for_py_version, periodic, search_dirs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 237, in _run_do_update
    to_folder=wheelhouse,
TypeError: download_wheel() missing 1 required positional argument: 'env'

upgrade setuptools for python 3.9 with current setuptools-51.3.3-py3-none-any.whl
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 342, in _run_manual_upgrade
    periodic=False,
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 207, in do_update
    versions = _run_do_update(app_data, distribution, embed_filename, for_py_version, periodic, search_dirs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 237, in _run_do_update
    to_folder=wheelhouse,
TypeError: download_wheel() missing 1 required positional argument: 'env'

upgrade wheel for python 3.9 with current wheel-0.36.2-py2.py3-none-any.whl
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 342, in _run_manual_upgrade
    periodic=False,
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 207, in do_update
    versions = _run_do_update(app_data, distribution, embed_filename, for_py_version, periodic, search_dirs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 237, in _run_do_update
    to_folder=wheelhouse,
TypeError: download_wheel() missing 1 required positional argument: 'env'

upgrade pip for python 3.8 with current pip-20.3.3-py2.py3-none-any.whl
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 342, in _run_manual_upgrade
    periodic=False,
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 207, in do_update
    versions = _run_do_update(app_data, distribution, embed_filename, for_py_version, periodic, search_dirs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 237, in _run_do_update
    to_folder=wheelhouse,
TypeError: download_wheel() missing 1 required positional argument: 'env'

upgrade setuptools for python 3.8 with current setuptools-51.3.3-py3-none-any.whl
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 342, in _run_manual_upgrade
    periodic=False,
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 207, in do_update
    versions = _run_do_update(app_data, distribution, embed_filename, for_py_version, periodic, search_dirs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 237, in _run_do_update
    to_folder=wheelhouse,
TypeError: download_wheel() missing 1 required positional argument: 'env'

upgrade wheel for python 3.8 with current wheel-0.36.2-py2.py3-none-any.whl
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 342, in _run_manual_upgrade
    periodic=False,
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 207, in do_update
    versions = _run_do_update(app_data, distribution, embed_filename, for_py_version, periodic, search_dirs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 237, in _run_do_update
    to_folder=wheelhouse,
TypeError: download_wheel() missing 1 required positional argument: 'env'

upgrade pip for python 3.7 with current pip-20.3.3-py2.py3-none-any.whl
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 342, in _run_manual_upgrade
    periodic=False,
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 207, in do_update
    versions = _run_do_update(app_data, distribution, embed_filename, for_py_version, periodic, search_dirs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 237, in _run_do_update
    to_folder=wheelhouse,
TypeError: download_wheel() missing 1 required positional argument: 'env'

upgrade setuptools for python 3.7 with current setuptools-51.3.3-py3-none-any.whl
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 342, in _run_manual_upgrade
    periodic=False,
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 207, in do_update
    versions = _run_do_update(app_data, distribution, embed_filename, for_py_version, periodic, search_dirs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 237, in _run_do_update
    to_folder=wheelhouse,
TypeError: download_wheel() missing 1 required positional argument: 'env'

upgrade wheel for python 3.7 with current wheel-0.36.2-py2.py3-none-any.whl
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 342, in _run_manual_upgrade
    periodic=False,
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 207, in do_update
    versions = _run_do_update(app_data, distribution, embed_filename, for_py_version, periodic, search_dirs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 237, in _run_do_update
    to_folder=wheelhouse,
TypeError: download_wheel() missing 1 required positional argument: 'env'

upgrade pip for python 3.6 with current pip-20.3.3-py2.py3-none-any.whl
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 342, in _run_manual_upgrade
    periodic=False,
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 207, in do_update
    versions = _run_do_update(app_data, distribution, embed_filename, for_py_version, periodic, search_dirs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 237, in _run_do_update
    to_folder=wheelhouse,
TypeError: download_wheel() missing 1 required positional argument: 'env'

upgrade setuptools for python 3.6 with current setuptools-51.3.3-py3-none-any.whl
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 342, in _run_manual_upgrade
    periodic=False,
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 207, in do_update
    versions = _run_do_update(app_data, distribution, embed_filename, for_py_version, periodic, search_dirs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 237, in _run_do_update
    to_folder=wheelhouse,
TypeError: download_wheel() missing 1 required positional argument: 'env'

upgrade wheel for python 3.6 with current wheel-0.36.2-py2.py3-none-any.whl
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 342, in _run_manual_upgrade
    periodic=False,
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 207, in do_update
    versions = _run_do_update(app_data, distribution, embed_filename, for_py_version, periodic, search_dirs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 237, in _run_do_update
    to_folder=wheelhouse,
TypeError: download_wheel() missing 1 required positional argument: 'env'

upgrade pip for python 3.5 with current pip-20.3.3-py2.py3-none-any.whl
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 342, in _run_manual_upgrade
    periodic=False,
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 207, in do_update
    versions = _run_do_update(app_data, distribution, embed_filename, for_py_version, periodic, search_dirs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 237, in _run_do_update
    to_folder=wheelhouse,
TypeError: download_wheel() missing 1 required positional argument: 'env'

upgrade setuptools for python 3.5 with current setuptools-50.3.2-py3-none-any.whl
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 342, in _run_manual_upgrade
    periodic=False,
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 207, in do_update
    versions = _run_do_update(app_data, distribution, embed_filename, for_py_version, periodic, search_dirs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 237, in _run_do_update
    to_folder=wheelhouse,
TypeError: download_wheel() missing 1 required positional argument: 'env'

upgrade wheel for python 3.5 with current wheel-0.36.2-py2.py3-none-any.whl
Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 342, in _run_manual_upgrade
    periodic=False,
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 207, in do_update
    versions = _run_do_update(app_data, distribution, embed_filename, for_py_version, periodic, search_dirs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 237, in _run_do_update
    to_folder=wheelhouse,
TypeError: download_wheel() missing 1 required positional argument: 'env'

upgrade pip for python 3.4 with current pip-19.1.1-py2.py3-none-any.whl
upgrade setuptools for python 3.4 with current setuptools-43.0.0-py2.py3-none-any.whl
Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 342, in _run_manual_upgrade
    periodic=False,
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 207, in do_update
    versions = _run_do_update(app_data, distribution, embed_filename, for_py_version, periodic, search_dirs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 237, in _run_do_update
    to_folder=wheelhouse,
TypeError: download_wheel() missing 1 required positional argument: 'env'

upgrade wheel for python 3.4 with current wheel-0.33.6-py2.py3-none-any.whl
Exception in thread Thread-21:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 342, in _run_manual_upgrade
    periodic=False,
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 207, in do_update
    versions = _run_do_update(app_data, distribution, embed_filename, for_py_version, periodic, search_dirs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 237, in _run_do_update
    to_folder=wheelhouse,
TypeError: download_wheel() missing 1 required positional argument: 'env'

upgrade pip for python 2.7 with current pip-20.3.3-py2.py3-none-any.whl
Exception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 342, in _run_manual_upgrade
    periodic=False,
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 207, in do_update
    versions = _run_do_update(app_data, distribution, embed_filename, for_py_version, periodic, search_dirs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 237, in _run_do_update
    to_folder=wheelhouse,
TypeError: download_wheel() missing 1 required positional argument: 'env'

upgrade setuptools for python 2.7 with current setuptools-44.1.1-py2.py3-none-any.whl
Exception in thread Thread-23:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 342, in _run_manual_upgrade
    periodic=False,
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 207, in do_update
    versions = _run_do_update(app_data, distribution, embed_filename, for_py_version, periodic, search_dirs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 237, in _run_do_update
    to_folder=wheelhouse,
TypeError: download_wheel() missing 1 required positional argument: 'env'

Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 342, in _run_manual_upgrade
    periodic=False,
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 207, in do_update
    versions = _run_do_update(app_data, distribution, embed_filename, for_py_version, periodic, search_dirs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 237, in _run_do_update
    to_folder=wheelhouse,
TypeError: download_wheel() missing 1 required positional argument: 'env'

upgrade wheel for python 2.7 with current wheel-0.36.2-py2.py3-none-any.whl
Exception in thread Thread-24:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 342, in _run_manual_upgrade
    periodic=False,
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 207, in do_update
    versions = _run_do_update(app_data, distribution, embed_filename, for_py_version, periodic, search_dirs)
  File "/home/kususer/.local/pipx/venvs/virtualenv/lib64/python3.6/site-packages/virtualenv/seed/wheels/periodic_update.py", line 237, in _run_do_update
    to_folder=wheelhouse,
TypeError: download_wheel() missing 1 required positional argument: 'env'

SystemExit: None
```

</details>

**Comment by gaborbernat** [comment]
A PR fixing this by passing on the env here https://github.com/pypa/virtualenv/blob/main/src/virtualenv/seed/wheels/periodic_update.py#L231 would be welcomed, and a test that validates this.
