### ISSUE TITLE
Package missing when using PyPy

### ISSUE THREAD

**Issue by CyanBook** [pypa/virtualenv#2065]
**Issue**
When a virtual environment is created using pypy as interpreter, using pip is impossible due to missing package. Copying every file in `site-packages/pip/_vendor` from my pypy installation folder to my virtual environment resolves the issue.

Traceback (most recent call last):
  File "/home/cyan/Documents/test-pypy2/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/home/cyan/Documents/test-pypy2/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/cyan/Documents/test-pypy2/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/cyan/Documents/test-pypy2/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/cyan/Documents/test-pypy2/site-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
  File "/home/cyan/Documents/test-pypy2/site-packages/pip/_internal/cli/progress_bars.py", line 7, in <module>
    from pip._vendor import six
ImportError: cannot import name 'six'

**Environment**

Provide at least:
- OS: Pop!_OS 20.10 x86_64
- ``pip list`` of the host python where ``virtualenv`` is installed:

  ```console
cyan@pop-os:~/Documents$ python3 -m pip list
Package                 Version
----------------------- ---------------
appdirs                 1.4.4
beautifulsoup4          4.9.1
blinker                 1.4
Brlapi                  0.7.0
certifi                 2020.4.5.1
chardet                 3.0.4
chrome-gnome-shell      0.0.0
click                   7.1.2
colorama                0.4.3
command-not-found       0.3
cryptography            3.0
cupshelpers             1.0
dbus-python             1.2.16
defer                   1.0.6
distlib                 0.3.1
distro                  1.5.0
distro-info             0.23ubuntu1
evdev                   1.3.0
filelock                3.0.12
flake8                  3.8.4
hidpidaemon             18.4.6
html5lib                1.1
httplib2                0.18.1
idna                    2.10
importlib-metadata      1.6.0
jeepney                 0.4.3
kernelstub              3.1.4
keyring                 21.3.0
language-selector       0.1
launchpadlib            1.10.13
lazr.restfulclient      0.14.2
lazr.uri                1.0.5
louis                   3.14.0
lxml                    4.5.2
macaroonbakery          1.3.1
mccabe                  0.6.1
meson                   0.55.3
more-itertools          4.2.0
netifaces               0.10.4
oauthlib                3.1.0
pip                     20.1.1
pop-transition          1.0.1
protobuf                3.12.3
pycairo                 1.16.2
pycodestyle             2.6.0
pycups                  2.0.1
pydbus                  0.6.0
pyflakes                2.2.0
Pygments                2.3.1
PyGObject               3.38.0
PyJWT                   1.7.1
pymacaroons             0.13.0
PyNaCl                  1.4.0
pyRFC3339               1.1
python-apt              2.1.3+ubuntu1.3
python-debian           0.1.37
python-xlib             0.27
pytz                    2020.1
pyxdg                   0.26
PyYAML                  5.3.1
repolib                 1.5.2
repoman                 1.4.0
requests                2.23.0
requests-unixsocket     0.2.0
screen-resolution-extra 0.0.0
SecretStorage           3.1.2
sessioninstaller        0.0.0
setuptools              49.3.1
simplejson              3.17.0
six                     1.15.0
soupsieve               2.0.1
systemd-python          234
ubuntu-advantage-tools  24.4
ubuntu-drivers-common   0.0.0
ufw                     0.36
urllib3                 1.25.9
virtualenv              20.0.29+ds
wadllib                 1.3.4
webencodings            0.5.1
wheel                   0.34.2
xkit                    0.0.0
zipp                    1.0.0
  ```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console
cyan@pop-os:~/Documents$ virtualenv -p pypy -vvv --with-traceback test-pypy2
44 setup logging to NOTSET [DEBUG report:43]
61 find interpreter for spec PythonSpec(implementation=pypy) [INFO builtin:44]
61 proposed PythonInfo(spec=CPython3.8.6.final.0-64, exe=/usr/bin/python3, platform=linux, version='3.8.6 (default, Sep 25 2020, 09:36:53) \n[GCC 10.2.0]', encoding_fs_io=utf-8-utf-8) [INFO builtin:50]
61 discover PATH[0]=/home/cyan/.local/bin [DEBUG builtin:84]
62 filesystem is case-sensitive [DEBUG info:28]
62 discover PATH[1]=/usr/local/sbin [DEBUG builtin:84]
62 discover PATH[2]=/usr/local/bin [DEBUG builtin:84]
62 Attempting to acquire lock 140115142006912 on /home/cyan/.local/share/virtualenv/py_info/1/61268e353b6ab0b2cea6f6657229c3f682a75cb1e55c635f860b4a9b418cf58b.lock [DEBUG filelock:270]
63 Lock 140115142006912 acquired on /home/cyan/.local/share/virtualenv/py_info/1/61268e353b6ab0b2cea6f6657229c3f682a75cb1e55c635f860b4a9b418cf58b.lock [INFO filelock:274]
63 got python info of /usr/local/bin/pypy from /home/cyan/.local/share/virtualenv/py_info/1/61268e353b6ab0b2cea6f6657229c3f682a75cb1e55c635f860b4a9b418cf58b.json [DEBUG via_disk_folder:133]
63 Attempting to release lock 140115142006912 on /home/cyan/.local/share/virtualenv/py_info/1/61268e353b6ab0b2cea6f6657229c3f682a75cb1e55c635f860b4a9b418cf58b.lock [DEBUG filelock:315]
63 Lock 140115142006912 released on /home/cyan/.local/share/virtualenv/py_info/1/61268e353b6ab0b2cea6f6657229c3f682a75cb1e55c635f860b4a9b418cf58b.lock [INFO filelock:318]
63 proposed PathPythonInfo(spec=PyPy3.7.4.final.0-64, exe=/usr/local/bin/pypy, platform=linux, version='3.7.4 (c2256364b915, Mar 22 2020, 21:45:53)\n[PyPy 7.3.1-alpha0 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]', encoding_fs_io=utf-8-UTF-8) [INFO builtin:50]
63 accepted PathPythonInfo(spec=PyPy3.7.4.final.0-64, exe=/usr/local/bin/pypy, platform=linux, version='3.7.4 (c2256364b915, Mar 22 2020, 21:45:53)\n[PyPy 7.3.1-alpha0 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]', encoding_fs_io=utf-8-UTF-8) [DEBUG builtin:52]
95 create virtual environment via PyPy3Posix(dest=/home/cyan/Documents/test-pypy2, clear=False, global=False) [INFO session:52]
95 create folder /home/cyan/Documents/test-pypy2/bin [DEBUG _sync:25]
95 create folder /home/cyan/Documents/test-pypy2/lib/python3.7/site-packages [DEBUG _sync:25]
95 create folder /home/cyan/Documents/test-pypy2/site-packages [DEBUG _sync:25]
95 write /home/cyan/Documents/test-pypy2/pyvenv.cfg [DEBUG pyenv_cfg:34]
95 	home = /opt/pypy [DEBUG pyenv_cfg:38]
95 	implementation = PyPy [DEBUG pyenv_cfg:38]
96 	version_info = 3.7.4.final.0 [DEBUG pyenv_cfg:38]
96 	virtualenv = 20.0.29+ds [DEBUG pyenv_cfg:38]
96 	include-system-site-packages = false [DEBUG pyenv_cfg:38]
96 	base-prefix = /opt/pypy [DEBUG pyenv_cfg:38]
96 	base-exec-prefix = /opt/pypy [DEBUG pyenv_cfg:38]
96 	base-executable = /usr/local/bin/pypy [DEBUG pyenv_cfg:38]
96 symlink /usr/local/bin/pypy to /home/cyan/Documents/test-pypy2/bin/pypy [DEBUG _sync:44]
96 symlink /opt/pypy/bin/libpypy3-c.so to /home/cyan/Documents/test-pypy2/bin/libpypy3-c.so [DEBUG _sync:44]
96 symlink /opt/pypy/lib/libtcl8.5.so to /home/cyan/Documents/test-pypy2/lib/libtcl8.5.so [DEBUG _sync:44]
96 symlink /opt/pypy/lib/libgdbm.so.2.0.0 to /home/cyan/Documents/test-pypy2/lib/libgdbm.so.2.0.0 [DEBUG _sync:44]
96 symlink /opt/pypy/lib/libtinfow.so.6.1 to /home/cyan/Documents/test-pypy2/lib/libtinfow.so.6.1 [DEBUG _sync:44]
96 symlink /opt/pypy/lib/libncursesw.so.6 to /home/cyan/Documents/test-pypy2/lib/libncursesw.so.6 [DEBUG _sync:44]
97 symlink directory /opt/pypy/lib/tk to /home/cyan/Documents/test-pypy2/lib/tk [DEBUG _sync:44]
97 symlink /opt/pypy/lib/libexpat.so.1 to /home/cyan/Documents/test-pypy2/lib/libexpat.so.1 [DEBUG _sync:44]
97 symlink /opt/pypy/lib/liblzma.so.5.2.4 to /home/cyan/Documents/test-pypy2/lib/liblzma.so.5.2.4 [DEBUG _sync:44]
97 symlink /opt/pypy/lib/libsqlite3.so.0 to /home/cyan/Documents/test-pypy2/lib/libsqlite3.so.0 [DEBUG _sync:44]
97 symlink /opt/pypy/lib/libpanelw.so.6 to /home/cyan/Documents/test-pypy2/lib/libpanelw.so.6 [DEBUG _sync:44]
97 symlink /opt/pypy/lib/libpanelw.so.6.1 to /home/cyan/Documents/test-pypy2/lib/libpanelw.so.6.1 [DEBUG _sync:44]
97 symlink /opt/pypy/lib/libncursesw.so.6.1 to /home/cyan/Documents/test-pypy2/lib/libncursesw.so.6.1 [DEBUG _sync:44]
97 symlink /opt/pypy/lib/libexpat.so.1.5.2 to /home/cyan/Documents/test-pypy2/lib/libexpat.so.1.5.2 [DEBUG _sync:44]
97 symlink /opt/pypy/lib/libtinfow.so.6 to /home/cyan/Documents/test-pypy2/lib/libtinfow.so.6 [DEBUG _sync:44]
97 symlink /opt/pypy/lib/libgdbm.so.2 to /home/cyan/Documents/test-pypy2/lib/libgdbm.so.2 [DEBUG _sync:44]
97 symlink /opt/pypy/lib/libtk8.5.so to /home/cyan/Documents/test-pypy2/lib/libtk8.5.so [DEBUG _sync:44]
97 symlink /opt/pypy/lib/libffi.so.6 to /home/cyan/Documents/test-pypy2/lib/libffi.so.6 [DEBUG _sync:44]
98 symlink /opt/pypy/lib/libsqlite3.so.0.8.6 to /home/cyan/Documents/test-pypy2/lib/libsqlite3.so.0.8.6 [DEBUG _sync:44]
98 symlink directory /opt/pypy/lib/tcl to /home/cyan/Documents/test-pypy2/lib/tcl [DEBUG _sync:44]
98 symlink /opt/pypy/lib/libffi.so.6.0.4 to /home/cyan/Documents/test-pypy2/lib/libffi.so.6.0.4 [DEBUG _sync:44]
98 symlink /opt/pypy/lib/liblzma.so.5 to /home/cyan/Documents/test-pypy2/lib/liblzma.so.5 [DEBUG _sync:44]
98 create virtualenv import hook file /home/cyan/Documents/test-pypy2/site-packages/_virtualenv.pth [DEBUG api:94]
98 create /home/cyan/Documents/test-pypy2/site-packages/_virtualenv.py [DEBUG api:97]
99 ============================== target debug ============================== [DEBUG session:54]
99 debug via /home/cyan/Documents/test-pypy2/bin/pypy3 /usr/lib/python3/dist-packages/virtualenv/create/debug.py [DEBUG creator:209]
99 {
  "sys": {
    "executable": "/home/cyan/Documents/test-pypy2/bin/pypy3",
    "_base_executable": null,
    "prefix": "/home/cyan/Documents/test-pypy2",
    "base_prefix": "/opt/pypy",
    "real_prefix": null,
    "exec_prefix": "/home/cyan/Documents/test-pypy2",
    "base_exec_prefix": "/opt/pypy",
    "path": [
      "/opt/pypy/lib_pypy/__extensions__",
      "/opt/pypy/lib_pypy",
      "/opt/pypy/lib-python/3",
      "/opt/pypy/lib-python/3/lib-tk",
      "/opt/pypy/lib-python/3/plat-linux2",
      "/home/cyan/Documents/test-pypy2/site-packages"
    ],
    "meta_path": [
      "<class '_virtualenv._Finder'>",
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib_external.PathFinder'>"
    ],
    "fs_encoding": "utf-8",
    "io_encoding": "UTF-8"
  },
  "version": "3.7.4 (c2256364b915, Mar 22 2020, 21:45:53)\n[PyPy 7.3.1-alpha0 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]",
  "makefile_filename": "/opt/pypy/lib-pypy/config-3.7/Makefile",
  "os": "<module 'os' from '/opt/pypy/lib-python/3/os.py'>",
  "site": "<module 'site' from '/opt/pypy/lib-python/3/site.py'>",
  "datetime": "<module 'datetime' from '/opt/pypy/lib-python/3/datetime.py'>",
  "math": "<module 'math' (built-in)>",
  "json": "<module 'json' from '/opt/pypy/lib-python/3/json/__init__.py'>"
} [DEBUG session:55]
183 add seed packages via FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/cyan/.local/share/virtualenv) [INFO session:59]
187 install setuptools from wheel /usr/share/python-wheels/setuptools-44.0.0-py2.py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:53]
187 Attempting to acquire lock 140115139750544 on /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/setuptools-44.0.0-py2.py3-none-any.lock [DEBUG filelock:270]
187 install pip from wheel /usr/share/python-wheels/pip-20.1.1-py2.py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:53]
187 install wheel from wheel /usr/share/python-wheels/wheel-0.34.2-py2.py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:53]
187 install pkg_resources from wheel /usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:53]
187 Lock 140115139750544 acquired on /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/setuptools-44.0.0-py2.py3-none-any.lock [INFO filelock:274]
187 Attempting to acquire lock 140115139750928 on /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/pip-20.1.1-py2.py3-none-any.lock [DEBUG filelock:270]
187 Attempting to acquire lock 140115139751024 on /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/wheel-0.34.2-py2.py3-none-any.lock [DEBUG filelock:270]
188 Attempting to acquire lock 140115139751216 on /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/pkg_resources-0.0.0-py2.py3-none-any.lock [DEBUG filelock:270]
188 Lock 140115139750928 acquired on /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/pip-20.1.1-py2.py3-none-any.lock [INFO filelock:274]
188 Attempting to release lock 140115139750544 on /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/setuptools-44.0.0-py2.py3-none-any.lock [DEBUG filelock:315]
188 Lock 140115139751024 acquired on /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/wheel-0.34.2-py2.py3-none-any.lock [INFO filelock:274]
188 Lock 140115139751216 acquired on /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/pkg_resources-0.0.0-py2.py3-none-any.lock [INFO filelock:274]
188 Lock 140115139750544 released on /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/setuptools-44.0.0-py2.py3-none-any.lock [INFO filelock:318]
188 Attempting to release lock 140115139750928 on /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/pip-20.1.1-py2.py3-none-any.lock [DEBUG filelock:315]
188 Attempting to release lock 140115139751024 on /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/wheel-0.34.2-py2.py3-none-any.lock [DEBUG filelock:315]
188 Attempting to release lock 140115139751216 on /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/pkg_resources-0.0.0-py2.py3-none-any.lock [DEBUG filelock:315]
189 Lock 140115139750928 released on /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/pip-20.1.1-py2.py3-none-any.lock [INFO filelock:318]
189 copy directory /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/setuptools-44.0.0-py2.py3-none-any/setuptools to /home/cyan/Documents/test-pypy2/site-packages/setuptools [DEBUG _sync:52]
189 Lock 140115139751216 released on /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/pkg_resources-0.0.0-py2.py3-none-any.lock [INFO filelock:318]
189 Lock 140115139751024 released on /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/wheel-0.34.2-py2.py3-none-any.lock [INFO filelock:318]
189 copy directory /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/pip-20.1.1-py2.py3-none-any/pip-20.1.1.dist-info to /home/cyan/Documents/test-pypy2/site-packages/pip-20.1.1.dist-info [DEBUG _sync:52]
189 copy directory /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/pkg_resources-0.0.0-py2.py3-none-any/pkg_resources to /home/cyan/Documents/test-pypy2/site-packages/pkg_resources [DEBUG _sync:52]
190 copy directory /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/wheel-0.34.2-py2.py3-none-any/wheel-0.34.2.dist-info to /home/cyan/Documents/test-pypy2/site-packages/wheel-0.34.2.dist-info [DEBUG _sync:52]
198 copy directory /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/pip-20.1.1-py2.py3-none-any/pip to /home/cyan/Documents/test-pypy2/site-packages/pip [DEBUG _sync:52]
198 copy /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/wheel-0.34.2-py2.py3-none-any/wheel-0.34.2.virtualenv to /home/cyan/Documents/test-pypy2/site-packages/wheel-0.34.2.virtualenv [DEBUG _sync:52]
199 copy directory /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/wheel-0.34.2-py2.py3-none-any/wheel to /home/cyan/Documents/test-pypy2/site-packages/wheel [DEBUG _sync:52]
208 copy /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/pkg_resources-0.0.0-py2.py3-none-any/pkg_resources-0.0.0.virtualenv to /home/cyan/Documents/test-pypy2/site-packages/pkg_resources-0.0.0.virtualenv [DEBUG _sync:52]
209 copy directory /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/pkg_resources-0.0.0-py2.py3-none-any/pkg_resources-0.0.0.dist-info to /home/cyan/Documents/test-pypy2/site-packages/pkg_resources-0.0.0.dist-info [DEBUG _sync:52]
225 generated console scripts wheel wheel3.7 wheel3 wheel-3.7 [DEBUG base:48]
234 generated console scripts  [DEBUG base:48]
253 copy /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/pip-20.1.1-py2.py3-none-any/pip-20.1.1.virtualenv to /home/cyan/Documents/test-pypy2/site-packages/pip-20.1.1.virtualenv [DEBUG _sync:52]
254 generated console scripts pip3.7 pip-3.7 pip pip3 [DEBUG base:48]
255 copy /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/setuptools-44.0.0-py2.py3-none-any/easy_install.py to /home/cyan/Documents/test-pypy2/site-packages/easy_install.py [DEBUG _sync:52]
255 copy directory /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/setuptools-44.0.0-py2.py3-none-any/setuptools-44.0.0.dist-info to /home/cyan/Documents/test-pypy2/site-packages/setuptools-44.0.0.dist-info [DEBUG _sync:52]
257 copy /home/cyan/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall/setuptools-44.0.0-py2.py3-none-any/setuptools-44.0.0.virtualenv to /home/cyan/Documents/test-pypy2/site-packages/setuptools-44.0.0.virtualenv [DEBUG _sync:52]
259 generated console scripts easy_install-3.7 easy_install easy_install3 easy_install3.7 [DEBUG base:48]
259 add activators for Bash, CShell, Fish, PowerShell, Python, Xonsh [INFO session:64]
261 write /home/cyan/Documents/test-pypy2/pyvenv.cfg [DEBUG pyenv_cfg:34]
261 	home = /opt/pypy [DEBUG pyenv_cfg:38]
261 	implementation = PyPy [DEBUG pyenv_cfg:38]
262 	version_info = 3.7.4.final.0 [DEBUG pyenv_cfg:38]
262 	virtualenv = 20.0.29+ds [DEBUG pyenv_cfg:38]
262 	include-system-site-packages = false [DEBUG pyenv_cfg:38]
262 	base-prefix = /opt/pypy [DEBUG pyenv_cfg:38]
262 	base-exec-prefix = /opt/pypy [DEBUG pyenv_cfg:38]
262 	base-executable = /usr/local/bin/pypy [DEBUG pyenv_cfg:38]
262 created virtual environment PyPy3.7.4.final.0-64 in 220ms
  creator PyPy3Posix(dest=/home/cyan/Documents/test-pypy2, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/cyan/.local/share/virtualenv)
    added seed packages: pip==20.1.1, pkg_resources==0.0.0, setuptools==44.0.0, wheel==0.34.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator [WARNING __main__:17]
```

**Comment by gaborbernat** [comment]
How did you install virtualenv. If you used your operating systems installer, please report the issue with them, because their incorrect repackaging is the problem.

**Comment by CyanBook** [comment]
Installed via apt.
`sudo apt install python3-virtualenv`

**Comment by gaborbernat** [comment]
Then it's your os issue.

**Comment by CyanBook** [comment]
How can i report this issue to the right person? Aren't you distributing the package across various package manager?

**Comment by gaborbernat** [comment]
Nope. We provide the raw sources, but operating systems take that and repackage it. In this case you want to submit a bug to pop os bug tracker.

**Comment by mattip** [comment]
This issue is closed, but you could do (in the original PyPy checkout) `pypy -m ensurepip; pypy -m pip install virtualenv` and then you can use `pypy -m virtualenv <path>`
