### ISSUE TITLE
`python -m virtualenv venv` tries to execute python files in current working directory

### ISSUE THREAD

**Issue by vl2376** [pypa/virtualenv#2067]
**Issue**

`python -m virtualenv venv` tries to execute python files in current working directory. Works fine if cwd is empty. 

**Environment**

Provide at least:
- OS: Windows 10
- ``pip list`` of the host python where ``virtualenv`` is installed:

  ```Package                       Version
----------------------------- -------------------
-ffi                          1.12.3
-umpy                         1.18.1
alabaster                     0.7.12
alembic                       1.4.1
anaconda-client               1.7.2
anaconda-navigator            1.8.7
appdirs                       1.4.4
argh                          0.26.2
argon2-cffi                   20.1.0
astroid                       2.4.2
async-generator               1.10
atomicwrites                  1.4.0
attrs                         20.3.0
autopep8                      1.5.4
awscli                        1.18.183
azure-core                    1.11.0
azure-storage-blob            12.7.1
Babel                         2.9.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.1
backports.tempfile            1.0
backports.weakref             1.0.post1
bcrypt                        3.2.0
beautifulsoup4                4.9.3
black                         19.10b0
bleach                        3.3.0
blis                          0.4.1
boto                          2.49.0
boto3                         1.14.13
botocore                      1.17.63
brotlipy                      0.7.0
cachetools                    4.1.1
catalogue                     1.0.0
catboost                      0.24.4
certifi                       2020.12.5
cffi                          1.14.4
chardet                       4.0.0
click                         7.1.2
cloudpickle                   1.6.0
clyent                        1.2.2
colorama                      0.4.4
colorlover                    0.3.0
combo                         0.1.2
conda                         4.9.2
conda-build                   3.10.5
conda-package-handling        1.7.2
conda-verify                  3.4.2
confuse                       1.4.0
convertdate                   2.2.1
cryptography                  3.3.1
cufflinks                     0.17.3
cycler                        0.10.0
cymem                         2.0.3
Cython                        0.29.14
dash                          1.7.0
dash-core-components          1.6.0
dash-daq                      0.3.3
dash-html-components          1.0.2
dash-renderer                 1.2.2
dash-table                    4.5.1
databricks-cli                0.14.1
decorator                     4.4.2
defusedxml                    0.6.0
diff-match-patch              20200713
distlib                       0.3.1
docker                        4.4.1
docutils                      0.15.2
entrypoints                   0.3
eventregistry                 8.7
filelock                      3.0.12
flake8                        3.8.4
Flask                         1.1.2
Flask-Compress                1.4.0
funcy                         1.15
future                        0.18.2
gensim                        3.8.3
gitdb                         4.0.5
GitPython                     3.1.13
glob2                         0.7
graphviz                      0.16
holidays                      0.10.2
htmlmin                       0.1.12
idna                          2.10
ImageHash                     4.2.0
imagesize                     1.2.0
imbalanced-learn              0.7.0
importlib-metadata            2.0.0
importlib-resources           5.1.0
intervaltree                  3.1.0
ipykernel                     5.3.4
ipython                       7.16.1
ipython-genutils              0.2.0
ipywidgets                    7.6.3
isodate                       0.6.0
isort                         5.7.0
itsdangerous                  1.1.0
jedi                          0.17.2
jellyfish                     0.8.2
Jinja2                        2.11.3
jmespath                      0.10.0
joblib                        1.0.1
json5                         0.9.5
jsonschema                    3.2.0
jupyter-client                6.1.7
jupyter-core                  4.7.1
jupyterlab                    2.2.6
jupyterlab-pygments           0.1.2
jupyterlab-server             1.2.0
jupyterlab-widgets            1.0.0
keyring                       22.0.1
kiwisolver                    1.3.1
kmodes                        0.11.0
korean-lunar-calendar         0.2.1
lazy-object-proxy             1.4.3
lightgbm                      3.1.1
llvmlite                      0.35.0
Mako                          1.1.4
MarkupSafe                    1.1.1
matplotlib                    3.3.4
mccabe                        0.6.1
menuinst                      1.4.16
missingno                     0.4.2
mistune                       0.8.4
mlflow                        1.13.1
mlxtend                       0.18.0
msrest                        0.6.21
murmurhash                    1.0.2
mypy-extensions               0.4.3
navigator-updater             0.2.1
nbclient                      0.5.1
nbconvert                     6.0.7
nbformat                      5.1.2
nest-asyncio                  1.4.3
networkx                      2.5
nltk                          3.5
notebook                      6.2.0
numba                         0.52.0
numexpr                       2.7.2
numpy                         1.19.0
numpydoc                      1.1.0
oauthlib                      3.1.0
olefile                       0.46
packaging                     20.9
pandas                        0.25.3
pandas-profiling              2.10.1
pandocfilters                 1.4.3
paramiko                      2.7.2
parso                         0.7.0
pathspec                      0.7.0
patsy                         0.5.1
pexpect                       4.8.0
phik                          0.11.0
pickleshare                   0.7.5
Pillow                        8.1.0
pip                           20.3.3
pkginfo                       1.7.0
plac                          1.1.3
plotly                        4.4.1
pluggy                        0.13.1
preshed                       3.0.2
prometheus-client             0.9.0
prometheus-flask-exporter     0.18.1
prompt-toolkit                3.0.8
protobuf                      3.14.0
psutil                        5.8.0
ptyprocess                    0.7.0
pyasn1                        0.4.8
pycaret                       2.2.3
pycodestyle                   2.6.0
pycosat                       0.6.3
pycparser                     2.20
pydocstyle                    5.1.1
pyemd                         0.5.1
pyflakes                      2.2.0
Pygments                      2.7.4
pyLDAvis                      3.2.0
pylint                        2.6.0
pyls-black                    0.4.6
pyls-spyder                   0.3.0
PyMeeus                       0.3.7
PyNaCl                        1.4.0
pynndescent                   0.5.2
pyod                          0.8.6
pyOpenSSL                     20.0.1
pyparsing                     2.4.7
Pyphen                        0.9.5
pyrsistent                    0.17.3
PySocks                       1.7.1
python-dateutil               2.8.1
python-editor                 1.0.4
python-jsonrpc-server         0.4.0
python-language-server        0.36.2
pytz                          2021.1
PyWavelets                    1.1.1
pywin32                       227
pywin32-ctypes                0.2.0
pywinpty                      0.5.7
PyYAML                        5.4.1
pyzmq                         20.0.0
QDarkStyle                    2.8.1
QtAwesome                     1.0.1
qtconsole                     5.0.2
QtPy                          1.9.0
querystring-parser            1.2.4
regex                         2020.11.13
requests                      2.25.1
requests-oauthlib             1.3.0
retrying                      1.3.3
rope                          0.18.0
rsa                           4.5
Rtree                         0.9.4
ruamel-yaml                   0.15.87
s3transfer                    0.3.3
scikit-learn                  0.23.2
scikit-plot                   0.3.7
scipy                         1.5.4
seaborn                       0.11.1
selenium                      3.141.0
Send2Trash                    1.5.0
setuptools                    52.0.0.post20210125
six                           1.15.0
sklearn                       0.0
smart-open                    2.1.0
smmap                         3.0.5
snowballstemmer               2.1.0
sortedcontainers              2.3.0
soupsieve                     2.1
spacy                         2.3.1
Sphinx                        3.4.3
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
spyder                        4.2.1
spyder-kernels                1.10.1
SQLAlchemy                    1.3.23
SQLAlchemy-Utils              0.36.1
sqlparse                      0.4.1
srsly                         1.0.5
statsmodels                   0.12.2
suod                          0.0.6
tabulate                      0.8.7
tangled-up-in-unicode         0.0.6
terminado                     0.9.2
testpath                      0.4.4
textacy                       0.10.0
textblob                      0.15.3
textdistance                  4.2.1
thinc                         7.4.1
threadpoolctl                 2.1.0
three-merge                   0.1.1
toml                          0.10.1
tornado                       6.1
tqdm                          4.56.0
traitlets                     4.3.3
typed-ast                     1.4.2
typing-extensions             3.7.4.3
ujson                         4.0.2
umap-learn                    0.5.1
urllib3                       1.25.11
vacances-scolaires-france     0.7.1
virtualenv                    20.4.2
visions                       0.6.0
waitress                      1.4.4
wasabi                        0.7.0
watchdog                      1.0.2
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              0.57.0
Werkzeug                      1.0.1
wheel                         0.36.2
widgetsnbextension            3.5.1
win-inet-pton                 1.1.0
wincertstore                  0.2
wordcloud                     1.8.1
wrapt                         1.11.2
xgboost                       1.3.3
yapf                          0.30.0
yellowbrick                   1.3.post1
zipp                          3.4.0  
```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```Traceback (most recent call last):
  File "C:\Users\Vincent Liagre\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Vincent Liagre\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\Vincent Liagre\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Vincent Liagre\AppData\Local\Continuum\Anaconda3\lib\site-packages\virtualenv\__init__.py", line 3, in <module>
    from .run import cli_run, session_via_cli
  File "C:\Users\Vincent Liagre\AppData\Local\Continuum\Anaconda3\lib\site-packages\virtualenv\run\__init__.py", line 3, in <module>
    import logging
  File "C:\Users\Vincent Liagre\OneDrive - xxx\Documents\KM\python_code\logging.py", line 15, in <module>
    logging.basicConfig(filename='example.log',
AttributeError: module 'logging' has no attribute 'basicConfig'
```

**Comment by gaborbernat** [comment]
This is not virtualenv related per se. You have a file named logging in your CWD, which is hiding the standard library ``logging`` module. In general, it's recommended to avoid any modules with the same name as the standard library. Python can only hold one copy of a module at a time, so if your own library and the standard library both have a module with the same name, only one will be used; and the other cause such breakages.

**Comment by vl2376** [comment]
Thanks ; just figured that as well
