### ISSUE TITLE
Error message misformatting

### ISSUE THREAD

**Issue by ENDrain** [pypa/virtualenv#2092]
**Issue**

 I'm trying to create a virtual environment:
 ```console
 > python -m virtualenv -p="C:/Program Files/Python30/python.exe" venv
 ```
 The resulting error message has some formatting issues:
 ```console
 RuntimeError: failed to query C:\Program Files\Python30\python.exe with code 1 err: '  File "C:\\Program Files (x86)\\Python39-32\\lib\\site-packages\\virtualenv\\discovery\\py_info.py", line 97\n    self.sysconfig_vars[u"implementation_lower"] = u"python"\n                                              ^\nSyntaxError: invalid syntax\n'
 ```
I've learned since creating this that virtualenv does not support 3.0, but this issue is about the error message formatting.

**Environment**

- OS: Windows_NT x64 10.0.19042
- Python: 3.9.2
- ``pip list`` of the host python where ``virtualenv`` is installed:
 <details><summary>Console output</summary>

  ```console
  Package            Version
  ------------------ -----------
  appdirs            1.4.4
  bleach             3.3.0
  build              0.3.1.post1
  certifi            2020.12.5
  chardet            4.0.0
  colorama           0.4.4
  cumd               1.4.0
  distlib            0.3.1
  docutils           0.17
  filelock           3.0.12
  idna               2.10
  importlib-metadata 3.10.1
  keyring            23.0.1
  lxml               4.6.3
  lxmlx              2.0.2
  Markdown           3.2.1
  packaging          20.9
  pep517             0.10.0
  pip                21.0.1
  pkginfo            1.7.0
  Pygments           2.8.1
  pyparsing          2.4.7
  pywin32-ctypes     0.2.0
  readme-renderer    29.0
  requests           2.25.1
  requests-toolbelt  0.9.1
  rfc3986            1.4.0
  setuptools         49.2.1
  six                1.15.0
  toml               0.10.2
  tqdm               4.60.0
  twine              3.4.1
  urllib3            1.26.4
  virtualenv         20.4.3
  webencodings       0.5.1
  zipp               3.4.1
  ```

</details>

**Output of the virtual environment creation**
<details><summary>Console output</summary>

```console
164 setup logging to NOTSET [DEBUG report:43]
186 find interpreter for spec PythonSpec(path=C:/Program Files/Python30/python.exe) [INFO builtin:51]
187 Attempting to acquire lock 68179040 on C:\Users\USERNAME\AppData\Local\pypa\virtualenv\py_info\1\75b9f66602e54ff5df93f303d8f7368168b079fd99dc3aac134e2a3410d47ece.lock [DEBUG filelock:270]
188 Lock 68179040 acquired on C:\Users\USERNAME\AppData\Local\pypa\virtualenv\py_info\1\75b9f66602e54ff5df93f303d8f7368168b079fd99dc3aac134e2a3410d47ece.lock [INFO filelock:274]
189 get interpreter info via cmd: 'C:\Program Files\Python30\python.exe' 'C:\Program Files (x86)\Python39-32\lib\site-packages\virtualenv\discovery\py_info.py' [DEBUG cached_py_info:87]
243 Attempting to release lock 68179040 on C:\Users\USERNAME\AppData\Local\pypa\virtualenv\py_info\1\75b9f66602e54ff5df93f303d8f7368168b079fd99dc3aac134e2a3410d47ece.lock [DEBUG filelock:315]
245 Lock 68179040 released on C:\Users\USERNAME\AppData\Local\pypa\virtualenv\py_info\1\75b9f66602e54ff5df93f303d8f7368168b079fd99dc3aac134e2a3410d47ece.lock [INFO filelock:318]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python39-32\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Python39-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\virtualenv\__main__.py", line 77, in <module>
    run_with_catch()  # pragma: no cov
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\virtualenv\__main__.py", line 62, in run_with_catch
    run(args, options)
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\virtualenv\__main__.py", line 16, in run
    session = cli_run(args, options)
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\virtualenv\run\__init__.py", line 26, in cli_run
    of_session = session_via_cli(args, options, setup_logging)
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\virtualenv\run\__init__.py", line 42, in session_via_cli
    parser, elements = build_parser(args, options, setup_logging)
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\virtualenv\run\__init__.py", line 64, in build_parser
    parser._interpreter = interpreter = discover.interpreter
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\virtualenv\discovery\discover.py", line 44, in interpreter
    self._interpreter = self.run()
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\virtualenv\discovery\builtin.py", line 36, in run
    result = get_interpreter(python_spec, self.app_data)
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\virtualenv\discovery\builtin.py", line 53, in get_interpreter
    for interpreter, impl_must_match in propose_interpreters(spec, app_data):
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\virtualenv\discovery\builtin.py", line 73, in propose_interpreters
    yield PythonInfo.from_exe(os.path.abspath(spec.path), app_data), True
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\virtualenv\discovery\py_info.py", line 316, in from_exe
    proposed = from_exe(cls, app_data, exe, raise_on_error=raise_on_error, ignore_cache=ignore_cache)
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\virtualenv\discovery\cached_py_info.py", line 31, in from_exe
    raise result
RuntimeError: failed to query C:\Program Files\Python30\python.exe with code 1 err: '  File "C:\\Program Files (x86)\\Python39-32\\lib\\site-packages\\virtualenv\\discovery\\py_info.py", line 97\n    self.sysconfig_vars[u"implementation_lower"] = u"python"\n                                              ^\nSyntaxError: invalid syntax\n'
```
</details>

**Comment by gaborbernat** [comment]
As this is 2 years old without updates closing it. If still valid we can reopen.
