### ISSUE TITLE
20.4.7: setuptools 'build_sphinx' command fails

### ISSUE THREAD

**Issue by kloczek** [pypa/virtualenv#2128]
After `setup.py build_sphinx`
```console
+ /usr/bin/python3 setup.py build_sphinx -b man
running build_sphinx
Running Sphinx v4.0.2

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 323, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/virtualenv-20.4.7/docs/conf.py", line 8, in <module>
    from virtualenv.version import __version__
ModuleNotFoundError: No module named 'virtualenv.version'; 'virtualenv' is not a package
```

**Comment by gaborbernat** [comment]
We don't support building docs like that, use tox instead.
