### ISSUE TITLE
Wrong pip version 21.x used when creating virtual env for python2.7

### ISSUE THREAD

**Issue by Michal-Szelag-Sonos** [pypa/virtualenv#2153]
**Issue**

This is a new issue introduced in `16.7.11` that did not exist in `16.7.10`.  While building virtual env for python2.7, it tries to use the wrong version of pip, `21.x`, when installing packages.  I seems that a 21.x wheel appears with the package which may be the cause.

**Environment**

Provide at least:
- OS:  Debian Buster 10 (Ubuntu 18.04)
- ``pip list`` of the host python where ``virtualenv`` is installed:

```console
# pip list
Package            Version
------------------ -----------
attrs              21.2.0
CacheControl       0.12.6
cachy              0.3.0
certifi            2021.5.30
cffi               1.14.6
chardet            4.0.0
cleo               0.7.6
clikit             0.4.3
configparser       4.0.2
contextlib2        0.6.0.post1
cryptography       3.3.2
entrypoints        0.3
enum34             1.1.10
functools32        3.2.3.post2
glob2              0.6
html5lib           1.1
idna               2.10
importlib-metadata 1.1.3
ipaddress          1.0.23
jsonschema         3.2.0
keyring            18.0.1
lockfile           0.12.2
msgpack            1.0.2
pastel             0.2.1
pathlib2           2.3.6
pexpect            4.8.0
pip                20.2.4
pkginfo            1.7.1
poetry             1.0.10
ptyprocess         0.7.0
pycparser          2.20
pylev              1.4.0
pyparsing          2.4.7
pyrsistent         0.14.11
requests           2.26.0
requests-toolbelt  0.8.0
scandir            1.10.0
SecretStorage      2.3.1
setuptools         44.1.1
shellingham        1.4.0
six                1.16.0
subprocess32       3.5.4
tomlkit            0.5.11
typing             3.10.0.0
urllib3            1.26.6
virtualenv         16.7.11
webencodings       0.5.1
zipp               1.2.0
```

**Output of the virtual environment creation**
Note the use of pip 21.1.3 wheel:
```console
# .virtualenv -p python2.7 .venv
Installing Python virtual environment to ././.venv
Remove previous Python's env: ./.venv
Running virtualenv with interpreter /usr/bin/python2.7
Already using interpreter /usr/bin/python2.7
New python executable in /test/python/.venv/bin/python2.7
Also creating executable in /test/python/.venv/bin/python
Command /test/python/.venv/bin/python2.7 -m pip config list had error code 1
Installing setuptools, pip, wheel...

  Complete output from command /test/python/.venv/bin/python2.7 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 15, in <module>
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-21.1.3-py3-none-any.whl/pip/__init__.py", line 1, in <module>
ImportError: No module named typing
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 2644, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 869, in main
    symlink=options.symlink,
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1188, in create_environment
    install_wheel(to_install, py_executable, search_dirs, download=download)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1028, in install_wheel
    _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1125, in _install_wheel_with_search_dir
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=script)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 962, in call_subprocess
    raise OSError("Command {} failed with error code {}".format(cmd_desc, proc.returncode))
OSError: Command /test/python/.venv/bin/python2.7 - setuptools pip wheel failed with error code 1
```

**Comment by gaborbernat** [comment]
Resolved by https://github.com/pypa/virtualenv/commit/4fc39bfe3b91e2cd28e0451b0e1855414fd59ba8
