### ISSUE TITLE
Python 2.7: import virtualenv error: ImportError: No module named entry_points_selectable

### ISSUE THREAD

**Issue by bialix** [pypa/virtualenv#2154]
**Issue**

Virtualenv 20.6.0 does not work on Python 2.7.16 on Linux
Installed with command:

`python2.7 -m pip install virtualenv`

```
tomcat@tomcat:~/$ python2.7
Python 2.7.16 (default, Oct  7 2019, 17:36:04) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import virtualenv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tomcat/.local/lib/python2.7/site-packages/virtualenv/__init__.py", line 3, in <module>
    from .run import cli_run, session_via_cli
  File "/home/tomcat/.local/lib/python2.7/site-packages/virtualenv/run/__init__.py", line 13, in <module>
    from .plugin.activators import ActivationSelector
  File "/home/tomcat/.local/lib/python2.7/site-packages/virtualenv/run/plugin/activators.py", line 6, in <module>
    from .base import ComponentBuilder
  File "/home/tomcat/.local/lib/python2.7/site-packages/virtualenv/run/plugin/base.py", line 5, in <module>
    from backports.entry_points_selectable import entry_points
ImportError: No module named entry_points_selectable
>>>

<module 'backports' from '/usr/lib64/python2.7/site-packages/backports/__init__.pyc'>

```
**Environment**

Provide at least:
- OS: Linux Ubuntu 19.04
- ``pip list`` of the host python where ``virtualenv`` is installed:

 
```
tomcat@tomcat:~/$ python2.7 -m pip list
Package                            Version    
---------------------------------- -----------
alembic                            1.0.6      
asn1crypto                         0.24.0     
backports.entry-points-selectable  1.1.0      
backports.functools-lru-cache      1.5        
backports.shutil-get-terminal-size 1.0.0      
banal                              0.4.2      
beautifulsoup4                     4.7.1      
certifi                            2018.11.29 
chardet                            3.0.4      
configparser                       4.0.2      
contextlib2                        0.6.0.post1
cryptography                       2.3        
dataset                            1.1.0      
decorator                          4.3.0      
distlib                            0.3.2      
entrypoints                        0.3        
enum34                             1.1.6      
filelock                           3.0.12     
idna                               2.8        
importlib-metadata                 2.1.1      
importlib-resources                3.3.1      
ipaddress                          1.0.17     
ipython                            5.8.0      
ipython-genutils                   0.2.0      
keyring                            17.1.1     
keyrings.alt                       3.1.1      
Mako                               1.0.7      
MarkupSafe                         1.1.0      
normality                          1.0.0      
pathlib2                           2.3.3      
pexpect                            4.6.0      
pickleshare                        0.7.5      
pip                                18.1       
platformdirs                       2.0.2      
prompt-toolkit                     1.0.15     
pycrypto                           2.6.1      
Pygments                           2.3.1      
PyGObject                          3.32.0     
PyICU                              2.2        
pyTelegramBotAPI                   3.7.2      
python-dateutil                    2.7.5      
python-editor                      1.0.3      
pyxdg                              0.25       
requests                           2.21.0     
scandir                            1.9.0      
SecretStorage                      2.3.1      
setuptools                         40.8.0     
simplegeneric                      0.8.1      
singledispatch                     3.6.2      
six                                1.12.0     
soupsieve                          1.7.1      
SQLAlchemy                         1.2.16     
traitlets                          4.3.2      
typing                             3.10.0.0   
urllib3                            1.24.1     
virtualenv                         20.6.0     
wcwidth                            0.1.7      
wheel                              0.32.3     
zipp                               1.2.0

```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console

```

Can you please suggest which prev version I should use?

**Comment by gaborbernat** [comment]
How did you install it? Thanks

**Comment by joaodelgado13** [comment]
I had the same problem, try 20.4.7

**Comment by gaborbernat** [comment]
@joaodelgado13 How did you install it? Thanks

**Comment by joaodelgado13** [comment]
pip install virtualenv==20.4.7

**Comment by gaborbernat** [comment]
@joaodelgado13 I meant for the troublesome version, please also attach a detailed installation log of it. With packages installed before and after.

**Comment by joaodelgado13** [comment]
- docker pull debian
- run the container
- apt update
- apt install python-pip
- pip install virtualenv

nothing more

**Comment by pfmoore** [comment]
Doing that, `pip --version` says 18.1. That's pretty old. It provavly doesn't handle markers in dependencies, or `python-requires` metadata, properly. You should bug Debian to provide a newer version of pip. Or a newer version of virtualenv (they package 15.1.0) so you don't have to `pip install` it yourself.

Or upgrade pip as well - but be aware that neither the pip developers nor Debian support doing a `pip install --upgrade pip` as root, so don't do that if you want help when things go wrong...

**Comment by bialix** [comment]
python2.7 -m pip install virtualenv

чт, 22 июл. 2021 г., 18:07 Bernát Gábor ***@***.***>:

**Comment by ThSGM** [comment]
Same issues as everyone else running Debian v10 (Buster) on a Raspberry Pi Zero. Using 

`pip install virtualenv==20.4.7`

fixed it.

**Comment by gaborbernat** [comment]
Seems a pip issue, so closing.
