### ISSUE TITLE
virtualenv not being created in AWS EC2 Ubuntu on Python 3.10

### ISSUE THREAD

**Issue by garvit-joshi** [pypa/virtualenv#2249]
**Issue**

When Creating an environment on AWS EC2 Ubuntu, I get this error ```AttributeError: 'PathDistribution' object has no attribute '_normalized_name'```

**Environment**

Provide at least:
- OS: 20.04.1-Ubuntu
- ``pip list`` of the host python where ``virtualenv`` is installed:
```
ubuntu@ip:~/test$ python3.10 -m pip list
Package                           Version
--------------------------------- --------------------
argcomplete                       1.12.3
attrs                             19.3.0
Automat                           0.8.0
backports.entry-points-selectable 1.1.1
blinker                           1.4
certifi                           2019.11.28
chardet                           3.0.4
Click                             7.0
cloud-init                        21.4
colorama                          0.4.3
command-not-found                 0.3
configobj                         5.0.6
constantly                        15.1.0
cryptography                      2.8
dbus-python                       1.2.16
distlib                           0.3.3
distro                            1.4.0
distro-info                       0.23ubuntu1
ec2-hibinit-agent                 1.0.0
entrypoints                       0.3
filelock                          3.4.0
hibagent                          1.0.1
httplib2                          0.14.0
hyperlink                         19.0.0
idna                              2.8
importlib-metadata                1.5.0
incremental                       16.10.1
Jinja2                            2.10.1
jsonpatch                         1.22
jsonpointer                       2.0
jsonschema                        3.2.0
keyring                           18.0.1
language-selector                 0.1
launchpadlib                      1.10.13
lazr.restfulclient                0.14.2
lazr.uri                          1.0.3
MarkupSafe                        1.1.0
more-itertools                    4.2.0
netifaces                         0.10.4
oauthlib                          3.1.0
packaging                         21.3
pexpect                           4.6.0
pip                               21.3.1
pipx                              0.16.4
platformdirs                      2.4.0
pyasn1                            0.4.2
pyasn1-modules                    0.2.1
PyGObject                         3.36.0
PyHamcrest                        1.9.0
PyJWT                             1.7.1
pymacaroons                       0.13.0
PyNaCl                            1.3.0
pyOpenSSL                         19.0.0
pyparsing                         3.0.6
pyrsistent                        0.15.5
pyserial                          3.4
python-apt                        2.0.0+ubuntu0.20.4.6
python-debian                     0.1.36ubuntu1
PyYAML                            5.3.1
requests                          2.22.0
requests-unixsocket               0.2.0
SecretStorage                     2.3.1
service-identity                  18.1.0
setuptools                        57.4.0
simplejson                        3.16.0
six                               1.14.0
sos                               4.1
ssh-import-id                     5.10
systemd-python                    234
Twisted                           18.9.0
ubuntu-advantage-tools            27.4
ufw                               0.36
unattended-upgrades               0.1
urllib3                           1.25.8
userpath                          1.7.0
virtualenv                        20.10.0
wadllib                           1.3.3
wheel                             0.34.2
zipp                              1.0.0
zope.interface                    4.7.1

```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console
ubuntu@ip:~/test$ python3.10 -m virtualenv env -vvv --with-traceback
141 setup logging to NOTSET [DEBUG report:39]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/virtualenv/__main__.py", line 80, in <module>
    run_with_catch()  # pragma: no cov
  File "/home/ubuntu/.local/lib/python3.10/site-packages/virtualenv/__main__.py", line 65, in run_with_catch
    run(args, options, env)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/virtualenv/__main__.py", line 18, in run
    session = cli_run(args, options, env)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/virtualenv/run/__init__.py", line 30, in cli_run
    of_session = session_via_cli(args, options, setup_logging, env)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/virtualenv/run/__init__.py", line 48, in session_via_cli
    parser, elements = build_parser(args, options, setup_logging, env)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/virtualenv/run/__init__.py", line 69, in build_parser
    discover = get_discover(parser, args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/virtualenv/run/plugin/discovery.py", line 11, in get_discover
    discover_types = Discovery.entry_points_for("virtualenv.discovery")
  File "/home/ubuntu/.local/lib/python3.10/site-packages/virtualenv/run/plugin/base.py", line 14, in entry_points_for
    return OrderedDict((e.name, e.load()) for e in cls.entry_points().select(group=key))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/virtualenv/run/plugin/base.py", line 19, in entry_points
    PluginLoader._ENTRY_POINTS = entry_points()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 971, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 429, in load
    ordered = sorted(eps, key=by_group)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 968, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/usr/lib/python3.10/importlib/metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
AttributeError: 'PathDistribution' object has no attribute '_normalized_name'
```

**Comment by gaborbernat** [comment]
How did you install virtualenv?

**Comment by garvit-joshi** [comment]
First Installed python3.10 through deadsnake's PPA.
Then ```python3.10 -m pip install -U virtualenv```

**Comment by gaborbernat** [comment]
Can you replicate it via a docker image?

**Comment by garvit-joshi** [comment]
Really sorry I have not used docker till date. Will give you a docker image in the coming days.
The issue is reproducible if you have an EC2 Instance, and install deadsnakes PPA for installing Python3.10.
Here is a list of commands that I roughly used.
```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt install python3.10
python3.10 -m pip install -U pip wheel
python3.10 -m pip install -U virtualenv
sudo reboot
virtualenv env
```

**Comment by gaborbernat** [comment]
Sorry, I don't use EC2. :+1:

**Comment by garvit-joshi** [comment]
Will be happy to provide you with an EC2 instance for the day ff you want. We can talk over mail for the details.

**Comment by garvit-joshi** [comment]
Hi, Just Found out: when creating virtualenv as ```virtualenv env``` the environment is created successfully:
```
ubuntu@ip:~/test$ virtualenv env
created virtual environment CPython3.10.1.final.0-64 in 139ms
  creator CPython3Posix(dest=/home/ubuntu/test/env, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/ubuntu/.local/share/virtualenv)
    added seed packages: pip==21.3.1, setuptools==59.2.0, wheel==0.37.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
ubuntu@ip-172-31-1-88:~/test$ source env/bin/activate
(env) ubuntu@ip:~/test$ python3 --version
Python 3.10.1

```
 but when creating with ```python3.10 -m virtualenv env``` it fails with the above message.

**Comment by gaborbernat** [comment]
@garvit-joshi the main difference between those two is that the latter put the CWD on the sys.path. What's the content of your current working directory there?

**Comment by tomwojcik** [comment]
I guess this `backports` thing would have to be upgraded for python 10.

https://github.com/saltstack/salt/pull/61064/files

https://github.com/pypa/pipenv/issues/4883

https://github.com/jaraco/backports.entry_points_selectable/blob/d4b54f47796d0ee86581808bf1f1de27e3c02ec1/backports/entry_points_selectable.py#L271-L273

**Comment by tomwojcik** [comment]
I just run into this myself and it seems it's been fixed 12h ago. 

Python3.10 [changelog](https://docs.python.org/3/whatsnew/3.10.html#importlib-metadata)

> importlib.metadata entry points now provide a nicer experience for selecting entry points by group and name through a new importlib.metadata.EntryPoints class. See the Compatibility Note in the docs for more info on the deprecation and usage.

https://github.com/pypa/virtualenv/commit/bb82a73b6dbf577874f6d4bfaf72d2a7f59dfffe
