### ISSUE TITLE
'site' has no attribute "getsitepackages"

### ISSUE THREAD

**Issue by npinto** [pypa/virtualenv#228]
Any virtualenv, with or without `--system-site-packages`, gives me:

```
% python -c 'import site; site.getsitepackages()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getsitepackages'
```

**Comment by Tset-Noitamotua** [comment]
have this issue with Python 3.6.5
```bash
>> python --version && python -c "import site; print(site.getsitepackages())"
Python 3.6.5
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'site' has no attribute 'getsitepackages'
```

not duplicate of #355
