### ISSUE TITLE
How to recover from broken sync - request for improving error message

### ISSUE THREAD

**Issue by WolfgangFahl** [pypa/virtualenv#2326]
**Issue**

tox runs into downstream virtualenv copy issue.
This happened after the source disk of the snc was full. When disk space was released again the problem persists. The sync does not recover from the problem.The error message is not helpful.

**Environment**

Provide at least:
- OS: Ubuntu 20.04.LTS
- ``pip list`` of the host python where ``virtualenv`` is installed:
```pip list | grep virtualenv
virtualenv                    20.14.0
```

  ```console
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 57, in _install
    installer.install(creator.interpreter.version_info)
  File "/usr/local/lib/python3.9/dist-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 39, in install
    self._sync(filename, into)
  File "/usr/local/lib/python3.9/dist-packages/virtualenv/seed/embed/via_app_data/pip_install/copy.py", line 13, in _sync
    copy(src, dst)
  File "/usr/local/lib/python3.9/dist-packages/virtualenv/util/path/_sync.py", line 52, in copy
    method(norm(src), norm(dest))
  File "/usr/local/lib/python3.9/dist-packages/virtualenv/util/path/_sync.py", line 63, in copytree
    shutil.copy(src_f, dest_f)
  File "/usr/lib/python3.9/shutil.py", line 427, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.9/shutil.py", line 277, in copyfile
    _fastcopy_sendfile(fsrc, fdst)
  File "/usr/lib/python3.9/shutil.py", line 172, in _fastcopy_sendfile
    raise err
  File "/usr/lib/python3.9/shutil.py", line 152, in _fastcopy_sendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
OSError: [Errno 5] Input/output error:

  ```
some obscure file in the wheel/3.9 directory

**Comment by WolfgangFahl** [comment]
as a workaround i had to remove the wheel/3.9 directory

**Comment by gaborbernat** [comment]
> as a workaround i had to remove the wheel/3.9 directory

This is one option, alternatively you can also use https://virtualenv.pypa.io/en/latest/cli_interface.html#reset-app-data
