### ISSUE TITLE
Unable to create a virtualenv: failed to build image setuptools

### ISSUE THREAD

**Issue by keiranmraine** [pypa/virtualenv#2361]
**Issue**

Unable to create a virtualenv with `python3.10 -m virtualenv .venv`.

`-m venv .venv` works to create an environment, but `pre-commit` uses `-m virtualenv` internally.

**Environment**

Provide at least:
- OS: Windows 10 (10.0.19044 Build 19044)
  - Behaviour same under git-bash (in VSCode) and Powershell.
- `pip list` of the host python where `virtualenv` is installed:

```console
Package      Version
------------ -------
cfgv         3.3.1
distlib      0.3.4
filelock     3.7.1
identify     2.5.1
nodeenv      1.6.0
pip          22.1.2
platformdirs 2.5.2
pre-commit   2.19.0
PyYAML       6.0
setuptools   62.3.3
six          1.16.0
toml         0.10.2
virtualenv   20.14.1
```

Path:

```console
/c/Users/XXXX/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/XXXX/bin:/c/windows/system32:/c/windows:/c/windows/System32/Wbem:/c/windows/System32/WindowsPowerShell/v1.0:/c/windows/System32/OpenSSH:/c/Users/XXXX/AppData/Local/Microsoft/WindowsApps:/c/Users/XXXX/AppData/Local/Programs/Microsoft VS Code/bin:/cmd:/usr/bin/vendor_perl:/usr/bin/core_perl:/c/Users/XXXX/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/Scripts
```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console
459 setup logging to NOTSET [DEBUG report:39]
463 find interpreter for spec PythonSpec(path=C:\Users\XXXX\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe) [INFO builtin:62]
464 proposed PythonInfo(spec=CPython3.10.5.final.0-64, exe=C:\Users\XXXX\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe, platform=win32, version='3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]', encoding_fs_io=utf-8-cp1252) [INFO builtin:69]
464 accepted PythonInfo(spec=CPython3.10.5.final.0-64, exe=C:\Users\XXXX\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe, platform=win32, version='3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]', encoding_fs_io=utf-8-cp1252) [DEBUG builtin:71]
466 symlink on filesystem does not work [DEBUG info:48]
466 filesystem is not case-sensitive [DEBUG info:29]
500 create virtual environment via Venv(dest=C:\Users\XXXX\git\test\.venv, clear=False, no_vcs_ignore=False, global=False, describe=CPython3Windows) [INFO session:52]
511 create virtualenv import hook file C:\Users\XXXX\git\test\.venv\Lib\site-packages\_virtualenv.pth [DEBUG api:95]
511 create C:\Users\XXXX\git\test\.venv\Lib\site-packages\_virtualenv.py [DEBUG api:98]
513 ============================== target debug ============================== [DEBUG session:54]
513 debug via 'C:\Users\XXXX\git\test\.venv\Scripts\python.exe' 'C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\create\debug.py' [DEBUG creator:224]
513 {
  "sys": {
    "executable": "C:\\Users\\XXXX\\git\\test\\.venv\\Scripts\\python.exe",
    "_base_executable": "C:\\Users\\XXXX\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\python.exe",
    "prefix": "C:\\Users\\XXXX\\git\\test\\.venv",
    "base_prefix": "C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0",
    "real_prefix": null,
    "exec_prefix": "C:\\Users\\XXXX\\git\\test\\.venv",
    "base_exec_prefix": "C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0",
    "path": [
      "C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\\python310.zip",
      "C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\\DLLs",
      "C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\\lib",
      "C:\\Users\\XXXX\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0",
      "C:\\Users\\XXXX\\git\\test\\.venv",
      "C:\\Users\\XXXX\\git\\test\\.venv\\lib\\site-packages"
    ],
    "meta_path": [
      "<class '_virtualenv._Finder'>",
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib_external.PathFinder'>"
    ],
    "fs_encoding": "utf-8",
    "io_encoding": "cp1252"
  },
  "version": "3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]",
  "makefile_filename": "C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\\Lib\\config\\Makefile",
  "os": "<module 'os' from 'C:\\\\Program Files\\\\WindowsApps\\\\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\\\\lib\\\\os.py'>",
  "site": "<module 'site' from 'C:\\\\Program Files\\\\WindowsApps\\\\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\\\\lib\\\\site.py'>",
  "datetime": "<module 'datetime' from 'C:\\\\Program Files\\\\WindowsApps\\\\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\\\\lib\\\\datetime.py'>",
  "math": "<module 'math' (built-in)>",
  "json": "<module 'json' from 'C:\\\\Program Files\\\\WindowsApps\\\\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\\\\lib\\\\json\\\\__init__.py'>"
} [DEBUG session:55]
661 add seed packages via FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv) [INFO session:59]
666 got embed update of distribution pip from C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\embed\3\pip.json [DEBUG via_disk_folder:135]
666 got embed update of distribution wheel from C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\embed\3\wheel.json [DEBUG via_disk_folder:135]
667 got embed update of distribution setuptools from C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\embed\3\setuptools.json [DEBUG via_disk_folder:135]
670 got embed update of distribution wheel from C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\embed\3\wheel.json [DEBUG via_disk_folder:135]
670 got embed update of distribution setuptools from C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\embed\3\setuptools.json [DEBUG via_disk_folder:135]
671 using periodically updated wheel C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\house\setuptools-62.2.0-py3-none-any.whl [DEBUG periodic_update:53]
671 got embed update of distribution pip from C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\embed\3\pip.json [DEBUG via_disk_folder:135]
671 using periodically updated wheel C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\house\pip-22.1.2-py3-none-any.whl [DEBUG periodic_update:53]
672 install wheel from wheel C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\seed\wheels\embed\wheel-0.37.1-py2.py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:49]
672 install setuptools from wheel C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\house\setuptools-62.2.0-py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:49]
672 install pip from wheel C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\house\pip-22.1.2-py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:49]
673 Attempting to acquire lock 1712874214192 on C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\image\1\CopyPipInstall\setuptools-62.2.0-py3-none-any.lock [DEBUG _api:172]
673 Attempting to acquire lock 1712874210784 on C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\image\1\CopyPipInstall\pip-22.1.2-py3-none-any.lock [DEBUG _api:172]
673 Lock 1712874214192 acquired on C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\image\1\CopyPipInstall\setuptools-62.2.0-py3-none-any.lock [DEBUG _api:176]
674 Lock 1712874210784 acquired on C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\image\1\CopyPipInstall\pip-22.1.2-py3-none-any.lock [DEBUG _api:176]
674 Attempting to release lock 1712874214192 on C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\image\1\CopyPipInstall\setuptools-62.2.0-py3-none-any.lock [DEBUG _api:209]
674 Attempting to acquire lock 1712874214576 on C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\image\1\CopyPipInstall\wheel-0.37.1-py2.py3-none-any.lock [DEBUG _api:172]
674 Attempting to release lock 1712874210784 on C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\image\1\CopyPipInstall\pip-22.1.2-py3-none-any.lock [DEBUG _api:209]
674 Lock 1712874214192 released on C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\image\1\CopyPipInstall\setuptools-62.2.0-py3-none-any.lock [DEBUG _api:212]
674 Lock 1712874210784 released on C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\image\1\CopyPipInstall\pip-22.1.2-py3-none-any.lock [DEBUG _api:212]
674 Lock 1712874214576 acquired on C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\image\1\CopyPipInstall\wheel-0.37.1-py2.py3-none-any.lock [DEBUG _api:176]
675 Attempting to release lock 1712874214576 on C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\image\1\CopyPipInstall\wheel-0.37.1-py2.py3-none-any.lock [DEBUG _api:209]
675 copy C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\image\1\CopyPipInstall\setuptools-62.2.0-py3-none-any\distutils-precedence.pth to C:\Users\XXXX\git\test\.venv\Lib\site-packages\distutils-precedence.pth [DEBUG _sync:51]
675 copy directory C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\image\1\CopyPipInstall\pip-22.1.2-py3-none-any\pip to C:\Users\XXXX\git\test\.venv\Lib\site-packages\pip [DEBUG _sync:51]
675 Lock 1712874214576 released on C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\image\1\CopyPipInstall\wheel-0.37.1-py2.py3-none-any.lock [DEBUG _api:212]
676 copy directory C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\image\1\CopyPipInstall\wheel-0.37.1-py2.py3-none-any\wheel to C:\Users\XXXX\git\test\.venv\Lib\site-packages\wheel [DEBUG _sync:51]
676 copy directory C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\image\1\CopyPipInstall\setuptools-62.2.0-py3-none-any\pkg_resources to C:\Users\XXXX\git\test\.venv\Lib\site-packages\pkg_resources [DEBUG _sync:51]
691 copy directory C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\image\1\CopyPipInstall\wheel-0.37.1-py2.py3-none-any\wheel-0.37.1.dist-info to C:\Users\XXXX\git\test\.venv\Lib\site-packages\wheel-0.37.1.dist-info [DEBUG _sync:51]
697 copy C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\image\1\CopyPipInstall\wheel-0.37.1-py2.py3-none-any\wheel-0.37.1.virtualenv to C:\Users\XXXX\git\test\.venv\Lib\site-packages\wheel-0.37.1.virtualenv [DEBUG _sync:51]
702 generated console scripts wheel3.exe wheel3.10.exe wheel.exe wheel-3.10.exe [DEBUG base:45]
707 copy directory C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\image\1\CopyPipInstall\setuptools-62.2.0-py3-none-any\setuptools to C:\Users\XXXX\git\test\.venv\Lib\site-packages\setuptools [DEBUG _sync:51]
1082 copy directory C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\image\1\CopyPipInstall\pip-22.1.2-py3-none-any\pip-22.1.2.dist-info to C:\Users\XXXX\git\test\.venv\Lib\site-packages\pip-22.1.2.dist-info [DEBUG _sync:51]
1087 copy C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\image\1\CopyPipInstall\pip-22.1.2-py3-none-any\pip-22.1.2.virtualenv to C:\Users\XXXX\git\test\.venv\Lib\site-packages\pip-22.1.2.virtualenv [DEBUG _sync:51]
1091 generated console scripts pip3.exe pip.exe pip3.10.exe pip-3.10.exe [DEBUG base:45]
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\__main__.py", line 80, in <module>
    run_with_catch()  # pragma: no cov
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\__main__.py", line 65, in run_with_catch
    run(args, options, env)
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\__main__.py", line 18, in run
    session = cli_run(args, options, env)
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\run\__init__.py", line 32, in cli_run
    of_session.run()
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\run\session.py", line 47, in run
    self._seed()
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\run\session.py", line 60, in _seed
    self.seeder.run(self.creator)
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\seed\embed\via_app_data\via_app_data.py", line 71, in run
    raise RuntimeError("\n".join(messages))
RuntimeError: failed to build image setuptools because:
Traceback (most recent call last):
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\seed\embed\via_app_data\via_app_data.py", line 57, in _install
    installer.install(creator.interpreter.version_info)
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 39, in install
    self._sync(filename, into)
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\seed\embed\via_app_data\pip_install\copy.py", line 13, in _sync
    copy(src, dst)
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\util\path\_sync.py", line 52, in copy
    method(norm(src), norm(dest))
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\util\path\_sync.py", line 63, in copytree
    shutil.copy(src_f, dest_f)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\XXXX\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\Local\\pypa\\virtualenv\\wheel\\3.10\\image\\1\\CopyPipInstall\\setuptools-62.2.0-py3-none-any\\setuptools\\config\\_validate_pyproject\\extra_validations.py'
```

**Comment by gaborbernat** [comment]
I think this is no longer valid.

**Comment by dimbleby** [comment]
> I think this is no longer valid

On what grounds, I wonder?

Probably duplicate #1769 though
