### ISSUE TITLE
"RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.11'" (Python 3.11 is installed)

### ISSUE THREAD

**Issue by rehypothecation** [pypa/virtualenv#2376]
**Issue**

I have installed Python 3.11 on a new Linux Mint installation via deadsnakes. When I run:

```
virtualenv env --python=python3.11
```

I get an error:

```
RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.11'
```

Virtualenv is able to locate and create a virtual environment for the system Python version. 

Here are my Python versions:

```
> ls /usr/bin/python*

/usr/bin/python3     /usr/bin/python3.11  /usr/bin/python3.8-config
/usr/bin/python3.10  /usr/bin/python3.8   /usr/bin/python3-config
```

**Environment**

Provide at least:
- OS: Linux Mint 20.3.
- ``pip list`` of the host python where ``virtualenv`` is installed:

  ```console

Package               Version
--------------------- --------------------
appdirs               1.4.3
apt-clone             0.2.1
apturl                0.5.2
astroid               2.11.6
beautifulsoup4        4.8.2
blinker               1.4
blis                  0.7.8
Brlapi                0.7.0
catalogue             2.0.7
certifi               2019.11.28
chardet               3.0.4
click                 8.1.3
colorama              0.4.3
command-not-found     0.3
configobj             5.0.6
cryptography          2.8
cupshelpers           1.0
cymem                 2.0.6
dbus-python           1.2.16
defer                 1.0.6
dill                  0.3.5.1
distlib               0.3.4
distro                1.4.0
entrypoints           0.3
filelock              3.7.1
grpcio                1.16.1
httplib2              0.14.0
idna                  2.8
ifaddr                0.1.6
IMDbPY                6.8
importlib-metadata    1.5.0
isort                 5.10.1
Jinja2                3.1.2
keyring               18.0.1
langcodes             3.3.0
launchpadlib          1.10.13
lazr.restfulclient    0.14.2
lazr.uri              1.0.3
lazy-object-proxy     1.7.1
louis                 3.12.0
macaroonbakery        1.3.1
Mako                  1.1.0
MarkupSafe            2.1.1
mccabe                0.7.0
more-itertools        4.2.0
murmurhash            1.0.7
nemo-emblems          5.2.0
netaddr               0.7.19
netifaces             0.10.4
numpy                 1.23.0
oauthlib              3.1.0
onboard               1.4.1
packaging             20.3
PAM                   0.4.2
pathy                 0.6.2
pexpect               4.6.0
Pillow                7.0.0
pip                   22.1.2
pipenv                2022.7.4
platformdirs          2.5.2
preshed               3.0.6
protobuf              3.6.1
psutil                5.5.1
pycairo               1.16.2
pycrypto              2.6.1
pycups                1.9.73
pycurl                7.43.0.2
pydantic              1.8.2
PyGObject             3.36.0
PyICU                 2.4.2
pyinotify             0.9.6
PyJWT                 1.7.1
pylint                2.14.4
pymacaroons           0.13.0
PyNaCl                1.3.0
pyparsing             2.4.6
pyparted              3.11.2
pyRFC3339             1.1
python-apt            2.0.0+ubuntu0.20.4.7
python-debian         0.1.36ubuntu1
python-magic          0.4.16
python-xapp           2.2.1
python-xlib           0.23
pytz                  2019.3
pyxdg                 0.26
PyYAML                5.3.1
reportlab             3.5.34
requests              2.22.0
requests-file         1.4.3
requests-unixsocket   0.2.0
SecretStorage         2.3.1
setproctitle          1.1.10
setuptools            45.2.0
simplejson            3.16.0
six                   1.14.0
smart-open            5.2.1
soupsieve             1.9.5
spacy                 3.3.1
spacy-legacy          3.0.9
spacy-loggers         1.0.2
srsly                 2.4.3
systemd-python        234
thinc                 8.0.17
tinycss2              1.0.2
tldextract            2.2.1
tomli                 2.0.1
tomlkit               0.11.1
tqdm                  4.64.0
typer                 0.4.2
typing_extensions     4.3.0
ubuntu-drivers-common 0.0.0
ufw                   0.36
Unidecode             1.1.1
urllib3               1.25.8
virtualenv            20.0.17
virtualenv-clone      0.5.7
wadllib               1.3.3
wasabi                0.9.1
webencodings          0.5.1
wheel                 0.34.2
wrapt                 1.14.1
xkit                  0.0.0
xlrd                  1.1.0
youtube-dl            2021.4.26
zipp                  1.0.0


  ```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console
> virtualenv env --python=python3.11 -vvv --with-traceback
14 setup logging to NOTSET [DEBUG report:43]
25 find interpreter for spec PythonSpec(implementation=CPython, major=3, minor=11) [INFO builtin:44]
25 proposed PythonInfo(spec=CPython3.8.10.final.0-64, exe=/usr/bin/python3, platform=linux, version='3.8.10 (default, Mar 15 2022, 12:22:08) \n[GCC 9.4.0]', encoding_fs_io=utf-8-utf-8) [INFO builtin:50]
25 discover PATH[0]=/home/user/.local/bin [DEBUG builtin:84]
33 filesystem is case-sensitive [DEBUG info:28]
33 discover PATH[1]=/usr/local/sbin [DEBUG builtin:84]
33 discover PATH[2]=/usr/local/bin [DEBUG builtin:84]
34 discover PATH[3]=/usr/sbin [DEBUG builtin:84]
34 discover PATH[4]=/usr/bin [DEBUG builtin:84]
34 Attempting to acquire lock 140612371409888 on /home/user/.local/share/virtualenv/py_info/20.0.17/ca3ed784184f1b3bb7c3539bfb45e71710cd27667424f92c2d5bb4df9c107c23.lock [DEBUG _api:172]
34 Lock 140612371409888 acquired on /home/user/.local/share/virtualenv/py_info/20.0.17/ca3ed784184f1b3bb7c3539bfb45e71710cd27667424f92c2d5bb4df9c107c23.lock [DEBUG _api:176]
34 get interpreter info via cmd: /usr/bin/python3.11 /usr/lib/python3/dist-packages/virtualenv/discovery/py_info.py [DEBUG cached_py_info:108]
61 Attempting to release lock 140612371409888 on /home/user/.local/share/virtualenv/py_info/20.0.17/ca3ed784184f1b3bb7c3539bfb45e71710cd27667424f92c2d5bb4df9c107c23.lock [DEBUG _api:209]
61 Lock 140612371409888 released on /home/user/.local/share/virtualenv/py_info/20.0.17/ca3ed784184f1b3bb7c3539bfb45e71710cd27667424f92c2d5bb4df9c107c23.lock [DEBUG _api:212]
61 failed to query /usr/bin/python3.11 with code 1 err: '/usr/lib/python3/dist-packages/virtualenv/discovery/py_info.py:16: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives\n  from distutils.command.install import SCHEME_KEYS\nTraceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/virtualenv/discovery/py_info.py", line 16, in <module>\n    from distutils.command.install import SCHEME_KEYS\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nModuleNotFoundError: No module named \'distutils.command\'\n' [INFO cached_py_info:37]
61 discover PATH[5]=/sbin [DEBUG builtin:84]
61 discover PATH[6]=/bin [DEBUG builtin:84]
61 Attempting to acquire lock 140612371408688 on /home/user/.local/share/virtualenv/py_info/20.0.17/ead1b95f633dc9c51826328e1846203f51a198c6fb5f2884a80417ba131d4e82.lock [DEBUG _api:172]
61 Lock 140612371408688 acquired on /home/user/.local/share/virtualenv/py_info/20.0.17/ead1b95f633dc9c51826328e1846203f51a198c6fb5f2884a80417ba131d4e82.lock [DEBUG _api:176]
61 get interpreter info via cmd: /bin/python3.11 /usr/lib/python3/dist-packages/virtualenv/discovery/py_info.py [DEBUG cached_py_info:108]
86 Attempting to release lock 140612371408688 on /home/user/.local/share/virtualenv/py_info/20.0.17/ead1b95f633dc9c51826328e1846203f51a198c6fb5f2884a80417ba131d4e82.lock [DEBUG _api:209]
86 Lock 140612371408688 released on /home/user/.local/share/virtualenv/py_info/20.0.17/ead1b95f633dc9c51826328e1846203f51a198c6fb5f2884a80417ba131d4e82.lock [DEBUG _api:212]
86 failed to query /bin/python3.11 with code 1 err: '/usr/lib/python3/dist-packages/virtualenv/discovery/py_info.py:16: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives\n  from distutils.command.install import SCHEME_KEYS\nTraceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/virtualenv/discovery/py_info.py", line 16, in <module>\n    from distutils.command.install import SCHEME_KEYS\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nModuleNotFoundError: No module named \'distutils.command\'\n' [INFO cached_py_info:37]
86 Attempting to acquire lock 140612371407632 on /home/user/.local/share/virtualenv/py_info/20.0.17/916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1.lock [DEBUG _api:172]
87 Lock 140612371407632 acquired on /home/user/.local/share/virtualenv/py_info/20.0.17/916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1.lock [DEBUG _api:176]
87 get PythonInfo from /home/user/.local/share/virtualenv/py_info/20.0.17/916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1.json for /bin/python3 [DEBUG cached_py_info:79]
87 Attempting to release lock 140612371407632 on /home/user/.local/share/virtualenv/py_info/20.0.17/916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1.lock [DEBUG _api:209]
87 Lock 140612371407632 released on /home/user/.local/share/virtualenv/py_info/20.0.17/916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1.lock [DEBUG _api:212]
87 proposed PathPythonInfo(spec=CPython3.8.10.final.0-64, exe=/bin/python3, platform=linux, version='3.8.10 (default, Mar 15 2022, 12:22:08) \n[GCC 9.4.0]', encoding_fs_io=utf-8-utf-8) [INFO builtin:50]
87 discover PATH[7]=/usr/games [DEBUG builtin:84]
87 discover PATH[8]=/usr/local/games [DEBUG builtin:84]
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 11, in <module>
    load_entry_point('virtualenv==20.0.17', 'console_scripts', 'virtualenv')()
  File "/usr/lib/python3/dist-packages/virtualenv/__main__.py", line 51, in run_with_catch
    run(args, options)
  File "/usr/lib/python3/dist-packages/virtualenv/__main__.py", line 20, in run
    session = cli_run(args, options)
  File "/usr/lib/python3/dist-packages/virtualenv/run/__init__.py", line 27, in cli_run
    session = session_via_cli(args, options)
  File "/usr/lib/python3/dist-packages/virtualenv/run/__init__.py", line 35, in session_via_cli
    parser = build_parser(args, options)
  File "/usr/lib/python3/dist-packages/virtualenv/run/__init__.py", line 73, in build_parser
    raise RuntimeError("failed to find interpreter for {}".format(discover))
RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.11'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_virtualenv.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 11, in <module>
    load_entry_point('virtualenv==20.0.17', 'console_scripts', 'virtualenv')()
  File "/usr/lib/python3/dist-packages/virtualenv/__main__.py", line 51, in run_with_catch
    run(args, options)
  File "/usr/lib/python3/dist-packages/virtualenv/__main__.py", line 20, in run
    session = cli_run(args, options)
  File "/usr/lib/python3/dist-packages/virtualenv/run/__init__.py", line 27, in cli_run
    session = session_via_cli(args, options)
  File "/usr/lib/python3/dist-packages/virtualenv/run/__init__.py", line 35, in session_via_cli
    parser = build_parser(args, options)
  File "/usr/lib/python3/dist-packages/virtualenv/run/__init__.py", line 73, in build_parser
    raise RuntimeError("failed to find interpreter for {}".format(discover))
RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.11'
user@user:~$

```

**Comment by rehypothecation** [comment]
Fixed by running:

```
apt install python3.11-venv
```

which installed:

```
Unpacking python3.11-venv (3.11.0~b3-1+focal1) ...
Setting up python3.11-lib2to3 (3.11.0~b3-1+focal1) ...
Setting up python3.11-distutils (3.11.0~b3-1+focal1) ...
Setting up python3.11-venv (3.11.0~b3-1+focal1) ...
```

I don't know why this worked. Maybe virtualenv needed distutils?
