### ISSUE TITLE
tox broken with "ImportError: cannot import name '_split_env' from 'tox.config'"

### ISSUE THREAD

**Issue by deepaksibm** [pypa/virtualenv#2471]
**Issue**

Getting import error in virtualenv when i run tox command
**Environment**
py3.9, 3.8, 3.7
Provide at least:

- OS:
- `pip list` of the host python where `virtualenv` is installed:

  ```console

  ```

**Output of the virtual environment creation**
```

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.9.15/bin/tox", line 8, in <module>
    sys.exit(run())
  File "/home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages/tox/run.py", line 19, in run
    result = main(sys.argv[1:] if args is None else args)
  File "/home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages/tox/run.py", line 38, in main
    state = setup_state(args)
  File "/home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages/tox/run.py", line 53, in setup_state
    options = get_options(*args)
  File "/home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages/tox/config/cli/parse.py", line 38, in get_options
    guess_verbosity, log_handler, source = _get_base(args)
  File "/home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages/tox/config/cli/parse.py", line 61, in _get_base
    MANAGER.load_plugins(source.path)
  File "/home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages/tox/plugin/manager.py", line 90, in load_plugins
    self._register_plugins(inline)
  File "/home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages/tox/plugin/manager.py", line 38, in _register_plugins
    self.manager.load_setuptools_entrypoints(NAME)
  File "/home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "/opt/python/3.9.15/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages/tox_travis/hooks.py", line 6, in <module>
    from .envlist import (
  File "/home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages/tox_travis/envlist.py", line 10, in <module>
    from tox.config import _split_env as split_env
ImportError: cannot import name '_split_env' from 'tox.config' (/home/travis/virtualenv/python3.9.15/lib/python3.9/site-packages/tox/config/__init__.py)
The command "tox" exited with 1.
```
Make sure to run the creation with `-vvv --with-traceback`:

```console

```

**Comment by gaborbernat** [comment]
Lacking pip list from template and seems a tox error, not virtualenv.
