### ISSUE TITLE
Interpreter discovery fails with KeyError for unavailable plugins when setting through VIRTUALENV_DISCOVERY

### ISSUE THREAD

**Issue by faph** [pypa/virtualenv#2483]
**Issue**

When a user set the OS environment variable `VIRTUALENV_DISCOVERY` to some value, `virtualenv` commands might fail if a corresponding `virtualenv.discovery` plugin is not installed. It raises a simple `KeyError`.

I wouldn't expect an OS env var setting to be raising a critical failure like that. Users might have various needs to set some "default"/system-wide OS environments. They could have a virtualenv plugin installed in say, the system's default Python environment, without such a plugin being absolutely available all the time everywhere.

Would it be acceptable for the discovery mechanism to fall back to the built-in mechanism when the env var contains an unknown value?

**Environment**

- OS: Windows
- Virtualenv version: 20.17.1

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console
$ set VIRTUALENV_DISCOVERY=abc
$ virtualenv tmpenv
KeyError: 'abc'
```

Detailed:

```console
$ virtualenv tmpenv -vvv --with-traceback
175 setup logging to NOTSET [DEBUG report:35]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "<edited>\python3.11\latest\Scripts\virtualenv.exe\__main__.py", line 7, in <module>
  File "<edited>\python3.11\latest\Lib\site-packages\virtualenv\__main__.py", line 54, in run_with_catch
    run(args, options, env)
  File "<edited>\python3.11\latest\Lib\site-packages\virtualenv\__main__.py", line 16, in run
    session = cli_run(args, options, env)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<edited>\python3.11\latest\Lib\site-packages\virtualenv\run\__init__.py", line 28, in cli_run
    of_session = session_via_cli(args, options, setup_logging, env)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<edited>\python3.11\latest\Lib\site-packages\virtualenv\run\__init__.py", line 46, in session_via_cli
    parser, elements = build_parser(args, options, setup_logging, env)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<edited>\python3.11\latest\Lib\site-packages\virtualenv\run\__init__.py", line 67, in build_parser
    discover = get_discover(parser, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<edited>\python3.11\latest\Lib\site-packages\virtualenv\run\plugin\discovery.py", line 25, in get_discover
    discover_class = discover_types[options.discovery]
                     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'abc'
```

**Comment by MarcinKonowalczyk** [comment]
@gaborbernat, Have just run into this too. All in all I agree that this is an expected behaviour. Maybe something like the following, though, would make the error a tiny bit more informative??

```
diff --git a/src/virtualenv/run/plugin/discovery.py b/src/virtualenv/run/plugin/discovery.py
index a963042..d789dbb 100644
--- a/src/virtualenv/run/plugin/discovery.py
+++ b/src/virtualenv/run/plugin/discovery.py
@@ -24,7 +24,9 @@ def get_discover(parser, args):
         help="interpreter discovery method",
     )
     options, _ = parser.parse_known_args(args)
-    discover_class = discover_types[options.discovery]
+    discover_class = discover_types.get(options.discovery, None)
+    if discover_class is None:
+        raise ValueError(f"virtualenv discovery type '{options.discovery}' not found, available: {', '.join(discover_types)}")
     discover_class.add_parser_arguments(discovery_parser)
     options, _ = parser.parse_known_args(args, namespace=options)
     return discover_class(options)
```

At the very lest it points the user towards the fact that it's something to do with discovery.

For context; I've run into this because I've had `VIRTUALENV_DISCOVERY=pyenv` but it was discovered as `builtin`. This may be my error though. I'm unsure whether this is [pyenv](https://github.com/pyenv/pyenv)'s work or leftover from some ancient installation and different way of doing things. pyenv seems to work fine even if I unset it. It was also quite confusing for me since virtualenv was being called by pre-commit so I had to dig a bit to find it. Anyway, the point is that it can happen in the wild, and without any purposeful misconfiguration.
