### ISSUE TITLE
All virtualenv commands failing with TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by NicerNewerCar** [pypa/virtualenv#2541]
**Issue**
All commands are failing with the error `TypeError: expected string or bytes-like object`

```bash
$ virtualenv --version
Traceback (most recent call last):
  File "C:\Users\anthony.lombardi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\anthony.lombardi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\anthony.lombardi\AppData\Local\Programs\Python\Python310\Scripts\virtualenv.exe\__main__.py", line 4, in <module>
  File "C:\Users\anthony.lombardi\AppData\Local\Programs\Python\Python310\lib\site-packages\virtualenv\__init__.py", line 1, in <module>
    from .run import cli_run, session_via_cli
  File "C:\Users\anthony.lombardi\AppData\Local\Programs\Python\Python310\lib\site-packages\virtualenv\run\__init__.py", line 12, in <module>
    from .plugin.creators import CreatorSelector
  File "C:\Users\anthony.lombardi\AppData\Local\Programs\Python\Python310\lib\site-packages\virtualenv\run\plugin\creators.py", line 4, in <module>
    from virtualenv.create.via_global_ref.builtin.builtin_way import VirtualenvBuiltin
  File "C:\Users\anthony.lombardi\AppData\Local\Programs\Python\Python310\lib\site-packages\virtualenv\create\via_global_ref\builtin\builtin_way.py", line 3, in <module>
    from virtualenv.create.creator import Creator
  File "C:\Users\anthony.lombardi\AppData\Local\Programs\Python\Python310\lib\site-packages\virtualenv\create\creator.py", line 11, in <module>
    from virtualenv.discovery.cached_py_info import LogCmd
  File "C:\Users\anthony.lombardi\AppData\Local\Programs\Python\Python310\lib\site-packages\virtualenv\discovery\cached_py_info.py", line 23, in <module>
    _CACHE[Path(sys.executable)] = PythonInfo()
  File "C:\Users\anthony.lombardi\AppData\Local\Programs\Python\Python310\lib\site-packages\virtualenv\discovery\py_info.py", line 103, in __init__
    self.distutils_install = {u(k): u(v) for k, v in self._distutils_install().items()}
  File "C:\Users\anthony.lombardi\AppData\Local\Programs\Python\Python310\lib\site-packages\virtualenv\discovery\py_info.py", line 186, in _distutils_install
    d = dist.Distribution({"script_args": "--no-user-cfg"})  # conf files not parsed so they do not hijack paths
  File "C:\Users\anthony.lombardi\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 486, in __init__
    for ep in metadata.entry_points(group='distutils.setup_keywords'):
  File "C:\Users\anthony.lombardi\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 1009, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "C:\Users\anthony.lombardi\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 459, in load
    ordered = sorted(eps, key=by_group)
  File "C:\Users\anthony.lombardi\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 1006, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "C:\Users\anthony.lombardi\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\_itertools.py", line 16, in unique_everseen
    k = key(element)
  File "C:\Users\anthony.lombardi\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 941, in _normalized_name
    return self._name_from_stem(stem) or super()._normalized_name
  File "C:\Users\anthony.lombardi\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 622, in _normalized_name
    return Prepared.normalize(self.name)
  File "C:\Users\anthony.lombardi\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 871, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
  File "C:\Users\anthony.lombardi\AppData\Local\Programs\Python\Python310\lib\re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

**Environment**

Provide at least:

- OS: Windows 11
- Python: 3.10.5
- `pip list` of the host python where `virtualenv` is installed:

```console
Package         Version
--------------- -------
argcomplete     3.0.5
black           23.3.0
cfgv            3.3.1
click           8.1.3
colorama        0.4.6
distlib         0.3.6
filelock        3.11.0
identify        2.5.22
mypy-extensions 1.0.0
nodeenv         1.7.0
numpy           1.24.2
packaging       23.0
pandas          2.0.0
pathspec        0.11.1
pip             23.0.1
pipx            1.2.0
platformdirs    3.2.0
pre-commit      3.2.2
python-dateutil 2.8.2
pytz            2023.3
PyYAML          6.0
setuptools      67.6.1
six             1.16.0
tomli           2.0.1
tzdata          2023.3
userpath        1.8.0
virtualenv      20.21.0
```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console
N/A
```

**Comment by gaborbernat** [comment]
As the stack shows the error does not come from virtualenv but from distutils/importlib.metadata

**Comment by esatterwhite** [comment]
I have this same thing happening on python3.11. I can't even execute `--help`. My error stack is a little different

```txl
Traceback (most recent call last):
  File "/home/esatterwhite/.local/bin/virtualenv", line 33, in <module>
    sys.exit(load_entry_point('virtualenv==20.11.0', 'console_scripts', 'virtualenv')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/virtualenv/__main__.py", line 54, in run_with_catch
    run(args, options, env)
  File "/usr/lib/python3.11/site-packages/virtualenv/__main__.py", line 16, in run
    session = cli_run(args, options, env)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/virtualenv/run/__init__.py", line 28, in cli_run
    of_session = session_via_cli(args, options, setup_logging, env)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/virtualenv/run/__init__.py", line 46, in session_via_cli
    parser, elements = build_parser(args, options, setup_logging, env)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/virtualenv/run/__init__.py", line 67, in build_parser
    discover = get_discover(parser, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/virtualenv/run/plugin/discovery.py", line 9, in get_discover
    discover_types = Discovery.entry_points_for("virtualenv.discovery")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/virtualenv/run/plugin/base.py", line 21, in entry_points_for
    return OrderedDict((e.name, e.load()) for e in cls.entry_points().select(group=key))
                                                   ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/virtualenv/run/plugin/base.py", line 28, in entry_points
    PluginLoader._ENTRY_POINTS = entry_points()
                                 ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 1040, in entry_points
    return SelectableGroups.load(eps).select(**params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 476, in load
    ordered = sorted(eps, key=by_group)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 1037, in <genexpr>
    eps = itertools.chain.from_iterable(
                                       ^
  File "/usr/lib/python3.11/importlib/metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
        ^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 954, in _normalized_name
    or super()._normalized_name
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 627, in _normalized_name
    return Prepared.normalize(self.name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 882, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
```
What do I do with this?

**Comment by NicerNewerCar** [comment]
> I have this same thing happening on python3.11. I can't even execute `--help`. My error stack is a little different
> 
> What do I do with this?

The issue I ran into was related to a broken package being installed. If I remember correctly the package was missing a name for me. Good luck!
