### ISSUE TITLE
virtualenv 20.22.0 fails to find python3.6

### ISSUE THREAD

**Issue by ap-wtioit** [pypa/virtualenv#2550]
**Issue**

Running `virtualenv -p python3.6 .test` on a system (docker image from ubuntu:20.04) with python3.8 and python3.6 installed fails with 20.22.0 and works with 20.21.1.

**Environment**

Provide at least:

- OS: ubuntu:20.04 (docker image)
- `pip list` of the host python where `virtualenv` is installed:

```console
#12 [ 8/12] RUN pip list
#12 0.531 Package             Version             
#12 0.531 ------------------- --------------------
#12 0.531 certifi             2019.11.28          
#12 0.531 chardet             3.0.4               
#12 0.531 dbus-python         1.2.16              
#12 0.531 distlib             0.3.6               
#12 0.531 distro-info         0.23ubuntu1         
#12 0.531 filelock            3.12.0              
#12 0.531 idna                2.8                 
#12 0.531 pip                 20.0.2              
#12 0.531 platformdirs        3.2.0               
#12 0.531 PyGObject           3.36.0              
#12 0.531 python-apt          2.0.1+ubuntu0.20.4.1
#12 0.531 requests            2.22.0              
#12 0.531 requests-unixsocket 0.2.0               
#12 0.531 setuptools          45.2.0              
#12 0.531 six                 1.14.0              
#12 0.531 unattended-upgrades 0.1                 
#12 0.531 urllib3             1.25.8              
#12 0.531 virtualenv          20.22.0             
#12 0.531 wheel               0.34.2              
#12 DONE 0.6s
```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console
#13 [ 9/12] RUN virtualenv -vvv --with-traceback -p python3.6 .test
#13 0.375 28 setup logging to NOTSET [DEBUG report:37]
#13 0.375 28 created app data folder /root/.local/share/virtualenv [DEBUG __init__:42]
#13 0.377 30 find interpreter for spec PythonSpec(major=3, minor=6) [INFO builtin:58]
#13 0.377 30 proposed PythonInfo(spec=CPython3.8.10.final.0-64, exe=/usr/bin/python3, platform=linux, version='3.8.10 (default, Mar 13 2023, 10:26:41) \n[GCC 9.4.0]', encoding_fs_io=utf-8-utf-8) [INFO builtin:65]
#13 0.377 30 discover PATH[0]=/home/oca-precommit/.local/bin [DEBUG builtin:110]
#13 0.377 30 discover PATH[1]=/usr/local/sbin [DEBUG builtin:110]
#13 0.377 30 discover PATH[2]=/usr/local/bin [DEBUG builtin:110]
#13 0.377 30 discover PATH[3]=/usr/sbin [DEBUG builtin:110]
#13 0.377 30 discover PATH[4]=/usr/bin [DEBUG builtin:110]
#13 0.378 31 Attempting to acquire lock 140230947818416 on /root/.local/share/virtualenv/py_info/1/30295c5bec572e859485b1ffa5e89b8b3e2022ef6e3e739c1ac40f143a557caf.lock [DEBUG _api:216]
#13 0.378 31 Lock 140230947818416 acquired on /root/.local/share/virtualenv/py_info/1/30295c5bec572e859485b1ffa5e89b8b3e2022ef6e3e739c1ac40f143a557caf.lock [DEBUG _api:219]
#13 0.378 31 get interpreter info via cmd: /usr/bin/python3.6 /usr/local/lib/python3.8/dist-packages/virtualenv/discovery/py_info.py 9R42V6NfsmRzxTJMm8tE99IbHaPlxRVX TD9YCYa0yPmspqgQafYGoK14law59JpD [DEBUG cached_py_info:110]
#13 0.385 38 Attempting to release lock 140230947818416 on /root/.local/share/virtualenv/py_info/1/30295c5bec572e859485b1ffa5e89b8b3e2022ef6e3e739c1ac40f143a557caf.lock [DEBUG _api:249]
#13 0.385 38 Lock 140230947818416 released on /root/.local/share/virtualenv/py_info/1/30295c5bec572e859485b1ffa5e89b8b3e2022ef6e3e739c1ac40f143a557caf.lock [DEBUG _api:252]
#13 0.385 38 failed to query /usr/bin/python3.6 with code 1 err: '  File "/usr/local/lib/python3.8/dist-packages/virtualenv/discovery/py_info.py", line 7\n    from __future__ import annotations\n    ^\nSyntaxError: future feature annotations is not defined\n' [INFO cached_py_info:35]
#13 0.386 38 discover PATH[5]=/sbin [DEBUG builtin:110]
#13 0.386 39 discover PATH[6]=/bin [DEBUG builtin:110]
#13 0.386 39 Attempting to acquire lock 140230947817984 on /root/.local/share/virtualenv/py_info/1/db0f6cbdde3eb805f0a229b988d6bd72d452c42e640dd9958b4355934ec01bf5.lock [DEBUG _api:216]
#13 0.386 39 Lock 140230947817984 acquired on /root/.local/share/virtualenv/py_info/1/db0f6cbdde3eb805f0a229b988d6bd72d452c42e640dd9958b4355934ec01bf5.lock [DEBUG _api:219]
#13 0.386 39 get interpreter info via cmd: /bin/python3.6 /usr/local/lib/python3.8/dist-packages/virtualenv/discovery/py_info.py fgqtsryQTzppGJHM2OASvVf9KKA7FOCJ ojKGnJElArXXRZbz4KrMNhfzBIYG4hoH [DEBUG cached_py_info:110]
#13 0.393 46 Attempting to release lock 140230947817984 on /root/.local/share/virtualenv/py_info/1/db0f6cbdde3eb805f0a229b988d6bd72d452c42e640dd9958b4355934ec01bf5.lock [DEBUG _api:249]
#13 0.393 46 Lock 140230947817984 released on /root/.local/share/virtualenv/py_info/1/db0f6cbdde3eb805f0a229b988d6bd72d452c42e640dd9958b4355934ec01bf5.lock [DEBUG _api:252]
#13 0.393 46 failed to query /bin/python3.6 with code 1 err: '  File "/usr/local/lib/python3.8/dist-packages/virtualenv/discovery/py_info.py", line 7\n    from __future__ import annotations\n    ^\nSyntaxError: future feature annotations is not defined\n' [INFO cached_py_info:35]
#13 0.393 46 Attempting to acquire lock 140230947815920 on /root/.local/share/virtualenv/py_info/1/916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1.lock [DEBUG _api:216]
#13 0.393 46 Lock 140230947815920 acquired on /root/.local/share/virtualenv/py_info/1/916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1.lock [DEBUG _api:219]
#13 0.393 46 get interpreter info via cmd: /bin/python3 /usr/local/lib/python3.8/dist-packages/virtualenv/discovery/py_info.py 9HJQZnr8HseVGegBWlUccfWRA2pU0g0C YVajrjdFEfkguZGufH9Nib8K2VAkZMg0 [DEBUG cached_py_info:110]
#13 0.419 72 wrote python info of /bin/python3 at /root/.local/share/virtualenv/py_info/1/916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1.json [DEBUG via_disk_folder:157]
#13 0.419 72 Attempting to release lock 140230947815920 on /root/.local/share/virtualenv/py_info/1/916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1.lock [DEBUG _api:249]
#13 0.419 72 Lock 140230947815920 released on /root/.local/share/virtualenv/py_info/1/916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1.lock [DEBUG _api:252]
#13 0.419 72 proposed PathPythonInfo(spec=CPython3.8.10.final.0-64, exe=/bin/python3, platform=linux, version='3.8.10 (default, Mar 13 2023, 10:26:41) \n[GCC 9.4.0]', encoding_fs_io=utf-8-utf-8) [INFO builtin:65]
#13 0.419 Traceback (most recent call last):
#13 0.419   File "/home/oca-precommit/.local/bin/virtualenv", line 8, in <module>
#13 0.419     sys.exit(run_with_catch())
#13 0.419   File "/usr/local/lib/python3.8/dist-packages/virtualenv/__main__.py", line 56, in run_with_catch
#13 0.419     run(args, options, env)
#13 0.419   File "/usr/local/lib/python3.8/dist-packages/virtualenv/__main__.py", line 18, in run
#13 0.419     session = cli_run(args, options, env)
#13 0.419   File "/usr/local/lib/python3.8/dist-packages/virtualenv/run/__init__.py", line 30, in cli_run
#13 0.419     of_session = session_via_cli(args, options, setup_logging, env)
#13 0.419   File "/usr/local/lib/python3.8/dist-packages/virtualenv/run/__init__.py", line 48, in session_via_cli
#13 0.419     parser, elements = build_parser(args, options, setup_logging, env)
#13 0.419   File "/usr/local/lib/python3.8/dist-packages/virtualenv/run/__init__.py", line 72, in build_parser
#13 0.419     raise RuntimeError(f"failed to find interpreter for {discover}")
#13 0.419 RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.6'
#13 ERROR: process "/bin/sh -c virtualenv -vvv --with-traceback -p python3.6 .test" did not complete successfully: exit code: 1
```

Note:
python3 (3.8), python3.6 and python3.8 can be found in path:
```
#10 [ 6/13] RUN python3 --version
#10 0.339 Python 3.8.10
#10 DONE 0.3s

#11 [ 7/13] RUN python3.6 --version
#11 0.344 Python 3.6.15
#11 DONE 0.4s

#12 [ 8/13] RUN python3.8 --version
#12 0.312 Python 3.8.10
#12 DONE 0.3s
```

**Comment by ap-wtioit** [comment]
"minimal" Dockerfile to reproduce this:
```Dockerfile
FROM ubuntu:20.04
RUN set -x \
 && DEBIAN_FRONTEND=noninteractive \
 && export DEBIAN_FRONTEND \
 && apt update \
 && apt upgrade -y \
 && apt install python3-pip software-properties-common -y \
 && add-apt-repository ppa:deadsnakes/ppa \
 && apt install python3.6 python3.6-distutils -y
ARG virtualenv_version=20.22.0
RUN pip3 install virtualenv==$virtualenv_version
RUN virtualenv -vvv --with-traceback -p python3.6 .test
```
with this image the following command works:
```bash
docker build --build-arg virtualenv_version=20.21.1 .
```
while this doesn't
```bash
docker build --build-arg virtualenv_version=20.21.1 .
```

Note the [release log](https://virtualenv.pypa.io/en/latest/changelog.html#features-20-22-0) says
> Drop support for creating Python <3.6 

which for me would mean 3.6 should still be supported

**Comment by hroncok** [comment]
The [PR that removed support for Python \< 3.6](https://github.com/pypa/virtualenv/pull/2548) also removed wheel 0.37.1 which was required for Python 3.6 becasue wheel 0.40.0 requires Python \>= 3.7.

**Comment by gaborbernat** [comment]
There's a typo in the changelog that should be <=3.6.

**Comment by gaborbernat** [comment]
PR welcome 😁
