### ISSUE TITLE
Entry points leaking from "higher" site-packages on Python < 3.10, causing AttributeError from plugin loader

### ISSUE THREAD

**Issue by mgorny** [pypa/virtualenv#2554]
**Issue**

When virtualenv is installed on Python < 3.10, it is using the "old" `importlib.metadata` API. It seems to collect entry points from all directories on `sys.path`. If virtualenv 20.22.0 is installed on top of `sys.path` but an earlier version is installed somewhere along the line, it tries to load entry points specified by the older version and fails:

```
AttributeError: module 'virtualenv.create.via_global_ref.builtin.cpython.mac_os' has no attribute 'CPython2macOsArmFramework'
```

This affects us on Gentoo when we are running the test suite before installing the newer version to the system. The tested version is installed in a venv with `--system-site-packages`, so that it can be tested against already-installed versions of dependencies. However, this breaks if system site-packages contain an older version of virtualenv that specifies the entry point listed above.

One possible solution would be to always prefer `importlib_metadata`, so that the newer API could be exercised.

**Environment**

Provide at least:

- OS: Gentoo Linux

<details><summary>`pip list` of the host python where `virtualenv` is installed:</summary>

```console
Package                       Version
----------------------------- -----------
aiohttp                       3.8.4
aiosignal                     1.3.1
alabaster                     0.7.13
anyio                         3.6.1
appdirs                       1.4.4
apsw                          3.41.2.0
argcomplete                   3.0.5
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
astroid                       2.15.3
asttokens                     2.2.1
async-generator               1.10
async-timeout                 4.0.2
asyncstdlib                   3.10.6
attrs                         23.1.0
autocommand                   2.2.2
Automat                       22.10.0
Babel                         2.12.1
backcall                      0.2.0
beautifulsoup4                4.12.2
beniget                       0.4.1
black                         23.3.0
bleach                        6.0.0
blessed                       1.20.0
blurb                         1.1.0
boolean.py                    4.0
borgbackup                    1.2.4
bpython                       0.24
breezy                        3.2.1
Brotli                        1.0.9
build                         0.10.0
CacheControl                  0.12.11
cachetools                    5.3.0
cairocffi                     1.5.1
calver                        2023.4.3
cchardet                      2.1.7
certifi-system-store          3021.3.16
certifi-system-store          3021.3.16
cffi                          1.15.1
cfgv                          3.3.1
chardet                       5.1.0
charset-normalizer            3.1.0
click                         8.1.3
cloudpickle                   2.2.1
colorama                      0.4.6
colorlog                      6.7.0
comm                          0.1.3
configobj                     5.0.8
constantly                    15.1.0
contourpy                     1.0.7
coverage                      7.2.3
cppy                          1.2.1
cryptography                  40.0.2
css-parser                    1.0.8
cssselect                     1.2.0
curtsies                      0.4.1
cwcwidth                      0.1.8
cycler                        0.11.0
Cython                        0.29.34
debugpy                       1.6.6
decorator                     5.1.1
defusedxml                    0.7.1
denonavr                      0.11.2
denonavr_cli                  3
Deprecated                    1.2.13
deprecation                   2.1.0
diffmask                      0.3.3
dill                          0.3.6
distlib                       0.3.6
distro                        1.8.0
dnspython                     2.3.0
docutils                      0.19
docutils-glep                 1.5
dulwich                       0.21.3
eclean-kernel                 2.99.4
editables                     0.3
entrypoints                   0.4
exceptiongroup                1.1.1
execnet                       1.9.0
executing                     1.2.0
fastimport                    0.9.14
fastjsonschema                2.16.3
feedparser                    6.0.10
fields                        5.0.0
filelock                      3.12.0
findimports                   2.3.0
flaggie                       0.99.3
flake8                        6.0.0
flit                          3.8.0
flit_core                     3.8.0
flit_scm                      1.7.0
fonttools                     4.39.3
fqdn                          1.5.1
frozenlist                    1.3.3
fs                            2.4.16
future                        0.18.2
gast                          0.5.3
gaupol                        1.12
gemato                        20.1
gentoolkit                    0.6.1.post3
gentoopm                      0.5.0
glep63-check                  11
gpg                           1.19.0
gpyutils                      0.9
greenlet                      2.0.2
h11                           0.14.0
h2                            4.1.0
hatch-fancy-pypi-readme       22.8.0
hatch-vcs                     0.3.0
hatchling                     1.1.0
hg-evolve                     11.0.1
hpack                         4.0.0
html2text                     2020.1.16
html5-parser                  0.4.11
html5lib                      1.1
httpcore                      0.17.0
httplib2                      0.22.0
httpx                         0.24.0
hyperframe                    6.0.1
hyperlink                     21.0.0
identify                      2.5.22
idna                          3.4
ifaddr                        0.2.0
imagesize                     1.4.1
importlib_metadata            6.5.0
importlib_resources           5.12.0
incremental                   22.10.0
inflect                       6.0.4
iniconfig                     2.0.0
installer                     0.7.0
ipykernel                     6.22.0
ipyparallel                   8.6.1
ipython                       8.12.0
ipython-genutils              0.2.0
isoduration                   20.11.0
isort                         5.12.0
jaraco.classes                3.2.3
jaraco.context                4.3.0
jaraco.functools              3.6.0
jaraco.text                   3.11.1
jedi                          0.18.2
jeepney                       0.8.0
Jinja2                        3.1.2
joblib                        1.1.0
jsonpointer                   2.3
jsonschema                    4.17.3
jupyter_client                8.2.0
jupyter_core                  5.3.0
jupyter-events                0.6.3
jupyter_packaging             0.12.3
jupyter_server                2.5.0
jupyter_server_terminals      0.4.4
jupyterlab-pygments           0.2.2
jwcrypto                      1.4.2
keyring                       23.13.1
kiwisolver                    1.4.4
lark                          1.1.5
lazy-object-proxy             1.9.0
Levenshtein                   0.21.0
license-expression            30.1.0
linkify-it-py                 2.0.0
lit                           17.0.0.dev0
lockfile                      0.12.2
loky                          3.4.0
lxml                          4.9.2
lz4                           4.3.2
M2Crypto                      0.38.0
m64py                         0.2.5
Mako                          1.2.4
Markdown                      3.4.3
markdown-it-py                2.2.0
MarkupSafe                    2.1.2
matplotlib                    3.7.1
matplotlib-inline             0.1.6
mccabe                        0.7.0
mdurl                         0.1.2
mechanize                     0.4.8
mercurial                     6.4
meson                         1.1.0
meson-python                  0.13.0
mistune                       2.0.5
more-itertools                9.1.0
msgpack                       1.0.5
multidict                     6.0.4
mypy                          1.2.0
mypy-extensions               1.0.0
natsort                       8.3.1
nattka                        0.4.1
nbclient                      0.7.3
nbconvert                     7.3.1
nbformat                      5.7.1
nest-asyncio                  1.5.6
netifaces                     0.11.0
networkx                      3.1
nodeenv                       1.7.0
nox                           2022.11.21
nspektr                       0.4.0
numpy                         1.24.2
olefile                       0.46
openpaperwork-core            2.1.2
openpaperwork-gtk             2.1.2
ordered-set                   4.1.0
outcome                       1.2.0
packaging                     23.1
pandocfilters                 1.5.0
paperwork                     2.1.2
paperwork-backend             2.1.2
parso                         0.8.3
path                          16.6.0
pathspec                      0.11.1
patiencediff                  0.2.13
pbr                           5.11.1
Pebble                        5.0.3
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.5.0
pip                           23.1
pkgcheck                      0.10.23
pkgconfig                     1.5.5
pkgcore                       0.12.20
pkgdev                        0.2.5
pkginfo                       1.9.6
platformdirs                  3.2.0
pluggy                        1.0.0
ply                           3.11
poetry-core                   1.5.2
pooch                         1.7.0
portage                       3.0.46
process-tests                 2.1.2
prometheus-client             0.16.0
prompt-toolkit                3.0.38
psutil                        5.9.5
ptyprocess                    0.7.0
pure-eval                     0.2.2
py                            1.11.0
pyasn1                        0.5.0
pyasn1-modules                0.3.0
pybind11                      2.10.4
pybugz                        0.13
pycairo                       1.23.0
pycargoebuild                 0.6.3
pychm                         0.8.6
pycodestyle                   2.10.0
pycountry                     22.3.5
pycparser                     2.21
pycryptodome                  3.17
pydantic                      1.10.7
pydevd                        2.9.5
pyenchant                     3.2.2
pyflakes                      3.0.1
pyfuse3                       3.2.2
Pygments                      2.15.1
PyGObject                     3.44.1
PyJWT                         2.6.0
pylint                        2.17.2
pymountboot                   0.2.3
PyNaCl                        1.5.0
pyocr                         0.8.3
pyOpenSSL                     23.1.1
pyparsing                     3.0.9
pypillowfight                 0.3.0
pyproject_api                 1.5.1
pyproject_hooks               1.0.0
pyproject-metadata            0.7.1
PyQt-builder                  1.15.0
PyQt5                         5.15.9
PyQt5-sip                     12.12.0
PyQtWebEngine                 5.15.6
pyrsistent                    0.19.3
PySDL2                        0.9.13
PySocks                       1.7.1
pytest                        7.3.1
pytest-asyncio                0.21.0
pytest-forked                 1.6.0
pytest-xdist                  3.2.1
pytest-xprocess               0.22.2
python-bugzilla               3.2.0
python-dateutil               2.8.2
python-json-logger            2.0.7
python-lzo                    1.14
python-magic                  0.4.27
pythran                       0.12.1
pytz                          2023.3
pyxdg                         0.28
PyYAML                        6.0
pyzmq                         25.0.2
qtconsole                     5.4.2
QtPy                          2.3.1
quasselgrep                   0.1
rapidfuzz                     3.0.0
rapidfuzz-capi                1.0.5
readme-renderer               37.3
redis                         4.5.4
regex                         2023.3.23
requests                      2.28.2
requests_download             0.1.2
requests-toolbelt             0.10.1
rfc3339-validator             0.1.4
rfc3986                       2.0.0
rfc3986-validator             0.1.1
rfc3987                       1.3.8
rich                          13.3.4
ruamel.yaml                   0.17.21
ruamel.yaml.clib              0.2.7
scikit-build                  0.17.1
scikit-learn                  1.1.2
scipy                         1.10.1
SCons                         4.5.2
scour                         0.38.2
SecretStorage                 3.3.3
semantic-version              2.10.0
Send2Trash                    1.8.0
sentry-sdk                    0.16.4
service-identity              21.1.0
setuptools                    67.6.1
setuptools-rust               1.5.2
setuptools-scm                7.1.0
setuptools-scm-git-archive    1.4
sgmllib3k                     1.0.0
sip                           6.7.8
six                           1.16.0
smartliverebuild              1.4.1
snakeoil                      0.10.5
sniffio                       1.3.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.4.1
Sphinx                        6.1.3
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.1
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
stack-data                    0.6.2
strict-rfc3339                0.7
termcolor                     2.2.0
terminado                     0.17.1
testpath                      0.6.0
threadpoolctl                 3.1.0
tinycss2                      1.2.1
tomli                         2.0.1
tomli_w                       1.0.0
tomlkit                       0.11.7
tornado                       6.3
tox                           4.4.12
tqdm                          4.65.0
traitlets                     5.9.0
tree-sitter                   0.20.1
trio                          0.22.0
trove-classifiers             2023.4.18
twine                         4.0.2
Twisted                       22.10.0
typed-ast                     1.5.4
typing_extensions             4.5.0
uc-micro-py                   1.0.1
ukkonen                       1.0.1
uri-template                  1.2.0
urllib3                       1.26.15
vcrpy                         4.2.1
virtualenv                    20.22.0
wcwidth                       0.2.6
webcolors                     1.13
webencodings                  0.5.1
websocket-client              1.5.1
wheel                         0.40.0
Whoosh                        2.7.4
wrapt                         1.15.0
xcffib                        1.3.0
yarl                          1.8.2
yt-dlp                        2023.3.4
zeroconf                      0.56.0
zipp                          3.15.0
zope.interface                6.0
zstandard                     0.21.0

```
</details>

**Output of the virtual environment creation**

Example method of reproducing:

1. Install `virtualenv==20.21.0` system-wide.
2. `python -m venv --system-site-packages /tmp/venv`
3. `. /tmp/venv/bin/activate`
4. `pip install -U virtualenv`

Make sure to run the creation with `-vvv --with-traceback`:

```console
480 setup logging to NOTSET [DEBUG report:37]
513 find interpreter for spec PythonSpec(path=/tmp/venv/bin/python) [INFO builtin:58]
513 discover exe for PythonInfo(spec=CPython3.9.16.final.0-64, exe=/tmp/venv/bin/python, platform=linux, version='3.9.16 (main, Mar 15 2023, 15:25:52) \n[GCC 12.2.1 20230304]', encoding_fs_io=utf-8-utf-8) in /usr [DEBUG py_info:435]
514 filesystem is case-sensitive [DEBUG info:26]
515 Attempting to acquire lock 140623662025168 on /home/mgorny/.local/share/virtualenv/py_info/1/36cf16204b8548560b1c020c4e8fb5b57f0e4c58016f52f2d4be01e192833930.lock [DEBUG _api:216]
515 Lock 140623662025168 acquired on /home/mgorny/.local/share/virtualenv/py_info/1/36cf16204b8548560b1c020c4e8fb5b57f0e4c58016f52f2d4be01e192833930.lock [DEBUG _api:219]
515 got python info of /usr/bin/python3.9 from /home/mgorny/.local/share/virtualenv/py_info/1/36cf16204b8548560b1c020c4e8fb5b57f0e4c58016f52f2d4be01e192833930.json [DEBUG via_disk_folder:131]
730 Attempting to release lock 140623662025168 on /home/mgorny/.local/share/virtualenv/py_info/1/36cf16204b8548560b1c020c4e8fb5b57f0e4c58016f52f2d4be01e192833930.lock [DEBUG _api:249]
730 Lock 140623662025168 released on /home/mgorny/.local/share/virtualenv/py_info/1/36cf16204b8548560b1c020c4e8fb5b57f0e4c58016f52f2d4be01e192833930.lock [DEBUG _api:252]
730 proposed PythonInfo(spec=CPython3.9.16.final.0-64, system=/usr/bin/python3.9, exe=/tmp/venv/bin/python, platform=linux, version='3.9.16 (main, Mar 15 2023, 15:25:52) \n[GCC 12.2.1 20230304]', encoding_fs_io=utf-8-utf-8) [INFO builtin:65]
730 accepted PythonInfo(spec=CPython3.9.16.final.0-64, system=/usr/bin/python3.9, exe=/tmp/venv/bin/python, platform=linux, version='3.9.16 (main, Mar 15 2023, 15:25:52) \n[GCC 12.2.1 20230304]', encoding_fs_io=utf-8-utf-8) [DEBUG builtin:67]
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/venv/lib/python3.9/site-packages/virtualenv/__main__.py", line 71, in <module>
    run_with_catch()  # pragma: no cov
  File "/tmp/venv/lib/python3.9/site-packages/virtualenv/__main__.py", line 56, in run_with_catch
    run(args, options, env)
  File "/tmp/venv/lib/python3.9/site-packages/virtualenv/__main__.py", line 18, in run
    session = cli_run(args, options, env)
  File "/tmp/venv/lib/python3.9/site-packages/virtualenv/run/__init__.py", line 30, in cli_run
    of_session = session_via_cli(args, options, setup_logging, env)
  File "/tmp/venv/lib/python3.9/site-packages/virtualenv/run/__init__.py", line 48, in session_via_cli
    parser, elements = build_parser(args, options, setup_logging, env)
  File "/tmp/venv/lib/python3.9/site-packages/virtualenv/run/__init__.py", line 74, in build_parser
    CreatorSelector(interpreter, parser),
  File "/tmp/venv/lib/python3.9/site-packages/virtualenv/run/plugin/creators.py", line 15, in __init__
    creators, self.key_to_meta, self.describe, self.builtin_key = self.for_interpreter(interpreter)
  File "/tmp/venv/lib/python3.9/site-packages/virtualenv/run/plugin/creators.py", line 22, in for_interpreter
    for key, creator_class in cls.options("virtualenv.create").items():
  File "/tmp/venv/lib/python3.9/site-packages/virtualenv/run/plugin/base.py", line 46, in options
    cls._OPTIONS = cls.entry_points_for(key)
  File "/tmp/venv/lib/python3.9/site-packages/virtualenv/run/plugin/base.py", line 25, in entry_points_for
    return OrderedDict((e.name, e.load()) for e in cls.entry_points().get(key, {}))
  File "/tmp/venv/lib/python3.9/site-packages/virtualenv/run/plugin/base.py", line 25, in <genexpr>
    return OrderedDict((e.name, e.load()) for e in cls.entry_points().get(key, {}))
  File "/tmp/venv/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 210, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'virtualenv.create.via_global_ref.builtin.cpython.mac_os' has no attribute 'CPython2macOsArmFramework'
```

**Comment by gaborbernat** [comment]
It's not supported to have multiple versions of virtualenv.
