### ISSUE TITLE
Upgrading to virtualenv 20.21.1

### ISSUE THREAD

**Issue by rickyyx** [pypa/virtualenv#2568]
**Issue**

We have a ci job running and it starts to fail with the below error message when the virtualenv 20.21.1 is released. 

Is there any known issue with the version? 

```
E                       ray._private.runtime_env.utils.SubprocessCalledProcessError: Run cmd[18] failed with the following details.
--
  | E                       Command '['/tmp/ray/session_2023-05-04_10-14-12_298537_5033/runtime_resources/pip/daeea39f183e195bbbf9c29c975107dd17bc46b3/virtualenv/bin/python', '-m', 'pip', 'install', '--disable-pip-version-check', '--no-cache-dir', '-r', '/tmp/ray/session_2023-05-04_10-14-12_298537_5033/runtime_resources/pip/daeea39f183e195bbbf9c29c975107dd17bc46b3/requirements.txt']' returned non-zero exit status 1.
  | E                       Last 50 lines of stdout:
  | E                           Processing /tmp/pytest-of-root/pytest-2/test_pip_with_env_vars_no_ray_0/test_package.tar.gz
  | E                             Preparing metadata (setup.py): started
  | E                             Preparing metadata (setup.py): finished with status 'done'
  | E                           Building wheels for collected packages: test-package
  | E                             Building wheel for test-package (setup.py): started
  | E                             Building wheel for test-package (setup.py): finished with status 'error'
  | E                             error: subprocess-exited-with-error
  | E
  | E                             × python setup.py bdist_wheel did not run successfully.
  | E                             │ exit code: 1
  | E                             ╰─> [28 lines of output]
  | E                                 running bdist_wheel
  | E                                 running build
  | E                                 /tmp/ray/session_2023-05-04_10-14-12_298537_5033/runtime_resources/pip/daeea39f183e195bbbf9c29c975107dd17bc46b3/virtualenv/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  | E                                   setuptools.SetuptoolsDeprecationWarning,
  | E                                 installing to build/bdist.linux-x86_64/wheel
  | E                                 running install
  | E                                 Traceback (most recent call last):
  | E                                   File "<string>", line 36, in <module>
  | E                                   File "<pip-setuptools-caller>", line 34, in <module>
  | E                                   File "/tmp/pip-req-build-ohziu6x0/setup.py", line 16, in <module>
  | E                                     zip_safe=False,
  | E                                   File "/tmp/ray/session_2023-05-04_10-14-12_298537_5033/runtime_resources/pip/daeea39f183e195bbbf9c29c975107dd17bc46b3/virtualenv/lib/python3.7/site-packages/setuptools/__init__.py", line 108, in setup
  | E                                     return distutils.core.setup(**attrs)
  | E                                   File "/tmp/ray/session_2023-05-04_10-14-12_298537_5033/runtime_resources/pip/daeea39f183e195bbbf9c29c975107dd17bc46b3/virtualenv/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
  | E                                     return run_commands(dist)
  | E                                   File "/tmp/ray/session_2023-05-04_10-14-12_298537_5033/runtime_resources/pip/daeea39f183e195bbbf9c29c975107dd17bc46b3/virtualenv/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
  | E                                     dist.run_commands()
  | E                                   File "/tmp/ray/session_2023-05-04_10-14-12_298537_5033/runtime_resources/pip/daeea39f183e195bbbf9c29c975107dd17bc46b3/virtualenv/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
  | E                                     self.run_command(cmd)
  | E                                   File "/tmp/ray/session_2023-05-04_10-14-12_298537_5033/runtime_resources/pip/daeea39f183e195bbbf9c29c975107dd17bc46b3/virtualenv/lib/python3.7/site-packages/setuptools/dist.py", line 1221, in run_command
  | E                                     super().run_command(command)
  | E                                   File "/tmp/ray/session_2023-05-04_10-14-12_298537_5033/runtime_resources/pip/daeea39f183e195bbbf9c29c975107dd17bc46b3/virtualenv/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
  | E                                     cmd_obj.run()
  | E                                   File "/tmp/ray/session_2023-05-04_10-14-12_298537_5033/runtime_resources/pip/daeea39f183e195bbbf9c29c975107dd17bc46b3/virtualenv/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 395, in run
  | E                                     self.egg2dist(self.egginfo_dir, distinfo_dir)
  | E                                   File "/tmp/ray/session_2023-05-04_10-14-12_298537_5033/runtime_resources/pip/daeea39f183e195bbbf9c29c975107dd17bc46b3/virtualenv/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 524, in egg2dist
  | E                                     raise ValueError(err)
  | E                                 ValueError: Egg metadata expected at build/bdist.linux-x86_64/wheel/test_package-0.0.1-py3.7.egg-info but not found
  | E                                 [end of output]



```
**Environment**

Provide at least:

- OS:
- `pip list` of the host python where `virtualenv` is installed:

  ```console

  ```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console

```

**Comment by rickyyx** [comment]
Happy to provide more details - it's running in CI so getting all the env info is not trivial, but I could try to pull them out. Just wanna get a quick idea first if this is already something know.

**Comment by gaborbernat** [comment]
Seems stale.
