### ISSUE TITLE
tox fails to find python interpreter with spec(s): python2.7 running virtualenv 20.23.0

### ISSUE THREAD

**Issue by thecesrom** [pypa/virtualenv#2579]
**Issue**

Using 20.23.0 tox cannot run py27 environments.

**Environment**

Provide at least:

- OS: macOS
- `pip list` of the host python where `virtualenv` is installed:

```sh
$ python -m pip list
Package       Version
------------- -------
cachetools    5.3.0
chardet       5.1.0
colorama      0.4.6
distlib       0.3.6
filelock      3.12.0
packaging     23.1
pip           23.1.2
platformdirs  3.5.1
pluggy        1.0.0
pyproject_api 1.5.1
setuptools    67.7.2
tomli         2.0.1
tox           4.5.1
virtualenv    20.23.0
wheel         0.40.0
```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```sh
$ virtualenv --version
virtualenv 20.23.0 from /Users/thecesrom/.pyenv/versions/virtualenv/lib/python3.10/site-packages/virtualenv/__init__.py
$ vritualenv -vvv --with-traceback vvv -p python2.7
...
Traceback (most recent call last):
  File "/Users/thecesrom/.pyenv/versions/virtualenv/bin/virtualenv", line 8, in <module>
    sys.exit(run_with_catch())
  File "/Users/thecesrom/.pyenv/versions/virtualenv/lib/python3.10/site-packages/virtualenv/__main__.py", line 56, in run_with_catch
    run(args, options, env)
  File "/Users/thecesrom/.pyenv/versions/virtualenv/lib/python3.10/site-packages/virtualenv/__main__.py", line 18, in run
    session = cli_run(args, options, env)
  File "/Users/thecesrom/.pyenv/versions/virtualenv/lib/python3.10/site-packages/virtualenv/run/__init__.py", line 30, in cli_run
    of_session = session_via_cli(args, options, setup_logging, env)
  File "/Users/thecesrom/.pyenv/versions/virtualenv/lib/python3.10/site-packages/virtualenv/run/__init__.py", line 48, in session_via_cli
    parser, elements = build_parser(args, options, setup_logging, env)
  File "/Users/thecesrom/.pyenv/versions/virtualenv/lib/python3.10/site-packages/virtualenv/run/__init__.py", line 74, in build_parser
    CreatorSelector(interpreter, parser),
  File "/Users/thecesrom/.pyenv/versions/virtualenv/lib/python3.10/site-packages/virtualenv/run/plugin/creators.py", line 15, in __init__
    creators, self.key_to_meta, self.describe, self.builtin_key = self.for_interpreter(interpreter)
  File "/Users/thecesrom/.pyenv/versions/virtualenv/lib/python3.10/site-packages/virtualenv/run/plugin/creators.py", line 43, in for_interpreter
    raise RuntimeError(f"No virtualenv implementation for {interpreter}")
RuntimeError: No virtualenv implementation for PathPythonInfo(spec=CPython2.7.18.final.0-64, system=/Users/thecesrom/.pyenv/versions/2.7.18/bin/python2.7, exe=/Users/thecesrom/.pyenv/shims/python2.7, platform=darwin, version='2.7.18 (default, Dec 29 2022, 09:23:27) \n[GCC Apple LLVM 14.0.0 (clang-1400.0.29.202)]', encoding_fs_io=utf-8-None)
```

While version 20.21.0 works without issues.

This works:

```sh
$ python -m pip list
Package      Version
------------ -------
distlib      0.3.6
filelock     3.12.0
pip          23.1.2
platformdirs 3.5.1
setuptools   67.8.0
virtualenv   20.21.0
```

This does not:

```sh
$ python -m pip list                                     
Package      Version
------------ -------
distlib      0.3.6
filelock     3.12.0
pip          23.1.2
platformdirs 3.5.1
setuptools   67.8.0
virtualenv   20.23.0
```

**Comment by gaborbernat** [comment]
https://tox.wiki/en/latest/faq.html#testing-end-of-life-python-versions
