### ISSUE TITLE
Unable to create any virtual environments with a fresh re-installation of Python 3.9 and 3.11

### ISSUE THREAD

**Issue by SudoCerb** [pypa/virtualenv#2597]
**Issue**

The following commands are yielding the same error for me (note - full traceback provided in the last section below):

```powershell
pipenv shell
```
Output:
```
Creating a virtualenv for this project...
Pipfile: <PATH TO EXISTING PIPFILE>
Using <USER_HOME>/AppData/Local/Programs/Python/Python39/python.exe (3.9.13) to create virtualenv...
[=== ] Creating virtual environment...RuntimeError: No implementation for PythonInfo(spec=CPython3.9.13.final.0-64, exe=<USER_HOME>\AppData\Local\Programs\Python\Python39\python.exe, platform=win32, version='3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]', encoding_fs_io=utf-8-utf-8)

Failed creating virtual environment
[pipenv.exceptions.VirtualenvCreationException]:
Failed to create virtual environment.
```

```powershell
python -m virtualenv venv

OR

py -3.9 -m virtualenv venv
```
Output:
```
RuntimeError: No implementation for PythonInfo(spec=CPython3.11.4.final.0-64, exe=<USER_HOME>\AppData\Local\Programs\Python\Python311\python.exe, platform=win32, version='3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]', encoding_fs_io=utf-8-utf-8)

OR

RuntimeError: No implementation for PythonInfo(spec=CPython3.9.13.final.0-64, exe=<USER_HOME>\AppData\Local\Programs\Python\Python39\python.exe, platform=win32, version='3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]', encoding_fs_io=utf-8-utf-8)
```

**Environment**

Provide at least:

- OS: Windows 11 Enterprise 22H2 (OS Build: 22621.1702)
- `pip list` of the host python where `virtualenv` is installed:

```console
$ > py -3.11 -m pip list
Package          Version
---------------- ---------
certifi          2023.5.7
distlib          0.3.6
filelock         3.12.2
pip              23.1.2
pipenv           2023.6.26
platformdirs     3.8.0
setuptools       68.0.0
virtualenv       20.23.1
virtualenv-clone 0.5.7
```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console
$ > py -3.11 -m virtualenv venv -vvv --with-traceback
188 setup logging to NOTSET [DEBUG report:37]
204 find interpreter for spec PythonSpec(path=<USER_HOME>\AppData\Local\Programs\Python\Python311\python.exe) [INFO builtin:58]
204 proposed PythonInfo(spec=CPython3.11.4.final.0-64, exe=<USER_HOME>\AppData\Local\Programs\Python\Python311\python.exe, platform=win32, version='3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]', encoding_fs_io=utf-8-utf-8) [INFO builtin:65]
204 accepted PythonInfo(spec=CPython3.11.4.final.0-64, exe=<USER_HOME>\AppData\Local\Programs\Python\Python311\python.exe, platform=win32, version='3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]', encoding_fs_io=utf-8-utf-8) [DEBUG builtin:67]
211 symlink on filesystem does work [DEBUG info:45]
212 filesystem is not case-sensitive [DEBUG info:26]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "<USER_HOME>\AppData\Local\Programs\Python\Python311\Lib\site-packages\virtualenv\__main__.py", line 70, in <module>
    run_with_catch()  # pragma: no cov
    ^^^^^^^^^^^^^^^^
  File "<USER_HOME>\AppData\Local\Programs\Python\Python311\Lib\site-packages\virtualenv\__main__.py", line 56, in run_with_catch
    run(args, options, env)
  File "<USER_HOME>\AppData\Local\Programs\Python\Python311\Lib\site-packages\virtualenv\__main__.py", line 18, in run
    session = cli_run(args, options, env)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<USER_HOME>\AppData\Local\Programs\Python\Python311\Lib\site-packages\virtualenv\run\__init__.py", line 31, in cli_run
    of_session = session_via_cli(args, options, setup_logging, env)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<USER_HOME>\AppData\Local\Programs\Python\Python311\Lib\site-packages\virtualenv\run\__init__.py", line 49, in session_via_cli
    parser, elements = build_parser(args, options, setup_logging, env)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<USER_HOME>\AppData\Local\Programs\Python\Python311\Lib\site-packages\virtualenv\run\__init__.py", line 88, in build_parser
    element.handle_selected_arg_parse(options)
  File "<USER_HOME>\AppData\Local\Programs\Python\Python311\Lib\site-packages\virtualenv\run\plugin\seeders.py", line 32, in handle_selected_arg_parse
    return super().handle_selected_arg_parse(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<USER_HOME>\AppData\Local\Programs\Python\Python311\Lib\site-packages\virtualenv\run\plugin\base.py", line 55, in handle_selected_arg_parse
    raise RuntimeError(msg)
RuntimeError: No implementation for PythonInfo(spec=CPython3.11.4.final.0-64, exe=<USER_HOME>\AppData\Local\Programs\Python\Python311\python.exe, platform=win32, version='3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]', encoding_fs_io=utf-8-utf-8)
```

**Comment by SudoCerb** [comment]
For now I've reverted to an older version of `virtualenv`, my `pip list` is as follows:

```console
$ > py -3.9 -m pip list
Package          Version
---------------- ----------
certifi          2023.5.7
distlib          0.3.6
filelock         3.12.2
pip              23.1.2
pipenv           2022.12.19
platformdirs     3.8.0
setuptools       68.0.0
virtualenv       16.7.12
virtualenv-clone 0.5.7
```

**Comment by tsmcgrath** [comment]
I'm getting this error on a Mac M1 with a fresh install of python 3.11.4. Seems like the same issues, correct?
 % pipenv install
Creating a virtualenv for this project...
Pipfile: /Users/tim/DocumentsLocal/Github/catchtest1/Pipfile
Using /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 (3.11.4) to create virtualenv...
⠙ Creating virtual environment...AttributeError: 'dict' object has no attribute 'select'

✘ Failed creating virtual environment 
[pipenv.exceptions.VirtualenvCreationException]: 
Failed to create virtual environment.

**Comment by gaborbernat** [comment]
Please submit that bug to pipenv.

**Comment by tsmcgrath** [comment]
Done:
https://github.com/pypa/pipenv/issues/5799
