### ISSUE TITLE
virtualenv creates not downgrade compatible caching data in %LOCALAPPDATA%

### ISSUE THREAD

**Issue by schlamar** [pypa/virtualenv#2600]
**Issue**

When downgrading to virtualenv<20.22 (required for some Python 2 projects) virtualenv crashes, because it cannot read some cached data in %LOCALAPPDATA%\pypa\virtualenv\py_info

**Environment**

Provide at least:

- OS: Windows
- `pip list` of the host python where `virtualenv` is installed:

```console
> pip list
Package      Version
------------ -------
distlib      0.3.6
filelock     3.12.2
pip          22.3.1
platformdirs 3.8.0
setuptools   65.5.0
virtualenv   20.21.1
```

**Steps to reproduce**

```powershell 
> Remove-Item $env:LOCALAPPDATA\pypa -Recurse
> pip install virtualenv
> virtualenv venv1
> pip install -U "virtualenv<20.22"
> virtualenv venv2
```

**Output of the virtual environment creation**

```console
> virtualenv venv2 -vvv --with-traceback
488 setup logging to NOTSET [DEBUG report:35]
493 find interpreter for spec PythonSpec(path=C:\Users\schlaich\Desktop\venv\Scripts\python.exe) [INFO builtin:56]
495 Attempting to acquire lock 82977120 on C:\Users\schlaich\AppData\Local\pypa\virtualenv\py_info\1\71a187be2728a321a6ad3c7927b65ff260725c8c80d0d239ee03bbda5c35d117.lock [DEBUG _api:212]
495 Lock 82977120 acquired on C:\Users\schlaich\AppData\Local\pypa\virtualenv\py_info\1\71a187be2728a321a6ad3c7927b65ff260725c8c80d0d239ee03bbda5c35d117.lock [DEBUG _api:215]
496 got python info of C:\Users\schlaich\AppData\Local\Programs\Python\Python310-32\python.exe from C:\Users\schlaich\AppData\Local\pypa\virtualenv\py_info\1\71a187be2728a321a6ad3c7927b65ff260725c8c80d0d239ee03bbda5c35d117.json [DEBUG via_disk_folder:129]
508 Attempting to release lock 82977120 on C:\Users\schlaich\AppData\Local\pypa\virtualenv\py_info\1\71a187be2728a321a6ad3c7927b65ff260725c8c80d0d239ee03bbda5c35d117.lock [DEBUG _api:244]
509 Lock 82977120 released on C:\Users\schlaich\AppData\Local\pypa\virtualenv\py_info\1\71a187be2728a321a6ad3c7927b65ff260725c8c80d0d239ee03bbda5c35d117.lock [DEBUG _api:247]
509 proposed PythonInfo(spec=CPython3.10.9.final.0-32, system=C:\Users\schlaich\AppData\Local\Programs\Python\Python310-32\python.exe, exe=C:\Users\schlaich\Desktop\venv\Scripts\python.exe, platform=win32, version='3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 19:43:38) [MSC v.1934 32 bit (Intel)]', encoding_fs_io=utf-8-cp1252) [INFO builtin:63]
509 accepted PythonInfo(spec=CPython3.10.9.final.0-32, system=C:\Users\schlaich\AppData\Local\Programs\Python\Python310-32\python.exe, exe=C:\Users\schlaich\Desktop\venv\Scripts\python.exe, platform=win32, version='3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 19:43:38) [MSC v.1934 32 bit (Intel)]', encoding_fs_io=utf-8-cp1252) [DEBUG builtin:65]
515 symlink on filesystem does not work [DEBUG info:43]
516 filesystem is not case-sensitive [DEBUG info:24]
568 create virtual environment via CPython3Windows(dest=C:\Users\schlaich\Desktop\venv2, clear=False, no_vcs_ignore=False, global=False) [INFO session:48]
Traceback (most recent call last):
  File "C:\Users\schlaich\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\schlaich\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\schlaich\Desktop\venv\Scripts\virtualenv.exe\__main__.py", line 7, in <module>
  File "C:\Users\schlaich\Desktop\venv\lib\site-packages\virtualenv\__main__.py", line 54, in run_with_catch
    run(args, options, env)
  File "C:\Users\schlaich\Desktop\venv\lib\site-packages\virtualenv\__main__.py", line 16, in run
    session = cli_run(args, options, env)
  File "C:\Users\schlaich\Desktop\venv\lib\site-packages\virtualenv\run\__init__.py", line 30, in cli_run
    of_session.run()
  File "C:\Users\schlaich\Desktop\venv\lib\site-packages\virtualenv\run\session.py", line 42, in run
    self._create()
  File "C:\Users\schlaich\Desktop\venv\lib\site-packages\virtualenv\run\session.py", line 49, in _create
    self.creator.run()
  File "C:\Users\schlaich\Desktop\venv\lib\site-packages\virtualenv\create\creator.py", line 149, in run
    self.create()
  File "C:\Users\schlaich\Desktop\venv\lib\site-packages\virtualenv\create\via_global_ref\builtin\via_global_self_do.py", line 75, in create
    dirs = self.ensure_directories()
  File "C:\Users\schlaich\Desktop\venv\lib\site-packages\virtualenv\create\via_global_ref\builtin\via_global_self_do.py", line 100, in ensure_directories
    return {self.dest, self.bin_dir, self.script_dir, self.stdlib} | set(self.libs)
  File "C:\Users\schlaich\Desktop\venv\lib\site-packages\virtualenv\create\describe.py", line 44, in stdlib
    self._stdlib = Path(self.interpreter.sysconfig_path("stdlib", config_var=self._config_vars))
  File "C:\Users\schlaich\Desktop\venv\lib\site-packages\virtualenv\create\describe.py", line 56, in _config_vars
    self._conf_vars = self._calc_config_vars(self.dest)
  File "C:\Users\schlaich\Desktop\venv\lib\site-packages\virtualenv\create\describe.py", line 61, in _calc_config_vars
    return {k: (to if v.startswith(self.interpreter.prefix) else v) for k, v in sys_vars.items()}
  File "C:\Users\schlaich\Desktop\venv\lib\site-packages\virtualenv\create\describe.py", line 61, in <dictcomp>
    return {k: (to if v.startswith(self.interpreter.prefix) else v) for k, v in sys_vars.items()}
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by gaborbernat** [comment]
This is unfortunate but ultimately unsupported. Older versions of virtualenv are unsupported. Therefore, I invite you to put in a PR against 21.x and we'll release it as a special release. However, we will not accept new issues for not supported versions.
