### ISSUE TITLE
Missing file: activation/bash/activate.sh

### ISSUE THREAD

**Issue by grzs** [pypa/virtualenv#2629]
**Issue**

Can't find activation.sh while creating virtualenv

**Environment**

Provide at least:

- OS: Ubuntu 22.04
- `pip list` of the host python where `virtualenv` is installed:

  ```console
Package                   Version
------------------------- -------------
ansible-compat            4.1.5
ansible-core              2.15.2
ansible-lint              6.17.2
apturl                    0.5.2
asn1crypto                1.4.0
attrs                     23.1.0
bcrypt                    4.0.1
black                     23.7.0
blinker                   1.6.2
bottle                    0.12.19
bracex                    2.3.post1
Brlapi                    0.8.3
certifi                   2023.7.22
cffi                      1.15.1
chardet                   5.2.0
charset-normalizer        3.2.0
click                     8.1.6
command-not-found         0.3
configobj                 5.0.6
cryptography              41.0.3
cupshelpers               1.0
dbus-python               1.3.2
defer                     1.0.6
defusedxml                0.7.1
distlib                   0.3.7
distro                    1.8.0
distro-info               1.4
docker                    6.1.3
duplicity                 0.8.21
fasteners                 0.18
filelock                  3.12.2
future                    0.18.2
Glances                   3.2.4.2
html5lib                  1.1
httplib2                  0.20.2
idna                      3.4
importlib-metadata        6.8.0
importlib-resources       6.0.1
influxdb                  5.3.1
jaraco.classes            3.3.0
jeepney                   0.8.0
Jinja2                    3.1.2
jsonschema                4.19.0
jsonschema-specifications 2023.7.1
keyring                   24.2.0
language-selector         0.1
launchpadlib              1.10.16
lazr.restfulclient        0.14.4
lazr.uri                  1.0.6
lockfile                  0.12.2
louis                     3.20.0
macaroonbakery            1.3.1
Mako                      1.2.4
Markdown                  3.3.6
markdown-it-py            3.0.0
MarkupSafe                2.1.3
mdurl                     0.1.2
mechanize                 0.4.7
more-itertools            10.1.0
msgpack                   1.0.5
mypy-extensions           1.0.0
netifaces                 0.11.0
oauthlib                  3.2.2
olefile                   0.46
packaging                 23.1
paramiko                  3.3.1
pathspec                  0.11.2
pbr                       5.11.1
pexpect                   4.8.0
Pillow                    10.0.0
pip                       23.2.1
pkgutil-resolve-name      1.3.10
platformdirs              3.10.0
ply                       3.11
podman-compose            1.0.6
protobuf                  4.24.0
psutil                    5.9.5
psycopg2                  2.9.6
ptyprocess                0.7.0
pyasn1                    0.5.0
pycairo                   1.24.0
pycparser                 2.21
pycryptodomex             3.11.0
pycups                    2.0.1
Pygments                  2.16.1
PyGObject                 3.44.1
PyJWT                     2.8.0
pymacaroons               0.13.0
PyNaCl                    1.5.0
pyparsing                 3.1.1
pyRFC3339                 1.1
pysmi                     0.3.2
pysnmp                    4.4.12
pystache                  0.6.0
python-apt                2.4.0+ubuntu2
python-dateutil           2.8.2
python-debian             0.1.49
python-distutils-extra    2.39
python-dotenv             1.0.0
pytz                      2023.3
pyxdg                     0.28
PyYAML                    6.0.1
railroad-diagrams         3.0.1
referencing               0.30.2
reportlab                 3.6.8
requests                  2.31.0
resolvelib                1.0.1
rich                      13.5.2
rpds-py                   0.9.2
ruamel.yaml               0.17.32
ruamel.yaml.clib          0.2.7
SecretStorage             3.3.3
setuptools                68.0.0
six                       1.16.0
ssh-import-id             5.11
stevedore                 3.5.0
subprocess-tee            0.4.1
systemd-python            234
terminator                2.1.1
tomli                     2.0.1
typing-extensions         4.7.1
ubuntu-advantage-tools    8001
ubuntu-drivers-common     0.0.0
ufw                       0.36.1
unattended-upgrades       0.1
urllib3                   1.26.16
usb-creator               0.3.7
virtualenv                20.24.3
virtualenv-clone          0.3.0
virtualenvwrapper         4.8.4
wadllib                   1.3.6
wcmatch                   8.4.1
webencodings              0.5.1
websocket-client          1.6.1
wheel                     0.41.1
xkit                      0.0.0
yamllint                  1.32.0
zipp                      3.16.2
  ```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console
26 setup logging to NOTSET [DEBUG report:37]
30 find interpreter for spec PythonSpec(path=/usr/bin/python3) [INFO builtin:58]
30 proposed PythonInfo(spec=CPython3.10.12.final.0-64, exe=/usr/bin/python3, platform=linux, version='3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]', encoding_fs_io=utf-8-utf-8) [INFO builtin:65]
30 accepted PythonInfo(spec=CPython3.10.12.final.0-64, exe=/usr/bin/python3, platform=linux, version='3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]', encoding_fs_io=utf-8-utf-8) [DEBUG builtin:67]
31 filesystem is case-sensitive [DEBUG info:26]
46 create virtual environment via CPython3Posix(dest=/home/jgerzson/.virtualenvs/myvenv, clear=False, no_vcs_ignore=False, global=False) [INFO session:50]
46 create folder /home/jgerzson/.virtualenvs/myvenv/bin [DEBUG _sync:12]
46 create folder /home/jgerzson/.virtualenvs/myvenv/lib/python3.10/site-packages [DEBUG _sync:12]
46 write /home/jgerzson/.virtualenvs/myvenv/pyvenv.cfg [DEBUG pyenv_cfg:32]
46 	home = /usr/bin [DEBUG pyenv_cfg:36]
46 	implementation = CPython [DEBUG pyenv_cfg:36]
46 	version_info = 3.10.12.final.0 [DEBUG pyenv_cfg:36]
46 	virtualenv = 20.24.3 [DEBUG pyenv_cfg:36]
46 	include-system-site-packages = false [DEBUG pyenv_cfg:36]
46 	base-prefix = /usr [DEBUG pyenv_cfg:36]
46 	base-exec-prefix = /usr [DEBUG pyenv_cfg:36]
46 	base-executable = /usr/bin/python3 [DEBUG pyenv_cfg:36]
47 symlink /usr/bin/python3 to /home/jgerzson/.virtualenvs/myvenv/bin/python [DEBUG _sync:32]
47 create virtualenv import hook file /home/jgerzson/.virtualenvs/myvenv/lib/python3.10/site-packages/_virtualenv.pth [DEBUG api:91]
47 create /home/jgerzson/.virtualenvs/myvenv/lib/python3.10/site-packages/_virtualenv.py [DEBUG api:94]
47 ============================== target debug ============================== [DEBUG session:52]
47 debug via /home/jgerzson/.virtualenvs/myvenv/bin/python /usr/lib/python3/dist-packages/virtualenv/create/debug.py [DEBUG creator:200]
47 {
  "sys": {
    "executable": "/home/jgerzson/.virtualenvs/myvenv/bin/python",
    "_base_executable": "/home/jgerzson/.virtualenvs/myvenv/bin/python",
    "prefix": "/home/jgerzson/.virtualenvs/myvenv",
    "base_prefix": "/usr",
    "real_prefix": null,
    "exec_prefix": "/home/jgerzson/.virtualenvs/myvenv",
    "base_exec_prefix": "/usr",
    "path": [
      "/usr/lib/python310.zip",
      "/usr/lib/python3.10",
      "/usr/lib/python3.10/lib-dynload",
      "/home/jgerzson/.virtualenvs/myvenv/lib/python3.10/site-packages"
    ],
    "meta_path": [
      "<class '_virtualenv._Finder'>",
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib_external.PathFinder'>"
    ],
    "fs_encoding": "utf-8",
    "io_encoding": "utf-8"
  },
  "version": "3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]",
  "makefile_filename": "/usr/lib/python3.10/config-3.10-x86_64-linux-gnu/Makefile",
  "os": "<module 'os' from '/usr/lib/python3.10/os.py'>",
  "site": "<module 'site' from '/usr/lib/python3.10/site.py'>",
  "datetime": "<module 'datetime' from '/usr/lib/python3.10/datetime.py'>",
  "math": "<module 'math' (built-in)>",
  "json": "<module 'json' from '/usr/lib/python3.10/json/__init__.py'>"
} [DEBUG session:53]
64 add seed packages via FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/jgerzson/.local/share/virtualenv) [INFO session:57]
65 got embed update of distribution %s from ('pip', PosixPath('/home/jgerzson/.local/share/virtualenv/wheel/3.10/embed/3/pip.json')) [DEBUG via_disk_folder:131]
65 got embed update of distribution %s from ('wheel', PosixPath('/home/jgerzson/.local/share/virtualenv/wheel/3.10/embed/3/wheel.json')) [DEBUG via_disk_folder:131]
65 got embed update of distribution %s from ('setuptools', PosixPath('/home/jgerzson/.local/share/virtualenv/wheel/3.10/embed/3/setuptools.json')) [DEBUG via_disk_folder:131]
68 got embed update of distribution %s from ('wheel', PosixPath('/home/jgerzson/.local/share/virtualenv/wheel/3.10/embed/3/wheel.json')) [DEBUG via_disk_folder:131]
68 got embed update of distribution %s from ('pip', PosixPath('/home/jgerzson/.local/share/virtualenv/wheel/3.10/embed/3/pip.json')) [DEBUG via_disk_folder:131]
68 using periodically updated wheel /home/jgerzson/.local/share/virtualenv/wheel/house/wheel-0.38.4-py3-none-any.whl [DEBUG periodic_update:49]
68 got embed update of distribution %s from ('setuptools', PosixPath('/home/jgerzson/.local/share/virtualenv/wheel/3.10/embed/3/setuptools.json')) [DEBUG via_disk_folder:131]
68 using periodically updated wheel /home/jgerzson/.local/share/virtualenv/wheel/house/setuptools-66.0.0-py3-none-any.whl [DEBUG periodic_update:49]
68 using periodically updated wheel /home/jgerzson/.local/share/virtualenv/wheel/house/pip-22.3.1-py3-none-any.whl [DEBUG periodic_update:49]
69 install wheel from wheel /home/jgerzson/.local/share/virtualenv/wheel/house/wheel-0.38.4-py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:49]
69 install setuptools from wheel /home/jgerzson/.local/share/virtualenv/wheel/house/setuptools-66.0.0-py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:49]
69 install pip from wheel /home/jgerzson/.local/share/virtualenv/wheel/house/pip-22.3.1-py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:49]
69 Attempting to acquire lock 140131625940832 on /home/jgerzson/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/setuptools-66.0.0-py3-none-any.lock [DEBUG _api:212]
69 Attempting to acquire lock 140131639075952 on /home/jgerzson/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/wheel-0.38.4-py3-none-any.lock [DEBUG _api:212]
69 Lock 140131625940832 acquired on /home/jgerzson/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/setuptools-66.0.0-py3-none-any.lock [DEBUG _api:215]
69 Attempting to acquire lock 140131625941600 on /home/jgerzson/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/pip-22.3.1-py3-none-any.lock [DEBUG _api:212]
69 Lock 140131639075952 acquired on /home/jgerzson/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/wheel-0.38.4-py3-none-any.lock [DEBUG _api:215]
69 Lock 140131625941600 acquired on /home/jgerzson/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/pip-22.3.1-py3-none-any.lock [DEBUG _api:215]
70 Attempting to release lock 140131625940832 on /home/jgerzson/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/setuptools-66.0.0-py3-none-any.lock [DEBUG _api:244]
70 Lock 140131625940832 released on /home/jgerzson/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/setuptools-66.0.0-py3-none-any.lock [DEBUG _api:247]
70 Attempting to release lock 140131625941600 on /home/jgerzson/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/pip-22.3.1-py3-none-any.lock [DEBUG _api:244]
70 Lock 140131625941600 released on /home/jgerzson/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/pip-22.3.1-py3-none-any.lock [DEBUG _api:247]
70 Attempting to release lock 140131639075952 on /home/jgerzson/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/wheel-0.38.4-py3-none-any.lock [DEBUG _api:244]
70 copy directory /home/jgerzson/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/setuptools-66.0.0-py3-none-any/setuptools-66.0.0.dist-info to /home/jgerzson/.virtualenvs/myvenv/lib/python3.10/site-packages/setuptools-66.0.0.dist-info [DEBUG _sync:40]
70 Lock 140131639075952 released on /home/jgerzson/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/wheel-0.38.4-py3-none-any.lock [DEBUG _api:247]
70 copy directory /home/jgerzson/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/pip-22.3.1-py3-none-any/pip-22.3.1.dist-info to /home/jgerzson/.virtualenvs/myvenv/lib/python3.10/site-packages/pip-22.3.1.dist-info [DEBUG _sync:40]
71 copy directory /home/jgerzson/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/wheel-0.38.4-py3-none-any/wheel to /home/jgerzson/.virtualenvs/myvenv/lib/python3.10/site-packages/wheel [DEBUG _sync:40]
72 copy /home/jgerzson/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/setuptools-66.0.0-py3-none-any/distutils-precedence.pth to /home/jgerzson/.virtualenvs/myvenv/lib/python3.10/site-packages/distutils-precedence.pth [DEBUG _sync:40]
72 copy /home/jgerzson/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/pip-22.3.1-py3-none-any/pip-22.3.1.virtualenv to /home/jgerzson/.virtualenvs/myvenv/lib/python3.10/site-packages/pip-22.3.1.virtualenv [DEBUG _sync:40]
73 copy directory /home/jgerzson/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/setuptools-66.0.0-py3-none-any/_distutils_hack to /home/jgerzson/.virtualenvs/myvenv/lib/python3.10/site-packages/_distutils_hack [DEBUG _sync:40]
73 copy directory /home/jgerzson/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/pip-22.3.1-py3-none-any/pip to /home/jgerzson/.virtualenvs/myvenv/lib/python3.10/site-packages/pip [DEBUG _sync:40]
73 copy directory /home/jgerzson/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/setuptools-66.0.0-py3-none-any/setuptools to /home/jgerzson/.virtualenvs/myvenv/lib/python3.10/site-packages/setuptools [DEBUG _sync:40]
77 copy /home/jgerzson/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/wheel-0.38.4-py3-none-any/wheel-0.38.4.virtualenv to /home/jgerzson/.virtualenvs/myvenv/lib/python3.10/site-packages/wheel-0.38.4.virtualenv [DEBUG _sync:40]
77 copy directory /home/jgerzson/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/wheel-0.38.4-py3-none-any/wheel-0.38.4.dist-info to /home/jgerzson/.virtualenvs/myvenv/lib/python3.10/site-packages/wheel-0.38.4.dist-info [DEBUG _sync:40]
80 generated console scripts wheel3 wheel wheel3.10 wheel-3.10 [DEBUG base:43]
95 copy directory /home/jgerzson/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/setuptools-66.0.0-py3-none-any/pkg_resources to /home/jgerzson/.virtualenvs/myvenv/lib/python3.10/site-packages/pkg_resources [DEBUG _sync:40]
100 copy /home/jgerzson/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/setuptools-66.0.0-py3-none-any/setuptools-66.0.0.virtualenv to /home/jgerzson/.virtualenvs/myvenv/lib/python3.10/site-packages/setuptools-66.0.0.virtualenv [DEBUG _sync:40]
100 generated console scripts  [DEBUG base:43]
112 generated console scripts pip3.10 pip-3.10 pip3 pip [DEBUG base:43]
112 add activators for Bash, CShell, Fish, Nushell, PowerShell, Python [INFO session:63]
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 33, in <module>
    sys.exit(load_entry_point('virtualenv==20.24.3', 'console_scripts', 'virtualenv')())
  File "/usr/lib/python3/dist-packages/virtualenv/__main__.py", line 56, in run_with_catch
    run(args, options, env)
  File "/usr/lib/python3/dist-packages/virtualenv/__main__.py", line 18, in run
    session = cli_run(args, options, env)
  File "/usr/lib/python3/dist-packages/virtualenv/run/__init__.py", line 33, in cli_run
    of_session.run()
  File "/usr/lib/python3/dist-packages/virtualenv/run/session.py", line 46, in run
    self._activate()
  File "/usr/lib/python3/dist-packages/virtualenv/run/session.py", line 65, in _activate
    activator.generate(self.creator)
  File "/usr/lib/python3/dist-packages/virtualenv/activation/via_template.py", line 27, in generate
    generated = self._generate(replacements, self.templates(), dest_folder, creator)
  File "/usr/lib/python3/dist-packages/virtualenv/activation/via_template.py", line 44, in _generate
    text = self.instantiate_template(replacements, template, creator)
  File "/usr/lib/python3/dist-packages/virtualenv/activation/via_template.py", line 60, in instantiate_template
    binary = read_binary(self.__module__, template)
  File "/usr/lib/python3/dist-packages/virtualenv/activation/via_template.py", line 13, in read_binary
    return (files(module_name) / filename).read_bytes()
  File "/usr/lib/python3.10/pathlib.py", line 1126, in read_bytes
    with self.open(mode='rb') as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/virtualenv/activation/bash/activate.sh'
```

**Comment by gaborbernat** [comment]
Sounds like you're using virtualenv from your distro and they messed up packaging. Please submit the bug to them, not here.

**Comment by grzs** [comment]
That was my bet too, I just wanted to be sure that it's not a hidden branch
of virtualenv or something like that.

Thanks / Köszönöm a gyors választ!

Bernát Gábor ***@***.***> ezt írta (időpont: 2023. aug. 24.,
Cs, 15:46):
