### ISSUE TITLE
RuntimeError: no .dist-info python3.9 macos

### ISSUE THREAD

**Issue by babanesma** [pypa/virtualenv#2630]
**Issue**

I noticed this error when I upgraded python3.9 through brew upgrade , then I create a fresh git repo to test
Whenever I run `pre-commit` or run `git commit` I get this error

```
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/usr/local/opt/python@3.9/bin/python3.9', '-mvirtualenv', '/Users/adhamsaad/.cache/pre-commit/repo3pmq58n0/py_env-python3.9')
return code: 1
stdout:
    RuntimeError: failed to build image pip because:
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 57, in _install
        installer.install(creator.interpreter.version_info)
      File "/usr/local/lib/python3.9/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 33, in install
        self._uninstall_previous_version()
      File "/usr/local/lib/python3.9/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 144, in _uninstall_previous_version
        dist_name = self._dist_info.stem.split("-")[0]
      File "/usr/local/lib/python3.9/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 110, in _dist_info
        raise RuntimeError(msg)  # pragma: no cover
    RuntimeError: no .dist-info at /Users/adhamsaad/Library/Application Support/virtualenv/wheel/3.9/image/1/CopyPipInstall/pip-23.2.1-py3-none-any, has pip
stderr: (none)
Check the log at /Users/adhamsaad/.cache/pre-commit/pre-commit.log
```

I created an [issue](https://github.com/pre-commit/pre-commit/issues/2976) at pre-commit but they claim it's a virtualenv issue 

**Environment**

Provide at least:

- OS: MacOS
- `pip list` of the host python where `virtualenv` is installed:

```console
(venv) ➜  test-pre-commit git:(main) ✗ pip list                       
Package            Version
------------------ ---------
certifi            2023.7.22
cfgv               3.4.0
charset-normalizer 3.2.0
distlib            0.3.7
filelock           3.12.2
identify           2.5.27
idna               3.4
nodeenv            1.8.0
pip                23.2.1
platformdirs       3.10.0
pre-commit         3.3.3
PyYAML             6.0.1
requests           2.31.0
setuptools         68.1.2
urllib3            2.0.4
virtualenv         20.24.3
```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console

```

**Comment by gaborbernat** [comment]
Delete /Users/adhamsaad/Library/Application Support/virtualenv and try again.
