### ISSUE TITLE
mkvirtualenv fails with: ModuleNotFoundError: No module named 'platformdirs'

### ISSUE THREAD

**Issue by orome** [pypa/virtualenv#2676]
**Issue**

Can no longer run `mkvirtualenv`. I get: `ModuleNotFoundError: No module named 'platformdirs'`

For years I've just used the following without issue, but not it no longer works.

```
brew install virtualenv
mkvirtualenv --python=`which python` FOO
```

**Environment**

Provide at least:

- OS: macOS 14.1.2 
- `pip list` of the host python where `virtualenv` is installed:

  ```console
Package    Version
---------- -------
docutils   0.20.1
gpg        1.23.2
gpg        1.23.2
gpg        1.23.2
pip        23.2.1
protobuf   4.25.1
setuptools 69.0.2
virtualenv 20.25.0
wheel      0.41.2
  ```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console
Traceback (most recent call last):
  File "/opt/homebrew/bin/virtualenv", line 5, in <module>
    from virtualenv.__main__ import run_with_catch
  File "/opt/homebrew/lib/python3.12/site-packages/virtualenv/__init__.py", line 3, in <module>
    from .run import cli_run, session_via_cli
  File "/opt/homebrew/lib/python3.12/site-packages/virtualenv/run/__init__.py", line 7, in <module>
    from virtualenv.app_data import make_app_data
  File "/opt/homebrew/lib/python3.12/site-packages/virtualenv/app_data/__init__.py", line 8, in <module>
    from platformdirs import user_data_dir
ModuleNotFoundError: No module named 'platformdirs'
```

**Comment by orome** [comment]
> Report it to mkvirtualenv, this is not that project. Probably bad installation.

A bad install of virtualenv though, no?
