### ISSUE TITLE
ensure tkinter works in virtualenv

### ISSUE THREAD

**Issue by yogeshc** [pypa/virtualenv#425]
On a virtualenv I get the following:

``` bash
DataVizProj)$ python
Python 2.7.3 |CUSTOM| (default, Apr 11 2012, 18:02:54) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-44)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import Tkinter
>>> Tkinter.Tk()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/epd/epd-7.3-2-rh5-x86/lib/python2.7/lib-tk/Tkinter.py", line 1685, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    /home/builder/work/core/lib/tcl8.5 /opt/Envs/DataVizProj/lib/tcl8.5 /opt/Envs/lib/tcl8.5 /opt/Envs/DataVizProj/library /opt/Envs/library /opt/Envs/tcl8.5.9/library /opt/tcl8.5.9/library


This probably means that Tcl wasn't installed properly.


>>> quit()
(DataVizProj)$ deactivate 
```

But it works outside fine once I deactivate it:

``` bash
$ python
Enthought Python Distribution -- www.enthought.com
Version: 7.3-2 (32-bit)

Python 2.7.3 |EPD 7.3-2 (32-bit)| (default, Apr 11 2012, 18:02:54) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-44)] on linux2
Type "credits", "demo" or "enthought" for more information.
>>> import Tkinter
>>> Tkinter.Tk()
<Tkinter.Tk instance at 0xb73f7fcc>
```

I guess this is similar to Issue #56  But this is on Ubuntu based distro

**Comment by c0d3h4x0r** [comment]
This is still an issue on Mac.  Someone need to reactivate this issue.  Just because it has sat around without getting any traction, that doesn't mean it's no longer an issue.  It just means the project maintainers have not prioritized it like they should.

**Comment by gaborbernat** [comment]
Hello, just to clear up things here. Project maintainers "should" do something is a very bad way to look at this. This is an open source project, project maintainers maintain the package, which means they ensure that patches applied don't break the world, as much as possible. If there's issue please look it in the spirit of open source and post a solution pull request, rather then telling them off for not solving it for you.

**Comment by gaborbernat** [comment]
Seems no longer an issue as no one reported it in 3 years.

**Comment by LexiconCode** [comment]
> Seems no longer an issue as no one reported it in 3 years.

Python 3.10.13 (main, Feb 25 2024, 03:45:35) [MSC v.1929 32 bit (Intel)] on win32
```
(venv) C:\Users\MainLaptop\Desktop\natlink_vert>python -m tkinter
Traceback (most recent call last):
  File "C:\Users\MainLaptop\Desktop\natlink_vert\setup_files\base_python\3.10.13\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\MainLaptop\Desktop\natlink_vert\setup_files\base_python\3.10.13\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\MainLaptop\Desktop\natlink_vert\setup_files\base_python\3.10.13\python\lib\tkinter\__main__.py", line 7, in <module>
    main()
  File "C:\Users\MainLaptop\Desktop\natlink_vert\setup_files\base_python\3.10.13\python\lib\tkinter\__init__.py", line 4596, in _test
    root = Tk()
  File "C:\Users\MainLaptop\Desktop\natlink_vert\setup_files\base_python\3.10.13\python\lib\tkinter\__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable tk.tcl in the following directories:
    C:/Users/MainLaptop/Desktop/natlink_vert/setup_files/base_python/3.10.13/python/tcl/tcl8.6/tk8.6 C:/Users/MainLaptop/Desktop/natlink_vert/setup_files/base_python/3.10.13/python/tcl/tk8.6 C:/Users/MainLaptop/Desktop/natlink_vert/setup_files/base_python/3.10.13/lib/tk8.6 C:/Users/MainLaptop/Desktop/natlink_vert/setup_files/base_python/3.10.13/lib/tk8.6 C:/Users/MainLaptop/Desktop/natlink_vert/setup_files/base_python/lib/tk8.6 C:/Users/MainLaptop/Desktop/natlink_vert/setup_files/base_python/3.10.13/library
```

**Comment by c0d3h4x0r** [comment]
It's still an issue. We just worked around it in our own systems by copying the right files into the right places ourselves.

**Comment by c0d3h4x0r** [comment]
This issue needs to be reopened. It shouldn't have been closed in the first place.

**Comment by gaborbernat** [comment]
PR welcome.

**Comment by LexiconCode** [comment]
> PR welcome. 

I apologize my issue ended up being related to the standalone python build not the virtual environment.
