### ISSUE TITLE
Unable to create vrtualenv with 1.11 (when virtualenv installed by ez_install/setuptools)

### ISSUE THREAD

**Issue by s0undt3ch** [pypa/virtualenv#524]
```
# virtualenv /tmp/123
Overwriting /tmp/123/lib/python2.7/site.py with new content
New python executable in /tmp/123/bin/python
Installing setuptools, pip...
  Complete output from command /tmp/123/bin/python -c "import sys, pip; pip...ll\"] + sys.argv[1:])" setuptools pip:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/virtualenv-1.11-py2.7.egg/virtualenv_support/pip-1.5-py2.py3-none-any.whl/pip/__init__.py", line 9, in <module>
  File "/usr/local/lib/python2.7/dist-packages/virtualenv-1.11-py2.7.egg/virtualenv_support/pip-1.5-py2.py3-none-any.whl/pip/log.py", line 8, in <module>
  File "/usr/local/lib/python2.7/dist-packages/virtualenv-1.11-py2.7.egg/virtualenv_support/setuptools-2.0.2-py2.py3-none-any.whl/pkg_resources.py", line 2696, in <module>
    def _dep_map(self):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv-1.11-py2.7.egg/virtualenv_support/setuptools-2.0.2-py2.py3-none-any.whl/pkg_resources.py", line 429, in __init__
    def get_resource_stream(manager, resource_name):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv-1.11-py2.7.egg/virtualenv_support/setuptools-2.0.2-py2.py3-none-any.whl/pkg_resources.py", line 443, in add_entry
    """Is the named resource a directory?  (like ``os.path.isdir()``)"""
  File "/usr/local/lib/python2.7/dist-packages/virtualenv-1.11-py2.7.egg/virtualenv_support/setuptools-2.0.2-py2.py3-none-any.whl/pkg_resources.py", line 1722, in find_in_zip
    except AttributeError:
  File "/usr/local/lib/python2.7/dist-packages/virtualenv-1.11-py2.7.egg/virtualenv_support/setuptools-2.0.2-py2.py3-none-any.whl/pkg_resources.py", line 1298, in has_metadata
    def test(nodelist):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv-1.11-py2.7.egg/virtualenv_support/setuptools-2.0.2-py2.py3-none-any.whl/pkg_resources.py", line 1614, in _has
    def _parts(self,zip_path):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv-1.11-py2.7.egg/virtualenv_support/setuptools-2.0.2-py2.py3-none-any.whl/pkg_resources.py", line 1488, in _zipinfo_name
    "Can't perform this operation for loaders without 'get_data()'"
AssertionError: /usr/local/lib/python2.7/dist-packages/virtualenv-1.11-py2.7.egg/EGG-INFO/PKG-INFO is not a subpath of /usr/local/lib/python2.7/dist-packages/virtualenv-1.11-py2.7.egg/virtualenv_support/setuptools-2.0.2-py2.py3-none-any.whl/
----------------------------------------
...Installing setuptools, pip...done.
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 9, in <module>
    load_entry_point('virtualenv==1.11', 'console_scripts', 'virtualenv')()
  File "/usr/local/lib/python2.7/dist-packages/virtualenv-1.11-py2.7.egg/virtualenv.py", line 820, in main
    symlink=options.symlink)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv-1.11-py2.7.egg/virtualenv.py", line 988, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv-1.11-py2.7.egg/virtualenv.py", line 956, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/usr/local/lib/python2.7/dist-packages/virtualenv-1.11-py2.7.egg/virtualenv.py", line 898, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /tmp/123/bin/python -c "import sys, pip; pip...ll\"] + sys.argv[1:])" setuptools pip failed with error code 1
```

```
# python -V
Python 2.7.3
```

```
# pip freeze
Cheetah==2.4.4
GnuPGInterface==0.3.2
Jinja2==2.6
Landscape-Client==12.05
M2Crypto==0.21.1
MarkupSafe==0.15
PAM==0.4.2
PyYAML==3.10
SaltTesting==0.5.5
Twisted-Core==11.1.0
apache-libcloud==0.13.3
apt-xapian-index==0.44
argparse==1.2.1
boto==2.2.2
chardet==2.0.1
cloud-init==0.6.3
command-not-found==0.2.44
configobj==4.7.2
coverage==3.7.1
euca2ools==2.0.0
httplib2==0.7.2
keyring==0.9.2
language-selector==0.1
launchpadlib==1.9.12
lazr.restfulclient==0.12.0
lazr.uri==1.0.3
mock==1.0.1
msgpack-python==0.1.10
oauth==1.0.1
paramiko==1.7.7.1
pyOpenSSL==0.12
pycrypto==2.4.1
pycurl==7.19.0
pyserial==2.5
python-apt==0.8.3ubuntu7.1
python-debian==0.1.21ubuntu1
pyzmq==13.0.0
salt==2014.1.0-31-g0998b54
simplejson==2.3.2
timelib==0.2.4
ufw==0.31.1-1
unattended-upgrades==0.1
unittest-xml-reporting==1.7.0
virtualenv==1.11
wadllib==1.3.0
wsgiref==0.1.2
zope.interface==3.6.1
```

Is there any more info that I can provide?

**Comment by gkoshyk** [comment]
Looks like a similar error, Please help!
$virtualenv venv

New python executable in venv/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /Users/george/D...ores/venv/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/george/anaconda/lib/python2.7/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/__init__.py", line 13, in <module>
  File "/Users/george/anaconda/lib/python2.7/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/utils/__init__.py", line 15, in <module>
  File "/Users/george/anaconda/lib/python2.7/zipfile.py", line 6, in <module>
    import io
  File "/Users/george/anaconda/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/Users/george/Downloads/flaskApps/userScores/venv/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyErr_ReplaceException
  Referenced from: /Users/george/Downloads/flaskApps/userScores/venv/lib/python2.7/lib-dynload/_io.so
  Expected in: dynamic lookup

----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/Users/george/anaconda/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/Users/george/anaconda/lib/python2.7/site-packages/virtualenv.py", line 832, in main
    symlink=options.symlink)
  File "/Users/george/anaconda/lib/python2.7/site-packages/virtualenv.py", line 1004, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/Users/george/anaconda/lib/python2.7/site-packages/virtualenv.py", line 969, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/Users/george/anaconda/lib/python2.7/site-packages/virtualenv.py", line 910, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/george/D...ores/venv/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 1

**Comment by aronysidoro** [comment]
I am having a similar error on Centos 7 with Python 3.3. 

Has anyone been able to solve this??

Here's my command:

```
virtualenv -p /usr/local/bin/python3 ~/.virtualenvs/bs_py3
```

And Error:

```
[~]$ virtualenv -p /usr/local/bin/python3 ~/.virtualenvs/bs_py3
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local'
New python executable in /home/vagrant/.virtualenvs/bs_py3/bin/python3
Not overwriting existing python script /home/vagrant/.virtualenvs/bs_py3/bin/python (you must use /home/vagrant/.virtualenvs/bs_py3/bin/python3)
Installing setuptools, pip, wheel...
  Complete output from command /home/vagrant/.virtualenvs/bs_py3/bin/python3 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/__init__.py", line 15, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/vcs/subversion.py", line 9, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/index.py", line 30, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/wheel.py", line 35, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/_vendor/distlib/scripts.py", line 14, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/_vendor/distlib/compat.py", line 66, in <module>
ImportError: cannot import name HTTPSHandler
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 832, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 1004, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 969, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 910, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/vagrant/.virtualenvs/bs_py3/bin/python3 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 1
```

**Comment by ellockie** [comment]
I had a very similar issues on my <strong>Windows 7</strong> machine. Both paths, to python and to my VE had <strong>spaces</strong> in it. Couple of months before it worked fine. I found the following note on virtualenv website: 

<i><strong>Windows Notes</strong>
[...] To create a virtualenv under a path with spaces in it on Windows, you’ll need the win32api library installed.</i>
The following steps lead me to success:
<ol>
<li>Make sure I used pip to install virtualenv and it's the latest version (pip-7.1.0). Result: failure</li>
<li>Install <strong>win32api</strong>. Result: failure (although there was some error at the very end of installation process).</li>
<li>Try to install my VE in a path without spaces. Result: failure.</li>
<li>Reinstall my Anaconda python distribution to the path that didn't contain the "[" and "]" brackets. VE had spaces in the path. Result: failure.</li>
<li>Reinstall my Anaconda python distribution to the path that also didn't contain any spaces. VE had spaces in the path. Result: <strong>success!</strong></li>
</ol>
So at least the Anaconda (python) installation simple, non space-pollutted path was crucial. Maybe win32api installation was also important. Not sure.

**Comment by ShuaiW** [comment]
@gkoshyk I have the exact same issue as you did. Did you solve it?

**Comment by dustinlakin** [comment]
I was recently getting this error on OS X 10.10.4. I ended up doing a fresh install of python (2.7.9) with brew, reopened my terminal and "virtualenv venv" worked fine.

**Comment by RoboGenius** [comment]
When I recently ran in to this problem within a Windows installation of Python 2.7.10 and the latest update for virtualenv and setuptools, I hit the internet and found nothing but "this is already fixed" messages from 2014. Thank you to @ellockie for suggesting the simple solution of making sure Python is installed in a path without any spaces. I uninstalled my current installation (c:\DevTools\Python 27), and reinstalled to a new directory (c:\DevTools\Python27) and it worked the first time. Cheers!

**Comment by gkoshyk** [comment]
@ShuaiW I was not able to resolve it.

**Comment by downunder54** [comment]
I just did a "brew install python" on Yosemite followed by "virtualenv flaskapp" but it still conks out with "OSError: Command /Users/foo/src/python/flaskapp/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1"
Any ideas anyone?

**Comment by downunder54** [comment]
on the pip install it mentions: "AttributeError: 'module' object has no attribute 'mac_ver'"

**Comment by drewberes** [comment]
@RoboGenius your fix resolved my issue

**Comment by Ivoz** [comment]
Hi there, could all new comments with a similar problem please open a new issue instead of posting a comment. This issue is getting far too convoluted, and its hard to see if problems mentioned are all coming from the same source or have differences.

**Comment by shintojoseph1234** [comment]
This will work for virtualenv pip wheel errorcode1 problems and also E unable to locate package problems

    apt-get update

    apt-get install python-software-properties

    apt-get install apt-file

    apt-file update

    apt-get install software-properties-common

    apt-get install <your filename>

**Comment by mohammedyunus009** [comment]
Even i was having the same problem with python virtualenv It got corrected by a simple restart

`sudo shutdown -r now`
