### ISSUE TITLE
test_always_copy_option() fails

### ISSUE THREAD

**Issue by Arfrever** [pypa/virtualenv#530]
test_always_copy_option() fails with all Python versions (2.6, 2.7, 3.1, 3.2, 3.3).

```
$ nosetests-2.7
.......E
======================================================================
ERROR: Should be no symlinks in directory tree
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/virtualenv/tests/test_virtualenv.py", line 131, in test_always_copy_option
    virtualenv.create_environment(ve_path, symlink=False)
  File "/tmp/virtualenv/virtualenv.py", line 984, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/tmp/virtualenv/virtualenv.py", line 952, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/tmp/virtualenv/virtualenv.py", line 894, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /tmp/tmp_As_WG/venv/bin/python2.7 -c "import sys, pip; pip...ll\"] + sys.argv[1:])" setuptools pip failed with error code 1

----------------------------------------------------------------------
Ran 8 tests in 0.623s

FAILED (errors=1)
```

**Comment by blueyed** [comment]
I assume this has been fixed in the meantime?

@Arfrever 
Is it still an issue for you?

**Comment by blueyed** [comment]
For reference, it currently fails with pypy 2.5.0 - but with a different error: https://github.com/pypa/virtualenv/issues/725

**Comment by Arfrever** [comment]
Error is still reproducible in virtualenv trunk.

**Comment by opoplawski** [comment]
I seem to see this testing locally, but not in Fedora rpm builds of virtualenv in koji.  Failing command seems to be:

/tmp/tmpRyOd9Y/venv/bin/python -c "import sys, pip; sys.exit(pip.main([\"install\", \"--ignore-installed\"] + sys.argv[1:]))" setuptools pip

error is:

ImportError: No module named time

**Comment by opoplawski** [comment]
Scratch that - 12.1.1 is failing in koji as well.
