### ISSUE TITLE
virtualenv-1.11.2 not compatible with Python-2.6 anymore

### ISSUE THREAD

**Issue by cecton** [pypa/virtualenv#572]
Hello,

**Sorry I'm totally new with virtualenv so this issue may be false.**

-   I downloaded and compiled Python2.6.

-   I tried to run my virtualenv-1.11.2 provided by my distribution (which is virtualenv-1.11.2) using Python-2.6 and it fails while trying to import pip.

-   I tried to make a simple test to make sure it is an incompatibility problem:

    -   export the ```PYTHONPATH``` make sure it will use the system virtualenv-1.11.2
    -   start python2.6 and simply import pip

```
[09:22:12] ~> set -x PYTHONPATH /usr/lib/python2.7/site-packages/virtualenv_support/pip-1.5.2py2.py3-none-any.whl
[09:22:32] ~> ./env_2.6/bin/python -c 'import pip'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-1.5.2-py2.py3-none-any.whl/pip/__init__.py", line 11, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-1.5.2-py2.py3-none-any.whl/pip/vcs/subversion.py", line 4, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-1.5.2-py2.py3-none-any.whl/pip/index.py", line 17, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-1.5.2-py2.py3-none-any.whl/pip/_vendor/html5lib/__init__.py", line 16, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-1.5.2-py2.py3-none-any.whl/pip/_vendor/html5lib/html5parser.py", line 7, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-1.5.2-py2.py3-none-any.whl/pip/_vendor/html5lib/tokenizer.py", line 21, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-1.5.2-py2.py3-none-any.whl/pip/_vendor/html5lib/trie/py.py", line 12, in __init__
TypeError: All keys must be strings
```

It is the exact same error. Am I right to conclude that if Python-2.6 can't import pip from virtualenv-1.11.2, it means that the module is not compatible anymore?

I downloaded virtualenv-1.9.1, use setup.py to install the library in my Python2.6 environment, and run the same test. It works fine.

After that, I downloaded the same version of my system of virtualenv and install in my Python2.6 environment. I got the very same error:

```
[09:58:30] ~> set -e PYTHONPATH
[10:13:46] ~> env_2.6/bin/virtualenv -p env_2.6/bin/python /tmp/new_env
New python executable in /tmp/new_env/bin/python
Installing setuptools, pip...
  Complete output from command /tmp/new_env/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/cecile/env_2.6/lib/python2.6/site-packages/virtualenv_support/pip-1.5.2-py2.py3-none-any.whl/pip/__init__.py", line 11, in <module>
  File "/home/cecile/env_2.6/lib/python2.6/site-packages/virtualenv_support/pip-1.5.2-py2.py3-none-any.whl/pip/vcs/subversion.py", line 4, in <module>
  File "/home/cecile/env_2.6/lib/python2.6/site-packages/virtualenv_support/pip-1.5.2-py2.py3-none-any.whl/pip/index.py", line 17, in <module>
  File "/home/cecile/env_2.6/lib/python2.6/site-packages/virtualenv_support/pip-1.5.2-py2.py3-none-any.whl/pip/_vendor/html5lib/__init__.py", line 16, in <module>
  File "/home/cecile/env_2.6/lib/python2.6/site-packages/virtualenv_support/pip-1.5.2-py2.py3-none-any.whl/pip/_vendor/html5lib/html5parser.py", line 7, in <module>
  File "/home/cecile/env_2.6/lib/python2.6/site-packages/virtualenv_support/pip-1.5.2-py2.py3-none-any.whl/pip/_vendor/html5lib/tokenizer.py", line 21, in <module>
  File "/home/cecile/env_2.6/lib/python2.6/site-packages/virtualenv_support/pip-1.5.2-py2.py3-none-any.whl/pip/_vendor/html5lib/trie/py.py", line 12, in __init__
TypeError: All keys must be strings
----------------------------------------
...Installing setuptools, pip...done.
Traceback (most recent call last):
  File "/home/cecile/env_2.6/lib/python2.6/site-packages/virtualenv.py", line 2338, in <module>
    main()
  File "/home/cecile/env_2.6/lib/python2.6/site-packages/virtualenv.py", line 824, in main
    symlink=options.symlink)
  File "/home/cecile/env_2.6/lib/python2.6/site-packages/virtualenv.py", line 992, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/home/cecile/env_2.6/lib/python2.6/site-packages/virtualenv.py", line 960, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/home/cecile/env_2.6/lib/python2.6/site-packages/virtualenv.py", line 902, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /tmp/new_env/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1
Running virtualenv with interpreter env_2.6/bin/python
```

Hope to not make a mistake.

Edit: tested virtualenv-1.11.2 with Python-2.6.5, it works fine

Best regards

**Comment by nueverest** [comment]
This still seems to not work for Python 2.6=>, and it doesn't look like anyone wants to take it further.  The only reason this would be nice is for compatibility testing.

**Comment by cecton** [comment]
Well, in the meantime I dropped the compatibility with Python<2.7 in my libs, so I don't really care anymore. If it's not for me you can keep the issue opened, otherwise you can close it.

**Comment by Ivoz** [comment]
Ok, seems mainly an issue that is with running a non-current 2.6 - The latest is 2.6.9. I'd hope distros would be at least updating to latest patch/security fixes for their distributions of software.
