### ISSUE TITLE
"ImportError: No module named datetime" - Werkzeug running inside a rebuilt virtualenv.

### ISSUE THREAD

**Issue by ModerationMike** [pypa/virtualenv#574]
I have a fresh installed cloud server with Ubuntu 12.04 LTS, python 2.7.3 and virtualenv 1.11.4.

I do the following in my webfoot for nginx:
- virtualenv venv
- . venv/bin/activate
- pip install uwsgi
- pip install flask

To host a simple Flask app. On a fresh box I have no issue. However if I remove the venv dir with a rm command after deactivate and do the same install I get these errors.

```
Traceback (most recent call last):
  File "/var/www/onsite/onsite.py", line 1, in <module>
    from flask import Flask
  File "/var/www/onsite/venv/local/lib/python2.7/site-packages/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "/var/www/onsite/venv/local/lib/python2.7/site-packages/werkzeug/__init__.py", line 154, in <module>
    __import__('werkzeug.exceptions')
  File "/var/www/onsite/venv/local/lib/python2.7/site-packages/werkzeug/exceptions.py", line 67, in <module>
    from werkzeug._internal import _get_environ
  File "/var/www/onsite/venv/local/lib/python2.7/site-packages/werkzeug/_internal.py", line 15, in <module>
    from datetime import datetime, date
ImportError: No module named date time
```

Tried multiple deletes and re-install of the venv. Spinning up a new host fixes the issue until the venv is removed or pip installs are made to it down the line. Whats breaking here?

**Comment by dddmw** [comment]
Why datetime not in the REQUIRED_MODULES  in virtualenv.py?

**Comment by gaborbernat** [comment]
We only copy stuff that is used before we can trigger the ``site.py`` import/package discovery mechanism.

**Comment by gaborbernat** [comment]
This should be fixed by the rewrite branch.
