### ISSUE TITLE
ImportError: No module named optparse.

### ISSUE THREAD

**Issue by biergaizi** [pypa/virtualenv#576]
Many Python Programs depends on Virtualenv, but I can not get it works on Gentoo ~mips N32. As an example, it caused Firefox unbuildable.

But both Python 2 & 3 works well on the system, it seems some files are not copied/symlinked to the prefix correctly. /lib on N32 is not a symlink of /lib32 or /lib64, maybe it is the reason? 

As a Pythonista, I don't know the actual reason... 

```
➜  virtualenv-1.11.4  ./virtualenv.py test_virtualenv 
New python executable in test_virtualenv/bin/python2.7 
Not overwriting existing python script test_virtualenv/bin/python (you must use test_virtualenv/bin/python2.7) 
Installing setuptools, pip... 
  Complete output from command /tmp/virtualenv-1.11...ualenv/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip: 
  Traceback (most recent call last): 
  File "<string>", line 1, in <module> 
  File "/tmp/virtualenv-1.11.4/virtualenv_support/pip-1.5.4-py2.py3-none-any.whl/pip/__init__.py", line 3, in <module> 
ImportError: No module named optparse 
---------------------------------------- 
...Installing setuptools, pip...done. 
Traceback (most recent call last): 
  File "./virtualenv.py", line 2338, in <module> 
    main() 
  File "./virtualenv.py", line 824, in main 
    symlink=options.symlink) 
  File "./virtualenv.py", line 992, in create_environment 
    install_wheel(to_install, py_executable, search_dirs) 
  File "./virtualenv.py", line 960, in install_wheel 
    'PIP_NO_INDEX': '1' 
  File "./virtualenv.py", line 902, in call_subprocess 
    % (cmd_desc, proc.returncode)) 
OSError: Command /tmp/virtualenv-1.11...ualenv/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1 
```

```
test_virtualenv 
├── bin 
│   ├── python -> python2.7 
│   ├── python2 -> python2.7 
│   └── python2.7 
├── include 
│   └── python2.7 -> /usr/include/python2.7 
├── lib 
│   └── python2.7 
│       ├── config -> /usr/lib32/python2.7/config 
│       ├── lib-dynload -> /usr/lib32/python2.7/lib-dynload 
│       └── site-packages 
└── lib32 
    └── python2.7 
        ├── _abcoll.py -> /usr/lib32/python2.7/_abcoll.py 
        ├── _abcoll.pyc 
        ├── abc.py -> /usr/lib32/python2.7/abc.py 
        ├── abc.pyc 
        ├── codecs.py -> /usr/lib32/python2.7/codecs.py 
        ├── codecs.pyc 
        ├── copy_reg.py -> /usr/lib32/python2.7/copy_reg.py 
        ├── copy_reg.pyc 
        ├── distutils 
        │   ├── distutils.cfg 
        │   └── __init__.py 
        ├── encodings -> /usr/lib32/python2.7/encodings 
        ├── fnmatch.py -> /usr/lib32/python2.7/fnmatch.py 
        ├── genericpath.py -> /usr/lib32/python2.7/genericpath.py 
        ├── genericpath.pyc 
        ├── lib-dynload 
        │   ├── readline.so -> /usr/lib32/python2.7/lib-dynload/readline.so 
        │   └── zlib.so -> /usr/lib32/python2.7/lib-dynload/zlib.so 
        ├── linecache.py -> /usr/lib32/python2.7/linecache.py 
        ├── linecache.pyc 
        ├── locale.py -> /usr/lib32/python2.7/locale.py 
        ├── no-global-site-packages.txt 
        ├── ntpath.py -> /usr/lib32/python2.7/ntpath.py 
        ├── orig-prefix.txt 
        ├── os.py -> /usr/lib32/python2.7/os.py 
        ├── os.pyc 
        ├── posixpath.py -> /usr/lib32/python2.7/posixpath.py 
        ├── posixpath.pyc 
        ├── re.py -> /usr/lib32/python2.7/re.py 
        ├── site.py 
        ├── site.pyc 
        ├── sre_compile.py -> /usr/lib32/python2.7/sre_compile.py 
        ├── sre_constants.py -> /usr/lib32/python2.7/sre_constants.py 
        ├── sre_parse.py -> /usr/lib32/python2.7/sre_parse.py 
        ├── sre.py -> /usr/lib32/python2.7/sre.py 
        ├── stat.py -> /usr/lib32/python2.7/stat.py 
        ├── stat.pyc 
        ├── types.py -> /usr/lib32/python2.7/types.py 
        ├── types.pyc 
        ├── UserDict.py -> /usr/lib32/python2.7/UserDict.py 
        ├── UserDict.pyc 
        ├── warnings.py -> /usr/lib32/python2.7/warnings.py 
        ├── warnings.pyc 
        ├── _weakrefset.py -> /usr/lib32/python2.7/_weakrefset.py 
        └── _weakrefset.pyc 

13 directories, 45 files 
```

**Comment by fuzzy76** [comment]
I am seeing this on Debian... Anyone found a fix?

**Comment by tanin47** [comment]
I encountered the same problem only when we use `python -S` (http://tanin.nanakorn.com/blogs/362). Using `python` without `-S` works fine. It might be related here.
