### ISSUE TITLE
bootstrap failure / can't find pyconfig.h

### ISSUE THREAD

**Issue by vbabiy** [pypa/virtualenv#59]
Trying to create a virtualenv (using 1.4.3) on a 64-bit Mandriva 2010 system yields the following:

```
#!shell
$ virtualenv /tmp/X
New python executable in /tmp/X/bin/python
Please make sure you remove any previous custom paths from your /home/antoine/.pydistutils.cfg file.
Installing setuptools....
  Complete output from command /tmp/X/bin/python -c "#!python
\"\"\"Bootstrap setuptoo...




" /usr/lib/python2.6/site-packag...6.egg:
  error: invalid Python installation: unable to open /tmp/X/include/multiarch-x86_64-linux/python2.6/pyconfig.h (No such file or directory)
----------------------------------------
...Installing setuptools...done.
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 8, in <module>
    load_entry_point('virtualenv==1.4.3', 'console_scripts', 'virtualenv')()
  File "/usr/lib/python2.6/site-packages/virtualenv-1.4.3-py2.6.egg/virtualenv.py", line 528, in main
    use_distribute=options.use_distribute)
  File "/usr/lib/python2.6/site-packages/virtualenv-1.4.3-py2.6.egg/virtualenv.py", line 618, in create_environment
    install_setuptools(py_executable, unzip=unzip_setuptools)
  File "/usr/lib/python2.6/site-packages/virtualenv-1.4.3-py2.6.egg/virtualenv.py", line 361, in install_setuptools
    _install_req(py_executable, unzip)
  File "/usr/lib/python2.6/site-packages/virtualenv-1.4.3-py2.6.egg/virtualenv.py", line 337, in _install_req
    cwd=cwd)
  File "/usr/lib/python2.6/site-packages/virtualenv-1.4.3-py2.6.egg/virtualenv.py", line 589, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /tmp/X/bin/python -c "#!python
\"\"\"Bootstrap setuptoo...




" /usr/lib/python2.6/site-packag...6.egg failed with error code 1
```

---
- Bitbucket: https://bitbucket.org/ianb/virtualenv/issue/13
- Originally Reported By: Antoine Pitrou
- Originally Created At: 2009-11-27 20:49:55

**Comment by gaborbernat** [comment]
I think this should be fixed, we don't support Python 2.6 anymore but if you can reproduce it with 2.7+ open it again.
