### ISSUE TITLE
option always-copy doesn't work with OOTB CentOS 6.5

### ISSUE THREAD

**Issue by ericfrederich** [pypa/virtualenv#605]
Using the latest release of CentOS (6.5)
Install virtualenv as root:

```
yum install python-setuptools
easy_install pip
pip install virtualenv
```

As a regular user try to use --always-copy option with virtualenv:

``````
$ virtualenv --always-copy foo
Cannot find file lib (bad symlink)
New python executable in foo/bin/python
Installing setuptools, pip...
  Complete output from command /home/frede00e/foo/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/virtualenv_support/pip-1.5.5-py2.py3-none-any.whl/pip/__init__.py", line 9, in <module>
  File "/usr/lib/python2.6/site-packages/virtualenv_support/pip-1.5.5-py2.py3-none-any.whl/pip/log.py", line 6, in <module>
  File "/usr/lib64/python2.6/logging/__init__.py", line 34, in <module>
    import sys, os, types, time, string, cStringIO, traceback
ImportError: No module named time
----------------------------------------
...Installing setuptools, pip...done.
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 9, in <module>
    load_entry_point('virtualenv==1.11.5', 'console_scripts', 'virtualenv')()
  File "/usr/lib/python2.6/site-packages/virtualenv.py", line 824, in main
    symlink=options.symlink)
  File "/usr/lib/python2.6/site-packages/virtualenv.py", line 992, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/usr/lib/python2.6/site-packages/virtualenv.py", line 960, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/usr/lib/python2.6/site-packages/virtualenv.py", line 902, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/frede00e/foo/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1```
``````

**Comment by selurvedu** [comment]
I've encountered this issue on Gentoo x86_64 too. The error messages are same as above, except one thing – this happens with Python 2.7.
