### ISSUE TITLE
pip does not work with DONTWRITEPYTHONBYTECODE=1

### ISSUE THREAD

**Issue by vbabiy** [pypa/virtualenv#62]
Hi, I'm not sure there is a problem with virtualenv or pip. I have installed pip globally with

```
easy_install -f http://bitbucket.org/ianb/pip/get/tip.gz#egg=pip pip
```

and it worked. Then I installed virtualenv with

```
pip install -e hg+http://bitbucket.org/ianb/virtualenv#egg=virtualenv
```

and created a virtual environment. The problem is pip does not work within the virtual environment:

```
$ pip help

Traceback (most recent call last):
  File "/home/jbar/.virtualenvs/bonus/bin/pip", line 5, in <module>
    pkg_resources.run_script('pip==0.7.1', 'pip')
  File "/home/jbar/.virtualenvs/bonus/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg/pkg_resources.py", line 489, in run_script
    if insert:
  File "/home/jbar/.virtualenvs/bonus/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg/pkg_resources.py", line 1214, in run_script
    raise NotImplementedError(
  File "/home/jbar/.virtualenvs/bonus/lib/python2.6/site-packages/pip-0.7.1-py2.6.egg/EGG-INFO/scripts/pip", line 2, in <module>
    # EASY-INSTALL-SCRIPT: 'pip==0.7.1','pip'
  File "/home/jbar/.virtualenvs/bonus/lib/python2.6/site-packages/pip-0.7.1-py2.6.egg/pip/__init__.py", line 234, in <module>

  File "/home/jbar/.virtualenvs/bonus/lib/python2.6/site-packages/pip-0.7.1-py2.6.egg/pip/vcs/__init__.py", line 231, in import_vcs_support

OSError: [Errno 20] Not a directory: '/home/jbar/.virtualenvs/bonus/lib/python2.6/site-packages/pip-0.7.1-py2.6.egg/pip/vcs'
```

Then I looked around to find 

```
/home/jbar/.virtualenvs/bonus/lib/python2.6/site-packages/pip-0.7.1-py2.6.egg
```

is a file while

```
/usr/local/lib/python2.6/dist-packages/pip-0.7.1-py2.6.egg
```

is a directory. This explains why pip works globally but does not work within the my virtualenv. This all happens on Ubuntu 10.04 vanilla. Is this a bug and how can I fix it?

Thanks
Jiri

---
- Bitbucket: https://bitbucket.org/ianb/virtualenv/issue/35
- Originally Reported By: Jiri Barton
- Originally Created At: 2010-05-05 11:38:12

**Comment by gaborbernat** [comment]
I think this should be fixed, we don't support Python 2.6 anymore but if you can reproduce it with 2.7+ open it again.
