### ISSUE TITLE
virtualenv 1.11.6 is broken on Windows

### ISSUE THREAD

**Issue by techtonik** [pypa/virtualenv#649]
`virtualenv 1.11.6` is broken, and as a result `tox` is broken too.

```
C:\>C:\Python27\python.exe -m virtualenv --python c:\python27\python.exe py27
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\lib\site-packages\virtualenv.py", line 2338, in <module>
    main()
  File "C:\Python27\lib\site-packages\virtualenv.py", line 774, in main
    interpreter = resolve_interpreter(options.python)
  File "C:\Python27\lib\site-packages\virtualenv.py", line 1575, in resolve_interpreter
    python_versions = get_installed_pythons()
  File "C:\Python27\lib\site-packages\virtualenv.py", line 93, in get_installed_pythons
    path = winreg.QueryValue(python_core, "%s\\InstallPath" % ver)
WindowsError: [Error 2] The system cannot find the file specified
```

**Comment by dragon788** [comment]
Having a possibly related issue with virtualenv==15.0.2 where I can't install certain packages inside a virtualenv but they sometimes work outside. I get the "cannot find the file specified error" within the virtualenv. This may be related to #660 or the older #505.

**Comment by techtonik** [comment]
Don't waste your time on Windows.
