### ISSUE TITLE
virtualenv venv OSError

### ISSUE THREAD

**Issue by liufule12** [pypa/virtualenv#668]
Windows 8.1, Python 2.7, virtualenv 1.11.6, pip 1.5.6, easy_install setuptools 2.1

F:\mypro>virtualenv venv

New python executable in venv\Scripts\python.exe
Installing setuptools, pip...
  Complete output from command F:\mypro\venv\Scripts\python.exe -c "import sys,pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
  Ignoring indexes: https://pypi.python.org/simple/
Downloading/unpacking setuptools
Cleaning up...
Exception:
Traceback (most recent call last):
  File "E:\Program Files (x86)\Python27\lib\site-packages\virtualenv-1.11.6-py2.7.egg\virtualenv_support\pip-1.5.6-py2.py3-none-any.whl\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "E:\Program Files (x86)\Python27\lib\site-packages\virtualenv-1.11.6-py2.7.egg\virtualenv_support\pip-1.5.6-py2.py3-none-any.whl\pip\commands\install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundl
e=self.bundle)
  File "E:\Program Files (x86)\Python27\lib\site-packages\virtualenv-1.11.6-py2.7.egg\virtualenv_support\pip-1.5.6-py2.py3-none-any.whl\pip\req.py", line 1177,in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "E:\Program Files (x86)\Python27\lib\site-packages\virtualenv-1.11.6-py2.7.egg\virtualenv_support\pip-1.5.6-py2.py3-none-any.whl\pip\index.py", line 252, in find_requirement
    for page in self._get_pages(locations, req):
  File "E:\Program Files (x86)\Python27\lib\site-packages\virtualenv-1.11.6-py2.7.egg\virtualenv_support\pip-1.5.6-py2.py3-none-any.whl\pip\index.py", line 387, in _get_pages
    page = self._get_page(location, req)
  File "E:\Program Files (x86)\Python27\lib\site-packages\virtualenv-1.11.6-py2.7.egg\virtualenv_support\pip-1.5.6-py2.py3-none-any.whl\pip\index.py", line 568, in _get_page
    session=self.session,
  File "E:\Program Files (x86)\Python27\lib\site-packages\virtualenv-1.11.6-py2.7.egg\virtualenv_support\pip-1.5.6-py2.py3-none-any.whl\pip\index.py", line 670, in get_page
    resp = session.get(url, headers={"Accept": "text/html"})
  File "E:\Program Files (x86)\Python27\lib\site-packages\virtualenv-1.11.6-py2.7.egg\virtualenv_support\pip-1.5.6-py2.py3-none-any.whl\pip_vendor\requests\sessions.py", line 468, in get
    return self.request('GET', url, *_kwargs)
  File "E:\Program Files (x86)\Python27\lib\site-packages\virtualenv-1.11.6-py2.7.egg\virtualenv_support\pip-1.5.6-py2.py3-none-any.whl\pip\download.py", line 237, in request
    return super(PipSession, self).request(method, url, *args, *_kwargs)
  File "E:\Program Files (x86)\Python27\lib\site-packages\virtualenv-1.11.6-py2.7.egg\virtualenv_support\pip-1.5.6-py2.py3-none-any.whl\pip_vendor\requests\sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Program Files (x86)\Python27\lib\site-packages\virtualenv-1.11.6-py2.7.egg\virtualenv_support\pip-1.5.6-py2.py3-none-any.whl\pip_vendor\requests\sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "E:\Program Files (x86)\Python27\lib\site-packages\virtualenv-1.11.6-py2.7.egg\virtualenv_support\pip-1.5.6-py2.py3-none-any.whl\pip_vendor\requests\sessions.py", line 608, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for 'e:\Program'

Storing debug log for failure in C:\Users\liufule12\pip\pip.log

...Installing setuptools, pip...done.
Traceback (most recent call last):
  File "E:\Program Files (x86)\Python27\Scripts\virtualenv-script.py", line 9, in <module>
    load_entry_point('virtualenv==1.11.6', 'console_scripts', 'virtualenv')()
  File "E:\Program Files (x86)\Python27\lib\site-packages\virtualenv-1.11.6-py2.7.egg\virtualenv.py", line 824, in main
    symlink=options.symlink)
  File "E:\Program Files (x86)\Python27\lib\site-packages\virtualenv-1.11.6-py2.7.egg\virtualenv.py", line 992, in create_environment    install_wheel(to_install, py_executable, search_dirs)
  File "E:\Program Files (x86)\Python27\lib\site-packages\virtualenv-1.11.6-py2.7.egg\virtualenv.py", line 960, in install_wheel
    'PIP_NO_INDEX': '1'
  File "E:\Program Files (x86)\Python27\lib\site-packages\virtualenv-1.11.6-py2.7.egg\virtualenv.py", line 902, in call_subprocess    % (cmd_desc, proc.returncode))
**OSError: Command F:\mypro\venv\Scripts\python.exe -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 2**

**Comment by PoolloverNathan** [comment]
keepalive
