### ISSUE TITLE
mac: install_name_tool breaks on 64-bit Python 2.7 | Leopard only

### ISSUE THREAD

**Issue by vbabiy** [pypa/virtualenv#7]
```
#!python

$ /Library/Frameworks/Python.framework/Versions/2.7/bin/virtualenv --distribute --no-site-packages /tmp/v2New python executable in /tmp/v2/bin/python
install_name_tool: for architecture i386 object: /tmp/v2/bin/python malformed object (unknown load command 4)
Could not call install_name_tool -- you must have Apple's development tools installed
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/virtualenv", line 9, in <module>
    load_entry_point('virtualenv==1.4.9', 'console_scripts', 'virtualenv')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/virtualenv.py", line 534, in main
    use_distribute=options.use_distribute)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/virtualenv.py", line 617, in create_environment
    site_packages=site_packages, clear=clear))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/virtualenv.py", line 811, in install_python
    py_executable])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/virtualenv.py", line 595, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command install_name_tool -change /Library/Frameworks/Python.fra...ython @executable_path/../.Python /tmp/v2/bin/python failed with error code 1



$ /Library/Frameworks/Python.framework/Versions/2.7/bin/virtualenv --version
1.4.9
$ /Library/Frameworks/Python.framework/Versions/2.7/bin/python --version
Python 2.7
```

I used ActivePython 2.7.0.1 - but I do believe this also reproduces on Python 2.7 64-bit dmg. This can only be reproduced on 10.5 (neither 10.4 nor 10.6).

---
- Bitbucket: https://bitbucket.org/ianb/virtualenv/issue/50
- Originally Reported By: Sridhar Ratnakumar
- Originally Created At: 2010-07-13 23:17:23

**Comment by gaborbernat** [comment]
I think this should be fixed, we don't support Python 2.6 anymore but if you can reproduce it with 2.7+ open it again.
