### ISSUE TITLE
Virtualenv 12.0.5 from py2.7 broken with py3.4 target on Windows

### ISSUE THREAD

**Issue by ionelmc** [pypa/virtualenv#705]
Few tests:

```
C:\Users\ionel_000>pip install -I https://pypi.python.org/packages/py2.py3/v/virtualenv/virtualenv-12.0.5-py2.py3-none-any.whl#md5=2d469eb9081deef1b2b86b58f8913fca
Collecting virtualenv==12.0.5 from https://pypi.python.org/packages/py2.py3/v/virtualenv/virtualenv-12.0.5-py2.py3-none-any.whl#md5=2d469eb9081deef1b2b86b58f8913fca
  Starting new HTTPS connection (1): pypi.python.org
  "GET /packages/py2.py3/v/virtualenv/virtualenv-12.0.5-py2.py3-none-any.whl HTTP/1.1" 304 0
  Using cached virtualenv-12.0.5-py2.py3-none-any.whl
  Downloading from URL https://pypi.python.org/packages/py2.py3/v/virtualenv/virtualenv-12.0.5-py2.py3-none-any.whl#md5=2d469eb9081deef1b2b86b58f8913fca
Installing collected packages: virtualenv

Successfully installed virtualenv-12.0.5
Cleaning up...

C:\Users\ionel_000>virtualenv _test_env --python=c:\Python34\python.exe
Running virtualenv with interpreter c:\Python34\python.exe
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\virtualenv.py", line 8, in <module>
    import base64
  File "c:\Python34\lib\base64.py", line 9, in <module>
    import re
  File "c:\Python34\lib\re.py", line 324, in <module>
    import copyreg
  File "C:\Python27\lib\site-packages\copyreg.py", line 3, in <module>
    from copy_reg import *
ImportError: No module named 'copy_reg'

C:\Users\ionel_000>python --version
Python 2.7.9

C:\Users\ionel_000>virtualenv --version
12.0.5

C:\Users\ionel_000>python -mvirtualenv _test_env --python=c:\Python34\python.exe
Running virtualenv with interpreter c:\Python34\python.exe
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\virtualenv.py", line 8, in <module>
    import base64
  File "c:\Python34\lib\base64.py", line 9, in <module>
    import re
  File "c:\Python34\lib\re.py", line 324, in <module>
    import copyreg
  File "c:\Python27\lib\site-packages\copyreg.py", line 3, in <module>
    from copy_reg import *
ImportError: No module named 'copy_reg'

C:\Users\ionel_000>c:\Python34\python.exe --version
Python 3.4.2
```

Windows is 8.1

**Comment by ionelmc** [comment]
More details:

```
C:\Users\ionel_000>pip list
aspectlib (1.2.2)
backports.ssl-match-hostname (3.4.0.2)
blinker (1.3)
bumpversion (0.5.1.dev0)
certifi (14.5.14)
click (3.3)
colorama (0.3.2)
cssmin (0.2.0)
docutils (0.12)
enum34 (1.0)
faulthandler (2.3)
feedgenerator (1.7)
ipaddress (1.0.6)
ipython (2.1.0)
isort (3.9.0)
jedi (0.8.1-final0)
Jinja2 (2.7.3)
MarkupSafe (0.23)
natsort (3.5.0)
pelican (3.5.0)
pies (2.6.1)
pies2overrides (2.6.1)
pip (6.0.6)
pkginfo (1.1)
py (1.4.25)
Pygments (1.6)
pyreadline (2.0)
python-dateutil (2.3)
pytz (2014.10)
pywin32 (219)
pyzmq (14.4.1)
qrcode (5.0.1.post0)
setuptools (8.2.1)
six (1.9.0)
tornado (4.0.2)
tox (1.8.1)
twine (1.3.1)
Unidecode (0.4.17)
virtualenv (12.0.5)
webassets (0.10.1)
wheel (0.24.0)
```

**Comment by ionelmc** [comment]
For reference this still reproduces on `12.1.1`.

It doesn't reproduce on https://github.com/ionelmc/virtualenv/tree/develop
