### ISSUE TITLE
Unable to use maltparser in nltk. WindowsError: [Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by timebeing** [pypa/virtualenv#711]
I am new to python. I am trying to use maltparser for typed dependencies in nltk. I have used the following sample code.

import nltk
import os

os.environ["MALTPARSERHOME"] = "/Users/nishitha/.spyder2/maltparser-1.8.1"

parser = nltk.parse.malt.MaltParser(working_dir="/Users/nishitha/.spyder2/maltparser-1.8.1",mco="engmalt.linear-1.7.mco",additional_java_args=['-Xmx512m'])
txt="Anish plays cricket really well"
graph=parser.raw_parse(txt)

I get the following error. Kindly help

runfile('C:/Users/nishitha/.spyder2/customer_reviews/sample.py', wdir='C:/Users/nishitha/.spyder2/customer_reviews')
Traceback (most recent call last):

  File "<ipython-input-23-8c16219ac26e>", line 1, in <module>
    runfile('C:/Users/nishitha/.spyder2/customer_reviews/sample.py', wdir='C:/Users/nishitha/.spyder2/customer_reviews')

  File "C:\Users\nishitha\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 580, in runfile
    execfile(filename, namespace)

  File "C:/Users/nishitha/.spyder2/customer_reviews/sample.py", line 18, in <module>
    graph=parser.raw_parse(txt)

  File "C:\Users\nishitha\Anaconda\lib\site-packages\nltk\parse\malt.py", line 139, in raw_parse
    return self.parse(words, verbose)

  File "C:\Users\nishitha\Anaconda\lib\site-packages\nltk\parse\malt.py", line 126, in parse
    return self.parse_sents([sentence], verbose)[0]

  File "C:\Users\nishitha\Anaconda\lib\site-packages\nltk\parse\malt.py", line 114, in parse_sents
    return self.tagged_parse_sents(tagged_sentences, verbose)

  File "C:\Users\nishitha\Anaconda\lib\site-packages\nltk\parse\malt.py", line 191, in tagged_parse_sents
    ret = self._execute(cmd, verbose)

  File "C:\Users\nishitha\Anaconda\lib\site-packages\nltk\parse\malt.py", line 260, in _execute
    p = subprocess.Popen(cmd, stdout=output, stderr=output)

  File "C:\Users\nishitha\Anaconda\lib\subprocess.py", line 710, in __init__
    errread, errwrite)

  File "C:\Users\nishitha\Anaconda\lib\subprocess.py", line 958, in _execute_child
    startupinfo)

WindowsError: [Error 2] The system cannot find the file specified

**Comment by timebeing** [comment]
If someone could help me with this it would be great..I have spent hours trying to fix this without a solution anywhere.

**Comment by pfmoore** [comment]
This doesn't look like an error with virtualenv. It actually looks more like an error in using the various modules and/or with yout Anaconda setup. You'd probably get more help on the Python mailing list (see https://mail.python.org/mailman/listinfo/python-list) or an Anaconda-specific mailing list.
