### ISSUE TITLE
Cannot create Virtual Environment : OSError

### ISSUE THREAD

**Issue by mindheist** [pypa/virtualenv#720]
What I'm running into seems to be an old issue,but I m still not able to get past this ; I get the following error message when trying to create a new virtual environment using the command "virtualenv ve"

I have tried the following so far to get around this so far,

(1) Made sure that virtualenv was installed using pip and not easy_install
(2) The most latest version of vitualenv has been installed (ie) 12.0.7
(3) The most latest version of pip has been installed (ie) pip 6.0.8 from /Library/Python/2.7/site-packages (python 2.7)
(4) the python --version I'm using is - 'Python 2.7.6'
(5)  MAC version is as follows :

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.1
BuildVersion:	14B25

Error Trace:
----------------

$ virtualenv ve

New python executable in ve/bin/python
Installing setuptools, pip...
  Complete output from command /Users/../Desktop/...orkout/ve/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/virtualenv_support/pip-6.0.8-py2.py3-none-any.whl/pip/__init__.py", line 15, in <module>
  File "/Library/Python/2.7/site-packages/virtualenv_support/pip-6.0.8-py2.py3-none-any.whl/pip/vcs/mercurial.py", line 11, in <module>
  File "/Library/Python/2.7/site-packages/virtualenv_support/pip-6.0.8-py2.py3-none-any.whl/pip/download.py", line 30, in <module>
  File "/Library/Python/2.7/site-packages/virtualenv_support/pip-6.0.8-py2.py3-none-any.whl/pip/_vendor/__init__.py", line 61, in load_module
  File "/Library/Python/2.7/site-packages/virtualenv_support/pip-6.0.8-py2.py3-none-any.whl/pip/_vendor/requests/__init__.py", line 53, in <module>
  File "/Library/Python/2.7/site-packages/virtualenv_support/pip-6.0.8-py2.py3-none-any.whl/pip/_vendor/requests/packages/__init__.py", line 3, in <module>
  File "/Library/Python/2.7/site-packages/virtualenv_support/pip-6.0.8-py2.py3-none-any.whl/pip/_vendor/requests/packages/urllib3/__init__.py", line 10, in <module>
  File "/Library/Python/2.7/site-packages/virtualenv_support/pip-6.0.8-py2.py3-none-any.whl/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 31, in <module>
  File "/Library/Python/2.7/site-packages/virtualenv_support/pip-6.0.8-py2.py3-none-any.whl/pip/_vendor/requests/packages/urllib3/connection.py", line 11, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 69, in <module>
    from array import array
  File "array.py", line 4
    if not a[x+1] > a[x]
                       ^
SyntaxError: invalid syntax:

...Installing setuptools, pip...done.
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 825, in main
    symlink=options.symlink)
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 993, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 961, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 903, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/../Desktop/...orkout/ve/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1

Please do LMK if there is a way to fix this.

**Comment by ionelmc** [comment]
Do you happen to have an `array.py` file in the current directory? Try to rename it to something else.

**Comment by mindheist** [comment]
Ah ! good catch - thanks a lot ionelmc , I guess I do have the bad habit of naming files as array.py or io.py .. and running into these types of issue. Thanks a lot again.

$ virtualenv ve
New python executable in ve/bin/python
Installing setuptools, pip...done.
