### ISSUE TITLE
OS X 10.9.5 (13F1066) : Potential Version Error for Pip when Creating New Virtualenv?

### ISSUE THREAD

**Issue by ahlusar1989** [pypa/virtualenv#741]
Via terminal, when I type in "which pip" I am reported the following: 

```
 /Library/Frameworks/Python.framework/Versions/3.4/bin/pip
```

hen I type in "python -V" I am reported the following: 

```
Python 2.7.9 :: Anaconda 2.1.0 (x86_64)
```

This is my error:

```
Using base prefix '/Library/Frameworks/Python.framework/Versions/3.4'
New python executable in demoenv/bin/python3.4
Also creating executable in demoenv/bin/python
Cannot find a wheel for setuptools
Cannot find a wheel for pip
Installing setuptools, pip...
  Complete output from command /Users/sahluwalia/De...emoenv/bin/python3.4 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'pip'
----------------------------------------
...Installing setuptools, pip...done.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/virtualenv", line 9, in <module>
    load_entry_point('virtualenv==1.11.6', 'console_scripts', 'virtualenv')()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/virtualenv.py", line 824, in main
    symlink=options.symlink)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/virtualenv.py", line 992, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/virtualenv.py", line 960, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/virtualenv.py", line 902, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/sahluwalia/De...emoenv/bin/python3.4 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1
sahluwal51660m:learning-journal sahluwalia$ which OS
sahluwal51660m:learning-journal sahluwalia$ which OS?
sahluwal51660m:learning-journal sahluwalia$ virtualenv demoenv
Using base prefix '/Library/Frameworks/Python.framework/Versions/3.4'
New python executable in demoenv/bin/python3.4
Not overwriting existing python script demoenv/bin/python (you must use demoenv/bin/python3.4)
Cannot find a wheel for setuptools
Cannot find a wheel for pip
Installing setuptools, pip...
  Complete output from command /Users/sahluwalia/De...emoenv/bin/python3.4 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'pip'
----------------------------------------
...Installing setuptools, pip...done.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/virtualenv", line 9, in <module>
    load_entry_point('virtualenv==1.11.6', 'console_scripts', 'virtualenv')()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/virtualenv.py", line 824, in main
    symlink=options.symlink)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/virtualenv.py", line 992, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/virtualenv.py", line 960, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/virtualenv.py", line 902, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/sahluwalia/De...emoenv/bin/python3.4 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1
```

**Comment by DavidAwad** [comment]
+1 I just got this for a really unusual reason. 

```python
➜  twitter playlist  virtualenv venv -p /usr/local/bin/python
Running virtualenv with interpreter /usr/local/bin/python
Overwriting venv/lib/python2.7/orig-prefix.txt with new content
New python executable in venv/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /Users/david/Desktop...list/venv/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/virtualenv_support/pip-7.0.1-py2.py3-none-any.whl/pip/__init__.py", line 13, in <module>
  File "/Library/Python/2.7/site-packages/virtualenv_support/pip-7.0.1-py2.py3-none-any.whl/pip/utils/__init__.py", line 23, in <module>
  File "/Library/Python/2.7/site-packages/virtualenv_support/pip-7.0.1-py2.py3-none-any.whl/pip/_vendor/__init__.py", line 72, in load_module
  File "/Library/Python/2.7/site-packages/virtualenv_support/pip-7.0.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 37, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/feedparser.py", line 27, in <module>
    from email import message
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/message.py", line 16, in <module>
    import email.charset
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/charset.py", line 13, in <module>
    import email.base64mime
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/base64mime.py", line 40, in <module>
    from email.utils import fix_eols
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/utils.py", line 27, in <module>
    import random
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 49, in <module>
    import hashlib as _hashlib
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 138, in <module>
    _hashlib.openssl_md_meth_names)
AttributeError: 'module' object has no attribute 'openssl_md_meth_names'
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 832, in main
    symlink=options.symlink)
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 1004, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 969, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 910, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/david/Desktop...list/venv/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 1
```

**Comment by grisaitis** [comment]
See https://github.com/conda/conda/issues/1367. 

The best solution I know of now is to downgrade to python 2.7.9.

**Comment by Ivoz** [comment]
Both of these problem cases seem to be at least made worse by many disparate installations of python. Often cleaning them up and just using one system helps a lot.

**Comment by Catpants** [comment]
pip3.6 install --upgrade pip
pip3.6 install --upgrade virtualenvwrapper

worked for me

**Comment by gaborbernat** [comment]
Feels a conda issue, 👍
