### ISSUE TITLE
13.0.3 fails during upgrade on Mac OS 10.9.5 Mavericks

### ISSUE THREAD

**Issue by jschnurholmes** [pypa/virtualenv#768]
Ran command `sudo pip install  --upgrade virtualenv`
Output:

```
Downloading/unpacking virtualenv from https://pypi.python.org/packages/py2.py3/v/virtualenv/virtualenv-13.0.3-py2.py3-none-any.whl#md5=f40a95563e668fca630bd15ebb87ecbe
  Downloading virtualenv-13.0.3-py2.py3-none-any.whl (1.7MB): 1.7MB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/req.py", line 1265, in prepare_files
    req_to_install.extras):
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/_vendor/pkg_resources.py", line 2291, in requires
    dm = self._dep_map
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/_vendor/pkg_resources.py", line 2484, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/_vendor/pkg_resources.py", line 2506, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/_vendor/pkg_resources.py", line 2476, in _parsed_pkg_info
    self._pkg_info = Parser().parsestr(self.get_metadata(self.PKG_INFO))
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/_vendor/pkg_resources.py", line 1361, in get_metadata
    return self._get(self._fn(self.egg_info,name))
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/_vendor/pkg_resources.py", line 1470, in _get
    stream = open(path, 'rb')
IOError: [Errno 2] No such file or directory: '/private/tmp/pip_build_root/virtualenv/virtualenv-13.0.1.dist-info/METADATA'

Storing debug log for failure in /Users/user/Library/Logs/pip.log
```

**Comment by Ivoz** [comment]
@jschnurholmes could you try upgrading `pip` first and seeing if the error continues?
