### ISSUE TITLE
Will not overwrite existing env if old python is removed

### ISSUE THREAD

**Issue by dpwrussell** [pypa/virtualenv#776]
The way to "upgrade" a virtualenv when a new underlying python version is installed seems to be to recreate the virtualenv over the top of the old one. That has been the case for some years and I think has been working for me although I can't be 100% certain that I've done a python upgrade in that time, but I find it unlikely I wouldn't have.

Today I tried to upgrade a virtualenv for this exact reason and I now get an error.

```
$ mkvirtualenv django-cookiecutter
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 825, in main
    symlink=options.symlink)
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 985, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 1179, in install_python
    copyfile(join(stdlib_dir, fn), join(lib_dir, fn), symlink)
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 479, in copyfile
    copyfileordir(src, dest, symlink)
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 454, in copyfileordir
    shutil.copytree(src, dest, symlink)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 177, in copytree
    os.makedirs(dst)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: 'django-cookiecutter/lib/python2.7/config'
```

I tried on several virtualenvs (some had --system-site-packges, some did not) and it is the same in every case.
I think it is basically because when I upgraded python to 2.7.10, 2.7.9 was removed. This created a broken symlink for lib/python2.7/config and that causes the failure.

I thought this was a virtualenvwrapper issue so I filed it here: https://bitbucket.org/dhellmann/virtualenvwrapper/issue/268/mkvirtualenv-will-not-overwrite-existing, but the maintainer let me know it was a virtualenv problem.

Cheers

**Comment by fuzzy76** [comment]
Just got bit by the same :-/
