### ISSUE TITLE
ImportError: No module named 'logging'

### ISSUE THREAD

**Issue by mr-rodgers** [pypa/virtualenv#813]
I'm on Windows 10, using Python 3.5 (user-local) and virtualenv 13.1.2

Here's the full output:

```
C:\Dev> python -m virtualenv pyenv
Using base prefix 'C:\\Users\\Te-jé\\AppData\\Local\\Programs\\Python\\Python35-32'
New python executable in pyenv\Scripts\python.exe
Installing setuptools, pip, wheel...
  Complete output from command C:\Dev\pyenv\Scripts\python.exe -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Te-jé\AppData\Local\Programs\Python\Python35-32\lib\site-packages\virtualenv_support\pip-7.1.2-py2.py3-none-any.whl\pip\__init__.py", line 4, in <module>
ImportError: No module named 'logging'
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "C:\Users\Te-jé\AppData\Local\Programs\Python\Python35-32\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Te-jé\AppData\Local\Programs\Python\Python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Te-jé\AppData\Local\Programs\Python\Python35-32\lib\site-packages\virtualenv.py", line 2363, in <module>
    main()
  File "C:\Users\Te-jé\AppData\Local\Programs\Python\Python35-32\lib\site-packages\virtualenv.py", line 832, in main
    symlink=options.symlink)
  File "C:\Users\Te-jé\AppData\Local\Programs\Python\Python35-32\lib\site-packages\virtualenv.py", line 1004, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "C:\Users\Te-jé\AppData\Local\Programs\Python\Python35-32\lib\site-packages\virtualenv.py", line 969, in install_wheel
    'PIP_NO_INDEX': '1'
  File "C:\Users\Te-jé\AppData\Local\Programs\Python\Python35-32\lib\site-packages\virtualenv.py", line 910, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command C:\Dev\pyenv\Scripts\python.exe -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 1
```

**Comment by te-je** [comment]
I suspect that this error was somehow linked to the accented-e in my user path. Removing the user-local Python install and replacing it with a system-wide install has "fixed" this.
