### ISSUE TITLE
lib64 problem on bluehost shared hosting

### ISSUE THREAD

**Issue by mscalora** [pypa/virtualenv#826]
I've been trying to get virtualenv to work on bluehost for a number of hours. I've exhausted everything I can find on Google/StackOverflow. It appears that these CentOS boxes have both a lib/lib-dynload and lib64/lib-dynload and virtualenv doesn't like having both for some reason.

Full details/log at: https://gist.github.com/mscalora/638b1522d6ce1f096eac

```
+ virtualenv -vvv my-new-py-env
Creating my-new-py-env/lib/python2.6
This system uses lib64; symlinking lib64 to lib
Symlinking Python bootstrap modules
  Symlinking my-new-py-env/lib/python2.6/config
  Symlinking my-new-py-env/lib/python2.6/lib-dynload
  Symlinking my-new-py-env/lib64/python2.6/os.py
  Ignoring built-in bootstrap module: posix
  Symlinking my-new-py-env/lib64/python2.6/posixpath.py
  Cannot import bootstrap module: nt
  Symlinking my-new-py-env/lib64/python2.6/ntpath.py
  Symlinking my-new-py-env/lib64/python2.6/genericpath.py
  Symlinking my-new-py-env/lib64/python2.6/fnmatch.py
  Symlinking my-new-py-env/lib64/python2.6/locale.py
  Symlinking my-new-py-env/lib64/python2.6/encodings
  Symlinking my-new-py-env/lib64/python2.6/codecs.py
  Symlinking my-new-py-env/lib64/python2.6/stat.py
  Symlinking my-new-py-env/lib64/python2.6/UserDict.py
  Creating parent directories for my-new-py-env/lib64/python2.6/lib-dynload
Traceback (most recent call last):
  File "/home1/twomaste/.local/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/home1/twomaste/.local/lib/python2.6/site-packages/virtualenv.py", line 832, in main
    symlink=options.symlink)
  File "/home1/twomaste/.local/lib/python2.6/site-packages/virtualenv.py", line 994, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/home1/twomaste/.local/lib/python2.6/site-packages/virtualenv.py", line 1192, in install_python
    copy_required_modules(home_dir, symlink)
  File "/home1/twomaste/.local/lib/python2.6/site-packages/virtualenv.py", line 1131, in copy_required_modules
    copyfile(filename, dst_filename, symlink)
  File "/home1/twomaste/.local/lib/python2.6/site-packages/virtualenv.py", line 468, in copyfile
    os.makedirs(os.path.dirname(dest))
  File "/usr/lib64/python2.6/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: 'my-new-py-env/lib64/python2.6/lib-dynload'
bluehost-shared-$
```

Is there something simple I am missing. I have another account with a custom build of python 2.7 in the home folder but I am hoping I can get this working with the system python 2.6.

I think the problem are these actions:

```
This system uses lib64; symlinking lib64 to lib
```

then

```
Symlinking my-new-py-env/lib/python2.6/lib-dynload
```

then

```
Creating parent directories for my-new-py-env/lib64/python2.6/lib-dynload
```

boom!

I tried the lasted code from the virtualenv develop branch but ran into the same error.

Any ideas?

**Comment by gaborbernat** [comment]
I think this should be fixed, we don't support Python 2.6 anymore but if you can reproduce it with 2.7+ open it again.
