### ISSUE TITLE
Virtualenv seems to have overwritten system Python

### ISSUE THREAD

**Issue by jaraco** [pypa/virtualenv#828]
Today I was trying to create a Python 2.7 virtualenv, but when I did, it replaced my Python 3.5.0 binaries with Python 2.7.10 binaries. Thereafter, I had no usable Python 3 on my system.

```
$ python3.5
Python 2.7.10 (default, Aug 22 2015, 20:33:39) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> ^D
$ which python3.5
/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5
$ python3.5 -c "import sys; print(sys.prefix)"
/System/Library/Frameworks/Python.framework/Versions/2.7
```

As you can see, I'm using OS X. I had installed Python 3.5.0 using the OS X installer from python.org. I had `alias python='python3'` in my shell. I also had originally had virtualenv installed in my Python 3.5 environment, but it wasn't working so I installed it to my Python 2.7 environment as a user package.

When I invoked virtualenv, I used something like `virtualenv --python python2.7 ../.env` where `virtualenv` probably resolved to the broken script in the Python 3 environment.

Unfortunately, I wasn't paying that much attention when it happened, so I'm unsure all the details. I'm going to try to replicate it, but for now, I just wanted to register this highly unusual and unexpected behavior.

**Comment by jaraco** [comment]
I couldn't replicate this, so I'm calling it a fluke and moving on.

**Comment by jaraco** [comment]
This happened to me again today with virtualenv 14.0.5 and Python 3.5.1. This time, I have the bash history of the exact commands that led to the issue:

```
python -m virtualenv --python python2.7 env
rm -R env
python -m virtualenv --python python2.7 env
python2.7 -m virtualenv env
which virtualenv
head `which virtualenv`
python -m virtualenv
python
virtualenv --python python2.7 env
python -m easy_install virtualenv
```

In this environment, `python` is aliased to `python3`. Unfortunately, I don't have the output of those commands, but by the time I got to `python -m easy_install virtualenv`, the executable for `python3.5` now invokes `python2.7`.

**Comment by jaraco** [comment]
I just reinstalled my environment, including upgrading to pip==8.0.2, setuptools==20.2.2, and virtualenv==14.0.6, and I can't replicate the issue even with the commands from before. So either the issue is fixed in one of those packages, was an artifact of something else in my environment, or perhaps an existing `env` had some state that violated expectations.

**Comment by jaraco** [comment]
Yes! That was it. I'm able to replicate the failure now:

```
$ rm -R env
$ python -m venv env
$ python -m virtualenv --python python2.7 env
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /Users/jaraco/Dropbox/code/public/bitbucket_issue_migration/env/bin/python
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/virtualenv-14.0.6-py3.5.egg/virtualenv.py", line 2304, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/virtualenv-14.0.6-py3.5.egg/virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/virtualenv-14.0.6-py3.5.egg/virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/virtualenv-14.0.6-py3.5.egg/virtualenv.py", line 1198, in install_python
    make_exe(py_executable)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/virtualenv-14.0.6-py3.5.egg/virtualenv.py", line 386, in make_exe
    os.chmod(fn, newmode)
OSError: [Errno 1] Operation not permitted: '/Users/jaraco/Dropbox/code/public/bitbucket_issue_migration/env/bin/python'
$ python3.5
Python 2.7.10 (default, Oct 23 2015, 18:05:06) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by jaraco** [comment]
While I acknowledge that it's probably discouraged for someone to invoke virtualenv on a venv, it's not obvious to the user that an existing env is of one form or another, and my expectation is that virtualenv should fail fast and certainly not overwrite system python executables (or anything outside of the virtualenv for that matter).

**Comment by pfmoore** [comment]
Not that I disagree with your analysis, but given that you weren't using sudo, how could virtualenv have overwritten the system Python?

Does venv on OSX create any symlinks in the env that could be getting followed somehow?

**Comment by pfmoore** [comment]
I think an error message if the target directory already exists and contains a ```pyvenv.cfg``` file would be reasonable in the short term.

Longer term, though, I think that @dstufft hopes to change ```virtualenv``` to use ```venv``` on Python versions where it exists - at which point this issue goes away.

**Comment by jaraco** [comment]
> how could virtualenv have overwritten the system Python?

I'm not sure if it's something I configured or if it's the standard installation behavior, but Python 3.5 was installed from the python.org website and is writeable by me, the user who installed it. It does require using sudo to write to Python 2.7, but not to 3.5.

**Comment by jaraco** [comment]
>  I think that @dstufft hopes to change virtualenv to use venv on Python versions where it exists - at which point this issue goes away.

Hmm. Is that true? Does that mean that `virtualenv --python python2.7` would no longer be supported?

**Comment by jaraco** [comment]
> Does venv on OSX create any symlinks in the env that could be getting followed somehow?

Yes, seems that way.

```
$ python -m venv env
$ ls -la env/bin
total 80
drwxr-xr-x@ 12 jaraco  staff   408 Mar  4 15:16 .
drwxr-xr-x@  6 jaraco  staff   204 Mar  4 15:16 ..
-rw-rw-r--@  1 jaraco  staff  2177 Mar  4 15:37 activate
-rw-rw-r--@  1 jaraco  staff  1293 Mar  4 15:37 activate.csh
-rw-rw-r--@  1 jaraco  staff  2429 Mar  4 15:37 activate.fish
-rwxr-xr-x@  1 jaraco  staff   292 Mar  4 15:16 easy_install
-rwxr-xr-x@  1 jaraco  staff   292 Mar  4 15:16 easy_install-3.5
-rwxr-xr-x@  1 jaraco  staff   264 Mar  4 15:16 pip
-rwxr-xr-x@  1 jaraco  staff   264 Mar  4 15:16 pip3
-rwxr-xr-x@  1 jaraco  staff   264 Mar  4 15:16 pip3.5
lrwxr-xr-x   1 jaraco  staff     7 Mar  4 15:16 python -> python3
lrwxr-xr-x   1 jaraco  staff    61 Mar  4 15:16 python3 -> /Library/Frameworks/Python.framework/Versions/3.5/bin/python3
```

**Comment by dstufft** [comment]
It's true that I want to do that, an important part of that statement is "where it exists". We'd continue to support versions of Python that didn't have a ``venv`` module using the gross hacks we use today. It'd strictly be a sort of progressive enhancement to use the built in isolation mechanism instead of the terrible one we have now.

**Comment by Ivoz** [comment]
@jaraco where is the new `python3.5` located? (i.e, what is `which python3.5` ?)

**Comment by jaraco** [comment]
`which python3.5` isn't affected by the corruption, which is what leads me to believe the executable itself is being overridden, and which is validated by noticing that the mod date on the executable is roughly now.

```
$ which python3.5
/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5
```

I did do a shasum on the executable and compared it to the python2.7 executable on the system, but they weren't the same, so I'm not sure where the python2.7 executable comes from.
