### ISSUE TITLE
UnicodeDecodeError when running mkvirtualenv

### ISSUE THREAD

**Issue by mastokley** [pypa/virtualenv#834]
Hello,

On running this command:

    mkvirtualenv TestEnv

I receive the following error:
```
Running virtualenv with interpreter /usr/bin/python2
New python executable in TestEnv/bin/python2
Not overwriting existing python script TestEnv/bin/python (you must use TestEnv/bin/python2)
Installing setuptools, pip...done.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/dist-packages/virtualenvwrapper/hook_loader.py", line 16, in <module>
    from stevedore import ExtensionManager
  File "/usr/lib/python2.7/dist-packages/stevedore/__init__.py", line 11, in <module>
    from .extension import ExtensionManager
  File "/usr/lib/python2.7/dist-packages/stevedore/extension.py", line 4, in <module>
    import pkg_resources
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3124, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 652, in _build_master
    ws = cls()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 645, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 701, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2139, in find_on_path
    path_item, entry, metadata, precedence=DEVELOP_DIST
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2521, in from_location
    py_version=py_version, platform=platform, **kw
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2835, in _reload_version
    md_version = _version_from_file(self._get_metadata(self.PKG_INFO))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2486, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2654, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2030, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2025, in get_metadata
    metadata = f.read()
  File "/usr/lib/python2.7/codecs.py", line 296, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb6 in position 147: invalid start byte
```

I'm running Debian 8 (Bunsenlabs 8.2, specifically). I'm running version 1.11.6 of virtualenv, Python 2.7.9, and pip 7.1.2.

I've been researching this UnicodeDecodeError for the last week, fruitlessly. Forcing pip to upgrade helped to some extent.

**Comment by Ivoz** [comment]
I'm guessing: It'll be some package installed in your environment, that has non-utf8 metadata installed somewhere :/

**Comment by ri0t** [comment]
How is one supposed to find that bad apple? Not funny, to have such a non-verbose exception.

**Comment by ri0t** [comment]
Yaaay, all that stuff is wrapped in wheels. What a grandiose fun to debug/fix. I _hate_ wheels.
