### ISSUE TITLE
Providing python path breaks virtualenv creation

### ISSUE THREAD

**Issue by mat128** [pypa/virtualenv#847]
Under virtualenv 13.1.2, the following was possible:
```
$ venv13_1_2/bin/pip freeze
You are using pip version 6.0, however version 8.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
virtualenv==13.1.2
$ venv13_1_2/bin/virtualenv --python /usr/bin/python2.7 e
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in e/bin/python2.7
Also creating executable in e/bin/python
```

Now, under virtualenv 14.0, the same command results in the following:
```
$ venv14/bin/pip freeze
You are using pip version 6.0, however version 8.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
virtualenv==14.0.0
$ venv14/bin/virtualenv --python /usr/bin/python2.7 f
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /home/jenkins/f/bin/python2.7
Also creating executable in /home/jenkins/f/bin/python
Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 562, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 544, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python2.7/site.py", line 271, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python2.7/site.py", line 246, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python2.7/site.py", line 236, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python2.7/sysconfig.py", line 577, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python2.7/sysconfig.py", line 476, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python2.7/sysconfig.py", line 355, in _init_posix
    raise IOError(msg)
IOError: invalid Python installation: unable to open /home/jenkins/f/local/include/python2.7/pyconfig.h (No such file or directory)
ERROR: The executable /home/jenkins/f/bin/python2.7 is not functioning
ERROR: It thinks sys.prefix is u'/home/jenkins' (should be u'/home/jenkins/f')
ERROR: virtualenv is not compatible with this system or executable
```

Not providing python executable path works:
```
$ venv14/bin/virtualenv g
Using real prefix '/usr'
New python executable in /home/jenkins/g/bin/python
Installing setuptools, pip, wheel...done.
```

I think the regression was introduced by pull request #805.  Tox currently invokes virtualenv by providing a python path [1]. This issue breaks tox.

1. https://bitbucket.org/hpk42/tox/src/2d5d0e7584cc4cc35cc7e0519ce9610dd52b7a62/tox/venv.py?at=default&fileviewer=file-view-default#venv.py-382

**Comment by Ivoz** [comment]
Could I get some information on what your system looks like? I can't reproduce on my end.

OS? System packaged python? Any development headers installed?

**Comment by Ivoz** [comment]
Hmm, seems to be coming from the fact that the new python somehow expects headers to be in `{prefix}/local/include/python2.7/` when they should be coming from `{prefix}/include/python2.7/`

You can what any particular python executable thinks should be its include directory from running `$ {python} -m sysconfig | grep include`. Can you do this for `/usr/bin/python` and `venv14/bin/python` ?

**Comment by mat128** [comment]
## Background

Ubuntu 12.04 with system python 2.7.3 and development headers installed:
```
ii  python2.7                             2.7.3-0ubuntu3.5              Interactive high-level object-oriented language (version 2.7)
ii  python2.7-dev                         2.7.3-0ubuntu3.5              Header files and a static library for Python (v2.7)
```

```
$ /usr/bin/python -V
Python 2.7.3
```

I was also able to reproduce the issue on Ubuntu 14.04, running system-provided Python 2.7.6
```
ii  python2.7                             2.7.6-8                             amd64        Interactive high-level object-oriented language (version 2.7)
ii  python2.7-dev                         2.7.6-8                             amd64        Header files and a static library for Python (v2.7)
```

```
$ /usr/bin/python -V
Python 2.7.6
```

```
mmitchell@trusty1:~$ venv13_1_2/bin/virtualenv --python /usr/bin/python2.7 a
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in a/bin/python2.7
Not overwriting existing python script a/bin/python (you must use a/bin/python2.7)
Installing setuptools, pip, wheel...done.
```

```
mmitchell@trusty1:~$ venv14/bin/virtualenv --python /usr/bin/python2.7 a
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /home/mmitchell/a/bin/python2.7
Also creating executable in /home/mmitchell/a/bin/python
ERROR: The executable /home/mmitchell/a/bin/python2.7 is not functioning
ERROR: It thinks sys.prefix is u'/usr' (should be u'/home/mmitchell/a')
ERROR: virtualenv is not compatible with this system or executable
```

## sysconfig dumps

I had to use an alternative command (python -m sysconfig wouldnt print anything) but the result should be the same.

### Ubuntu 12.04 /usr/bin/python
```
$ /usr/bin/python -c "import sysconfig; import pprint; pprint.pprint(sysconfig.get_paths()); pprint.pprint(sysconfig.get_config_vars())" | grep include
 'include': '/usr/local/include/python2.7',
 'platinclude': '/usr/local/include/python2.7',
 'CONFINCLUDEDIR': '/usr/include',
 'CONFINCLUDEPY': '/usr/include/python2.7',
 'INCLDIRSTOMAKE': '/usr/include /usr/include /usr/include/python2.7 /usr/include/python2.7',
 'INCLUDEDIR': '/usr/include',
 'INCLUDEPY': '/usr/include/python2.7',
```

### Ubuntu 12.04 venv14/bin/python
```
$ venv14/bin/python -c "import sysconfig; import pprint; pprint.pprint(sysconfig.get_paths()); pprint.pprint(sysconfig.get_config_vars())" | grep include
 'include': '/home/jenkins/venv14/local/include/python2.7',
 'platinclude': '/home/jenkins/venv14/local/include/python2.7',
 'CONFINCLUDEDIR': '/usr/include',
 'CONFINCLUDEPY': '/usr/include/python2.7',
 'INCLDIRSTOMAKE': '/usr/include /usr/include /usr/include/python2.7 /usr/include/python2.7',
 'INCLUDEDIR': '/usr/include',
 'INCLUDEPY': '/usr/include/python2.7',
```

### Ubuntu 14.04 /usr/bin/python
```
$ /usr/bin/python -m sysconfig | grep include
	include = "/usr/local/include/python2.7"
	platinclude = "/usr/local/include/python2.7"
	CONFINCLUDEDIR = "/usr/include"
	CONFINCLUDEPY = "/usr/include/python2.7"
	INCLDIRSTOMAKE = "/usr/include /usr/include /usr/include/python2.7 /usr/include/python2.7"
	INCLUDEDIR = "/usr/include"
	INCLUDEPY = "/usr/include/python2.7"
```

### Ubuntu 14.04 venv14/bin/python
```
$ venv14/bin/python -m sysconfig | grep include
	include = "/home/mmitchell/venv14/local/include/python2.7"
	platinclude = "/home/mmitchell/venv14/local/include/python2.7"
	CONFINCLUDEDIR = "/usr/include"
	CONFINCLUDEPY = "/usr/include/python2.7"
	INCLDIRSTOMAKE = "/usr/include /usr/include /usr/include/python2.7 /usr/include/python2.7"
	INCLUDEDIR = "/usr/include"
	INCLUDEPY = "/usr/include/python2.7"
```

**Comment by mat128** [comment]
Tested just for fun on my laptop, interestingly, it works correctly.

Running OS X 10.9 with system-provided Python 2.7.5. Development headers are installed, but I can't recall how I installed them (I think they are provided by a fresh OS X installation, or maybe XCode).
```
$ /usr/bin/python -V
Python 2.7.5
```

```
~/virtualenv_bug847$ venv13_1_2/bin/virtualenv --python /usr/bin/python a
Running virtualenv with interpreter /usr/bin/python
New python executable in a/bin/python
Installing setuptools, pip, wheel...done.
```

```
~/virtualenv_bug847$ venv14/bin/virtualenv --python /usr/bin/python b
Running virtualenv with interpreter /usr/bin/python
New python executable in /Users/mmitchell/virtualenv_bug847/b/bin/python
Installing setuptools, pip, wheel...done.
```

### Sysconfig
#### /usr/bin/python
```
~/virtualenv_bug847$ /usr/bin/python -m sysconfig | grep include
	include = "/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7"
	platinclude = "/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7"
	CONFINCLUDEDIR = "/System/Library/Frameworks/Python.framework/Versions/2.7/include"
	CONFINCLUDEPY = "/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7"
	INCLDIRSTOMAKE = "/System/Library/Frameworks/Python.framework/Versions/2.7/include /System/Library/Frameworks/Python.framework/Versions/2.7/include /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7"
	INCLUDEDIR = "/System/Library/Frameworks/Python.framework/Versions/2.7/include"
	INCLUDEPY = "/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7"
```

#### venv14/bin/python
```
~/virtualenv_bug847$ venv14/bin/python -m sysconfig | grep include
	include = "/Users/mmitchell/virtualenv_bug847/venv14/include/python2.7"
	platinclude = "/Users/mmitchell/virtualenv_bug847/venv14/include/python2.7"
	CONFINCLUDEDIR = "/System/Library/Frameworks/Python.framework/Versions/2.7/include"
	CONFINCLUDEPY = "/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7"
	INCLDIRSTOMAKE = "/System/Library/Frameworks/Python.framework/Versions/2.7/include /System/Library/Frameworks/Python.framework/Versions/2.7/include /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7"
	INCLUDEDIR = "/System/Library/Frameworks/Python.framework/Versions/2.7/include"
	INCLUDEPY = "/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7"
```
