### ISSUE TITLE
Issues creating Jython environment

### ISSUE THREAD

**Issue by aarzee** [pypa/virtualenv#855]
When trying to create a Jython (installed via Homebrew) env on the latest virtualenv, I get these errors:

```
carloss-mbp:~ aarzee$ python -m virtualenv -p $(which jython) jythonenv
Running virtualenv with interpreter /usr/local/bin/jython
Cannot find file /usr/local/Cellar/jython/2.7.0/libexec/Include (bad symlink)
New jython executable in /Users/aarzee/jythonenv/bin/jython
Installing setuptools, pip, wheel...
  Complete output from command /Users/aarzee/jythonenv/bin/jython -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel:
  Collecting setuptools
/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/packages/urllib3/util/ssl_.py:307: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  warnings.warn(
/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/packages/urllib3/util/ssl_.py:114: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  warnings.warn(
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/commands/install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/commands/install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/req/req_set.py", line 355, in prepare_files
    discovered_reqs.extend(self._prepare_file(
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/req/req_set.py", line 355, in prepare_files
    discovered_reqs.extend(self._prepare_file(
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/req/req_set.py", line 510, in _prepare_file
    req_to_install.populate_link(
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/req/req_install.py", line 277, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/index.py", line 436, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/index.py", line 394, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/index.py", line 539, in _get_pages
    page = self._get_page(location)
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/index.py", line 642, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/index.py", line 747, in get_page
    resp = session.get(
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/index.py", line 747, in get_page
    resp = session.get(
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/download.py", line 377, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/adapters.py", line 366, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/adapters.py", line 366, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 557, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 557, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 784, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/packages/urllib3/connection.py", line 247, in connect
    self.sock = ssl_wrap_socket(conn, self.key_file, self.cert_file,
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/packages/urllib3/util/ssl_.py", line 317, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/packages/urllib3/util/ssl_.py", line 130, in wrap_socket
    return wrap_socket(socket, ciphers=self.ciphers, **kwargs)
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/_socket.py", line 357, in handle_exception
    return method_or_function(*args, **kwargs)
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/_socket.py", line 357, in handle_exception
    return method_or_function(*args, **kwargs)
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/_socket.py", line 357, in handle_exception
    return method_or_function(*args, **kwargs)
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/ssl.py", line 287, in wrap_socket
    return SSLSocket(
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/ssl.py", line 104, in __init__
    self.context = _get_ssl_context(keyfile, certfile, ca_certs)
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/_sslcerts.py", line 113, in _get_ssl_context
    trust_managers = _get_ca_certs_trust_manager(ca_certs).getTrustManagers()
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/_sslcerts.py", line 40, in _get_ca_certs_trust_manager
    num_certs_installed = 0
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/cacert.pem'
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 2278, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 693, in main
    create_environment(home_dir,
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 900, in create_environment
    install_wheel(
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 861, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 779, in call_subprocess
    raise OSError(
OSError: Command /Users/aarzee/jythonenv/bin/jython -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 2
```

This started happening when I updated my virtualenv, pip, wheel, and setuptools installations (virtualenv was at the last 13.x version).

**Comment by aarzee** [comment]
Apologies, this is in fact a Jython issue (http://bugs.jython.org/issue2390).
