### ISSUE TITLE
Whenever I try to create a virtualenv I get "Userwarning: Support for Python 3.0-3.2 has been dropped."

### ISSUE THREAD

**Issue by h-2-0** [pypa/virtualenv#879]
Hello!

I have tried many different ways to create a virtualenv using Python 3.2. See [here ](http://stackoverflow.com/questions/35781745/cant-create-virtualenv-using-python-3-2-whodunnit-pip-or-setuptools-or-python) for more reference.

Anyway, I think I now just broke virtualenv because I can't even create any virtual environment (see below).

I have tried this for hours and hours. It seems to me it has to do with the incompatibility between setuptools and python3.2. If it is, how can I make it? I tried using the **--no-setuptools** to no avail. 

What else can I try?

Thanks in advance!
```
$ virtualenv test
New python executable in /home/username/.virtualenvs/test/bin/python3.2
Also creating executable in /home/username/.virtualenvs/test/bin/python
/usr/local/lib/python3.2/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py:87: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.2/dist-packages/virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "/usr/local/lib/python3.2/dist-packages/virtualenv.py", line 924, in create_environment
    download=download,
  File "/usr/local/lib/python3.2/dist-packages/virtualenv.py", line 843, in install_wheel
    cert_data = pkgutil.get_data("pip._vendor.requests", "cacert.pem")
  File "/usr/lib/python3.2/pkgutil.py", line 573, in get_data
    loader = get_loader(package)
  File "/usr/lib/python3.2/pkgutil.py", line 461, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python3.2/pkgutil.py", line 471, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python3.2/pkgutil.py", line 427, in iter_importers
    __import__(pkg)
  File "/usr/local/lib/python3.2/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/__init__.py", line 15, in <module>
  File "/usr/local/lib/python3.2/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/vcs/mercurial.py", line 9, in <module>
  File "/usr/local/lib/python3.2/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/download.py", line 35, in <module>
  File "/usr/local/lib/python3.2/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/utils/ui.py", line 15, in <module>
  File "/usr/local/lib/python3.2/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/progress/bar.py", line 48
    empty_fill = u'∙'
                      ^
SyntaxError: invalid syntax
```

**UPDATE**

Oddly enough I can create a 'working' virtualenv using python3.4 from virtualenvwrapper .

```
$ mkvirtualenv --python=/opt/python3/bin/python3.4 venv34
Running virtualenv with interpreter /opt/python3/bin/python3.4
Using base prefix '/opt/python3'
New python executable in /home/username/.virtualenvs/venv34/bin/python3.4
Also creating executable in /home/username/.virtualenvs/venv34/bin/python
Installing setuptools, pip, wheel...done.
/usr/local/lib/python3.2/dist-packages/pkg_resources/__init__.py:87: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.
  warnings.warn(msg)
virtualenvwrapper.user_scripts creating /home/username/.virtualenvs/venv34/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/username/.virtualenvs/venv34/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/username/.virtualenvs/venv34/bin/preactivate
virtualenvwrapper.user_scripts creating /home/username/.virtualenvs/venv34/bin/postactivate
virtualenvwrapper.user_scripts creating /home/username/.virtualenvs/venv34/bin/get_env_details
/usr/local/lib/python3.2/dist-packages/pkg_resources/__init__.py:87: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.
  warnings.warn(msg)
/usr/local/lib/python3.2/dist-packages/pkg_resources/__init__.py:87: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.
  warnings.warn(msg)
/usr/local/lib/python3.2/dist-packages/pkg_resources/__init__.py:87: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.
  warnings.warn(msg)

```

However, look what happens when I hit work on:

```
$ workon venv32
/usr/local/lib/python3.2/dist-packages/pkg_resources/__init__.py:87: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.
  warnings.warn(msg)
/usr/local/lib/python3.2/dist-packages/pkg_resources/__init__.py:87: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.
  warnings.warn(msg)
/usr/local/lib/python3.2/dist-packages/pkg_resources/__init__.py:87: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.
  warnings.warn(msg)
/usr/local/lib/python3.2/dist-packages/pkg_resources/__init__.py:87: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.
  warnings.warn(msg)
```

...Fortunately after previous errors messages I get a virtualenv :

```
(venv34) $ pip list
pip (8.0.3)
setuptools (20.2.2)
wheel (0.29.0)

```

**Comment by dholth** [comment]
pip 8 and virtualenv 14 drop Python 3.2 support. You should not want to use Python 3.2, but if you do you must use pip < 8 and virtualenv < 14.

**Comment by h-2-0** [comment]
Thank you, dholth.
