### ISSUE TITLE
virtualenv should ignore most of pip.conf

### ISSUE THREAD

**Issue by anntzer** [pypa/virtualenv#896]
With the following pip.conf:
```
[global]
disable-pip-version-check = true

[install]
no-binary = :all:
no-dependencies = true
```
creating a virtualenv fails:
```
$ python2 -mvirtualenv ~/venvs/testenv
New python executable in /home/antony/venvs/testenv/bin/python2
Not overwriting existing python script /home/antony/venvs/testenv/bin/python (you must use /home/antony/venvs/testenv/bin/python2)
Installing setuptools, pip, wheel...
  Complete output from command /home/antony/venvs/testenv/bin/python2 - setuptools pip wheel:
  Collecting setuptools
  Using cached setuptools-21.0.0.zip
Collecting pip
  Using cached pip-8.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'entry_points'
      warnings.warn(msg)
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'extras_require'
      warnings.warn(msg)
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'
      warnings.warn(msg)
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'tests_require'
      warnings.warn(msg)
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: invalid command 'egg_info'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xFs0UI/pip/
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 2316, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 708, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 941, in create_environment
    download=download,
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 897, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 792, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/antony/venvs/testenv/bin/python2 - setuptools pip wheel failed with error code 1
```

You may argue that it's due to the config, but creating a venv with the standard library's pyvenv does work fine.

**Comment by scott-vsi** [comment]
Is there any update on this? I'm having the same problem. My system's pip.conf file sets a prefix and consequently, any virtualenv that I create tries to use that prefix when installing packages (including easy_install and pip). The only workaround I can find is to do 
```
PIP_CONFIG_FILE= virtualenv my_ve
echo "[install]
prefix=" > my_ve/pip.conf
```
