### ISSUE TITLE
Can not create a virtualenv in python 2.6 source compiled

### ISSUE THREAD

**Issue by gforcada** [pypa/virtualenv#932]
Hi all,

I get this traceback:
```
vagrant@vagrant-ubuntu-trusty-64:~$ /srv/python2.6.9/bin/virtualenv venv-2.6.9
New python executable in /home/vagrant/venv-2.6.9/bin/python2.6
Also creating executable in /home/vagrant/venv-2.6.9/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /home/vagrant/venv-2.6.9/bin/python2.6 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/srv/python2.6.9/lib/python2.6/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/__init__.py", line 16, in <module>
  File "/srv/python2.6.9/lib/python2.6/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/vcs/mercurial.py", line 9, in <module>
  File "/srv/python2.6.9/lib/python2.6/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/download.py", line 39, in <module>
  File "/srv/python2.6.9/lib/python2.6/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/_vendor/requests/__init__.py", line 61, in <module>
  File "/srv/python2.6.9/lib/python2.6/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
ImportError: No module named urllib3
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/srv/python2.6.9/bin/virtualenv", line 3, in <module>
    virtualenv.main()
  File "/srv/python2.6.9/lib/python2.6/site-packages/virtualenv.py", line 711, in main
    symlink=options.symlink)
  File "/srv/python2.6.9/lib/python2.6/site-packages/virtualenv.py", line 944, in create_environment
    download=download,
  File "/srv/python2.6.9/lib/python2.6/site-packages/virtualenv.py", line 900, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/srv/python2.6.9/lib/python2.6/site-packages/virtualenv.py", line 795, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/vagrant/venv-2.6.9/bin/python2.6 - setuptools pip wheel failed with error code 1
```

I'm using this [ansible role](https://github.com/gforcada/ansible-compile-python) to compile from sources python 2.6 (also 2.7 and 3.5) and then [install virtualenv](https://github.com/gforcada/ansible-compile-python/blob/master/tasks/venv.yml)

But as you can see above, when trying to create a python 2.6 virutalenv fails with this error. The python2.7 virtualenv runs completely fine... I tried older versions of virtualenv (13.x and 14.x releases) but they bump into similar tracebacks...

Is that actually a virtualenv issue or rather a pip one?

**Comment by Ivoz** [comment]
I haven't seen that in my own source-compiled python 2.6, I run ArchLinux and install 2.6 by using [pyenv](https://github.com/yyuu/pyenv) (which grabs source straight from python.org).

Very weird issue, pip vendors requests, which then also vendors urllib3, which for some reason it can't locate. [The folder should be physically there though...](https://github.com/pypa/pip/tree/8.1.2/pip/_vendor/requests/packages)

When you say "similar tracebacks", is the exact same urllib3 not being found or is it some other module not being found? I recently found I needed to recompile 2.6 so it could get latest linking to openssl.
