### ISSUE TITLE
Russian virtualenv is not possible on Windows

### ISSUE THREAD

**Issue by techtonik** [pypa/virtualenv#950]
```
E:\[Blender]\[Python]>virtualenv виртуаленв
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\virtualenv.EXE\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\virtualenv.py", line 711, in main
    symlink=options.symlink)
  File "c:\python27\lib\site-packages\virtualenv.py", line 920, in create_environment
    home_dir, lib_dir, inc_dir, bin_dir = path_locations(home_dir)
  File "c:\python27\lib\site-packages\virtualenv.py", line 964, in path_locations
    mkdir(home_dir)
  File "c:\python27\lib\site-packages\virtualenv.py", line 321, in mkdir
    os.makedirs(path)
  File "c:\python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'E:\\[Blender]\\[Python]\\??????????'
```

**Comment by yan12125** [comment]
Duplicate of #457.

**Comment by techtonik** [comment]
@yan12125 no, this one is different. Here virtualenv name gets garbled when it is read from `sys.argv`,  in #457 the name is parsed successfully.

**Comment by yan12125** [comment]
From the perspective of a soltuion, they are _roughly_ the same - #900 should handle both cases. At least with #900, ```virtualenv 中文``` works for me.

**Comment by techtonik** [comment]
Windows must die.
