### ISSUE TITLE
Overwriting virtualenv with different "-p" argument fails (Fedora 24)

### ISSUE THREAD

**Issue by ianw** [pypa/virtualenv#976]
This is an odd problem, I admit.

If an existing virtualenv has broken symlinks, you can't overwrite it with a new virtualenv 

```
$ ls -l ./test/bin/python2.7
lrwxrwxrwx. 1 iwienand iwienand 12 Nov  8 15:41 ./test/bin/python2.7 -> /tmp/nothere
```

If you try to recreate this virtualenv, it fails

```
$ virtualenv ./test/
New python executable in /tmp/test/bin/python2
Not overwriting existing python script /tmp/test/bin/python (you must use /tmp/test/bin/python2)
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 9, in <module>
    load_entry_point('virtualenv==15.0.3', 'console_scripts', 'virtualenv')()
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 711, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 924, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 1369, in install_python
    os.symlink(py_executable_base, full_pth)
OSError: [Errno 17] File exists
````

This is all part of an automated CI image build for openstack, where we were creating the virtualenv with puppet then overwriting it later on in a later part of the build.  Nothing about that is right and I still haven't fully ascertained why it gets broken.  However it does seem we could lexists() here and overwrite the broken symlink; testing shows that does work to fix up the virtualenv

**Comment by ianw** [comment]
Ok, some more info.  Not really a broken symlink, as such ... during our build firstly we install the virtualenv from puppet [1] and after that, it looks like

```
-rwxr-xr-x 1 root root 7096 Nov  8 21:07 python
-rwxr-xr-x 1 root root 2331 Nov  8 21:07 python-config
lrwxrwxrwx 1 root root    6 Nov  8 21:07 python2 -> python
lrwxrwxrwx 1 root root    6 Nov  8 21:07 python2.7 -> python
```

now, contrast that with a fresh virtualenv I just setup

```
lrwxrwxrwx. 1 iwienand iwienand    7 Nov  9 08:20 python -> python2
-rwxrwxr-x. 1 iwienand iwienand 7096 Nov  9 08:20 python2
lrwxrwxrwx. 1 iwienand iwienand    7 Nov  9 08:20 python2.7 -> python2
```

Note that python2 is the executable and python the symlink above, but not in the first version.   Presumably this changed at some point and somehow we've got conflicting versions of virtualenv?

[1]  http://git.openstack.org/cgit/openstack-infra/system-config/tree/modules/openstack_project/manifests/slave_common.pp#n154
